### ISSUE TITLE
conditional required values

### ISSUE THREAD

**Issue by kris2214** [eclipsesource/jsonforms#1045]
Consider I have a json schema as below:
....
```js
{
  "properties": {
    "minimumDelay": {
      "type": "number"
    },
    "length": {
      "type": "number"
    }
  },
  "required": {
    "minimumDelay",
    "length"
  }
}
```

Here the json data will be valid if I enter both minimumDelay and length values.

But my requirement is json data must be valid when I enter either 1 of the values(like XOR case). How my schema must be modified to achieve the same?

**Comment by eneufeld** [comment]
Please reopen if you still have questions.
