### ISSUE TITLE
Properly support validation of aggregation types

### ISSUE THREAD

**Issue by edgarmueller** [eclipsesource/jsonforms#1046]
`oneOf/anyOf/allOf` validation results are not displayed correctly, e.g. with the example given by #1045 error messages are not re-appearing once both controls contains values.

**Comment by edgarmueller** [comment]
oneOf and anyOf should be rendererd in way that allows categorization of the respective sub schemas. In case of `oneOf` navigating away from a forms, would prompt the user and let him/her know that the data will be cleared which will not be the case for `anyOf`. `allOf` will be rendered inlined by default, i.e. all subschemas will be part of a single form, but categorization should be possible (e.g. by introducing an additional option in the UI schema)

**Comment by edgarmueller** [comment]
This issue mixes up behavior of the aggregation type renderes with their actual validation. This issue is only about validation, e.g. the for the example given in #1045 no validation error appear anywhere although they do exist if the none of the required values is present.

**Comment by huangmr** [comment]
Any update on this?

Having the same issue with the form where validation works, but errors are not displayed in the form due to dataPath mapping issue in the errors.

here is a sample schema

`// schema.json
{
  "type": "object",
  "properties": {
    "drink": { "type": "string", "enum": ["beer", "wine"] },
    "beer_name": { "type": "string" },
    "wine_color": { "type": "string" }
  },
  "oneOf": [
    {
      "properties": { "drink": { "enum": ["beer"] } },
      "required": ["beer_name"]
    },
    {
      "properties": { "drink": { "enum": ["wine"] } },
      "required": ["wine_color"]
    }
  ]
}`

**Comment by sdirix** [comment]
This issue is currently not in our priority list as indicated by the `Backlog` Milestone. Of course it would be great to get this feature in at some point in time. We would definitely welcome any contribution to this topic. If interested we could also prioritize this feature via our [support packages](https://jsonforms.io/support).

**Comment by sdirix** [comment]
@LukasBoll Please check whether the schema posted above now produces errors in JSON Forms.

**Comment by LukasBoll** [comment]
JSON Forms shows errors, according to the rules provided.

**Comment by sdirix** [comment]
Thanks @LukasBoll, closing this issue then. Feel free to reopen if needed.
