### ISSUE TITLE
Enforce/apply formatting guidelines during build via grunt 

### ISSUE THREAD

**Issue by edgarmueller** [eclipsesource/jsonforms#105]
Make use of tslint formatter option.

**Comment by eneufeld** [comment]
There is this tool:
http://clang.llvm.org/docs/ClangFormat.html
and there is a grunt integration

**Comment by edgarmueller** [comment]
Another one which seems to be more popular: https://github.com/vkadam/grunt-jsbeautifier

**Comment by eneufeld** [comment]
@edgarmueller we should rename the ticket as we do not use grunt anymore

**Comment by edgarmueller** [comment]
@eneufeld Yes, I've updated the title & description.

**Comment by edgarmueller** [comment]
We are using `tslint` which is run during a regular `npm run build`.
