### ISSUE TITLE
Package versions should be unified

### ISSUE THREAD

**Issue by sdirix** [eclipsesource/jsonforms#1071]
**Describe the bug**
Released package versioned are different between the packages

**To Reproduce**
Visit: https://www.npmjs.com/search?q=jsonforms and check package versions

**Expected behavior**
All package versions within `@jsonforms` should be the same

**Comment by edgarmueller** [comment]
This has been taken care of already.

**Comment by edgarmueller** [comment]
This has been taken care of already.
