### ISSUE TITLE
jsonforms has implicit "any"

### ISSUE THREAD

**Issue by GabinH** [eclipsesource/jsonforms#1072]
**Describe the bug**
Some variables in @jsonforms/core have an implicit "any" (i.e. there is no type associated with these variables).
The problem is that, by default, TS compiler disallows that (compiler rule : "noImplicitAny": true)
and it seems to be a correct setting. The result is that we cannot compile a TS project using jsonforms without overriding this setting or modifying core d.ts

**To Reproduce**
1. create react ts project : `create-react-app my-app --scripts-version=react-scripts-ts`
2. add dependancies : `yarn add --dev @jsonforms/core yarn add --dev @jsonforms/material-renderers @types/react-redux`
3. goto node_modules/@jsonforms/core/lib/util/field.d.ts
4. lign 66 : You need to add the type "any" to dispatch parameter in mapDispatchToFieldProps function
5. goto node_modules/@jsonforms/core/lib/util/index.d.ts
6. lign 19 : You need to add the type "any" to data and path parameters within the wrapper Resolve

**Expected behavior**
no type error in node_modules

**Used Setup (please complete the following information):**
- OS: Windows
- IDE/Text Editor: Visual Studio Code 
 - Framework: react
- RendererSet: material

[jsonform-tester.zip](https://github.com/eclipsesource/jsonforms/files/2370819/jsonform-tester.zip)

**Comment by eneufeld** [comment]
Hi, 
thank you for the report. We will take a look at this.

**Comment by edgarmueller** [comment]
Fixed via #1105.
