### ISSUE TITLE
Finalize material object renderer

### ISSUE THREAD

**Issue by edgarmueller** [eclipsesource/jsonforms#1076]
**Describe the bug**
The Material object renderer needs to be reviewed, e.g. with regards to styling. Also, tests are missing.

**To Reproduce**
Navigate to the `material` package, run `npm run dev` and checkout the allOf example which utilizes the object renderer.

**Expected behavior**
The renderer should be covered in a test case. Styling updates are optional.

**Comment by eneufeld** [comment]
Added PR #1078 

The main problem is that the requirement of the control is unclear.
My personal expectation would be, that you can add rules to it which are then applied to the wrapped controls.
@edgarmueller  is this also your expectation, I would suggest to discuss the requirements on the test case on the PR

**Comment by edgarmueller** [comment]
I think that's fine for now (fixed via #1078).
