### ISSUE TITLE
ListWithDetail should query UI schema

### ISSUE THREAD

**Issue by edgarmueller** [eclipsesource/jsonforms#1086]
**Describe the bug**
The Master/Detail renderer generates its detail schema on the fly instead of querying it from the UI schema subsstate

**To Reproduce**
1. Register any UI schema with a respective tester with Actions#registerUISchema
2. Render a form with a master/detail
3. The registered UI schema will not be used for rendering the detail view

**Expected behavior**
The registered UI schema should be used to render the detail view of the master/detail.

**Screenshots**
N/A

**Additional context**
N/A

**Comment by sdirix** [comment]
Implemented with #1199
