### ISSUE TITLE
Angular Material Labels and Errors have different fonts

### ISSUE THREAD

**Issue by eneufeld** [eclipsesource/jsonforms#1118]
**Describe the bug**
As not all angular material controls can use the MatFormField directive, the labels and errors shown are different for the controls.

**To Reproduce**
1. Open Examples and produce errors 

**Expected behavior**
All Labels and errors have the same font.

**Browser (please complete the following information):**
 - Browser [e.g. chrome, safari] all
 - Version [e.g. 22] all

**Used Setup (please complete the following information):**
 - Framework: angular
 - RendererSet: material

**Comment by edgarmueller** [comment]
Fixed via #1194
