### ISSUE TITLE
Nested arrays button does not render nicely, and has no delete button

### ISSUE THREAD

**Issue by chrisjohnson** [eclipsesource/jsonforms#1124]
**Describe the bug**

Using a schema like this:
```json
{"$schema": "http://json-schema.org/draft-04/schema#",
  "type": "array",
  "items":
  {"type": "object",
    "required": ["message"],
    "properties": {
      "message": {"type": "string"},
      "reject_codes": {"type": "array", "items": {"type": "string", "minLength": 1}}
    }
  }
}
```

The rendered interface is poor

**To Reproduce**
1. Clone the seed demo app
2. Set the schema as specified above
3. Set uischema and data to undefined

**Expected behavior**
The button should be styled to match the rest of the form, and there should be a button to remove elements from the array

**Screenshots**
![image](https://user-images.githubusercontent.com/178144/47389993-3aab6a00-d6e4-11e8-9a1e-cb282fa87163.png)

**Browser (please complete the following information):**
- Chrome Version 69.0.3497.100 (Official Build) (64-bit)

**Used Setup (please complete the following information):**
 - Framework: react
 - RendererSet: material

**Additional context**
This appears to be exactly as it was screenshotted when the code to implement nested arrays was introduced: https://github.com/eclipsesource/jsonforms/issues/994

So I'm not sure if this was just a temporary fix for a bug, or the intended behavior long-term, or what. I dug around in the code but I'm not very familiar with this codebase so it was hard for me to see why the standard array layout renderer wouldn't be used here

**Comment by edgarmueller** [comment]
@chrisjohnson Thanks for the report!. Admittedly, the introduction of the array layout renderer was bit rushed, so we'll to address the issues.

**Comment by chrisjohnson** [comment]
@eneufeld  Please let me know if I can help provide feedback, test strategies, offer more insight into our use case, or even contribute to the solution. One thing to call out, I would really love to be able to specify the array uischema inline to the rest of the uischema -- rather than the current approach where you have to use `registerUISchema` with a tester that looks for my array, and it seems doable to me from a user context especially if it really properly becomes a first-class layout type.

**Comment by edgarmueller** [comment]
The fix is part of 2.0.12-rc.3 and was fixed via #1146

**Comment by edgarmueller** [comment]
Regarding your request about specifying the detail UI schema inline: please open another issue for this. Of course, we'd also be happy to receive any PRs. Thank you!

**Comment by chrisjohnson** [comment]
Thank you very much, I'll work on testing this out over the next few days :)
