### ISSUE TITLE
Material: export * from './util'; 

### ISSUE THREAD

**Issue by treg** [eclipsesource/jsonforms#1127]
**Describe the bug**
comparing Material:: index.ts vs Vanilla:: index.ts 
Material:: index.ts is missing  export * from './util';

**Expected behavior**
Material export utils same as Vanilla

**Comment by edgarmueller** [comment]
Thanks for the report! We'll add the missing export

**Comment by edgarmueller** [comment]
Fixed via #1135, will be released with 2.0.12-rc.2
