### ISSUE TITLE
Dev Examples should use theming

### ISSUE THREAD

**Issue by eneufeld** [eclipsesource/jsonforms#1131]
**Describe the bug**
The react examples are currently not themed. They should as MaterialUI Typography is throwing an error otherwise.

**To Reproduce**
1. Start the examples

**Expected behavior**
No errors logged, examples are themed.

**Used Setup (please complete the following information):**
 - OS: [e.g. Linux] Linux
 - IDE/Text Editor: [e.g. Visual Studio Code, Vim] -
 - Framework: [e.g. react, angular] react
 - RendererSet: [e.g. material, vanilla] material

**Comment by sdirix** [comment]
This issue is no longer relevant.
