### ISSUE TITLE
openapiforms

### ISSUE THREAD

**Issue by jbadeau** [eclipsesource/jsonforms#1132]
Hi,

I am currently looking into generating forms from openapi schemas instead of json schemas. My question then, is jsonforms extensible enough that the schema model could be replaced by another model (e.g. openapi)?

**Comment by edgarmueller** [comment]
Hi, no, I'm afraid that's not the case right now. The only viable solution which comes to my mind is to convert the OpenAPI schema to a JSON schema , e.g. by the means of https://github.com/mikunn/openapi-schema-to-json-schema. We didn't try this out ourselves yet, but are happy about any feedback.

**Comment by edgarmueller** [comment]
Closing due inactivity.

**Comment by somefreestring** [comment]
I think this is a given opportunity 😞
however I will try to create a mapping ...

**Comment by jbadeau** [comment]
I think the latest openapi schema is fully compatible with jsonschema
