### ISSUE TITLE
Ability to specify uischema of arrays inline

### ISSUE THREAD

**Issue by chrisjohnson** [eclipsesource/jsonforms#1157]
**Is your feature request related to a problem? Please describe.**
Right now we are using jsonforms by storing a schema and a uischema in a database column for various forms we want to render. As it stands, the only way to apply uischema to array elements (consider an array of objects) is via the use of some extra javascript using registerUISChema where you specifically have to write testers that match when you get into a specific array and inject that array's uischema at the appropriate place. This is incompatible with our approach since aren't injecting extra javascript (and that doesn't really seem like an appropriate solution). Right now we are just living with the default generated uischema for array elements because it's the only viable option here.

**Describe the solution you'd like**
Some sort of mechanism for specifying the uischema inline to the overall uischema without having to call out to extra schemas. Perhaps borrowing from the json schema standard with some sort of $ref system? Or just the ability to specify a hunk of schema that will be pointing at an array and should repeat for each element in the array? I'm not quite sure the best solution here, because there would still need to be a way to add a new blank entry for adding elements to the array.

**Describe alternatives you've considered**
The only alternative is to just live with the default, or write some special case javascript using registerUISchema. The latter is not feasible so we are living with the former

**Describe for which setup you like to have the improvement**
Framework: react
RendererSet: material

**Comment by edgarmueller** [comment]
This should be fixed via #1198. We'll still need to update the docs though

**Comment by chrisjohnson** [comment]
<3

**Comment by shivgarg5676** [comment]
Is there any documentation around this?

**Comment by sdirix** [comment]
Hi @shivgarg5676 you can check https://github.com/eclipsesource/jsonforms/pull/1198 for a description. We'll add them to the official documentation at some point in the future.
