### ISSUE TITLE
Rendering fields nested in oneOf

### ISSUE THREAD

**Issue by johnmorrell** [eclipsesource/jsonforms#1161]
The following JSONSchema example does not appear to be supported by the UISchema. Can the selection of a fields nested in oneOf be rendered?

```
{
   "oneOf":[
      {
         "type":"object",
         "properties":{
            "value":{
               "type":"number"
            }
         }
      },
      {
         "type":"object",
         "properties":{
            "value":{
               "type":"string"
            }
         }
      }
   ]
}
```

**Comment by edgarmueller** [comment]
We have added an oneOf renderer for the react material renderers, see https://github.com/eclipsesource/jsonforms/pull/1163 (I just fixed an error in it).
If you clone that branch, follow the dev docs and execute `npm run dev` within the material folder you can have a look. Let me know if that covers your use case.

**Comment by edgarmueller** [comment]
For reference, it looks like this ![selection_110](https://user-images.githubusercontent.com/711092/48577158-bdf06200-e916-11e8-9045-53aaeb8fba5d.png)

**Comment by johnmorrell** [comment]
Thanks, this does look good but I was unable to build from this branch. I received the following error during npm install:

`npm ERR! 404 Not Found: @jsonforms/test@^2.0.12-rc.3`

**Comment by edgarmueller** [comment]
I'm not sure what went wrong there, but as we merged the PR today you can consume it directly now via the 2.0.12-rc.4 release. The code for the oneOf example can be found here https://github.com/eclipsesource/jsonforms/blob/master/packages/examples/src/oneOf.ts

**Comment by johnmorrell** [comment]
Working via 2.0.12-rc.4

This looks great thank you!
