### ISSUE TITLE
"No applicable field found." in deeply nested schema

### ISSUE THREAD

**Issue by johnmorrell** [eclipsesource/jsonforms#1169]
**Describe the bug**
In a deeply nested schema a valid JSON schema can fail to render form elements, instead presenting "No applicable field found.".

**To Reproduce**
Can be reproduced with the following Schema:
```
{
   "type":"object",
   "properties":{
      "Level1":{
         "type":"array",
         "items":{
            "type":"object",
            "properties":{
               "Level2":{
                  "type":"object",
                  "properties":{
                     "Level3":{
                        "type":"string"
                     }
                  }
               }
            }
         }
      }
   }
}
```
Interestingly if the bottom most element that is failing to render is nested further in an array, it does render correctly but not an object within an object.

**Expected behavior**
Text file to be rendered correctly.

**Browser (please complete the following information):**
 - Browser: Safari
 - Version: 12.0.1

**Used Setup (please complete the following information):**
 - Framework: React
 - RendererSet: Material

**Comment by edgarmueller** [comment]
Thanks for the report, we'll have a look soon.
