### ISSUE TITLE
Can we import schema from remote location ?

### ISSUE THREAD

**Issue by pragnesh-is** [eclipsesource/jsonforms#1183]
If we store schema in artifactory, can we import schema from there without storing those files in local source code ?

**Comment by edgarmueller** [comment]
You could just fetch it and use it once  the promise has been resolved to dispatch an `INIT` action as we do in e.g. in the [ionic playground](https://github.com/eclipsesource/jsonforms-ionic-playground/blob/737395d46a5be6037e70a561a2f6bceb8f6820a6/src/app/app.module.ts#L73). Would that work for you?

**Comment by edgarmueller** [comment]
I'm closing this one for now, hopefully your question is answered, if not, let us know.
