### ISSUE TITLE
On-the-fly re-rendering example throws Validation errors

### ISSUE THREAD

**Issue by sdirix** [eclipsesource/jsonforms#120]
As identified in #118: When using the on-the-fly re-renderer in the example app: After re-rendering the validator shows wrong validation alerts. To reproduce: Enter a date in the form and then re-render

**Comment by edgarmueller** [comment]
This has rather to do something with the DateTime control itself. It also happens when something is entered into the datetime field and then some other propety is modified. There's no need to re-render.
