### ISSUE TITLE
Path does not work in rule

### ISSUE THREAD

**Issue by calvinlch** [eclipsesource/jsonforms#1220]
**Describe the bug**

When I put the path in JsonForms, the rule in uischema will still pick up the data from the root scope.

**To Reproduce**
1. Init JsonForms
```js
 store.dispatch(Actions.init(data, schema, uischema));
```

where data = { main: <---data itself---->}

So here, I have a path in data called main

2. To render JsonForms
```jsx
<JsonForms schema={schema} uischema={uischema} path='main'></JsonForms>
```

I specify the path - "main" here.

3. Here my uischema
```json
"type":"VerticalLayout",
"rule": {
    "effect": "SHOW",
    "condition": {
    "type": "LEAF",
    "scope": "#/properties/index",
    "expectedValue": 1
},
"elements": [
    {
        "type": "VerticalLayout",
        "elements": [
            {
                "type": "Control",
                 "scope": "#/properties/Name"
            }
    }
]
```

With the path, I can display the "Name" correctly. However, if I put a rule, the rule will NOT go to path (which is main) to check the value. It will result in not handling the rule correctly

**Expected behavior**
The element should show or hide based on the path but not the root.

**Browser:**
 - Browser: chrome
 - Version: 71

**Used Setup:**
 - Framework: react,
 - RendererSet: material

**Comment by edgarmueller** [comment]
Thanks for the report! We'll have a look at the beginning of the week.
