### ISSUE TITLE
TypeScript error TS2351 with validator.ts 

### ISSUE THREAD

**Issue by clayroach** [eclipsesource/jsonforms#1228]
```
jsonforms version 2.1.0
typescript 3.2.2
webpack 4.28.2
```

```
ERROR in [blah]/uiproject/node_modules/@jsonforms/core/src/util/validator.ts
ERROR in [blah]/uiproject/node_modules/@jsonforms/core/src/util/validator.ts(5,15):
TS2351: Cannot use 'new' with an expression whose type lacks a call or construct signature.
```

**To Reproduce**
Compile project with webpack.

**Expected behavior**
No error

**Proposed solution**
Change import from:
`import * as AJV from 'ajv';`

To:
`import Ajv from 'ajv';`

**Comment by edgarmueller** [comment]
Thanks for the report, I guess we should avoid wildcard imports altogether. We'll try to address this issue in the upcoming sprint.

**Comment by clayroach** [comment]
Weirdly... the issue went away once I blew away the `package-lock.json` so some other library was causing this issue to manifest itself.

**Comment by clayroach** [comment]
@edgarmueller - Can you please consider getting this one fixed in the 2.2.0 version?  It came back for no good reason whatsoever, and now it is breaking all our builds unless we all individually patching this file.

**Comment by clayroach** [comment]
Thanks @edgarmueller.  Note that the following is what has resolved the issue, (capital `AJV`, not `Ajv`)
```
import AJV from 'ajv';
```

**Comment by edgarmueller** [comment]
@clayroach Could the issue be related to different compiler settings, i.e. do you have `allowSyntheticDefaultImports` and/es `esModuleInpterop` set? We opened #1242 and updated our tsconfig (https://github.com/eclipsesource/jsonforms/pull/1242/files#diff-bd08939a7f74f60ccd2a7d92682b57be), which hopefully should then fix your issue.

**Comment by edgarmueller** [comment]
We have released a pre-release 2.1.1-alpha.3, which contains #1242, i.e. the esModuleInterop flag is now set. Could you give it a try and let us know whether this solves your issue?

**Comment by clayroach** [comment]
Yes, will do!

**Comment by clayroach** [comment]
@edgarmueller Looks that resolved it!  Thanks.
