### ISSUE TITLE
Refactor dependencies to be peerDependencies

### ISSUE THREAD

**Issue by eneufeld** [eclipsesource/jsonforms#1230]
**Describe the bug**
Currently we declare all our runtime dependencies as dependencies. We probably should use peerDependencies instead.

**Expected behavior**
Some dependencies should be defined as peerDependencies instead of dependencies.

**Comment by eneufeld** [comment]
I think #1245 fixes all remaining issues.
I retested this and it looks good.
@edgarmueller do you think we can close this?

**Comment by edgarmueller** [comment]
Fixed via #1245
