### ISSUE TITLE
Add tests for filtering in autocomplete renderer

### ISSUE THREAD

**Issue by AlexandraBuzila** [eclipsesource/jsonforms#1239]
Add tests for #1182 (see fix in #1223).

**Comment by AlexandraBuzila** [comment]
Hi @howdyAnkit

Yes, this is still open. The tests for the `shouldFilter` prop are currently missing.

**Comment by howdyAnkit** [comment]
Can you assign it to me and show me where is this file? 
is it this one that we have to cover jasmine test cases ?
packages/angular-material/src/controls/autocomplete.renderer.ts

**Comment by AlexandraBuzila** [comment]
Hi @howdyAnkit 

Thank you for taking this on! :heart_decoration: 

Yes, the control that's missing the test case is the angular-material  autocomplete renderer. You can find it [here](https://github.com/eclipsesource/jsonforms/blob/c1686c1db33332bd7e820d53fdc29c27439acf1e/packages/angular-material/src/controls/autocomplete.renderer.ts#L110).

The existing tests for the control can be found [here](https://github.com/eclipsesource/jsonforms/blob/c1686c1db33332bd7e820d53fdc29c27439acf1e/packages/angular-material/test/autocomplete-control.spec.ts).

**Comment by howdyAnkit** [comment]
How do you check the coverage ?

**Comment by AlexandraBuzila** [comment]
After following the steps from the [developer documentation](https://github.com/eclipsesource/jsonforms#developers-documentation), you should be able to run the angular-material tests like this: `cd packages/angular-material && pnpm run test`.

To get the test coverage, you can use `pnpm run test-cov`. The coverage results will be in `packages/angular-material/coverage`

**Comment by howdyAnkit** [comment]
Hi @AlexandraBuzila 

Sorry for taking this much time I almost forgot the track of it.

I've attached the PR #2217 for you reference regarding the issue

Also a small headsup 
```options should prefer own props```
This mentioned testcase was quite unstable to run this test on my system and was passing and failing sometimes.

Please do run once in your system and if it still fails i'll check on your suggestions.


Again thanks for making this awesome library and Checking
