### ISSUE TITLE
Add support for JSONSchema "title" property

### ISSUE THREAD

**Issue by johnmorrell** [eclipsesource/jsonforms#1240]
**Is your feature request related to a problem? Please describe.**

Currently form titles appear to be a formatted version of the property name. This can be overridden by specifying a title in the UISchema, but as "title" is a part of JSONSchema it means the titles that already exist on the schema need to be uneccessarily duplicated  in a UISchema. The JSONSchema "description" property is currently used for additional information below the form item.

**Describe the solution you'd like**

Option to use JSONSchema titles where specified.

**Describe alternatives you've considered**

UISchema

**Describe for which setup you like to have the improvement**

Framework: react
RendererSet: material

**Additional context**

This would ideally also define the title for navigating options between oneOf options. This is currently using the first property name of each of the options.

**Comment by sdirix** [comment]
Thank you for the suggestion. We'll take a look in the near future.

**Comment by edgarmueller** [comment]
Fixed via #1335
