### ISSUE TITLE
Update to Ionic 4

### ISSUE THREAD

**Issue by edgarmueller** [eclipsesource/jsonforms#1243]
**Describe the bug**
Ionic 4 has been released a couple of days ago, we should check whether we can update our renderer set accordingly

**Comment by eneufeld** [comment]
@edgarmueller didn't you do this? I suggest to move this to 2.2.3 and open a follow up for the deactivated tests.

**Comment by edgarmueller** [comment]
Yes, thanks for pointing it out, see #1344.
