### ISSUE TITLE
Update to redux 4

### ISSUE THREAD

**Issue by edgarmueller** [eclipsesource/jsonforms#1244]
Update to redux 4.0.0

**Comment by edgarmueller** [comment]
This requires an update of the angular-based package as angular-redux only uses typedefs of redux 4 starting with version 9.x which only provides support for Angular 6.x

**Comment by eneufeld** [comment]
@edgarmueller isn't this done and thus should be part of 2.2.3?

**Comment by edgarmueller** [comment]
Yes & yes, moving & closing it.
