### ISSUE TITLE
Vanilla rendering has dependency to material-ui

### ISSUE THREAD

**Issue by tomhelmer** [eclipsesource/jsonforms#1252]
When I try to follow the tutorial, but replacing material-renderers with @jsonforms/vanilla-renderers there's a dependency to material-ui in the jsonforms core:
 
./node_modules/@jsonforms/react/lib/DispatchField.js
Module not found: Can't resolve '@material-ui/core' in 'jsonforms/node_modules/@jsonforms/react/lib'

**Comment by edgarmueller** [comment]
Thanks for the report, we'll have a look.

**Comment by edgarmueller** [comment]
While this has been fixed with v2.2.1-alpha.0, please note that the vanilla renderer set is currently not very well maintained as we do not have enough resources on our side to do so (it'll be moved to a separate repository starting with 3.x). Any help is of course appreciated.
