### ISSUE TITLE
Add support for JSONSchema constants

### ISSUE THREAD

**Issue by johnmorrell** [eclipsesource/jsonforms#1254]
**Is your feature request related to a problem? Please describe.**
Where a JSONSchema contains a constant value this does not get reflected in the output model. If this was a required property the output JSON would never validate against the Schema.

**Describe the solution you'd like**
Using JSONSchema constant:
```
{
   "type":"object",
   "properties":{
      "version":{
         "const":"1.0"
      }
   },
   "required":[
      "version"
   ]
}
```
Constants to be added to the model, via either a hidden or readonly form element.

**Describe alternatives you've considered**
Currently forcing constants by using an required Enum with a single and default value:
```
{
   "type":"object",
   "properties":{
      "version":{
         "type":"string",
         "enum":[
            "1.0"
         ],
         "default":"1.0"
      }
   },
   "required":[
      "version"
   ]
}
```
**Describe for which setup you like to have the improvement**
Framework: React
RendererSet: Material

**Additional context**
JSONForms: v2.2.0

**Comment by edgarmueller** [comment]
Thanks for the report, we'll try to have a look soon.

**Comment by johnmorrell** [comment]
Just for reference,  I have seen good results with populating oneOf data in v2.2.3 since #1273. I did hit a couple of cases where the intended option was not selected, due to partially complete data or where the oneOf structures are similar with optional fields. I think these case could be rectified with support for constants. Each of the oneOf types could be given a required const identifier that would have to be valid preventing early validation passes.

**Comment by edgarmueller** [comment]
Alright, thanks for letting us know. I hope we'll be able to tackle this for 2.3.0.

**Comment by edgarmueller** [comment]
https://github.com/eclipsesource/jsonforms/pull/1393 added support for `const`. I'm closing this therefore now. Any additional features related to `const` should be opened in a new issue. Thank you!
