### ISSUE TITLE
Add vscode config to repo

### ISSUE THREAD

**Issue by edgarmueller** [eclipsesource/jsonforms#1256]
**Describe the bug**
Common editor settings should be encapsulated via a .vscode file and added to the repo.

**Comment by sdirix** [comment]
Goal: Installing the prettier extension for VS Code and enabling auto-format on save should work seamlessly. At the moment many files are mishandled (for example switching from single-quotes to double-quotes or producing misaligned JSX).

**Comment by edgarmueller** [comment]
Fixed via #1331
