### ISSUE TITLE
updating data in same form (requesting help/advice)

### ISSUE THREAD

**Issue by emilylm** [eclipsesource/jsonforms#1260]
I have created a form to add a JSON object to my backend (via API).
I am trying to access the same form from another component in the app, but for this component I want to the form to load with new auto-filled data. So my question is:
- how do I update the form’s data (the entire data object, so essentially the same result as initialising the same form with different data), from my new component? After reading other issues, I have tried to use ‘init’ again in the componentDidMount method of my component, however this doesn’t seem to have updated the data.
- Note: the data from this form doesn’t need to be saved/accessible globally, or even after form submission.
Thank you for any help you can provide!

**Comment by edgarmueller** [comment]
What exactly did not work when updating the data. Did anything happen at all? Could you post a minimal example? 
What you could do nevertheless, is giving the `update` action a try with an empty path which denotes the root, as in `Actions.update('', () => myData)` which should update the data.

**Comment by emilylm** [comment]
Hi @edgarmueller, thanks for your quick response! Your suggestion is exactly what I needed, it's all working perfectly now!

**Comment by edgarmueller** [comment]
Great, glad I could help.
