### ISSUE TITLE
Duplicate validation warnings within oneOf

### ISSUE THREAD

**Issue by johnmorrell** [eclipsesource/jsonforms#1265]
**Describe the bug**
Duplicate validation warnings within oneOf block. Warnings seem to be accumulated, so the number of duplicates can go up the more oneOf items present.

<img width="543" alt="screenshot 2019-02-18 at 14 09 04" src="https://user-images.githubusercontent.com/874472/52956328-d3967d00-3386-11e9-9391-b26272a04d88.png">

**To Reproduce**
Use the following schema and add item to array, observing the waring count go from 1 to 4. Selecting the error count shows a 3x error message duplication:
```
{
   "type":"object",
   "properties":{
      "coloursOrNumbers":{
         "oneOf":[
            {
               "$ref":"#/definitions/colours"
            },
            {
               "$ref":"#/definitions/numbers"
            },
            {
               "$ref":"#/definitions/shapes"
            }
         ]
      }
   },
   "definitions":{
      "colours":{
         "title":"Colours",
         "type":"array",
         "items":{
            "title":"Type",
            "type":"string",
            "enum":[
               "Red",
               "Green",
               "Blue"
            ],
            "minItems":1
         }
      },
      "numbers":{
         "title":"Numbers",
         "type":"array",
         "items":{
            "title":"Type",
            "type":"string",
            "enum":[
               "One",
               "Two",
               "Three"
            ],
            "minItems":1
         }
      },
      "shapes":{
         "title":"Shapes",
         "type":"array",
         "items":{
            "title":"Type",
            "type":"string",
            "enum":[
               "Circle",
               "Triangle",
               "Square"
            ],
            "minItems":1
         }
      }
   }
}
```

**Expected behavior**
No duplication of validation errors.

**Browser (please complete the following information):**
Safari v12.0.3

**Used Setup (please complete the following information):**
React/Material

**Additional context**
^2.2.0

**Comment by edgarmueller** [comment]
Right, as you already suggested, this is the case because the validator validates against each oneOf subschema against the data and hence multiple messages with the same content, but with a different schema path, are created.
We'll look into it.
