### ISSUE TITLE
Horizontal and Vertical Layout with arrays by registering a UI schema

### ISSUE THREAD

**Issue by Nasir2712** [eclipsesource/jsonforms#1267]
Hello I am trying to go through this documentation - https://jsonforms.io/docs/providing-uischemas
I am trying to customize my array elements by using horizontal layouts and vertical layout. 
I get no data in the component. How do I pass data in the component?

This is the component code from the document
```import { composePaths, ControlElement, Resolve } from '@jsonforms/core';
import { JsonForms } from '@jsonforms/react';
import * as _ from 'lodash';
import * as React from 'react';

export const Playground =
  ({ data, path, schema, onAdd, uischema, findUISchema }) => {

    const controlElement = uischema as ControlElement;
    const resolvedSchema = Resolve.schema(schema, `${controlElement.scope}/items`);

    return (
      <fieldset>
        <legend>My Control</legend>
        <div>
          {
            data ? _.range(0, data.length).map((index) => {

              const uischema = findUISchema(resolvedSchema, controlElement.scope, path);
              const childPath = composePaths(path, `${index}`);

              return (
                <JsonForms
                  schema={resolvedSchema}
                  uischema={uischema}
                  path={childPath}
                  key={childPath}
                />
              );
            }) : <p>No data</p>
          }
        </div>
      </fieldset>
    );
  };

my store- 
store.dispatch(Actions.registerUISchema(
  (jsonSchema, schemaPath) => {
    return schemaPath === '#/properties/clients' ? 2 : NOT_APPLICABLE;
  },
  {
    type: 'VerticalLayout',
    elements: [
      {
        type: 'Control',
        scope: '#/properties/clients/items/properties/firstName'
      },
      {
        type: 'Control',
        scope: '#/properties/clients/items/properties/firstName'
      }
    ]
  }
));


my schema 
 const schema = {
  'type': 'object',
  'properties': {
    'clients': {
      'type': 'array',
      'items': {
        'type': 'object',
        'required': [
          'firstName'
        ],
        'properties': {
          'Client ID': {
            'type': 'string',
            'title': 'Service to Client'
          },
          'startDate': {
            'type': 'string',
            'title': 'Start Date',
            'format': 'date'
          },
          'endDate': {
            'type': 'string',
            'title': 'End Date',
            'format': 'date'
          },
          'firstName': {
            'type': 'string',
            'title': 'First name'
          },
          'middleName': {
            'type': 'string',
            'title': 'Middle name'
          },
          'lastName': {
            'type': 'string',
            'title': 'Last name'
          }
        }
      }
    }
  }
}
```

**Comment by Nasir2712** [comment]
<img width="1244" alt="screen shot 2019-02-19 at 11 37 06 am" src="https://user-images.githubusercontent.com/8887704/53042276-c5a23400-343a-11e9-9c47-9d09f6c6f056.png">
Trying to replicate this layout using an array.

**Comment by edgarmueller** [comment]
Hi, it depends, which version are you using (I'm asking because with 2.2.1 we introduced breaking changes)? And I suppose you are registering the `Playground` component as a custom renderer, if so, how do you do that?

**Comment by Nasir2712** [comment]
Hello, thanks for getting back to me. I am using version 2.2.0. Also, I did do any custom rendering for the playground component coz I didn't know I had too. What should be my next steps be to achieve the above screenshot layout?

**Comment by edgarmueller** [comment]
Ok, a couple of things. First, you'll need to override the default table-based array renderer which you do with:

```js
store.dispatch(
  Actions.registerRenderer(withIncreasedRank(1, materialArrayControlTester),  Playground)
);
```
where `Playground` is your connected component. If you want the default table-based array renderer to still be triggered in a different context you will need to refine your tester as `Playground` actually replaces it.

Here's the `Playground` component:

```js
const Playground =
  ({ data, path, schema, onAdd, uischema, findUISchema, scopedSchema }: any) => {

    const controlElement = uischema as ControlElement;

    return (
      <fieldset>
        <legend>My Control</legend>
        <div>
          {
            data ? _.range(0, data.length).map((index: number) => {

              const uischema = findUISchema(scopedSchema, controlElement.scope, path);
              const childPath = Paths.compose(path, `${index}`);

              return (
                <JsonForms
                  schema={scopedSchema}
                  uischema={uischema}
                  path={childPath}
                  key={childPath}
                />
              );
            }) : <p>No data</p>
          }
        </div>
      </fieldset>
    );
  };
export default connect(mapStateToArrayControlProps, mapDispatchToArrayControlProps)(Playground);
```

Note that it has been connected to the store and the usage of `scopedSchema` (which BTW has been renamed to `schema` starting with 2.2.1). Also there's no way of adding elements in your renderer but I guess this is something you are aware of.

Finally, in your `registerUISchema` call, you need to adapt the `scope` property of each Control as it is scoped relatively against the schema of the parent renderer, which in this case is the `items` subschema:

```js
store.dispatch(Actions.registerUISchema(
  (jsonSchema, schemaPath) => {
    return schemaPath === '#/properties/clients' ? 2 : NOT_APPLICABLE;
  },
  {
    type: 'VerticalLayout',
    elements: [
      {
        type: 'Control',
        scope: '#/properties/firstName'
      } as ControlElement,
      {
        type: 'Control',
        scope: '#/properties/lastName'
      }
    ]
  } as VerticalLayout
));
```

Let me know if this helps.

**Comment by Nasir2712** [comment]
my store - 
```import { Actions, mapDispatchToArrayControlProps, mapStateToArrayControlProps, NOT_APPLICABLE, withIncreasedRank } from '@jsonforms/core';
import { ControlElement, VerticalLayout } from '@jsonforms/core';
import { materialArrayControlTester } from '@jsonforms/material-renderers';
import Playground from '../Components/AddClient/playground';
import { store } from './index';

store.dispatch(
  Actions.registerRenderer(withIncreasedRank(1, materialArrayControlTester), Playground)
);

store.dispatch(Actions.registerUISchema(
  (jsonSchema, schemaPath) => {
    return schemaPath === '#/properties/clients' ? 2 : NOT_APPLICABLE;
  },
      {
        type: 'VerticalLayout',
        elements: [
        {
          type: 'Control',
          scope: '#/properties/firstName'
        } as ControlElement,
        {
          type: 'Control',
          scope: '#/properties/lastName'
        }
      ]
      } as VerticalLayout
));

Playground Component-
import { ControlElement, mapDispatchToArrayControlProps, mapStateToArrayControlProps, Paths } from '@jsonforms/core';
import { JsonForms } from '@jsonforms/react';
import * as _ from 'lodash';
import * as React from 'react';
import { connect } from 'react-redux';

const Playground =
  ({ data, path, schema, onAdd, uischema, findUISchema, scopedSchema }: any) => {

    const controlElement = uischema as ControlElement;

    return (
      <fieldset>
        <legend>My Control</legend>
        <div>
          {
            data ? _.range(0, data.length).map((index: number) => {

              const uischema = findUISchema(scopedSchema, controlElement.scope, path);
              const childPath = Paths.compose(path, `${index}`);

              return (
                <JsonForms
                  schema={scopedSchema}
                  uischema={uischema}
                  path={childPath}
                  key={childPath}
                />
              );
            }) : <p>No data</p>
          }
        </div>
      </fieldset>
    );
  };

export default connect(mapStateToArrayControlProps, mapDispatchToArrayControlProps)(Playground);
```
I get this error
<img width="1440" alt="screen shot 2019-02-20 at 3 56 22 pm" src="https://user-images.githubusercontent.com/8887704/53133561-63bff800-3528-11e9-868c-8983cb9a13ba.png">

**Comment by Nasir2712** [comment]
I am still confused on how to pass the ```jsonSchema``` when you use ```Actions.registerUISchema```?

**Comment by edgarmueller** [comment]
Have a look at https://github.com/edgarmueller/jsonforms-react-seed/tree/1267, which is the seed updated with your custom renderer. I hope it make things clear.

**Comment by Nasir2712** [comment]
Hello, so I did try that and it's working as expected. Just wanted to know if that layout can be achieved inside an array? so for example whenever I click 'Add' button I should be able to generate a row with the same layout.

**Comment by edgarmueller** [comment]
Well, kinda, but I don't know whether it matches your expectations. The thing is we actually have two array renderers, the one you are seeing is the default table-based one, which is used for rendering whenever JSONForms encounters an array of objects. 
The other one is used when the schema is more complex, e.g. when an array of objects containing other objects is encountered. What you basically want now, is to override the default table-based array renderer. You can do so by either providing your own custom renderer or by reconfiguring the array layout renderer.

You can try to do the later by calling:

```js
const MyArrayRenderer = connect(
  mapStateToArrayControlProps, 
  mapDispatchToArrayControlProps
)(MaterialArrayLayoutRenderer)))

store.dispatch(
  Actions.registerRenderer(
    withIncreasedRank(1, materialArrayControlTester),  
    MyArrayRenderer
)
```

Given you are registering your custom UI schema, which probably looks something like this:

```js
store.dispatch(Actions.registerUISchema(
  (jsonSchema, schemaPath) => {
    return schemaPath === '#/properties/clients' ? 2 : NOT_APPLICABLE;
  },
  {
    type: 'VerticalLayout',
    elements: [
      {
        type: 'HorizontalLayout',
        elements: [
          {
            type: 'Control',
            scope: '#/properties/clientId'
          } as ControlElement,
          {
            type: 'Control',
            scope: '#/properties/startDate'
          },
          {
            type: 'Control',
            scope: '#/properties/endDate'
          }
        ]
      } as HorizontalLayout,
      {
        type: 'HorizontalLayout',
        elements: [
          {
            type: 'Control',
            scope: '#/properties/firstName'
          } as ControlElement,
          {
            type: 'Control',
            scope: '#/properties/middleName'
          },
          {
            type: 'Control',
            scope: '#/properties/lastName'
          }
        ]
      }  as HorizontalLayout,
    ]
  } as VerticalLayout
));
```

you'll end up with the following, which is using expansion panels for each element

![selection_011](https://user-images.githubusercontent.com/711092/53261030-4bd8a780-36d3-11e9-9b1a-dab57cb172f8.png)

If you don't like that I'm afraid you need to roll your own layout render, which you could base on https://github.com/eclipsesource/jsonforms/blob/master/packages/material/src/layouts/MaterialArrayLayoutRenderer.tsx#L40

**Comment by Nasir2712** [comment]
The above layout is what I was looking for. What should be the import for ```MaterialArrayLayoutRenderer ```? Also is this available in this version -  2.2.1-alpha.4 or 2.2.0?

**Comment by Nasir2712** [comment]
ok i got it. It is MaterialArrayLayout for some reason and not MaterialArrayLayoutRenderer. A naming issue.

**Comment by Nasir2712** [comment]
Ok so with MaterialArrayLayout there is an issue with data mapping. When I try to use this 
```
const data = {
  "clients": [
    {
      firstName: 'bart'
    },
    {
      lastName: 'lisa'
    }
  ]
}```
The component loads with no data. When i try to add values to the layout. It overrides the data object and creates a clients array again. 
```
clients: Array(2)
0: {firstName: "bart"}
1: {lastName: "lisa"}
clients: [{…}]
}```
this is how it gets mapped.

**Comment by edgarmueller** [comment]
How do you add values? Via the plus button? I've updated https://github.com/edgarmueller/jsonforms-react-seed/tree/1267 with your example and it works. Can you clarify how you add values?

**Comment by Nasir2712** [comment]
Yup that worked fine. Thanks for all your help. I really appreciate it.

**Comment by Nasir2712** [comment]
Also, if I want to use both MaterialArrayLayoutRenderer  and MaterialArrayControlRenderer how would i do that?

**Comment by Nasir2712** [comment]
I am actually trying to override the default MaterialArrayLayoutRenderer by using the same code which you provided in the above comments. I am having issues in them, you can take a look at it here - https://github.com/Nasir2712/jsonforms-react-seed/tree/adding_material_array and let me know am i doing wrong.

**Comment by edgarmueller** [comment]
The problem here is that we defined some of the props to be optional, but in the seed we also enabled strict mode and hence the TS compiler rightfully complains about it. We need to fix our typings, because schema as well as a couple of other props are actually not undefined. I've opened https://github.com/eclipsesource/jsonforms/issues/1275 to track this. In the meantime you can disable strict null-checks as a workaround (set `strict` in `tsconfig.json` to false). Looking at your example you should probably also update to 2.2.1-alpha.4, which will cause the prop errors to go away (e.g. about missing `createDefaultValue` etc.)

**Comment by Nasir2712** [comment]
Ok, so since the tsx issues were giving me a lot of pain, I modified the extensions to jsx. Got rid of all the errors. I updated the versions as well, but i still get this issue. 
<img width="670" alt="screen shot 2019-02-26 at 4 52 53 pm" src="https://user-images.githubusercontent.com/8887704/53457560-aa5d9880-39e7-11e9-8a58-d5d9638278f4.png">

**Comment by Nasir2712** [comment]
@edgarmueller Did you get a chance to take a look at my last comment. I am kinda stuck there.

**Comment by edgarmueller** [comment]
@Nasir2712 No, not yet, but I'll have a look tomorrow.

**Comment by edgarmueller** [comment]
Ok, I had a quick look and here's what you need to do:
1. Please update all packages to the same version (the current one is 2.2.1), the `material-renderers` was still pointing to 2.2.0. So replace your current entries in `package.json` with these:
```json
"@jsonforms/core": "2.2.1",
"@jsonforms/material-renderers": "2.2.1",
"@jsonforms/react": "2.2.1",
```
2. The `ResolvedJsonForms` component does not take a `scopedSchema` prop, but a `schema` one. So in your `MaterialArrayLayout`, update the `ResolvedJsonForms` component on line 113 to 
```jsx
<ResolvedJsonForms
  schema={schema}
  uischema={foundUISchema}
  path={childPath}
  key={childPath}
/>
```

With these changes the form renders correctly again.

**Comment by edgarmueller** [comment]
I'm closing this one as your question seems to have been answered. If not, free to re-open or create a new issue.
