### ISSUE TITLE
Ratings Component showing value-1

### ISSUE THREAD

**Issue by goatandsheep** [eclipsesource/jsonforms#1268]
**Describe the bug**
On the [intro doc page](https://jsonforms.io/docs/intro), the rating component shows value = value - 1, i.e. if you click star 5, you will see it filled until only 4.

**To Reproduce**
1. Go to [intro doc page](https://jsonforms.io/docs/intro)
2. At the bottom, click on star 4
3. See that the stars are only coloured until star 3

**Expected behavior**
The rating should be coloured up to the star you click on

**Browser (please complete the following information):**
 - Browser: Chrome
 - Version: latest?

**Used Setup (please complete the following information):**
 - Framework: ?
 - RendererSet: ?

**Comment by edgarmueller** [comment]
Indeed, thanks for the report, we'll look into it.

**Comment by AlexandraBuzila** [comment]
Pull request: https://github.com/eclipsesource/jsonforms2-website/pull/57

**Comment by edgarmueller** [comment]
Fixed via https://github.com/eclipsesource/jsonforms2-website/pull/57
