### ISSUE TITLE
Table-based array renderer should use start case instead of capitalize

### ISSUE THREAD

**Issue by Nasir2712** [eclipsesource/jsonforms#1270]
Not sure if this is a bug or something that I am doing wrong. I am trying to fix the labels for the ui elements here is my schema.

```const schema = {
  type: 'object',
  properties: {
    "primaryPrograms": {
      "type": "array",
      "items": {
        type: 'object',
        properties: {
          "primaryProgram": {
            "type": "boolean"
          },
          "program": {
            "type": "string",
            "enum": []
          },
          "admitDate": {
            'type': 'string',
            'format': 'date'
          },
          "dischargeDate": {
            'type': 'string',
            'format': 'date'
          }
        }
      }
    }
  }
}
```
This is what i get
<img width="1305" alt="screen shot 2019-02-20 at 10 20 10 pm" src="https://user-images.githubusercontent.com/8887704/53147882-ba93f480-355d-11e9-9f69-eafa90300a2c.png">

```
ui schema - {
  "type": "VerticalLayout",
  "elements": [
    {
      "type": "Control",
      "label": "Primary Program"
      "scope": "#/properties/primaryPrograms/items/properties/primaryProgram"
    }
  ]
}
```
If I try to define a uischema as suggested in the docs, i lose the array renderer but the label works fine

**Comment by treg** [comment]
Try changing  "scope": "#/properties/primaryPrograms'

**Comment by Nasir2712** [comment]
Nope that didn't work either.

**Comment by edgarmueller** [comment]
With the default table-based array renderer this is currently not possible without using a custom renderer as it simply capitalizes the property name, but we can change that easily for the next interm release to use start case, which I think makes sense.
