### ISSUE TITLE
Can we get an onChange prop for the JsonForms component?

### ISSUE THREAD

**Issue by edgarmueller** [eclipsesource/jsonforms#1271]
**Describe the bug**
I'd be great if the the `JsonForms` could support an `onChange` prop that gets called whenever the UPDATE_DATA action is fired. This would enable easier integration within an existing redux app infrastructure as one would not need to take care of writing custom reducers anymore which sync the state between the app reducer and the jsonforms one.

**Used Setup (please complete the following information):**
 - Framework: react
 - RendererSet: n/A

**Comment by sunilb0575** [comment]
Hi @edgarmueller this feature will be very much helpful. I would like to make sure that this fix will also address the following issue
[request for onDelete props when used schema of type='array'](https://github.com/eclipsesource/jsonforms/issues/1286)
