### ISSUE TITLE
oneOf fields do not preselect with loaded data

### ISSUE THREAD

**Issue by johnmorrell** [eclipsesource/jsonforms#1273]
**Describe the bug**
When a schema with a oneOf property is rendered and loaded with a data set. The oneOf field always preselects the first items and may render data from the an incorrect option.

**To Reproduce**

UISchema:
```
{
   "type":"object",
   "properties":{
      "quantity":{
         "oneOf":[
            {
               "$ref":"#/definitions/unrangedQuantity"
            },
            {
               "$ref":"#/definitions/rangedQuantity"
            }
         ]
      }
   },
   "definitions":{
      "unrangedQuantity":{
         "title":"Value",
         "type":"object",
         "properties":{
            "value":{
               "type":"number"
            },
            "unit":{
               "type":"string"
            }
         },
         "required":[
            "value",
            "unit"
         ]
      },
      "rangedQuantity":{
         "title":"Range",
         "type":"object",
         "properties":{
            "valueLow":{
               "type":"number"
            },
            "valueHigh":{
               "type":"number"
            },
            "unit":{
               "type":"string"
            }
         },
         "required":[
            "valueLow",
            "valueHigh",
            "unit"
         ]
      }
   }
}
```

Data:
```
{
   "quantity":{
      "valueLow":1,
      "valueHigh":10,
      "unit":"kg"
   }
}
```

Screenshot:

<img width="332" alt="screenshot 2019-02-25 at 10 34 30" src="https://user-images.githubusercontent.com/874472/53331519-02fa3c00-38e9-11e9-997f-7e51125ad437.png">

**Expected behavior**
The correct field is selected and populated. This may be potentially quite complicated due to the recursive nature. Ideally the data could be validated against each of the oneOf items and populate the first it validates against.

**Browser (please complete the following information):**

**Used Setup (please complete the following information):**
 - Framework: React
 - RendererSet: Material

**Additional context**
- JSONForms: 2.2.1-alpha.4

**Comment by edgarmueller** [comment]
Thanks for the report. I'm not quite sure how to tackle this, specifically, how we'd prevent populating the first form in your example. We probably could change the default selection index or something similar, but, e.g. what would happen if we load invalid data? In that case we'd like to show any already existing data, but with any existing validation errors. Speaking of which, the `value` property in the form looks like it's missing a validation error message (as it is required).

**Comment by johnmorrell** [comment]
I don't think there is a complete solution, especially for invalid data but even with a oneOf where one case may contain a subset of another, and the data may be valid in both cases. As it stands the oneOf options clear when they are selected, so switching to the correct field then clears the data.

Far from ideal, but I wonder if there could be a specified identifier property that could be added to a oneOf object schema to explicitly indicate which of the oneOf options it relates to, eg.

Schema:
```
{
   "type":"object",
   "properties":{
      "quantity":{
         "oneOf":[
            {
               "$ref":"#/definitions/unrangedQuantity"
            },
            {
               "$ref":"#/definitions/rangedQuantity"
            }
         ]
      }
   },
   "definitions":{
      "unrangedQuantity":{
         "title":"Value",
         "type":"object",
         "properties":{
            "identifier":{
               "const":"unrangedQuantity"
            },
            "value":{
               "type":"number"
            },
            "unit":{
               "type":"string"
            }
         },
         "required":[
            "value",
            "unit"
         ]
      },
      "rangedQuantity":{
         "title":"Range",
         "type":"object",
         "properties":{
            "identifier":{
               "const":"rangedQuantity"
            },
            "valueLow":{
               "type":"number"
            },
            "valueHigh":{
               "type":"number"
            },
            "unit":{
               "type":"string"
            }
         },
         "required":[
            "valueLow",
            "valueHigh",
            "unit"
         ]
      }
   }
}
```

Data:
```
{
   "quantity":{
      "identifier":"rangedQuantity",
      "valueLow":1,
      "valueHigh":10,
      "unit":"kg"
   }
}
```

**Comment by johnmorrell** [comment]
@edgarmueller, I was wondering if you had any thoughts on how or if this can can be solved?

**Comment by edgarmueller** [comment]
@johnmorrell Yes, I think we'll need to adapt the oneOf renderer in such a way, does it checks validation errors by looking at each validation result of the oneOf and then picks the index of the first one that is valid, which then can be used to pre-select the respective tab. I'm note sure when exactly we will be able to start implementing this, probably after 2.2.3.
