### ISSUE TITLE
Improve performance

### ISSUE THREAD

**Issue by eneufeld** [eclipsesource/jsonforms#1290]
**Describe the bug**
Using big uischemas with many components leads to a slow performance resulting in a simple enum change taking 5 seconds.

**Expected behavior**
Simple updates of portions of data should feel the same independent of the complexity of the created form.

**Browser (please complete the following information):**
 - Browser [e.g. chrome, safari] chrome
 - Version [e.g. 22] 72.0.3626.121

**Used Setup (please complete the following information):**
 - Framework: [e.g. react, angular] react
 - RendererSet: [e.g. material, vanilla] material

This bug relies on:
- [x] #1291 
- [x] #1292
This bug will fix:
- #1202

**Comment by eneufeld** [comment]
@edgarmueller I think we can close this for the moment.  I would also suggest to close #1202 as it should not be needed anymore.

**Comment by edgarmueller** [comment]
Ok, closing both.
