### ISSUE TITLE
Check for cases where we a custom css is used instead of hidden element

### ISSUE THREAD

**Issue by eneufeld** [eclipsesource/jsonforms#1307]
**Describe the bug**
In some renderers we used a custom CSS to hide the element instead of using the Hidden element of the MUI library. We should check for all those occurrences and replace them with the Hidden element.

**Used Setup (please complete the following information):**
 - Framework: [e.g. react, angular] react
 - RendererSet: [e.g. material, vanilla] material

**Comment by edgarmueller** [comment]
I think this is not the case anymore after #1304, at least not for the `material-renderers` package.

**Comment by edgarmueller** [comment]
Well, it still is, occurrences include: MaterialLabelRenderer, NoBorderTableCell, MaterialInputControl and MaterialGroupLayout.

**Comment by edgarmueller** [comment]
Fixed via #1330.
