### ISSUE TITLE
Help! How to get the current data from store!

### ISSUE THREAD

**Issue by EricVicky** [eclipsesource/jsonforms#1311]
Hi ,

One simple question to need your help!
When I have updated the current data through 'handleChange" method, and we know that current data has been changed, and we can get current data from "this.props.data", but how can we get all the data in the forms?

Thanks!

**Comment by edgarmueller** [comment]
I think you are looking for `getData`, e.g. in our seed app we do:
```js
import {getData, JsonFormsState} from '@jsonforms/core';
/// ...
const mapStateToProps = (state: JsonFormsState) => {
  return { dataAsString: JSON.stringify(getData(state), null, 2) }
};
```

**Comment by edgarmueller** [comment]
I'm closing this one for now. If my answer didn't help you, feel free to re-open.
