### ISSUE TITLE
Should MaterialArrayLayoutRenderer support multiple open panels

### ISSUE THREAD

**Issue by eneufeld** [eclipsesource/jsonforms#1319]
**Describe the bug**
With #1297 we restricted the MaterialArrayLayoutRenderer to only allow one open panel.
Should we change this to support multiple open panels again?

**Used Setup (please complete the following information):**
 - Framework: [e.g. react, angular] react
 - RendererSet: [e.g. material, vanilla] material

**Comment by edgarmueller** [comment]
Obsolete for now, re-open if necessary.
