### ISSUE TITLE
Validation not working with multiple forms

### ISSUE THREAD

**Issue by guntur-ricardo** [eclipsesource/jsonforms#1329]
**Describe the bug**
The multiple forms example in https://jsonforms.io/docs/store has 'required' validation that does not seem to work.

I also get the same issue when attempting to use multiple forms in a single store on my react project.

**To Reproduce**
1. Go to https://jsonforms.io/docs/store
2. Scroll down to Multiple forms within single store
3. Click on First Name and type anything then erase
4. See that validation text does not appear

**Expected behavior**
When input is required, I expected to see red required text.

**Screenshots**
Validation not working
![image](https://user-images.githubusercontent.com/31665531/56147076-88a77900-5f75-11e9-8609-a9647ac8ad5a.png)

Validation Working
![image](https://user-images.githubusercontent.com/31665531/56147090-9230e100-5f75-11e9-9346-044ca2c0bd4d.png)

**Browser (please complete the following information):**
 - Browser Chrome
 - Version 73.0.3683.103

**Comment by edgarmueller** [comment]
Thanks for the report! You are right, it seems we broke the example, thanks for noticing. The problem is that the validator configuration is wrong as we don't call the `init` action. I think a possible workaround would be to manually wrap the referenced schemas, and then dispatch the init actions before rendering, in our case this would be:

```javascript
store.dispatch(
  Actions.init(
    {}, 
    {
      type: "object",
      properties: {
        person: schemas.person,
        shippingAddress: schemas.address
      }
    }
  )
);
```

But this isn't very nice, so we'll need to address this in one of the upcoming releases.

**Comment by DavidHenri008** [comment]
@edgarmueller I am about to use this library to create a multiple forms project and I would like to know if there is an approximate date to the release of the 2.3.0 version. I assume that this version will fully support the multiple forms including errors, schemas and validators in a single store.
This library is really an excellent work by the way.
Thanks.

**Comment by edgarmueller** [comment]
@DavidHenri008 Thanks for the kind words! We started working on this issue, and it seems likely that we'll support a Context-based API which currently seems to be the cleanest solution for this problem as each `JsonForms` element could be treated in isolation then. Unfortunately this involves a bit of work, so I can't tell for certain when we'll be able to create a final 2.3.0 release. I hope that by the end of the month we'll be able to release a first alpha though.
