### ISSUE TITLE
Update docs as doc and code doesn't match

### ISSUE THREAD

**Issue by qduxiaoliang** [eclipsesource/jsonforms#1336]
**Describe the bug**
document says generateUISchema  is exported, but code doesn't

**To Reproduce**
1. the below doc shows generateUISchema has been exported
https://jsonforms.io/api/core/globals.html#generateuischema

2. however, there is not export for this function in the below code
https://github.com/eclipsesource/jsonforms/blob/master/packages/core/src/generators/uischema.ts

**Expected behavior**
add export to generateUISchema function

**Comment by edgarmueller** [comment]
Thanks for the report. You're right, `generateUISchema` is not exported, but `Generate.uiSchema` is. We'll fix in the next couple of days.

**Comment by sdirix** [comment]
I rechecked the website and this is no longer the case: https://jsonforms.io/public/api/core/globals.html#generateuischema
