### ISSUE TITLE
sudden disappearance of tutorial sections?

### ISSUE THREAD

**Issue by nlac** [eclipsesource/jsonforms#1343]
Maybe i am wrong but i would swear that a couple of days ago there were tutorial sections about "linking forms" and "multiple forms within a single store" on the home page, as it described here:
https://github.com/eclipsesource/jsonforms/issues/900#issuecomment-373771710

also this url also was available: https://jsonforms.io/docs/tutorialTypescript (i bookmarked it some days ago but now i get "not found")

What is the reason of the deletion of these useful contents?

**Comment by edgarmueller** [comment]
Thanks for the report. We're currently in the process of updating our docs, so it might be the case that some parts are missing or have been moved. We'll fix these in the upcoming days.

**Comment by edgarmueller** [comment]
This should be fixed, I've added a section about 'Multiple forms' and re-added the typescript tutorial (URL is https://jsonforms.io/docs/tutorial-typescript). If you find any other issues, please let us know. Thanks!

**Comment by nlac** [comment]
Great, thank you!
