### ISSUE TITLE
No applicable cell found (string array)

### ISSUE THREAD

**Issue by johnmorrell** [eclipsesource/jsonforms#1350]
**Describe the bug**

String elements within an array are not being rendered, returning a 'No applicable cell found' message - this looks like a regression in v2.2.3

**To Reproduce**

```
{
   "type":"object",
   "properties":{
      "test":{
         "type":"array",
         "items":{
            "type":"string"
         }
      }
   }
}
```
**Expected behavior**

String input field rendered for each array element as in v2.2.2

**Browser**
 - Chrome

**Used Setup**
 - React
 - Material

**Additional context**

v2.2.3 improvements otherwise👌

**Comment by eneufeld** [comment]
Hi, did you see this breaking change:
`fields` have been replaced by `cells`
Is your store setup not correct because of this and thus the table is not finding the cells?
```
jsonforms: {
        cells: cells,
        renderers: renderers
}
```

**Comment by johnmorrell** [comment]
Thank you @eneufeld I missed this change, switching to cells resolved the issue.
