### ISSUE TITLE
Decimals lower than 0.1 are unsupported in 'number' fields

### ISSUE THREAD

**Issue by johnmorrell** [eclipsesource/jsonforms#1352]
**Describe the bug**

Entering a decimal lower than 0.1 (eg: 0.09) in to a number field, clears the file on the entry of the zero after the decimal place.

**To Reproduce**

Enter 0.09 in to a number field

**Expected behavior**

Decimals of lower than 0.1 to be retained in the UI and data

**Browser**
 - Browser: Chrome

**Used Setup**
 - Framework: react
 - RendererSet: material

**Additional context**

**Comment by eneufeld** [comment]
fixed via #1353
