### ISSUE TITLE
Small typo in side menu

### ISSUE THREAD

**Issue by guntur-ricardo** [eclipsesource/jsonforms#1357]
**Describe the bug**
I know you guys are updating the docs (awesome!). Just spotted a small typo with 'Renderers' in the side menu. See below.

![image](https://user-images.githubusercontent.com/31665531/56904549-7d237a00-6a6c-11e9-9456-69a75bd05edf.png)

Thanks!

**Comment by edgarmueller** [comment]
Thanks, it has been fixed!
