### ISSUE TITLE
[Question] Multiple Checkboxes

### ISSUE THREAD

**Issue by guntur-ricardo** [eclipsesource/jsonforms#1358]
**Describe the question**
Hi! I know there was a question about this in the backlog but I didn't want to necro that thread.

I'm trying to create 1 component where the user can select multiple checkboxes. The usage is for the user to select authentication scopes. IE: Read-Only: True, Write-Only:False

If this isn't currently supported, can you please point me in the right direction to set up some custom work?

**Code Sample**
This is the closest thing I have setup but these are separate inputs. I'm looking for one input with multiple checkboxes.
![image](https://user-images.githubusercontent.com/31665531/56905229-d4761a00-6a6d-11e9-9c5a-45cfb01661b5.png)

**Screenshots**
What it looks like.
![image](https://user-images.githubusercontent.com/31665531/56905102-a1338b00-6a6d-11e9-967b-2ce079bae400.png)

**Browser (please complete the following information):**
 - Browser Chrome, Mozilla

**Used Setup (please complete the following information):**
 - Framework: **React**
 - RendererSet: **Material**

**Comment by edgarmueller** [comment]
Depending on the type of boolean control and whether the selection is exclusive or not I think the [`MaterialGroupRadioControl`](https://github.com/eclipsesource/jsonforms/blob/master/packages/material/src/controls/MaterialRadioGroupControl.tsx) is what probably covers your use case or at least can act as a template. This control is not used by default because it expects an option to be set (namely `'format'` to '`radio`') and the prio is also too low currently, so if you want to make use of it, you should register it with your own custom tester. Let us know whether this helps.

**Comment by guntur-ricardo** [comment]
Thanks @edgarmueller!

This might be a dumb question but how do I import MaterialGroupRadioControl if it's not exported in the controls/index.ts file? I see that other Testers/Controls are included in that file.

**Comment by eneufeld** [comment]
You can import it directly `import MaterialGroupRadioControl,{materialRadioGroupControlTester} from '@jsonforms/material-renderers/controls/MaterialRadioGroupControl'`

**Comment by guntur-ricardo** [comment]
@eneufeld thanks. It looks like my MaterialRadioGroupControl doesn't match what's on this repo. I'm missing the export for the Tester. Are these updates included in 2.2.3? If so I may have messed up my npm install.

![image](https://user-images.githubusercontent.com/31665531/56925640-eb346500-6a9d-11e9-936b-ca86c34c3cfb.png)

**Comment by eneufeld** [comment]
strange, the tester should be part of the release:
https://github.com/eclipsesource/jsonforms/blob/6580c02c45fec40c51dd86b195ce02b5be1fb8df/packages/material/src/controls/MaterialRadioGroupControl.tsx#L109

**Comment by guntur-ricardo** [comment]
Alright, I'll debug my setup and report back. Thanks!

**Comment by guntur-ricardo** [comment]
@eneufeld I've cleared up my npm package and got the updated files.

I'm using create a react app and this import worked for me.
import MaterialGroupRadioControl, {materialRadioGroupControlTester} from "@jsonforms/material-renderers/lib/controls/MaterialRadioGroupControl";

Now I'll trying using this component for my use case. Thanks!

**Comment by edgarmueller** [comment]
Just a quick note as stated in my earlier comment: You might need to provide your own tester anyway (and we should fix this) because `materialRadioGroupControlTester` specifies a priority of 2, which is the same as for the default renderer, hence it might not be picked up.

**Comment by guntur-ricardo** [comment]
Just an update:

The **materialRadioGroupControlTester** wasn't right for my use case but still learned from it. I decided to branch off of the **MuiSelect** component and passed in the _multiple=True_ property, since I needed the user to be able to enable/disable multiple permission settings.

It's in JS and allows multiple options to be selected. The value is stored as an array. I'm using <SelectField> because we need to update our material lib.


```
export class MaterialEnumField extends Component {
    state = {
        values: []
    };
    
doChange = (event, index, values) => {
        this.setState({values})
        this.props.handleChange(this.props.path, values)
    };

    render() {
        let {schema} = this.props;
        const {values} = this.state;
        const options = schema.items.enum;

        return (
            <SelectField
                value={values}
                onChange={this.doChange}
                fullWidth={false}
                multiple={true}
                hintText={schema.hintText}
            >
                {
                    options.map(optionValue =>
                        (
                            <MenuItem value={optionValue}
                                      key={optionValue}
                                      primaryText={optionValue}
                                      checked={values && values.indexOf(optionValue) > -1}
                                      insetChildren={true}
                            />
                        )
                    )
                }
            </SelectField>
        );
    }
}
```


The control I made was simple and checked if scope ends with scope (permission scopes)
```
import {
  rankWith,
  scopeEndsWith
} from '@jsonforms/core';

export default rankWith(
  Number.MAX_VALUE,
  scopeEndsWith('scope')
);
```

I initially did not nest **enum** in **items** and that added the **allowedValues** validation which would not work since the value is an array and not an individual string. Nesting it in **items** seem to do the trick.
```
                "scope": {
                    "type": "array",
                    "items": {
                        "type": "string",
                        'enum': ['Read-Access', 'Write-Access', 'Full-Access']
                    },
                    "hintText": "Scope"
                }
```
This all seems to work thanks to your help!
