### ISSUE TITLE
Custom rules and layouts just like custom renderers

### ISSUE THREAD

**Issue by nlac** [eclipsesource/jsonforms#1362]
Hello,
i guess it would be great to allow and give a receipt for writing custom rules and layouts instead of just using the hard-coded ones. It would greatly widen the possibilities the community could achieve with jsonforms.

**Comment by edgarmueller** [comment]
Ok, thanks for your input. We'll try to add some documentation for the next release.

**Comment by eneufeld** [comment]
@nlac I created a PR for the custom layouts: https://github.com/eclipsesource/jsonforms2-website/pull/63

Could you explain what you want to achieve with custom rules? I would extend the rule docu accordingly.

**Comment by nlac** [comment]
Hi, thanks for it!
For custom rules, i didn't have a specific goal in mind. I just had a feeling that custom rules could be a proper place where other special behaviors can be hooked to controls, beside hiding and disabling them. Perhaps, for example, a kind of rule could dynamically populating the "enum" property of a control based on the filled data of an another control (eg. a multiple select, or and array of strings)? But this example may be out of the original scope of the rules.

**Comment by eneufeld** [comment]
Hi, 
yes the example you describe is outside the scope of the rules.

I would suggest to keep the scope of this issue then to document custom layouts.
If you need more info on how to use rules or want to extend the current functionality of the rules, please open a new issue.

**Comment by nlac** [comment]
Ok i got it. If you guys neither have any more useful aspect in mind (beside the two existing) that could be implemented by custom rules, there's no urge to document how to implement one.

**Comment by sdirix** [comment]
Merged eclipsesource/jsonforms2-website#63
