### ISSUE TITLE
documentation removed about providing ui schemas

### ISSUE THREAD

**Issue by nlac** [eclipsesource/jsonforms#1372]
Hi, i think it would be really useful to have it again https://jsonforms.io/docs/providing-uischemas, referred on several places earlier like https://github.com/eclipsesource/jsonforms/issues/1267

Now the doc has very little information about ui schemas.

**Comment by edgarmueller** [comment]
Thanks for pointing it out, we'll update the docs soon.

**Comment by sdirix** [comment]
Looking at it I noticed that most of the information was migrated to the [Available Actions](https://jsonforms.io/docs/available-actions) page. We'll also restore the `findUISchema` part.

**Comment by buskerone** [comment]
@sdirix I still don't see any documentation for uischemas apart of a small description here: [https://jsonforms.io/docs/integrations/react#uischemas](https://jsonforms.io/docs/integrations/react#uischemas)

Is there any other place that can explain how to use it?
