### ISSUE TITLE
Material Array renderer: Support for Element order change.

### ISSUE THREAD

**Issue by shivgarg5676** [eclipsesource/jsonforms#1378]
I am new to this project, so I might be wrong here.
Currently, array renderer does not support Element order change. Is it possible to change the order of elements in the array?
If not I think we should have support for this.

**Comment by edgarmueller** [comment]
Are you referring to the table-based array renderer? Either way, it's currently not supported, but you can always roll your own [custom controls](https://jsonforms.io/docs/custom-renderers). Maybe it also make sense to implement some sort of generic sort mechanism based on the data type for table, but this is currently not something we'll be able to work on

**Comment by shivgarg5676** [comment]
I am not talking about sorting but the ability to change the index of elements in an array. Something like this. 
![image](https://user-images.githubusercontent.com/6873680/58147483-537afe80-7c78-11e9-836b-691353aa7d6c.png)
https://mozilla-services.github.io/react-jsonschema-form ---> Array

I agree we can always roll custom controls. But it is nice to have such basic functionality.

**Comment by edgarmueller** [comment]
I see, thanks for clarifying. Yes that might make sense; it should probably also be configurable via `options`. Would you like to contribute by implementing this?

**Comment by shivgarg5676** [comment]
sure @edgarmueller, I would like to create this functionality and contribute.

**Comment by shivgarg5676** [comment]
@edgarmueller is there any chat room like discord etc. to ask a few handful questions about the source code?

**Comment by edgarmueller** [comment]
No, currently not, but this is a good idea. We'll set up something.

**Comment by eneufeld** [comment]
@shivgarg5676 we created a chat room: https://spectrum.chat/jsonforms

**Comment by shivgarg5676** [comment]
Thanks, @eneufeld. I joined the chat room. Will update the documentation.

**Comment by shivgarg5676** [comment]
@eneufeld  can we close this issue now or we close issues after the feature is pushed live?

**Comment by eneufeld** [comment]
Fixed with 2ee1ec1980e2dd1359f49dffa700156e23ad1ad0
