### ISSUE TITLE
[question] questions related to material-ui rendering

### ISSUE THREAD

**Issue by sahilkhosla** [eclipsesource/jsonforms#1383]
1. What's the difference between `src/mui-controls` and `src/controls`?

1. I want to customize the material-ui components rendered by JSONForms utilizing the `props` that are supported out of the box. How can I do so? 

1. How can I check which material-ui components are currently supported and specifically what the JSONSchema/UISchema looks like for each? Are there any examples? For example: How can I render `MaterialSliderControl`?

**Comment by sdirix** [comment]
Hi @sahilkhosla. Thanks for your interest in JSON Forms!

> 1. What's the difference between `src/mui-controls` and `src/controls`?

`mui-controls` contains small reusable components which are used in the actual JSON Forms controls and cells. For example `MuiInputNumber` is able to render a number input of material-ui and is reused in `MaterialNumberControl` and `MaterialNumberCell`. When we are talking about controls we usually refer to components which have `...Control` in their name.

> 2. I want to customize the material-ui components rendered by JSONForms utilizing the props that are supported out of the box. How can I do so?

This really depends on your use case and what you want to do:
 * For some of the material-ui components we are rendering, we already offer customization options. These are typically configured via the ui schema options object of the corresponding control. Therefore to customize these controls all you have to do is to adapt your ui schema.
Sadly we don't have nice documentation for that yet, so to see all configuration options which are currently available you'll need to check the code yourself. For example in [MuiInputNumber.tsx](https://github.com/eclipsesource/jsonforms/blob/4aa40d1ae42536aaef5d7a02b56d3d345f6b3cd0/packages/material/src/mui-controls/MuiInputNumber.tsx) you can see that you can configure the material-ui autofocus via an `options: { focus: yourValue }` object attached to the corresponding control in the ui schema.
 * If you want to use something we don't support yet or to get full control in general you'll need to register your own renderers (e.g. controls) and testers. JSON Forms checks all testers for each ui schema element and the one with the highest rank wins. The associated renderer is then called to generate the UI. Your renderers can (but don't have to) connect to redux and therefore use the same `props` a framework-provided renderer uses too. Please check the [jsonforms-react-seed](https://github.com/eclipsesource/jsonforms-react-seed) to see how an own [renderer](https://github.com/eclipsesource/jsonforms-react-seed/blob/21f5116ab08f15dc2d90cf50a3157cf6c1e52dd5/src/RatingControl.tsx) and [tester](https://github.com/eclipsesource/jsonforms-react-seed/blob/21f5116ab08f15dc2d90cf50a3157cf6c1e52dd5/src/ratingControlTester.js) can be implemented and connected to JSON Forms.

> 3. How can I check which material-ui components are currently supported and specifically what the JSONSchema/UISchema looks like for each?

We provide an overview over the available renderer sets and their feature set on the offical [JSON Forms website](https://jsonforms.io/docs/renderer-sets). There is also an [ui schema section](https://jsonforms.io/docs/uischema) describing which ui schema elements are supported in general. However we don't have a comprehensive list of schema, ui schema and ui schema options combinations and how they are rendered in each renderer set. To check what is supported you'll need to check the code. 

> 3. Are there any examples?

We maintain examples covering most of the options (but not all of them). You can check the [examples](https://github.com/eclipsesource/jsonforms/tree/4aa40d1ae42536aaef5d7a02b56d3d345f6b3cd0/packages/examples) package. To execute the examples with the react/material renderer set switch to the `packages/material` directory and execute `npm run dev`.

> 3. For example: How can I render `MaterialSliderControl`?

To check when the `MaterialSliderControl` is rendered you'll need to check its tester and when it indicates that it wants to be rendered. So let's take a look at the [MaterialSliderControl.tsx](https://github.com/eclipsesource/jsonforms/blob/4aa40d1ae42536aaef5d7a02b56d3d345f6b3cd0/packages/material/src/controls/MaterialSliderControl.tsx):
```typescript
export const materialSliderControlTester: RankedTester = rankWith(4, isRangeControl);
```
As you can see it returns a priority of 4 when `isRangeControl` returns `true`. So let's check that method. The implementation is located in [packages/core/src/testers](https://github.com/eclipsesource/jsonforms/blob/4aa40d1ae42536aaef5d7a02b56d3d345f6b3cd0/packages/core/src/testers/index.ts) and looks like this:
```typescript
/**
 * Tests whether a given UI schema is of type Control,
 * if the schema is of type number or integer and
 * whether the schema defines a numerical range with a default value.
 * @type {Tester}
 */
export const isRangeControl = and(
  uiTypeIs('Control'),
  or(schemaTypeIs('number'), schemaTypeIs('integer')),
  schemaMatches(
    schema =>
      schema.hasOwnProperty('maximum') &&
      schema.hasOwnProperty('minimum') &&
      schema.hasOwnProperty('default')
  ),
  optionIs('slider', true)
);
```
As you can see that reads quite nicely. It returns `true` when the ui schema type is a `Control` and the corresponding schema is of type `number` or `integer` and has a `maximum`, `minimum` and `default` value defined. Also the ui schema needs to have an `options` object in which `slider` is set to `true`.

Therefore the `MaterialSliderControl` is used for the following schema and ui schema, if there is not another tester which returns a higher rank:
```javascript
schema: {
  type: 'object',
  properties: {
    drivingSkill: {
      type: 'number',
      maximum: 10,
      minimum: 1,
      default: 7
    }
  }
},
uischema: {
  type: 'Control',
  scope: '#/properties/drivingSkill',
  options: {
    slider: true
  }
}
```
![SliderControl](https://user-images.githubusercontent.com/8998368/58328804-553cf180-7e33-11e9-92e5-a4d8f08275e0.png)


I hope this is helpful to you. We are aware of that our current documentation does not cover the full feature set of JSON Forms and we are actively working on improving it in the future (#1203). Of course any contribution is welcomed too ;)

Feel free to ask further questions if you need more help

**Comment by sahilkhosla** [comment]
Thank you @sdirix! Your response was very helpful. We are playing with all the options to see how well JSONForms will adapt to our requirements. I will be in touch again with further questions.
