### ISSUE TITLE
[React] - When is a stable release with Material-UI v4 expected?

### ISSUE THREAD

**Issue by sahilkhosla** [eclipsesource/jsonforms#1399]

**Comment by edgarmueller** [comment]
Definitely not June anymore, we'll probably do some more alpha and/or beta releases, but not a stable one. My guess is that we'll be able to release 2.3.0 sometime next month. Hope that answers your questions, if not feel free re-open.

**Comment by sahilkhosla** [comment]
Got it, thanks!
