### ISSUE TITLE
v2.3.0-alpha.0: Group Labels in Array Layout

### ISSUE THREAD

**Issue by Lily418** [eclipsesource/jsonforms#1403]
**Describe the bug**
When updating to v2.3.0-alpha.0 from v2.2.3 I noticed that the Group Layout labels now include an index number and the label for it's parent.

## v2.2.3
![Screenshot 2019-06-13 at 15 30 44](https://user-images.githubusercontent.com/1368025/59441620-c8150900-8df0-11e9-8614-a67b9a0a50fd.png)

## v2.3.0-alpha.0 
![Screenshot 2019-06-13 at 15 07 14](https://user-images.githubusercontent.com/1368025/59441673-dc590600-8df0-11e9-88d9-7dbb301dcb7f.png)

I used this schema
```
{
  type: 'object',
  properties: {
    ...personCoreSchema.properties,
    personalData: {
      type: 'array',
      items: {
        type: 'object',
        properties: {
          animal: {
            type: 'object',
            properties: {
              name: {
                type: 'string'
              },
              color: {
                type: 'string'
              }
            }

          },
          height: {
            type: 'number'
          },
          drivingSkill: {
            type: 'number',
            maximum: 10,
            minimum: 1,
            default: 7
          }
        }
      },
      required: ['age', 'height']
    },
    vegetarian: {
      type: 'boolean'
    },
    birthDate: {
      type: 'string',
      format: 'date'
    },
    occupation: {
      type: 'string'
    },
    postalCode: {
      type: 'string',
      maxLength: 5
    }
  },
  required: ['occupation', 'nationality']
}
```

**Expected behavior**
I expected the behaviour in v2.2.3, I don't want to show users labels with the array index. Also it looks spooky when it's deeply nested 👻 

(Previously this label read Usual Range)
![Screenshot 2019-06-13 at 15 38 55](https://user-images.githubusercontent.com/1368025/59442033-5ee1c580-8df1-11e9-8cb5-80d32e94dc18.png)

**Browser**
 - Browser Firefox 
 - Version 67.0.1

**Used Setup (please complete the following information):**
 - Framework: React
 - RendererSet: Material

**Comment by eneufeld** [comment]
Hmm, yes this looks weird, we will check.
