### ISSUE TITLE
v2.3.0-alpha.0 Performance Rendering React

### ISSUE THREAD

**Issue by Lily418** [eclipsesource/jsonforms#1407]
**Describe the bug**
Between v2.2.3 and v2.3.0-alpha.0 speed of rendering has decreased

**To Reproduce**
1. Running the Material Package Examples
2. Choose "Huge Test" example
3. Observe that in v2.3.0-alpha.0 when typing in a field takes ~0.5s to render, v2.2.3 is noticable faster to render

**Browser (please complete the following information):**
 - Browser Firefox
 - Version 67.0.2

**Used Setup (please complete the following information):**
 - Framework:React
 - RendererSet: Material

**Additional context**
I'm going to run the React Profiler to see if I can determine the cause

**Comment by Lily418** [comment]
Ah looks like #1406 is about this

**Comment by edgarmueller** [comment]
Yes, indeed, we noticed that performance degrade as well and working on it. Thanks for report.

**Comment by edgarmueller** [comment]
This should be fixed via #1406. If you experience significant slow-downs related to the context-based API, please re-open.

**Comment by georgiosd** [comment]
Is this still an issue @edgarmueller? Editing a text item in a nested array causes tons of re-renders as shown below.

<img width="659" alt="Screenshot 2020-09-22 at 1 10 07 PM" src="https://user-images.githubusercontent.com/1672054/93869804-fd3b2700-fcd4-11ea-925d-2667e89b12db.png">
