### ISSUE TITLE
v2.3.0-alpha.0: Add AJV and refParserOptions to JsonFormsInitStateProps

### ISSUE THREAD

**Issue by Lily418** [eclipsesource/jsonforms#1408]
As per this conversation with @edgarmueller on Spectrum Chat
https://spectrum.chat/jsonforms/general/providing-refparseroptions-and-custom-ajv-instance-to-context-based-json-forms~3a7accf9-01c4-409c-a4cf-832ef4deddc6

In v2.2.3 it was possible to initialize a store like
```
  store.dispatch(Actions.init(drugData, drugSchema, uischema, {
    ajv: ajv,
    refParserOptions: {
      resolve: {
        customerResolver
      }
    }
  }))
```

In JsonFormsInitStateProps 
```
export interface JsonFormsInitStateProps {
    data: any;
    schema: JsonSchema;
    uischema: UISchemaElement;
    renderers: JsonFormsRendererRegistryEntry[];
}
```

ajv and refParserOptions are currently not implemented.

I'm intending to take a look to see if I can make a PR this morning.

**Comment by edgarmueller** [comment]
Fixed via #1410
