### ISSUE TITLE
Is it possible to exclude values in the data result?

### ISSUE THREAD

**Issue by jj321** [eclipsesource/jsonforms#1434]
Hello all,

I want to hide the key/ value pair in the data result when a field is hidden.
For example: taking the rule example:
https://jsonforms.io/examples/rule

When changing the rule to SHOW if the 'alive' checkbox is checked, is it possible to remove the 'kindOfDead' from the data result when the 'alive' checkbox is false and only include it when the rule is met and the is alive checkbox is true?

Kind regards,

Jaap

**Comment by edgarmueller** [comment]
It's not possible out-of-the-box, but I _think_ you could achieve this behavior if you were to write a custom renderer. The renderer would check 

1. whether the `visible` prop is false
2. and whether the `uischema` prop has a rule attached to it

If both conditions apply it'd then trigger an `update` action which would clear the respective piece of data. The update would need to happen in a `componentDidUpdate`/`useEffect` likecycle hook. 
There's probably a cleaner way of handling (ideally this would be handled by the reducer, I guess?), but right now I can't think of any. Let me know if this helps.

**Comment by sdirix** [comment]
We'll close this issue for now. Let us know if you have any questions.

**Comment by luiz290788** [comment]
@sdirix is the suggestion above the final solution for this problem? Or is there any other way to solve it?
