### ISSUE TITLE
is this lib generic enough to integrate with Ant Design?

### ISSUE THREAD

**Issue by videni** [eclipsesource/jsonforms#1440]
hi, I am looking for JSON form schema lib that can be integrated with third party library, such as Ant Desigin,  is this lib good for this?  I checked [mozilla-services/react-jsonschema-form](https://github.com/mozilla-services/react-jsonschema-form) which is not useful for my case.

**Comment by edgarmueller** [comment]
We currently do not have a renderer set for Ant Design, but you can of course provide one. It also would be a great addition. We did this for Material UI as you probably saw and I it should serve as a good template for how to create a Ant Design renderer set. We also provide a react binding (`@jsonforms/react`) which provides the generic functionality needed to provide such a React-based renderer set.

**Comment by sdirix** [comment]
Related discussion on Spectrum: https://spectrum.chat/jsonforms/general/custom-ui~6d846359-d7d9-4610-9cfa-06952c57d593

**Comment by sdirix** [comment]
I will close this for now. Feel free to comment here or in Spectrum if you have further questions

**Comment by DrewHoo** [comment]
I can say definitively that jsonforms can work with antd =) check out our antd renderer package here: https://www.npmjs.com/package/@great-expectations/jsonforms-antd-renderers

**Comment by axetroy** [comment]
> I can say definitively that jsonforms can work with antd =) check out our antd renderer package here: [npmjs.com/package/@great-expectations/jsonforms-antd-renderers](https://www.npmjs.com/package/@great-expectations/jsonforms-antd-renderers)我可以肯定地说 jsonforms 可以与 antd 一起使用 =) 在这里查看我们的 antd 渲染器包： [npmjs.com/package/@great-expectations/jsonforms-antd-renderers](https://www.npmjs.com/package/@great-expectations/jsonforms-antd-renderers)

Looks great! Could this be an officially supported renderer?
