### ISSUE TITLE
Rule in categorization example not working

### ISSUE THREAD

**Issue by AlexandraBuzila** [eclipsesource/jsonforms#1461]
**Describe the bug**
The categorization example contains a rule that should hide the `Additional` category based on the value of the `vegetarian` property. However, this is not working and the category tab is not hidden.

I tested this from the documentation project: https://github.com/eclipsesource/jsonforms2-website

**Steps to repdoduce**
- navigate to the `/examples/categorization` page to see the categorization

**Browser:**
 - Browser: Chrome 
 - Version 75.0.3770.142 

**Used Setup:**
 - Framework: react
 - RendererSet: material

**Additional context**
Tested with the 2.3.0 beta 0 version.

**Comment by tujger** [comment]
The rule is still working incorrect, even in [official example](https://jsonforms.io/examples/categorization).
Uncheck "Provide Address" and check "Vegetarian", you'll have the content of "Address" in "Additional" tab; content of "Additional" tab is not available.
