### ISSUE TITLE
TypeError: Cannot read property 'showUnfocusedDescription' of undefined

### ISSUE THREAD

**Issue by Naveenraj006** [eclipsesource/jsonforms#1462]
I came up with this error in reactjs. I tried the basic example of JSON forms with material Renderer.

https://user-images.githubusercontent.com/6183340/61995824-dff7d200-b0aa-11e9-91f6-8244e48a0841.png)

**Comment by sdirix** [comment]
Thanks for the report. Sadly I'm not sure what exactly causes this problem for you. Could you provide some more details? Ideally you could send us a code snippet or example app which reproduces the problem. Did you try our [react-seed application](https://github.com/eclipsesource/jsonforms-react-seed)?

**Comment by QuentinMichotte** [comment]
I have the exact same bug in my React application :
![image](https://user-images.githubusercontent.com/26580406/62131396-6b57aa00-b2db-11e9-970b-881e4ac5144b.png)

gives me this error : 
![image](https://user-images.githubusercontent.com/26580406/62131446-832f2e00-b2db-11e9-93c6-98735c1c223f.png)

this line is causing the problem
![image](https://user-images.githubusercontent.com/26580406/62131532-aa85fb00-b2db-11e9-8c51-4f0c1d1bea55.png)

**Comment by sdirix** [comment]
Thank you for the very detailed information! We'll take a look soon.

**Comment by Lily418** [comment]
showUnfocusedDescription is a new property of config, seems like the default configuration is not being used by default. 

As a workaround provide this configDefault as the inital config 

```
export const configDefault = {
  /*
   * [text] whether to restrict the number of characters to maxLength,
   * if specified in the JSON schema
   */
  restrict: false,

  /*
   * [text] whether to resize the input's width to maxLength,
   * if specified in the JSON schema
   */
  trim: false,

  /*
   * [text] if input descriptions should hide when not focused
   */
  showUnfocusedDescription: false
};
```
