### ISSUE TITLE
Update to Angular 8/9

### ISSUE THREAD

**Issue by sdirix** [eclipsesource/jsonforms#1463]
**Description**
Support Angular 8/9

**Describe for which setup you like to have the improvement**
Framework: [angular]
RendererSet: [angular-material]

**Comment by sdirix** [comment]
Also see https://github.com/eclipsesource/jsonforms/pull/1489

**Comment by ruimarques** [comment]
Is anything missing from #1489 besides the CI build fail?

**Comment by sdirix** [comment]
PR #1489 isn't tested and none of the testcases are running. We'll probably close this PR and focus on https://github.com/eclipsesource/jsonforms/pull/1532

**Comment by sdirix** [comment]
We moved to Angular 9 with https://github.com/eclipsesource/jsonforms/pull/1532. This will be part of the official `2.4.0` release. For now we released an alpha version which can be installed via
```bash
npm install @jsonforms/core@next @jsonforms/angular@next @jsonforms/angular-material@next
```
or
```bash
npm install @jsonforms/core@2.4.0-alpha.0 @jsonforms/angular@2.4.0-alpha.0 @jsonforms/angular-material@2.4.0-alpha.0
```
