### ISSUE TITLE
Support @material-ui/core v4.3.0 remove dependency to @material-ui/lab

### ISSUE THREAD

**Issue by Schloemicher** [eclipsesource/jsonforms#1464]
**Description**
Support @material-ui/core v4.3.0
Remove dependency @material-ui/lab

Slider is now in the core package 

**Describe for which setup you like to have the improvement**
Framework: [react]
RendererSet: [material-renderers]

Related Pull request: #1025

**Comment by sdirix** [comment]
Thanks for creating the issue. We'd also like to remove `@material-ui/lab` (see #1028).

**Comment by woodreamz** [comment]
Good idea! I use jsonforms and material-ui 4.3.0. As jsonforms uses material-ui ~4.0.1, I have two instances of material-ui which is bad :(

What do you think about make material-ui a peer dependency (and externalized by webpack)?

**Comment by edgarmueller** [comment]
Sounds good! We'll take care of that.

**Comment by edgarmueller** [comment]
The peer dependencies have been configured via d0c756ec181ffefb319abe10960a8ad41af82fca
