### ISSUE TITLE
JsonForms is not refreshed when props are updated.

### ISSUE THREAD

**Issue by woodreamz** [eclipsesource/jsonforms#1467]
Hi,

Thank you for the good work with jsonforms!

**Describe the bug**
I recently updated my react app to jsonforms 2.3.0. As we can now use JsonForms without redux, I removed the redux integration. If i render a JsonForms with a schema A and then change to shcema B, JsonForms is not updated. It seems it does not re render when props change.

**To Reproduce**
Codesandbox : https://codesandbox.io/embed/json-formsrender-issue-5ukvm

1. Open the codesandbox
2. Click on 'Change name'
3. JsonForms should be updated.

**Expected behavior**
JsonForms should be re rendered when props are updated.

**Screenshots**
N/A

**Browser (please complete the following information):**
 - Browser: Chrome
 - Version: 76.0.3809.87

**Used Setup (please complete the following information):**
 - Framework: React
 - RendererSet: Material
 - "@jsonforms/core": "2.3.0"
 - "@jsonforms/material-renderers": "2.3.0"
 - "@jsonforms/react": "2.3.0"

**Additional context**
N/A

Thanks !

**Comment by sdirix** [comment]
Thanks for the detailed bug report. We plan to take a look at this for the next release.

**Comment by DavidHenri008** [comment]
I have the same issue

**Comment by woodreamz** [comment]
Maybe I am wrong but the useEffect [here](https://github.com/eclipsesource/jsonforms/blob/927e387935b3413463c3bde4cadf49ba495b20af/packages/react/src/JsonFormsContext.tsx#L98) has no dependency, if we change this to: 
`const { data, schema, uischema, ajv, refParserOptions } = initState.core;
  useEffect(() => {
    dispatch(Actions.init(data, schema, uischema, { ajv, refParserOptions }));
  }, [initState.core]);`

It could fix the issue?

**Comment by edgarmueller** [comment]
@woodreamz Yep, seems like it (I didn't have a look yet as I'm on vacation). This would be a good opportunity to create a PR :)

**Comment by sdirix** [comment]
Fixed by #1468

**Comment by woodreamz** [comment]
Thanks!

**Comment by woodreamz** [comment]
I think this issue is not completly fixed.

Jsonforms is refreshed when I change the schema but each input are rendered two times, the first time with the old label, the second time with the good one.

 I am trying to reproduce in codesandbox but jsonforms/react 2.3.1 is not working. I will figure out why.
