### ISSUE TITLE
[angular] table does not correctly propagate read-only state to children

### ISSUE THREAD

**Issue by edgarmueller** [eclipsesource/jsonforms#1479]
**Describe the bug**
When setting an UI schema containing a table to readonly, its children are still enabled.

**Comment by sdirix** [comment]
@LukasBoll Can you check whether this still occurs or was fixed in the mean time?

**Comment by LukasBoll** [comment]
`Readonly `works for tables and is propagated correctly to all children.
But I also checked the array-renderer and this one doesn’t work!
