### ISSUE TITLE
Documentation: Need to update Create a JSON Forms App (Redux) page. 

### ISSUE THREAD

**Issue by shivgarg5676** [eclipsesource/jsonforms#1483]
On the documentation website https://jsonforms.io, somehow we have missed updating the https://jsonforms.io/docs/tutorial-redux page. This still holds documentation of v2.2.0 and needs to be updated. 

Wanted to update that but I could not find the repo for the same. Can someone update that page?

**Comment by edgarmueller** [comment]
@shivgarg5676 thanks for point this out. The repo is here https://github.com/eclipsesource/jsonforms2-website in case you want to submit a PR

**Comment by shivgarg5676** [comment]
https://github.com/eclipsesource/jsonforms2-website/pull/70/files

**Comment by sdirix** [comment]
@shivgarg5676 Thank you very much!
