### ISSUE TITLE
uischema prop is required

### ISSUE THREAD

**Issue by hayk94** [eclipsesource/jsonforms#1504]
**Describe the bug**
In the docs https://jsonforms.io/examples/gen-uischema it says 

> If you provide no UI schema to JSON Forms it'll generate one.

However I am using typescript with react and TS complains if I don't provide `uischema`  prop.

![image](https://user-images.githubusercontent.com/9801183/65507561-3cc30d80-dedf-11e9-9cc2-aa029e512307.png)

This is probably just type problems.

**Comment by edgarmueller** [comment]
Hi, thanks for the report! The standalone component currently does not generate a UI schema by default, so we should either fix this or update the docs. We'll try to address it for the next release. You can get the behaviour by generating a UI schema yourself by calling `Generate.uiSchema` and passing in the schema.

**Comment by sdirix** [comment]
Implemented with #1515
