### ISSUE TITLE
Increase version of react-redux to ^6.0.0 || ^7.0.0

### ISSUE THREAD

**Issue by DavidHenri008** [eclipsesource/jsonforms#1507]
**Describe the bug**
It would be great to increase the possible version of peer dependency react-redux to include 7.0.0. Otherwise, it creates a warning when this package is used in an application using react-redux version 7.0.0.
```
warning " > @jsonforms/react@2.3.1" has incorrect peer dependency "react-redux@^6.0.0".
```

**Comment by edgarmueller** [comment]
Thanks for the report, we'll update next release.
