### ISSUE TITLE
Mouse over date and dropdown fields causes them to resize

### ISSUE THREAD

**Issue by Carus11** [eclipsesource/jsonforms#1508]
When I move my mouse over date fields, and dropdown fields, they resize causing the form to jump around. This can be seen on the jsonforms.io home page:

![jsonforms](https://user-images.githubusercontent.com/4925828/66256572-5d475f00-e74c-11e9-8c16-fb39bbec1b04.gif)

**Comment by edgarmueller** [comment]
Thanks for the report, we'll have a look

**Comment by sdirix** [comment]
The issue occurs because of a Chrome bug: https://bugs.chromium.org/p/chromium/issues/detail?id=992010

It is fixed with the next major version of Chrome.

**Comment by sdirix** [comment]
@Carus11 With the latest Chrome `Version 78.0.3904.70` this is now fixed for me. Can you confirm?

**Comment by Carus11** [comment]
Yes I can confirm this issue was resolved by upgrading my browser to chrome 78.
Thanks for looking into it!
