### ISSUE TITLE
Using jsonforms without redux

### ISSUE THREAD

**Issue by iluuu1994** [eclipsesource/jsonforms#1519]
**Describe the bug**

The tutorial [Create a JSON Forms App](https://jsonforms.io/docs/tutorial) doesn't require redux (I assume at least). However, as soon as I import `@jsonforms/react` I get the following error:

```js
import { JsonForms } from '@jsonforms/react';
```

```log
This dependency was not found:

* react-redux in ./node_modules/@jsonforms/react/lib/JsonFormsContext.js
```

**To Reproduce**

```jsx
import React from 'react';
import ReactDOM from 'react-dom';
import { JsonForms } from '@jsonforms/react';

ReactDOM.render(
    <p>Hello, world!</p>,
    document.getElementById('root')
);
```

That's literally my whole example.

Let me know if I can provide more information. Thank you!

**Comment by iluuu1994** [comment]
I included redux and it's working now, if this is expected behaviour feel free to close the issue. 🙂

**Comment by sdirix** [comment]
Yes that is currently expected. Explanation: For a long time we only supported usage with `redux`. Therefore the redux dependency is everywhere, even in the `@jsonforms/core`. The standalone component is a recent development and also only available for the React renderers, not Angular. For now you need to add redux as a dependency. At some point in the future we might clean this up and extract the redux integration into its own package, but we have no planned date for this.

**Comment by iluuu1994** [comment]
@sdirix Thank you for your response! I'm really exited to have found this project. There's dozens of libraries with similar goals but this looks like the best one so far 🙂

**Comment by Viswanathan24** [comment]
> I included redux and it's working now, if this is expected behaviour feel free to close the issue. 🙂

How do i use this example without redux, if you have any example please share it

**Comment by sdirix** [comment]
Hi @Viswanathan24, we're working on removing the Redux dependency completely with one of the next versions of JSON Forms. You can already use the JSON Forms component without touching any Redux at all, however it must be there during compile time. If you have more questions please check our [Spectrum community](https://spectrum.chat/jsonforms).

**Comment by Viswanathan24** [comment]
> Hi @Viswanathan24, we're working on removing the Redux dependency completely with one of the next versions of JSON Forms. You can already use the JSON Forms component without touching any Redux at all, however it must be there during compile time. If you have more questions please check our [Spectrum community](https://spectrum.chat/jsonforms).

Hi Sdirix , need a solution for  integrating Json forms to existing React application, i have standalone JsonForms app with typescript based on Redux , my requirement is to combine JSON form app into another react application in which i am finding difficulties  to combine both stores of the application. Also please let me know if any other approaches available creating JSON FORMS without redux store.
