### ISSUE TITLE
Improve UX input validation errors (React/Material)

### ISSUE THREAD

**Issue by LaszloDev** [eclipsesource/jsonforms#1535]
**Is your feature request related to a problem? Please describe.**
The user experience regards the input errors is not great in the moment. A user sees the form and directly sees errors in red like "... is a required property" ( which is already indicated by the *-symbol in the label) or while typing "should be >= 1000".

Input validation error are always shown, even **before** a user types an input and **until** his input is valid.

**Describe the solution you'd like**
As you can see on Airbnb user interfaces, the users does not see errors until he clicked "next", only then a validation check is done and the user notified.
see: https://streamable.com/1cxj4

I would like to know if this is possible with Ajv and changing its behavior.
Running on React with Material Design elements.

**Comment by sdirix** [comment]
At the moment the errors are calculated and set on each data change. The renderers then unconditionally display their respective errors.

It would be nice to allow the user to configure/filter errors in a straightforward way or even turn off validation completely.

There are multiple ways how you could achieve the desired functionality with the current JSON Forms. For example you could register your own renderers which just delegate to the existing ones, but filter the errors until you want to show them. Another way to filter errors could be to wrap Ajv. Alternatively you could also use the `updateErrors` action to remove all of them manually.

**Comment by AlexandraBuzila** [comment]
Something to have in mind when adding support for on demand validation: ajv can also be configured to assign default values to any missing properties during validation.
Defaults are currently not set when the `data` prop is undefined (should probably be fixed).

**Comment by sdirix** [comment]
I'll close this as we now support validation customization with which the original question can be easily implemented. See #1567 for more information.
