### ISSUE TITLE
[Question] How to style vanilla renderer without store?

### ISSUE THREAD

**Issue by WhileTrueEndWhile** [eclipsesource/jsonforms#1536]
Hi and a happy new year,

I was just testing this wonderful library and I unexpectedly came up with a question. I hope I'm not asking something "too stupid".

Referring [jsonforms-react-seed](https://github.com/eclipsesource/jsonforms-react-seed/blob/master/src/App.tsx#L161) customization for material rendering is applied using `withStyles`.
I was unable to find a `withStyles` function for vanilla rendering.
As mentioned in #1003, there seems to be a way for vanilla rendering using the store.
If this is the only possibility, this would already be an answer :-)

How to add CSS classes to a blank `<JsonForm />` using vanilla rendering, but not using a store?
Respectively, is there an alternative to the old `JsonFormsHolder.stylingRegistry`?

[example.ts](https://github.com/edgarmueller/jsonforms/blob/b561291f8e4c075f35da3ad108f5117ac00c7c8d/example/example.ts#L149)
```javascript
JsonFormsHolder.stylingRegistry.registerMany([
  {
    name: 'button',
    classNames: ['btn', 'btn-primary']
  },
  {
    name: 'select',
    classNames: ['custom-select']
  },
]);
```

Thanks in advance!

**Comment by eneufeld** [comment]
Hi and a happy new Year to you, too. :fireworks: 

Just for completeness the docu for the store is [here](https://github.com/eclipsesource/jsonforms/blob/master/packages/vanilla/Styles.md).
I checked the code and I didn't find a possibility to set the styles using a JSONForms without the store at the moment. Could you please open an issue for the support for setting the stylingRegistry in the store-less usecase?

As we have more and more request about using the vanilla renderer set, I'm pretty confident, that we will add the possibility in the future. Still any contribution would be very appreciated.

If you have any further question please use our [Spectrum](https://spectrum.chat/jsonforms).

**Comment by sdirix** [comment]
I added the actions to our general redux-refactoring ticket: https://github.com/eclipsesource/jsonforms/issues/1537. As this issue will be handled there I'll close this ticket.

**Comment by WhileTrueEndWhile** [comment]
Thank you!

**Comment by sdirix** [comment]
@WhileTrueEndWhile As a workaround until we implemented this you can manually place your desired styles into the JSON Forms context. You can follow the recipe of this [Spectrum question](https://spectrum.chat/jsonforms/general/help-with-config~50828af8-d86e-40f4-ae94-a7ba9888dcf1). There a user wanted to place the global configuration object into the context, which at the moment is also only possible via actions. Instead of the `config` you can place your `styles` which would have been registered by the style actions.
