### ISSUE TITLE
Buttom of some text cut off on text and select fields, maybe more.

### ISSUE THREAD

**Issue by guntur-ricardo** [eclipsesource/jsonforms#1540]
**Describe the bug**
A small visual bug where the bottom of some text is cut off. It is more pronounce in my implementation, possibly from using a different font.

**To Reproduce**
1. See the jsonforms person example [here](https://jsonforms.io/examples/person). 
2. Under Additional Information, the letters [g, y, p] are slightly cut off on the buttom.

**Expected behavior**
I expect to see the full text without being clipped.

**Screenshots**
This is my implementation where the clipping is more pronounced.
![image](https://user-images.githubusercontent.com/31665531/74045849-80547a80-499b-11ea-8e15-3ad295139469.png)

**Browser (please complete the following information):**
 - Chrome
 - Version 79.0.3945.130 (Official Build) (64-bit)

**Used Setup (please complete the following information):**
 - Framework: React
 - RendererSet: Material

**Additional context**
Let me know if you need additional information.

**Comment by sdirix** [comment]
Hi @guntur-ricardo, thanks for the bug report.

It doesn't seem to be a problem in [Vanilla Material UI](https://material-ui.com/components/text-fields/), so we're probably doing something wrong.

Were you able to find a workaround? I could imagine that adapting the Material UI rendering via its theme support can generically solve the problem for you for now.

**Comment by guntur-ricardo** [comment]
Hello @sdirix 

I was able to override `MuiFormLabel` through `createMuiTheme` which fixed it. The override looks like this.

`            MuiFormLabel: {
                root: {
                    lineHeight: ''
                }
            },`

I was looking in the jsonForms package for `lineHeight: '1'` but was not able to find how your team styles the mui components.

I'm not a huge fan of changing properties globally for 1 issue. I have not yet checked if it messes up other usages of `MuiFormLabel` across our platform but if I find them I'll be sure to update.

**Comment by sdirix** [comment]
Thanks for the investigation!

We'll definitely look into the issue.

You can avoid the local fix interfering with your whole codebase by using a separate (potentially nested) ThemeProvider which directly wraps JSON Forms and nothing else. The `lineHeight` change will then only affect Mui inputs rendered by JSON Forms and not your whole page.
