### ISSUE TITLE
Pattern validation

### ISSUE THREAD

**Issue by micheleo** [eclipsesource/jsonforms#1542]
Hello, reading the documentation I don't understand if the string pattern validation is available out of the box. 

I tried the following:

schema.xml
` "x1": {"type": "string", "pattern": "^\\w+$"},`

uischema.xml
` {
      "type": "Control",
      "scope": "#/properties/x1",
    },`

The field is rendered as a string but without validation or blocking extra chars. 
Thank you in advance

**Comment by sdirix** [comment]
Thanks for your interest in JSON Forms.

I quickly tried to reproduce the problem with our React seed by replacing the `schema.json` with
```json
{
  "type": "object",
  "properties": {
    "x1": { "type": "string", "pattern": "^\\w+$" }
  }
}
```
and `uischema.json` with
```
{ "type": "Control", "scope": "#/properties/x1" }
```
with the following result:

![PatternTest](https://user-images.githubusercontent.com/8998368/74451450-efd8d700-4e7f-11ea-96b5-8bd1dd2ecde4.gif)

so the validation seems to work, which is the expected behavior.

Can you provide a more detailed description of how you are using JSON Forms, e.g. which version and renderer set. Ideally you could provide a code example where we can reproduce the problem.

**Comment by micheleo** [comment]
Thank you for your prompt answer. 
With your example works indeed ( by the way, is there a way to customize the error string? ).
Here's the example that is not working ( I took the code from another ticket about supporting draft7 conditions, doesn't make sense, since I put a point as string, just for testing purposes ):

`{
  "type": "object",
  "required": ["shape"],
  "properties": {
    "shape": {
      "type": "string",
      "enum": [
        "point",
        "line"
      ]
    }
  },
  "allOf": [
    {
      "if": {"properties": {"shape": {"const": "point"}}},
      "then": {
        "properties": {
          "x": {"type": "number"},
          "y": {"type": "number"}
        }
      }
    },
    {
      "if": {"properties": {"shape": {"const": "line"}}},
      "then": {
        "properties": {
          "x1": {"type": "string", "pattern": "^\\w+$"},
          "x2": {"type": "number"},
          "y1": {"type": "number"},
          "y2": {"type": "number"}
        },
        "required": ["x1","x2","y1","y2"]
      }
    }
  ]
}`

`{
  "type": "VerticalLayout",
  "elements": [
    {
      "type": "Control",
      "scope": "#/properties/shape"
    },
    {
      "type": "Control",
      "scope": "#/allOf[0]/then/properties/x",
      "rule": {
        "effect": "SHOW",
        "condition": {
          "scope": "#/properties/shape",
          "schema": { "const": "point"}
        }
      }
    },
    {
      "type": "Control",
      "scope": "#/allOf[0]/then/properties/y",
      "rule": {
        "effect": "SHOW",
        "condition": {
          "scope": "#/properties/shape",
          "schema": { "const": "point"}
        }
      }
    },
    {
      "type": "Control",
      "scope": "#/allOf[1]/then/properties/x1",
      "rule": {
        "effect": "SHOW",
        "condition": {
          "scope": "#/properties/shape",
          "schema": { "const": "line"}
        }
      }
    },
    {
      "type": "Control",
      "scope": "#/allOf[1]/then/properties/x2",
      "rule": {
        "effect": "SHOW",
        "condition": {
          "scope": "#/properties/shape",
          "schema": { "const": "line"}
        }
      }
    },
    {
      "type": "Control",
      "scope": "#/allOf[1]/then/properties/y1",
      "rule": {
        "effect": "SHOW",
        "condition": {
          "scope": "#/properties/shape",
          "schema": { "const": "line"}
        }
      }
    },
    {
      "type": "Control",
      "scope": "#/allOf[1]/then/properties/y2",
      "rule": {
        "effect": "SHOW",
        "condition": {
          "scope": "#/properties/shape",
          "schema": { "const": "line"}
        }
      }
    }
  ]
}`

Thank you very much

**Comment by sdirix** [comment]
The problem with this schema is that we only have limited support for `oneOf`, `allOf` and `anyOf` and besides validation no support for `if`, `then`, `else`.

You can find more information in this ticket: https://github.com/eclipsesource/jsonforms/issues/1518

**Comment by sdirix** [comment]
I'll close this for now. If you have more questions feel free to re-open the ticket.
