### ISSUE TITLE
how to define custom field type in jsonforms

### ISSUE THREAD

**Issue by aryankuntal2016** [eclipsesource/jsonforms#1553]
Autocomplete.js

import React from 'react';

class Autocomplete extends React.Component {
    render() {
        return (
            <div>
                 <p>Auto Complete:</p>
                <input type="text" className="form-control" name="dummy_name" value = "" />
                <div className="dropdown_suggestion hidden">
                </div>
            </div>
        );
    }
}

export default  Autocomplete;

AutocompleteControl.js

import * as React from 'react';
import { withJsonFormsControlProps } from '@jsonforms/react';
import  Autocomplete  from './Autocomplete';

interface AutocompleteControlProps {
    data: any;
    handleChange(path: string, value: any): void;
    path: string;
  }

  const AutocompleteControl = ({ data, handleChange, path }: AutocompleteControlProps) => (
    <Autocomplete
      value={data}
      onClick={(ev: any) => handleChange(path, Number(ev.value))}
    />
  );

export default withJsonFormsControlProps(AutocompleteControl);

autocompleteControlTester.js

import { rankWith, scopeEndsWith } from '@jsonforms/core';

export default rankWith(
  1000,
  scopeEndsWith('autocomplete_custom')
);

index.js (writing only useful part)

import AutocompleteControl from './AutocompleteControl'
import autocompleteControlTester from './autocompleteControlTester'

import { devToolsEnhancer } from 'redux-devtools-extension';
import {
  materialCells,
  materialRenderers
} from '@jsonforms/material-renderers';

import { jsonformsReducer} from '@jsonforms/core';
import { combineReducers } from "redux";

const initState: JsonFormsState = {
  jsonforms: {
    cells: materialCells,
    renderers: materialRenderers
  }
};

const globalFunctions = combineReducers({
  jsonforms: jsonformsReducer()

});

const store = createStore(globalFunctions, initState, devToolsEnhancer({}));

store.dispatch(Actions.registerRenderer(autocompleteControlTester, AutocompleteControl));

App1.js (writing only useful part)

import AutocompleteControl from './AutocompleteControl'
import autocompleteControlTester from './autocompleteControlTester'

var schema = {
        "type": "object",
        "properties": {
          "name": {
            "title": "Name",
            "type": "string"
          },

          "LastName_autocomplete_custom": {
            "type": "string"

          }
        }
      }

    var data = {}

    <JsonForms
      schema={schema}
      data = {data}      
      renderers={[...materialRenderers,                                                         
                  { tester: autocompleteControlTester, renderer: AutocompleteControl }
                ]}
      cells={materialCells}
   />

App2.js (writing only useful part)

import AutocompleteControl from './AutocompleteControl'
import autocompleteControlTester from './autocompleteControlTester'

var schema = {
        "type": "object",
        "properties": {
          "name": {
            "title": "Name",
            "type": "string"
          },

          "LastName": {
            "type": "autocomplete_custom"

          }
        }
      }

    var data = {}

    <JsonForms
      schema={schema}
      data = {data}      
      renderers={[...materialRenderers,                                                         
                  { tester: autocompleteControlTester, renderer: AutocompleteControl }
                ]}
      cells={materialCells}
   />

slight changes in schema of "App1.js" and "App2.js" in names and types of keys (LastName_autocomplete_custom, LastName) respectively.

This code works perfectly with 'App1.js' means rendering happening properly. It's not working with "app2.js", I want to make it work with "App2.js". With "App2.js" no rendering happening but the error is thrown (Uncaught Error: Unknown type: {"type":"autocomplete_custom"})

**Comment by sdirix** [comment]
Hi @aryankuntal2016, thanks for your interest in JSON Forms.

The first example (`App1`) specifies the schema as
```json
{
  "type": "object",
  "properties": {
    "name": {
      "title": "Name",
      "type": "string"
    },
    "LastName_autocomplete_custom": {
      "type": "string"
    }
  }
}
```
Your tester is implemented to check for the scope
```javascript
export default rankWith(
  1000,
  scopeEndsWith('autocomplete_custom')
);
```
The tester will be successful as the scope of your property is `#/properties/LastName_autocomplete_custom`

In `App2.js` the schema is specified as
```json
{
  "type": "object",
  "properties": {
    "name": {
      "title": "Name",
      "type": "string"
    },
    "LastName": {
      "type": "autocomplete_custom"
    }
  }
}
```
Here the scope of the property is `#/properties/LastName` which is why the tester fails. To fix it your tester should also be successful for the type `autocomplete_custom`. For example the following tester will work for both examples

```javascript
export default rankWith(
  1000,
  or(scopeEndsWith('autocomplete_custom'), schemaTypeIs('autocomplete_custom'))
);
```

---

I don't know the specifics of your use case, but note that in general I would advise against introducing your own types in JSON schema as you'll lose one of the major benefits of JSON Schema: interoperability with other frameworks.

Instead I would either hardcode the tester to your specific scope, e.g. `#/properties/LastName` when you have a specific number of cases or adapt the UI Schema when you want to generalize the behavior.
 
For example if you want to use the custom renderer for all string controls with an autocomplete option I would use the following UI Schema approach
```json
{
  "type": "VerticalLayout",
  "elements": [
    { 
      "type": "Control",
      "scope": "#/properties/name"
    },
    {
      "type": "Control",
      "scope": "#/properties/LastName",
      "options": { "autoComplete": true }
    }
  ]
}
```
combined with this tester
```javascript
export default rankWith(
  1000,
  and(isStringControl, optionIs('autoComplete', true))
);
```

---

**Comment by sdirix** [comment]
Close this issue as this is a question handled on [Spectrum](https://spectrum.chat/jsonforms/general/jsonforms-watercooler~18b6626a-a02e-48fd-a543-015ba3be8837?m=MTU4MzE0NTg5MTkzMg==)

**Comment by aryankuntal2016** [comment]
I want to make work "App2.js" not "App1.js" and not both simultaneously. The given solution is not working. I don't want UI schema approach.

**Comment by aryankuntal2016** [comment]
Thanks a lot @sdirix to give respond so fast. I want to make it work only for "App2.js" not for the "App1.js". schemaTypeIs this method is not working. Please may you suggest the way.
