### ISSUE TITLE
Nested Forms, Info Required!

### ISSUE THREAD

**Issue by VadimTikhonyuk** [eclipsesource/jsonforms#1555]
**Describe the bug**
I can't find proper info about how to make nested forms or spit one big form on smaller separated forms

**To Reproduce**
1. Go to 'https://jsonforms.io/docs/multiple-forms' 
2. And try to find info about how adress and shipping adress is referenced?
3. what is "__filemeta" where I can find this file?
4. super unclear

**Expected behavior**
I want to see on this example how I can make nested forms

**Additional context**
I registered JsonForms in App.tsx
![image](https://user-images.githubusercontent.com/13260375/76071724-6197d280-5f9f-11ea-98bb-8ea8b4d1c054.png)

and in index.tsx I use "main" form
![image](https://user-images.githubusercontent.com/13260375/76071796-78d6c000-5f9f-11ea-9bbd-c42a0ee98296.png)

My main.json
`{
    "type": "object",
    "properties": {
        "application":{
            "$ref": "#/definitions/application"
        }
    }
}`

My application.json
`{
    "definitions":{
        "application":{
            "title": "Application",
            "type": "object",
            "properties": {
            "intro": {
                "title": "Intro",
                "type": "object",
                "properties": {
                    "scriptId": {
                        "title": "ScriptId",
                        "type": "string"
                    }
                }
            }
            }
        }
    }
}`

I'm using seed project and it gives me white page
![image](https://user-images.githubusercontent.com/13260375/76072017-e4b92880-5f9f-11ea-89c7-8afdad8a6d14.png)

no errors in console and I don't know where I'm wrong and where I can find help so I'm writing here

**Comment by sdirix** [comment]
Hi! Thanks for your interest in JSON Forms. I agree, https://jsonforms.io/docs/multiple-forms is partially outdated and needs some improvement. Also you can ignore `__filemeta` as this is a leaked from the Website and is not part of the example.

## Interlinked forms

The first example on the website is actually a single form, using the grouping mechanism. It shows how some inputs within a form can be interlinked. The respective schema and uischema are:

### schema
```javascript
{
  type: "object",
  properties: {
    person: {
      title: "Person",
      type: "object",
      properties: {
        firstName: {
          type: "string"
        },
        lastName: {
          type: "string"
        },
        age: {
          description: "Age in years",
          type: "integer",
          minimum: 0
        },
        shippingAddress: {
          $ref: "#/properties/address/properties/addressId"
        }
      },
      required: ["firstName", "lastName"]
    },
    address: {
      title: "Order",
      type: "object",
      properties: {
        addressId: {
          type: "string",
          label: "Address Type",
          enum: [
            "Home Address 1",
            "Home Address 2",
            "Workplace",
          ]
        },
        street: {
          type: "string",
        },
        city: {
          type: "string"
        },
        zipCode: {
          type: "string"
        }
      }
    }
  }
}
```
### uischema
```javascript
{
  type: "VerticalLayout",
  elements: [
    {
      type: "Group",
      label: "Person",
      elements: [
        {
          type: "HorizontalLayout",
          elements: [
            {
              type: "Control",
              scope: "#/properties/person/properties/firstName"
            },
            {
              type: "Control",
              scope: "#/properties/person/properties/lastName"
            }
          ]
        },
        {
          type: "HorizontalLayout",
          elements: [{
            type: "Control",
            scope: "#/properties/person/properties/age"
          },
            {
              type: "Control",
              label: "Address",
              scope: "#/properties/person/properties/shippingAddress"
            }
          ]
        }
      ]
    },
    {
      type: "Group",
      label: "Address",
      elements: [
        {
          type: "HorizontalLayout",
          elements: [
            {
              type: "Control",
              scope: "#/properties/person/properties/shippingAddress"
            },
            {
              type: "Control",
              scope: "#/properties/address/properties/street"
            }
          ]
        },
        {
          type: "HorizontalLayout",
          elements: [
            {
              type: "Control",
              scope: "#/properties/address/properties/city"
            },
            {
              type: "Control",
              scope: "#/properties/address/properties/zipCode"
            }
          ]
        }
      ]
    }
  ]
}
```

## Multiple forms
The second example shows that you can render multiple forms on the same page with JSON Forms. It's possible to render two forms within the same Redux store or using the standalone version of JSON Forms which operates without Redux. As the latter is more simple (by using two `JsonForms` components, this is described as the way to go in the linked tutorial.

## Regarding your example

### In general
 - When you want to use the Redux variant of JSON Forms you need to use the Redux store + `JsonFormsReduxContent` + `JsonFormsDispatch` to render a form. If not overridden, the schema, uischema, data, renderers, cells etc. are all then taken from the Redux store. To render multiple forms you can use multiple dispatches and override its props like for the `JsonForms` component.
```jsx
<Provider store={store}>
  <JsonFormsReduxContext>
    <JsonFormsDispatch />
  </JsonFormsReduxContext>
</Provider>
```
 * When you want to use the standalone non-Redux variant, then you need to use the `JsonForms` component where you always need to provide this information yourself. You can render as many of them as you want.
```jsx
<JsonForms schema={schema} uischema={uischema} {/* etc. */} />
```
 * I would like to suggest using only the non-Redux variant of JSON Forms as we are currently working on removing the Redux dependency from JSON Forms.

### Specifics

 * The example `main.json` won't work as its reference `#/definitions/application` is not resolvable. Each JSON Schema must be resolvable within itself or you need to customize resolving. The latter is more complex and I would only advise to use it when your use case absolutely requires it.
 * `application.json` only contains definitions. This won't work as your main described object is therefore empty.
* You should combine both jsons to one which is then a reasonable schema.

## Summary

I would go with a single form or multiple not interconnected forms in the non-redux variant of JSON Forms.

**Comment by sdirix** [comment]
I'll close this issue for now, if you have more questions please re-open or post a question in our [Spectrum community](https://spectrum.chat/jsonforms).
