### ISSUE TITLE
any guidance on  how to render nested arrays

### ISSUE THREAD

**Issue by aksdari** [eclipsesource/jsonforms#1561]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Describe for which setup you like to have the improvement**
Framework: [e.g. react, angular]
RendererSet: [e.g. material, vanilla]

**Additional context**

**Comment by aksdari** [comment]
I just need guidance on how to render nested arrays, the UI elements.

**Comment by buskerone** [comment]
@aksdari were you able to do it?
