### ISSUE TITLE
[Question] Applying styles to JsonForms

### ISSUE THREAD

**Issue by zwjohn** [eclipsesource/jsonforms#1562]
Hi,
I'm new to this library and it's a very powerful library after going through some examples. 
I have a question which I couldn't find an answer in the documentation.
How can I config style of controls or layout? I thought it should be part of uischema, but I failed to find any relevant configuration. 

I tried to add style or className like other React components, but it doesn't work

            <JsonForms
                style={{"paddingTop": "20px"}}
                className="red-background"
                schema={schema}
                uischema={uischema}
                data={stateData}
                renderers={materialRenderers}
                cells={materialCells}
                onChange={handleChanges}
            />
Can someone shed some light on how to config or apply styles to the controls and the form?

Thanks!

John

**Comment by sdirix** [comment]
You can style the Material UI controls via their theme support. Besides theming and CSS styling the only way to influence the result would be to implement custom renderers which do exactly what you want.

In the vanilla renderers we set a bunch of classes which you can use for styling. [You can even customize the classes which will be set](https://github.com/eclipsesource/jsonforms/blob/4b9bbbd2120e4d404f6e0a814c0c604e52f727bd/packages/vanilla/Styles.md).

**Comment by sdirix** [comment]
Closed as this is a question [duplicated in Spectrum](https://spectrum.chat/jsonforms/general/how-do-i-config-styles-or-classes-i-want-to-use-for-controls-or-forms~fd68a632-f9d1-480f-a2bc-235c2223691a)
