### ISSUE TITLE
Multiple Select SelectBox

### ISSUE THREAD

**Issue by Shubham6542** [eclipsesource/jsonforms#1575]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Describe for which setup you like to have the improvement**
Framework: [e.g. react, angular]
RendererSet: [e.g. material, vanilla]

**Additional context**

**Comment by sdirix** [comment]
Hi. Thanks for your interest in JSON Forms!

We don't provide a multi-select dropdown out of the box but you can implement this on your own using a custom renderer. There are many approaches to this. For example on the schema side you could use an array of strings like this:
```
type: 'array',
uniqueItems: true,
maxItems: 3,
minItems: 3,
items: {
  enum: ['Enum1', 'Enum2', 'Enum3', 'Enum4', 'Enum5']
}
```
Now register your own renderer for this element. Within the renderer you could use [Material Ui's Select which supports multi-selection](https://material-ui.com/components/selects/#multiple-select). See [this tutorial](https://jsonforms.io/docs/custom-renderers) on how to implement and register an own renderer.

**Comment by sdirix** [comment]
I hope this helps. As we don't plan to provide a multi-select dropdown I'll close this issue for now. If you have another question, feel free to ask in our [Spectrum community](https://spectrum.chat/jsonforms).
