### ISSUE TITLE
Control Mode support for the standalone component

### ISSUE THREAD

**Issue by shivgarg5676** [eclipsesource/jsonforms#1590]
In the standalone component, when we update the data, the JSON form does not re-render. 
e.g if I have following code
```
<JsonForms
	schema={schema}
	uischema={uiSchema}
	data={formData}
        renderers={materialRenderers}
	cells={materialCells}
	onChange={({ errors, data }) => { }}
/>


Now if I change formData, The JsonForm does not re-render I have to create a new Instance. 

First, what I am saying here, is It correct? If not, please give me a chance to look again at my code.
If it is the behaviour can we also support the controlled version where if I change formData then component also gets updated?

**Comment by sdirix** [comment]
I would expect `JsonForms` to rerender whenever `formData` changes. Just to be safe I quickly retested in in the [React seed](https://github.com/eclipsesource/jsonforms-react-seed) and there it also works as expected, i.e. the form is rerendered with the new data when `setStandaloneData` is called.

Could you provide the whole component using `JsonForms`? Where is the change of `formData` being handled?

**Comment by shivgarg5676** [comment]
Hmm checked in react seed its working fine. I will check my code in that case.
