### ISSUE TITLE
Categorization example missing Field

### ISSUE THREAD

**Issue by guntur-ricardo** [eclipsesource/jsonforms#1597]
**Describe the bug**
I believe the categorization example is not displaying the nationality field properly. The schema and data shows a nationality field that does not appear for me. I assume it's supposed to appear in the second tab to demonstrate additional fields?

**To Reproduce**
1. Go to https://jsonforms.io/examples/categorization

**Expected behavior**
I'm attempting to create a similar structure using this example. It should show the nationality field on the second tab perhaps.

**Screenshots**
![Screen Shot 2020-06-22 at 11 56 19 AM](https://user-images.githubusercontent.com/31665531/85308900-d4aa5380-b47f-11ea-9d8d-115aa21c8bff.png)
![Screen Shot 2020-06-22 at 11 56 36 AM](https://user-images.githubusercontent.com/31665531/85308901-d4aa5380-b47f-11ea-915f-aa2f5ce6aecc.png)

**Browser (please complete the following information):**
 - Browser Chrome
 - Version 83.0.4103.106 (Official Build) (64-bit)\

**Additional context**
Thanks!

**Comment by sdirix** [comment]
Thanks for the report! I agree, the example would be better with `nationality` also shown in a control. This needs to be fixed in the `example/categorization` ui schema.
