### ISSUE TITLE
MaterialRadioGroupControl not used

### ISSUE THREAD

**Issue by TheZoker** [eclipsesource/jsonforms#1601]
**Describe the bug**

MaterialRadioGroupControl not used. Instead MaterialEnumControl is used

**To Reproduce**

1. Use following schema:
```
export const schema = {
  type: 'object',
  properties: {
    exampleRadioEnum: {
      type: 'string',
      enum: ['One', 'Two', 'Three']
    }
  }
};
```
2. Use following uischema
```
export const uischema = {
  type: 'Control',
  scope: '#/properties/exampleRadioEnum',
  options: {
    format: 'radio'
  }
},
```

**Expected behavior**

Use `MaterialRadioGroupControl` when option `format: 'radio'` is applied

**Screenshots**
none

**Browser (please complete the following information):**
 - Browser:  chrome
 - Version: 83

**Used Setup (please complete the following information):**
 - Framework: react
 - RendererSet: material

**Additional context**
none

**Comment by sdirix** [comment]
ToDo:
 * Increase ranking of tester
 * Make sure it only applies to enums with format radio
 * Add radio example to example app if it doesn't exist yet
