### ISSUE TITLE
DISABLE effect could not be applied to array of strings

### ISSUE THREAD

**Issue by piyush0609** [eclipsesource/jsonforms#1619]
**Describe the bug**
We have an json schema where a property is mapped to array of objects. For eg. this is the json schema
```
{
  "type": "object",
  "properties": {
  "address": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
            "arrayField": {
            "type": "array",
            "items": {
              "type": "string",
              "pattern": ".*sg-"
            },
            "street1": {
            "type": "string"
          }
   }
}
```

JSON Data
```
{
    "person": {
        "address":
            [ {"street1": "street1", "arrayField": ["sg-121212", "sg-121212"]},
             {"street1": "street2", "arrayField": ["sg-12121", "sg-12121212"]} ] 
     }
}
```

Our UI schema looks like
```
{
  "type": "CustomRenderer",
  "label": "Person",
  "id": "person",
  "parentId": "something",
  "elements": [
      {
      "type": "Group",
      "id": "address",
      "parentId": "person",
      "label": "Addresses",
      "elements": [
        {
          "type": "Control",
          "label": {
            "show": false
          },
          "scope": "#/properties/person/properties/address",
          "elements": [
            {
              "type": "Control",
              "scope": "#/properties/person/properties/address/properties/arrayField",
              "rule": {
                "effect": "DISABLE",
                "condition": {
                  "scope": "#/properties/person/properties/address/properties/arrayField",
                  "schema": { "pattern": ".*sg-" }
                }
              }
            }
          ]
        }
      ]
    }
}
```

**To Reproduce**
Just use the json schema, ui schema and data

**Expected behavior**
The disable effect is not applied to the `arrayField`

**Used Setup (please complete the following information):**
 - Framework: React
 - RendererSet: Material

**Additional context**

**Comment by sdirix** [comment]
Hi @piyush0609, we don't support `elements` on `Control`s. However you can specify a detail ui schema for the array control via the `detail` property in the `options` object, e.g.
```json
{
  "type": "Control",
  "label": { "show": false },
  "scope": "#/properties/address",
  "options": {
    "detail": {
      "type": "VerticalLayout",
      "elements": [
        {
          "type": "Control",
          "scope": "#/properties/arrayField",
          "rule": {
            "effect": "ENABLE",
            "condition": {
              "scope": "#/properties/arrayField",
              "schema": { "pattern": ".*sg-" }
            }
          }
        }
      ]
    }
  }
}
```
Note however that there is a mismatch in the rule. The rule points to an `array` however the rule-`schema` is defined for `string`, because `pattern` validates strings. Can you elaborate on the exact use case?

**Comment by piyush0609** [comment]
Thanks @sdirix for the quick revert. We have a field in our schema i.e `arrayField` from above example which is an array of strings. When then field is rendered, we want it to be non editable i.e read-only so the only way i could find from the documentation was to try disable effect on the field which isn't working.

**Comment by piyush0609** [comment]
@sdirix I was able to solve my use case using `options` on array controls. Please do recommend a better way if its there to solve my use case.

**Comment by sdirix** [comment]
Sadly there is no better way at the moment, elements can only be disabled via a rule or by the `readOnly` flag in the `JsonForms` component, however that effects all elements ;)

**Comment by sdirix** [comment]
I'll close this for now. Feel free to reopen when you have further questions.
