### ISSUE TITLE
Rendering an array of string-only values

### ISSUE THREAD

**Issue by LukasFrm** [eclipsesource/jsonforms#1630]
**Description**
I want to nest a simple string value into array, e.g.:

```
        comments: {
          type: "array",
          title: "Comments",
          items: {  
            stringValue: {
              type: "string",
            },
          },
        },
```

I want the state form to return a value like the one below:
`comments: ["stringValue goes here", "another string value"]`

**Alternatives you've considered**
The very first code snippet above, obviously, does not work. For now, only nesting the objects in arrays is possible, AFAIK.

**Setup**
Framework: React
RendererSet: material

**Comment by eneufeld** [comment]
Hi @LukasFrm ,
did you check this tutorials: https://json-schema.org/understanding-json-schema/reference/array.html#items ?
Your schema should look like this:
```
comments: {
          type: "array",
          title: "Comments",
          items: {  
              type: "string",
          },
},
```

Please use the https://spectrum.chat/jsonforms chat for questions in the future.

Best,
Eugen
