### ISSUE TITLE
unable to run vanilla application

### ISSUE THREAD

**Issue by mburri** [eclipsesource/jsonforms#1638]
**Describe the bug**
On a fresh clone of the project, on the master branch, when following the instructions to run the react/vanilla example app compilation fails with the follwing error:

```
ERROR in /home/mburri/dev/jsonforms/jsonforms/packages/vanilla/example/index.ts
./example/index.ts
[tsl] ERROR in /home/mburri/dev/jsonforms/jsonforms/packages/vanilla/example/index.ts(35,3)
      TS2345: Argument of type '{ name: string; reducer: (state: StyleDef[], action: any) => any; state: ({ name: string; classNames: string[]; } | { name: string; classNames: ([size]: number[]) => string[]; })[]; }' is not assignable to parameter of type '(examples: ReactExampleDescription[]) => ReactExampleDescription[]'.
  Object literal may only specify known properties, and 'name' does not exist in type '(examples: ReactExampleDescription[]) => ReactExampleDescription[]'.
```

**To Reproduce**
```
git clone git@github.com:eclipsesource/jsonforms.git
cd jsonforms
npm ci
npm run init
cd packages/vanilla/ && npm run dev
```

**Expected behavior**
The application starts - like the material one.

**Used Setup (please complete the following information):**
 - OS: Linux
 - IDE/Text Editor: VS Code
 - Framework: react
 - RendererSet: vanilla

** Screenshot **
![vanilla-example-error](https://user-images.githubusercontent.com/4577216/93269927-4f012000-f7b0-11ea-9076-601f94a67b9a.png)

**Additional context**
```
node -v
v12.1.0
npm -v
6.9.0

**Comment by sdirix** [comment]
Thanks for the report! We recently changed the `renderExample` API and forgot to adapt the Vanilla example. I pushed a fix which should be merged soon. In the meantime you can fix it locally by adding `undefined` as a parameter after `vanillaCells`.
