### ISSUE TITLE
Ionic integration - quick start

### ISSUE THREAD

**Issue by ppmag** [eclipsesource/jsonforms#1639]
Hi, 
I saw here https://jsonforms.io/docs/renderer-sets,
Ionic is supported by JSONForms,

but unfortunately I couldn't find information how to integrate it into Ionic React based app.

Please point me, where I can find appropriate exampple.
TYA.

**Comment by sdirix** [comment]
Hi @ppmag, we supported the Ionic Angular renderers up until JSON Forms `v2.3.2` (https://www.npmjs.com/package/@jsonforms/ionic-renderers). As there was not much interest we froze them for now and stopped actively maintaining them. An update to the website is [under way](https://github.com/eclipsesource/jsonforms2-website/pull/112). You can find the sources for them [here](https://github.com/eclipsesource/jsonforms-angular-ionic-renderers).

We never had an Ionic React renderer set. If you want to write one yourself you could take a look at the [React Material renderer set](https://github.com/eclipsesource/jsonforms/tree/83a4dd26be88eaa3733d1a1f128f11c31a968cf5/packages/material) for inspiration.

I will close this issue for now. Feel free to reopen if necessary.
