### ISSUE TITLE
Any plan or way to use this for React Native?

### ISSUE THREAD

**Issue by krunalp1993** [eclipsesource/jsonforms#1647]
I see, This library provides out of the box support for React and Angular, so It would be awesome to add React Native in supported platforms.

**How to make it working?**
I am new to use this library so have nothing to solve this, but I think writing new renderers can make it working!

Hope my question / request is acceptable. Thanks!

**Comment by sdirix** [comment]
As the JSON Forms core is platform independent anyone could create a React Native renderer set. At the current point of time we don't have plans to develop and maintain such a renderer set.

However we also [offer support packages](https://jsonforms.io/support) with which we could help with the various tasks involved in creating a React Native renderer set, i.e. planning, developing, releasing etc.

**Comment by sdirix** [comment]
I'll close this issue for now.
