### ISSUE TITLE
Angular 10 support

### ISSUE THREAD

**Issue by sandeepreddy1248** [eclipsesource/jsonforms#1659]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Describe for which setup you like to have the improvement**
Framework: [e.g. react, angular]
RendererSet: [e.g. material, vanilla]

**Additional context**

**Comment by eneufeld** [comment]
We didn't test it against angular 10. The easiest way would be to update https://github.com/eclipsesource/jsonforms-angular-seed to angular 10. We would happily review and merge a PR there. If you run in issues we will gladly help in resolving them.

**Comment by sandeepreddy1248** [comment]
Thanks for updates

When I have gone through the code provided by in this link https://github.com/eclipsesource/jsonforms-angular-seed, I see that it is using external npms(AJV, JSON-REFS) packages support for integration. Why can't it be easy as react integration.

**Comment by sandeepreddy1248** [comment]
Please let me know if there are any reference links where I can find simple angular integration flow.....

**Comment by sandeepreddy1248** [comment]
here https://jsonforms.io/ we found simple steps how to use in react application where in angular we are not seeing any steps like that , if any reference it will help us, thanks advance

**Comment by sdirix** [comment]
@sandeepreddy1248 There is not much documentation for the Angular renderers specifically, however we keep the [JSON Forms Angular seed](https://github.com/eclipsesource/jsonforms-angular-seed) up to date for reference. The JSON Forms website is also [open source](https://github.com/eclipsesource/jsonforms2-website) so we would be happily accepting documentation.

We also [offer support packages](https://jsonforms.io/support) with which we could help with the various tasks involved in integrating JSON Forms into your Angular stack, i.e. planning, developing, releasing, etc. If preferred we could then also work on the Angular documentation.

**Comment by sdirix** [comment]
JSON Forms is compatible with Angular 10. The Angular seed [now uses Angular 10 too](https://github.com/eclipsesource/jsonforms-angular-seed/commit/943c5fc3ae0d3b6409cc6aa3d863a13c2a39a9c4).

**Comment by varun0209** [comment]
Hi Sdirix, Whatever you provide link(https://github.com/eclipsesource/jsonforms-angular-seed) it is working fine when i do nppm install in this jsonforms-angular-seed project but i have installed new angular10 project and trying to integrated then i am getting below error.

![Capture](https://user-images.githubusercontent.com/40246792/101072875-ab602880-35c4-11eb-9327-1f42ca589dc9.PNG)

**Comment by sandeepreddy1248** [comment]
Hi Sdirix, Whatever you provide link(https://github.com/eclipsesource/jsonforms-angular-seed) it is working fine when i do nppm install in this jsonforms-angular-seed project but i have installed new angular10 project and trying to integrated then i am getting below error.
![Uploading Capture.PNG…]()

**Comment by sandeepreddy1248** [comment]
[Uploading angular10.zip…]

here is the my angular 10 project code can please go through , can you help me out thanks in advance

**Comment by sandeepreddy1248** [comment]
[angular10.zip](https://github.com/eclipsesource/jsonforms/files/5638296/angular10.zip)

here is the my angular 10 project code can please go through , can you help me out thanks in advance
