### ISSUE TITLE
NumberControlRenderer does not provide a way to explicitly disable grouping

### ISSUE THREAD

**Issue by ttntrifork** [eclipsesource/jsonforms#1668]
**Is your feature request related to a problem? Please describe.**
Sometimes you want a number input to not use grouping even if your locale has a grouping character (e.g. da-DK).  
This is useful when presenting inputs for numerical "codes" in some code system, e.g. the Danish "Central Business Register" which assigns a 8 digit numerical code to each business registered (which does NOT contain grouping characters). 

jsonforms/angular-material `NumberControlRenderer` does not set a `useGrouping` property in the `NumberFormatOptions` object passed to the `Intl.NumberFormat` constructor, which causes Intl.NumberFormat to use the locale specific grouping.

**Describe the solution you'd like**
A uischema options element that sets useGrouping to false. 
See PR https://github.com/eclipsesource/jsonforms/pull/1669

**Describe for which setup you like to have the improvement**
Framework: angular
RendererSet: material

**Comment by sdirix** [comment]
Thank you for reporting this issue!
