### ISSUE TITLE
Create a repo for the make it happen example code

### ISSUE THREAD

**Issue by JonasHelming** [eclipsesource/jsonforms#167]
And fill it with an empty skelleton web application with one page

**Comment by JonasHelming** [comment]
This is urgent to start writing the tutorial

**Comment by edgarmueller** [comment]
I've set up a basic seed project and transferred ownership. We may close this once transfer has been  finished, right?

**Comment by hecforga** [comment]
I have made a pull request in the repository make-it-happen-jsonforms with the prototype I have implemented this week.
