### ISSUE TITLE
How to define Cascade dropdown in json forms?

### ISSUE THREAD

**Issue by maulik-modi** [eclipsesource/jsonforms#1673]
We would like to have cascade dropdown support. We are developing dynamic forms for taxation domain where all the fields are dependent on Assessment year. There are some cascade dropdown as well such as SectionCodeToClaimDeduction based on laws effective in given assessment year.

**Describe alternatives you've considered**
We are evaluating if update or onchange would help us 

**Describe for which setup you like to have the improvement**
Framework: react, angular
RendererSet: vanilla

**Comment by sdirix** [comment]
Hi @maulik-modi, thanks for your interest in JSON Forms. Please use the [Spectrum board](https://spectrum.chat/jsonforms?tab=posts) when you have further questions.

There are two main approaches to cascading dropdowns:
 * Exchange the JSON Schema whenever one of the dropdown values change
 * Implement custom (enum) renderers which dynamically adapt their options, depending on the current data.
 
 See also this [Spectrum question (Computed field values)](https://spectrum.chat/jsonforms/general/computed-field-values~a7192935-4a51-4748-aef9-06facaa03502) for more details.

**Comment by sdirix** [comment]
I'll close this for now as the question is answered.

**Comment by maulik-modi** [comment]
@sdirix , Spectrum is shutting down and becoming read only, I am adding this here: https://github.com/eclipsesource/jsonforms/issues/987 has code sample using old syntax.

**Comment by cjauvin** [comment]
Could a "discussions" board be a replacement for Spectrum, in the context of this project? The links above seem to want to redirect there, but it is not activated I believe.

**Comment by cjauvin** [comment]
Sorry for my confusion I just discovered the Discourse server, and if it can be useful to anyone, I believe the corresponding link for the one above is https://jsonforms.discourse.group/t/computed-field-values/114

**Comment by sdirix** [comment]
Sadly Github broke the old Spectrum links
