### ISSUE TITLE
Default value not applied

### ISSUE THREAD

**Issue by DavidHenri008** [eclipsesource/jsonforms#1676]
When a schema property has a default value it is ignored.
I would expect that if my schema is defined with a default value, like:
```
{
  type: "string",
  title: "Name",
  default: "Jim"
}
```
and my data does not include the field, or it is undefined, like:
```
{
   name: undefined,
   age: 26,
}
```
 the default value would be passed as data to the renderer.

The problem is easily reproducible and it is highlighted by the default.ts example.

I am using Chrome, the latest version of the library, and also the Material renderer.

Thanks.

**Comment by sdirix** [comment]
Hi @DavidHenri008, we let Ajv handle the default values. As we require certain Ajv settings you can use the exported Ajv factory `createAjv(options)` and set `useDefaults: true`. The customized Ajv can then be passed into the JsonForms component, e.g.
```
const handleDefaultsAjv = createAjv({useDefaults: true});
// [...]
        <JsonForms
            data={data}
            schema={schema}
            uischema={uischema}
            renderers={materialRenderers}
            cells={materialCells}
            onChange={({ errors, data }) => setData(data)}
            ajv={handleDefaultsAjv}
        />
```

**Comment by DavidHenri008** [comment]
Great, it does work Thanks.

**Comment by envynoiz** [comment]
I want to re-open this issue because looks like the default behavior doesnt work for Angular, even I tested it using the seed project provided by the official documentation. I already created the ajv instance using the native method "createAjv" but I was unable to get it to work.

**Comment by sdirix** [comment]
Hi @envynoiz, can you post the exact code and/or push the branch where you did the experiment? Then we can take an earlier look at the issue than when we need to reproduce it first on our side.
