### ISSUE TITLE
JSONForms VanillaLayouter does not expose enough CSS classes, which results in heavy code duplication on framework user code

### ISSUE THREAD

**Issue by hoelzl-florian** [eclipsesource/jsonforms#1677]
Files:
[firefox_inspector_result.html.txt](https://github.com/eclipsesource/jsonforms/files/5830093/firefox_inspector_result.html.txt) -	relevant HTML source as shown in Firefox Inspector mode
[named-commented-eobject.css.txt](https://github.com/eclipsesource/jsonforms/files/5830100/named-commented-eobject.css.txt)	-	CSS that achieved the result (BUT with heavy code duplication)
[model-properties-view-content-widget.react.txt](https://github.com/eclipsesource/jsonforms/files/5830120/model-properties-view-content-widget.react.txt)  -	JSONForms framework user code

**Expected behavior**
Every DIV section generated by JSONForms should have a proper CSS class that can be overridden by user code.

**Screenshots**
PropertySection.png					-	Screenshot of the Solution
![PropertySection](https://user-images.githubusercontent.com/50833574/104914280-320f7000-598f-11eb-9522-68759855c98c.png)

**Browser:**
 - firefox
 - 82.0.2

**Used Setup (please complete the following information):**
 - Framework: React
 - RendererSet: Vanilla
 - JSONForms: 2.5.0-alpha.1

Based on this information I submit 3 bugs in replies to this initial report.

**Comment by hoelzl-florian** [comment]
**BUG 1**:
_Refers to_:
	firefox_inspector_result.html.txt : line 6 (also line 13)
	model-properties-view-content-widget.react.txt : 116
	
_Observation_: It is possible to inject a custom CSS class "ctk4-model-properties-group-layout-item".
_Problem_: It's properties are overriden by the more generic CSS class "group-layout-item".
_Solution_: Swap the order of the CSS classes.

**Comment by hoelzl-florian** [comment]
**BUG 2**:
_Refers to_: 
	firefox_inspector_result.html.txt : line 10 (also line 17)
	
_Observation_: There is no custom CSS class in this element. If there were a CSS class, how would it
distinguish between an imperative message ("Please enter name.") and an error message ("Error: this
is not a name!").
_Problem_: It is not possible to inject a custom CSS class into the "validation" element.
_Solution_: Expose this element similar to the input and label element.

**Comment by hoelzl-florian** [comment]
_BUG 3_:
_Refers to_: 
	firefox_inspector_result.html : line 7 (also line 14)
	named-commented-eobject.css : all lines

_**Observation**_: CSS classes of this DIV section use names that correspond to the schema / UI schema.
There is no generic class for this section.
_**Problem**_: In my case, the schema and UI schema is composed of contributions from different sources,
which might not even know from one another. They all coordinate via the model properties service and
the properties view asks the service what should be displayed. Therefore, every contribution has to
bring its own CSS definition, as can be seen in the CSS file. This file contains heavy CSS code
duplication due to the fact that there is no generic CSS class next to the specific, named-dependent
classes that are already there.
_**Solution**_: Also generate a generic class for each item in the JSONForms, e.g., like this
	`div class="jsonform-property root_properties_comment" id="#/properties/comment"`
Then one can save a lot of duplicated CSS code by defining the default behavior / layout with
"jsonform-property" and still override it with "root_properties_comment".

**Comment by sdirix** [comment]
Thanks for this extensive report!

> **BUG 1**:
> _Refers to_:
> firefox_inspector_result.html.txt : line 6 (also line 13)
> model-properties-view-content-widget.react.txt : 116
> 
> _**Observation**_: It is possible to inject a custom CSS class "ctk4-model-properties-group-layout-item".
> _**Problem**_: It's properties are overriden by the more generic CSS class "group-layout-item".
> _**Solution**_: Swap the order of the CSS classes.

I agree, we can add the hardcoded `group-layout-item` at the beginning. For more stability I would recommend to select both classes in your CSS, i.e. `group-layout-item.ctk4-model-properties-group-layout-item` and therefore have higher prioritization than the standalone default CSS.

> **BUG 2**:
> _Refers to_:
> firefox_inspector_result.html.txt : line 10 (also line 17)
> 
> _**Observation**_: There is no custom CSS class in this element. If there were a CSS class, how would it
> distinguish between an imperative message ("Please enter name.") and an error message ("Error: this
> is not a name!").
> _**Problem**_: It is not possible to inject a custom CSS class into the "validation" element.
> _**Solution**_: Expose this element similar to the input and label element.

Good point, we should definitely do this.

> **BUG 3**:
> _Refers to_:
> firefox_inspector_result.html.txt : line 7 (also line 14)
> named-commented-eobject.css.txt : all lines
> 
> _**Observation**_: CSS classes of this DIV section use names that correspond to the schema / UI schema.
> There is no generic class for this section.
> _**Problem**_: In my case, the schema and UI schema is composed of contributions from different sources,
> which might not even know from one another. They all coordinate via the model properties service and
> the properties view asks the service what should be displayed. Therefore, every contribution has to
> bring its own CSS definition, as can be seen in the CSS file. This file contains heavy CSS code
> duplication due to the fact that there is no generic CSS class next to the specific, named-dependent
> classes that are already there.
> _**Solution**_: Also generate a generic class for each item in the JSONForms, e.g., like this
> `div class="jsonform-property root_properties_comment" id="#/properties/comment"`
> Then one can save a lot of duplicated CSS code by defining the default behavior / layout with
> "jsonform-property" and still override it with "root_properties_comment".

Makes sense to me! I would like to suggest the name `control` as this reflects the actual usage.
