### ISSUE TITLE
There shall be a default ui schema generator, which is used if not view model is specified

### ISSUE THREAD

**Issue by JonasHelming** [eclipsesource/jsonforms#168]
VerticalLayout and a list of all attributes.

**Comment by edgarmueller** [comment]
This is already the case if you leave out the `ui-schema` attribute, e.g.

```HTML
<jsonforms schema="vm.schema" data="vm.data"></jsonforms>
```

should do what you want. Does this already fit your needs?

**Comment by JonasHelming** [comment]
I will try and get back, if not
