### ISSUE TITLE
Vue support

### ISSUE THREAD

**Issue by buryndin** [eclipsesource/jsonforms#1681]
Hi @sdirix 
I see vue branch in you repo. Can you please tell which status of this draft? Is it ready? Are there any plans to merge it to master and publish in npm?

Thanks!

**Comment by sdirix** [comment]
Our plan is to release `@jsonforms/vue` (Vue 3) and `@jsonforms/vue2` (Vue 2) in a first version very soon. We'll also work on a basic renderer set after that and also plan to release a first version soonish, i.e. within Q1 2021.

**Comment by sdirix** [comment]
For questions please use our [Spectrum](https://spectrum.chat/jsonforms) community.

**Comment by sdirix** [comment]
The packages `@jsonforms/vue` and `@jsonforms/vue2` are now released. See the [Vue 3](https://github.com/eclipsesource/jsonforms/tree/master/packages/vue) and [Vue 2](https://github.com/eclipsesource/jsonforms/tree/master/packages/vue2) readmes for instructions on how to use them and write your own renderer set.

Stay tuned for the release of a basic renderer set we are currently working on.
