### ISSUE TITLE
Update readmes

### ISSUE THREAD

**Issue by sdirix** [eclipsesource/jsonforms#1683]
Update readmes of all packages. They contain outdated information which is then shown for example in npm.

**Comment by sdirix** [comment]
Also clarify that questions should be asked in Spectrum instead of in issues.

**Comment by sdirix** [comment]
Give a super small instruction in each README on how to install and use the package and link to the docs

**Comment by AlexandraBuzila** [comment]
Add quick start chaper with small code snippet:
- show what needs to be imported
- show how to use minimal example of component
- point to website/seed
