### ISSUE TITLE
Suppress the "should match pattern . . ." message?

### ISSUE THREAD

**Issue by kilsen** [eclipsesource/jsonforms#1685]
Is there a way to suppress the validation message that appears when a RegEx pattern is being used? For example, I have a Social Security Number field, defined as follows:
```
    "ssn": {
      "title": "Social security #",
      "type": "string",
      "description": "Enter SSN in the format ###-##-####",
      "pattern": "\\d\\d\\d-\\d\\d-\\d\\d\\d\\d"
    }
```
As soon as a user starts typing into the field, the following message appears below it:
`should match pattern "\d\d\d-\d\d-\d\d\d\d"`
The average user is not going to understand that.

**Comment by sdirix** [comment]
Hi @kilsen. Error messages can be customized for example via [ajv-errors](https://github.com/ajv-validator/ajv-errors) and handing a [custom Ajv instance over to JSON Forms](https://jsonforms.io/docs/validation).

Note that we prefer questions being asked in our [Spectrum](https://spectrum.chat/jsonforms).

Does this answer your question?

**Comment by kilsen** [comment]
Thank you for the prompt reply. I'll investigate using ajv-errors to configure the Ajv instance used by JSONForms.

Also, if I have other questions I'll enter them in the Spectrum channel. (The README.md file here states: "Feel free to start a discussion by opening an issue on this repo . . ." so you might want to change that if you'd prefer that questions not be asked here.)

**Comment by sdirix** [comment]
> Also, if I have other questions I'll enter them in the Spectrum channel. (The README.md file here states: "Feel free to start a discussion by opening an issue on this repo . . ." so you might want to change that if you'd prefer that questions not be asked here.)

You're right ;) Thanks for the pointer, I'll make sure that we change this.
