### ISSUE TITLE
Add `oneOf` enum cell renderer

### ISSUE THREAD

**Issue by sdirix** [eclipsesource/jsonforms#1692]
**Description**

We offer a `oneOf` enum control renderer which can handle enums with labels, i.e.

```json
"type": "string",
"oneOf": [
  {
    "const": "a",
    "title": "Option A"
  },
  {
    "const": "b",
    "title": "Option B"
  }
]
```
We should also offer a cell renderer which can handle these elements

**Describe alternatives you've considered**
Fallback to non-table renderings when such an element is detected

**Describe for which setup you like to have the improvement**
Framework: [react]
RendererSet: [material]

**Additional context**
Derived from [Spectrum question](https://spectrum.chat/jsonforms/general/oneof-nested-inside-array~64b83afc-7124-42fe-b76a-5c0b3de93e6e)

**Comment by msueping** [comment]
Has there been any progress on this capability? Is there any alternative to get the same functionality?

**Comment by sdirix** [comment]
Hi @msueping, this ticket is actually already implemented and the renderer can be consumed via the `3.0-alpha` releases
