### ISSUE TITLE
using '/' in initialisation json results in 'No applicable renderer found.'

### ISSUE THREAD

**Issue by neuralsea-lab** [eclipsesource/jsonforms#1696]
**Describe the bug**
using '/' in initialisation json results in 'No applicable renderer found.'

**To Reproduce**
1. Use JsonForms data json
```
{
    "some / initial / value": 0.0,
}
```
2. load form
4. Cell does not display with error  'No applicable renderer found.'

**Expected behavior**
Cell to display 

**Screenshots**

**Browser (please complete the following information):**
 - Browser - chrome latest

**Used Setup (please complete the following information):**
 - Framework: react
 - RendererSet: material

**Additional context**
None

**Comment by sdirix** [comment]
Hi @neuralsea-lab, thanks for the report!

JSON Forms doesn't [handle special characters like `/` and `~` properly](https://tools.ietf.org/html/rfc6901#section-4). The ui schema generator needs to improved to detect these characters and encode them to `~1` and `~0` in the scopes respectively. Also our resolving code needs to be adapted to respect these encodings and transform them back. We also need to keep backward compatibility in mind as currently you can just use `~` in JSON Forms without problems.

For now I would like to suggest to transform your `data` and `schema` before handing it to JSON Forms (for example by replacing all `/` in property names with `~`) and transforming the outgoing `data` back to using `/`. This should be rather straightforward.

**Comment by sdirix** [comment]
ToDo:
 - Adapt the ui schema generator, to properly encode the special characters in the `scope`. The ui schema generator code is [here](https://github.com/eclipsesource/jsonforms/blob/38153357a5b6dc0a02d940199fb71121f4197001/packages/core/src/generators/uischema.ts).
 - Adapt the resolving code to properly respect encoded values by transforming them back when needed. Maybe it's enough to decode them after [this split](https://github.com/eclipsesource/jsonforms/blob/38153357a5b6dc0a02d940199fb71121f4197001/packages/core/src/util/resolvers.ts#L117), but this needs to be checked.
 - Add testcases for the ui schema generator and the resolver

**Comment by sdirix** [comment]
Fixed in JSON Forms 3.0 with https://github.com/eclipsesource/jsonforms/pull/1834
