### ISSUE TITLE
Widget for object arrays

### ISSUE THREAD

**Issue by JonasHelming** [eclipsesource/jsonforms#170]
I think, we should provide two default widgets for this data type (array of objects).
The first default control is a table showing all attributes of the sub element.
The second widget shows a list of all sub element as embedded forms (very much like a comment thread).
Both allow to enter ne elements, the table preferably inline, the thread widget shows another empty form under the thread showing all attributes and allows to submit.
For the tutorial, we will adapt the thread widget by making the thread forms read-only (using the view model) and removing the date field from the submit form. Please consider this adaptation when implementing.

**Comment by edgarmueller** [comment]
Closed via PR #178.
