### ISSUE TITLE
Improve internal example app

### ISSUE THREAD

**Issue by sdirix** [eclipsesource/jsonforms#1706]
- [x] Use a unique path for each example
- [x] Offer a built version of the example app so we can build all example app variants with each JSON Forms PR and link them.
  - [x]  https://github.com/eclipsesource/jsonforms/pull/2056: Site with static index.html and links to react vanilla and react material examples. Use rollup to bundle examples
  - [x] Configure Netlify to build them for each PR
  - [x]  https://github.com/eclipsesource/jsonforms/pull/2074: Angular material example
  - [x] https://github.com/eclipsesource/jsonforms/pull/2074 Vue 3 Vanilla
  - [x] Vue 2 Vanilla: Will be handled in separate issue: https://github.com/eclipsesource/jsonforms/issues/2087
- [x] https://github.com/eclipsesource/jsonforms/pull/2101: Cleanup examples (e.g. add description, ordering)
---
Improving the webpack dev builds was descoped and is tracked in issue https://github.com/eclipsesource/jsonforms/issues/2093

**Comment by lucas-koehler** [comment]
All points are resolved or extracted to their own issues.
