### ISSUE TITLE
Support for Visibility rules including tooling support

### ISSUE THREAD

**Issue by JonasHelming** [eclipsesource/jsonforms#172]
Case will be to change the visibility of a control based on an enum

Known Tasks:
- [x] Review current UI Schema definition #203

**Comment by koegel** [comment]
- [ ] test

**Comment by edgarmueller** [comment]
Initial tooling support for rules has been implemented. If any issues should be left, please use the [JSON Forms Editor issue tracker](https://github.com/eclipsesource/JsonFormsEditor/issues/new).
