### ISSUE TITLE
Add padding to form helper text in Material renderers

### ISSUE THREAD

**Issue by AlexandraBuzila** [eclipsesource/jsonforms#1723]
The height of controls with helper texts changes when validation errors appear/disappear.
By setting the form helper text to a space (e.g. `&nbsp;` ) when it doesn't have any content, we can prevent this from happening. This will only be a solution for the cases where the helper text has one line, however this is the most common case.

Framework: react (we should investigate if it's a viable solution for other frameworks as well)
RendererSet: material

**Comment by sdirix** [comment]
This is not really needed as the use case can be solved via CSS or theming, e.g.
```ts
const theme = createMuiTheme({
  overrides: {
    MuiFormHelperText: {
      root: {
        minHeight: '1.6em',
      }
    }
  },
});
```
