### ISSUE TITLE
Integration of tooling with GitHub

### ISSUE THREAD

**Issue by JonasHelming** [eclipsesource/jsonforms#173]
We need a proper integration with GitHub.
It should allow to login with the GitHub account, specify, where ui schema and data schema are located, load the schemata from there, remember those locations somehow and allow to commit changes.

**Comment by edgarmueller** [comment]
From my point of view we can close this issue: for any issues left, please use the [issue tracker for the editor](https://github.com/eclipsesource/JsonFormsEditor/issues/new).
