### ISSUE TITLE
react 17 support

### ISSUE THREAD

**Issue by lukesmurray** [eclipsesource/jsonforms#1738]
If you try to install json forms with react 17 you get the following error.

```
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: my-jsonforms-app@0.1.0
npm ERR! Found: react@17.0.2
npm ERR! node_modules/react
npm ERR!   react@"^17.0.2" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.12.0" from @jsonforms/react@2.5.0
npm ERR! node_modules/@jsonforms/react
npm ERR!   @jsonforms/react@"*" from the root project
```

I believe this error can be traced to the following line

https://github.com/eclipsesource/jsonforms/blob/9b95669f6f28385a12b5c7d632e6941b2b9e0038/packages/react/package.json#L80

Is JSON forms actually incompatible with react 17? Is it possible to support both 16 and 17?

**Comment by sdirix** [comment]
Hi! JSON Forms works perfectly fine with React 17. We'll update the version constraints with the next release.

I'm wondering why this shows up as an error for you. Usually peer dependency issues are presented as warnings.

**Comment by lukesmurray** [comment]
I’ll try to come up with a simple reproduction and get back to you. You can
close for now.
