### ISSUE TITLE
Help: How do I render a submit button for React Material?

### ISSUE THREAD

**Issue by floofydoug** [eclipsesource/jsonforms#1757]
There are so many great patterns for so many input fields, but I couldn't find any documentation or examples of a submit. Are buttons an anti-pattern?

**Comment by sdirix** [comment]
Hi @floofydoug, you can just render the submit button next to the `JsonForms` component. Is there some specific feature you're missing from JSON Forms?

See [this forum question](https://spectrum.chat/jsonforms/general/are-there-any-crud-examples-of-using-jsonforms-using-restful-api~f705d3bd-6eed-4b21-b2d3-b46540f8669f) for a basic CRUD example.

**Comment by floofydoug** [comment]
Oh! TY. i get it now.
