### ISSUE TITLE
Vue 3 combinators: No applicable renderer found.

### ISSUE THREAD

**Issue by Taaitaaiger** [eclipsesource/jsonforms#1759]
**Describe the bug**
When I try to use one of the combinator examples in combination with Vue 3, only the message "No applicable renderer found." is shown. 

**To Reproduce**
1. Create a new Vue project and install jsonforms/core, jsonforms/vue, and jsonforms/vue-vanilla.
2. Add a form as in the seed app: https://github.com/eclipsesource/jsonforms-vue-seed/blob/main/src/App.vue
2. Use the schema and uischeme from the combinator examples: https://jsonforms.io/examples/combinators
3. `npm run serve` and open the website.

**Expected behavior**
I expected to see the combinator examples as on https://jsonforms.io/examples/combinators/, according to the information available on https://jsonforms.io/docs/renderer-sets this is supported.

**Browser (please complete the following information):**
 - Firefox 88 (Linux)

**Used Setup (please complete the following information):**
 - Framework: Vue 3
 - RendererSet: Vanilla

**Comment by sdirix** [comment]
Hi @Taaitaaiger, our new Vue2 and Vue3 renderer sets are not fully features yet and don't cover as many use cases as some of our other renderer sets. Currently they support all basic controls (e.g. `string`, `boolean`, `integer`, `date` etc.) as well as vertical, horizontal and group layouts and array lists. They don't support categorizations, combinators nor array tables.

Sadly the documentation on https://jsonforms.io/docs/renderer-sets is wrong. I opened [an issue](https://github.com/eclipsesource/jsonforms2-website/issues/181) for this and we'll fix it soon.

**Comment by Taaitaaiger** [comment]
Ah, I see, thank you for your reply!

**Comment by sdirix** [comment]
I'll close this for now. Please reopen when you have further questions / considerations.

To gather some feedback: Are you intending to use JSON Forms Vue / Vanilla? If not, what are you missing so that you would consider it?

**Comment by nenads** [comment]
i need to use object. It seems this is still thing.

Any advice how to create custom render
