### ISSUE TITLE
Datepicker only has one FormHelper and description is never shown

### ISSUE THREAD

**Issue by TheZoker** [eclipsesource/jsonforms#1767]
**Describe the bug**
The datepicker field only has one FormHelper field below the input field (instead of 2 like all other input fields) and when a description is set, it is not shown when focusing the field. 

**To Reproduce**
1. Use latest jsonforms (2.5.1)
2. Use below schema
3. Focus datepicker field

**Expected behavior**
Show description when set

**Screenshots**
![image](https://user-images.githubusercontent.com/1368405/123102989-dfeae300-d435-11eb-84f5-bef8fd519799.png)

**Browser (please complete the following information):**
 - Browser: edge
 - Version: 96

**Used Setup (please complete the following information):**
 - Framework: react
 - RendererSet: material

**Additional context**
Schema:
```
{
  "type": "object",
  "properties": {
    "due_date": {
      "type": "string",
      "format": "date",
      "description": "Lorem Ipsum"
    },
  },
}

```

**Comment by sdirix** [comment]
This is already fixed for a while with #1792
