### ISSUE TITLE
No re-rendering on ui schema and schema changes

### ISSUE THREAD

**Issue by wimueller** [eclipsesource/jsonforms#1771]
### Describe the bug

I am using the react `useState()` hook to update the jsonforms properties `schema` and `uischema`.
The problem is that the rendered form is not showing the added controls. I want to create a form-builder with drag and drop.
Here is the code from the sandbox:
```
export default function App() {
  // define the react state variables
  const [uiSchemaState, setuiSchemaState] = useState({
    type: "VerticalLayout",
    elements: [
      {
        type: "Control",
        scope: "#/properties/firstname"
      }
    ]
  });
  const [schemaState, setSchemaState] = useState({
    properties: {
      firstname: {
        type: "string"
      }
    }
  });
  const [count, setCount] = useState(0);

  // adds a form field onClick
  function addJSONFormControl() {
    setSchemaState((schema) => {
      Object.assign(schema.properties, {
        ["lastname" + count]: {
          type: "string"
        }
      });
      return schema;
    });

    setuiSchemaState((uischema) => {
      uischema.elements.push({
        type: "Control",
        scope: "#/properties/lastname" + count
      });
      return uischema;
    });
    setCount((counter) => counter + 1);
  }

  return (
    <div>
      <div>{"Click counter: " + count}</div>
      <div>{"Schema: " + JSON.stringify(schemaState)}</div>
      <div>{"UISchema: " + JSON.stringify(uiSchemaState)}</div>
      <JsonForms
        schema={schemaState}
        uischema={uiSchemaState}
        renderers={materialRenderers}
        cells={materialCells}
      />
      <button onClick={addJSONFormControl}>Add lastname</button>
    </div>
  );
}
```
I created a codesandbox to show the behaviour [https://codesandbox.io/s/sad-voice-ohnvy?file=/src/App.js](url)
On each click a _lastname_ field is added to the `schema` and `uischema`. When the `uischema` property is omitted in the jsonforms component the field is still not showing up.

### Expected behavior

Changes on the form-schema, handled by the react state, should lead to a re-rendering of the `JsonForms` component.
In the given example I would expect that on each button click a field is added to the form.

### Steps to reproduce the issue

1. Go to my sandbox: [https://codesandbox.io/s/sad-voice-ohnvy?file=/src/App.js](url)
2. Click on 'Add lastname'
4. See error: no lastname field was added

### In which browser are you experiencing the issue?

Google Chrome 91.0.4472.114 

### Framework

- [ ] Core
- [X] React
- [ ] Angular
- [ ] Vue 3
- [ ] Vue 2
- [ ] Other (please specify in the Additional context field)

### RendererSet

- [X] Material
- [ ] Vanilla
- [ ] Other (please specify in the Additional context field)

**Comment by sdirix** [comment]
Hi @wimueller,

In React it's mandatory that any state update does not equal (`Object.is`) the previous state. If that's not the case, like in the posted code, [React will not rerender the component](https://reactjs.org/docs/hooks-reference.html#bailing-out-of-a-state-update).

You can for example change your code to this:
```javascript
function addJSONFormControl() {
  setSchemaState((schema) => {
    return {
      ...schema,
      properties: {
        ...schema.properties,
        ["lastname" + count]: {
          type: "string"
        }
      }
    };
  });

  setuiSchemaState((uischema) => {
    return {
      ...uischema,
      elements: [
        ...uischema.elements,
        {
          type: "Control",
          scope: "#/properties/lastname" + count
        }
      ]
    };
  });
  setCount((counter) => counter + 1);
}
```
Now a new instance is created with each update and the component properly rerenders.

---

Note that we already open sourced an extensible graphical editor for JSON Forms. You can find the deployed version [here](https://jsonforms-editor.netlify.app/) and the source code [here](https://github.com/eclipsesource/jsonforms-editor).

**Comment by wimueller** [comment]
@sdirix Thanks for the heads up!
