### ISSUE TITLE
Is there any way to use bootstrap or tailwind instead of material ui ?

### ISSUE THREAD

**Issue by skandula106** [eclipsesource/jsonforms#1774]
### Describe the bug

is there any way can you guys please share the link it's very important for me 

### Expected behavior

bootstrap & tailwind ui in json forms

### In which browser are you experiencing the issue?

google chrome latest version 

### Framework

React

### RendererSet

Material

### Additional context

dssdafasd

**Comment by sdirix** [comment]
Hi @skandula106, you can combine the React Vanilla and Vue Vanilla renderer sets with any CSS based solution you like including Tailwind and Bootstrap. As indicated in the [respective](https://github.com/eclipsesource/jsonforms/tree/38153357a5b6dc0a02d940199fb71121f4197001/packages/vanilla#vanilla-renderers-package) [Readmes](https://github.com/eclipsesource/jsonforms/tree/38153357a5b6dc0a02d940199fb71121f4197001/packages/vue/vue-vanilla#styling) as well as on the JSON Forms [renderer set](https://jsonforms.io/docs/renderer-sets#react-vanilla-renderer-set) [overviews](https://jsonforms.io/docs/renderer-sets#vue-vanilla-renderer-set), you can find the React Vanilla guide [here](https://github.com/eclipsesource/jsonforms/blob/38153357a5b6dc0a02d940199fb71121f4197001/packages/vanilla/Styles.md) and the Vua Vanilla guide [here](https://github.com/eclipsesource/jsonforms/tree/38153357a5b6dc0a02d940199fb71121f4197001/packages/vue/vue-vanilla#styling).

**Comment by skandula106** [comment]
Thanks for the reply @sdirix i am started using react with Vanilla renderers(with bootstrap framework )while using i have one problem in vertical layout, by default one div is auto applying we need assign some classes how can i apply for that please look in below image and how can we use radio buttons with bootstrap code 


![image](https://user-images.githubusercontent.com/58414973/124637571-8956bd80-dea7-11eb-95c7-26bb7abad17b.png)

**Comment by sdirix** [comment]
Hi @skandula106, on a first glance I don't know where `row` is coming from. `vertical-layout-item` can be customized, as described in the [Styles](https://github.com/eclipsesource/jsonforms/blob/38153357a5b6dc0a02d940199fb71121f4197001/packages/vanilla/Styles.md) guide.

Whenever there is a mismatch between our renderers and what you need to apply for your CSS (for example different html element structure) you can register a custom renderer which does exactly what you expect.

**Comment by sdirix** [comment]
I'll close this issue for now as there is no more discussion going on. In general JSON Forms can be combined with any kind of UI framework.

Feel free to reopen if you disagree.
