### ISSUE TITLE
Handle primitive labeling in angular-material MasterListComponent

### ISSUE THREAD

**Issue by JBBianchi** [eclipsesource/jsonforms#1779]
### Is your feature request related to a problem? Please describe.

When using a `ListWithDetail` on an array of strings, the label stays undefined even if the `options.labelRef` is set to `#`.

```json
{
  "type": "ListWithDetail",
  "scope": "#/properties/an-array-of-strings",
  "options": {
    "labelRef": "#"
  }
}
```

### Describe the solution you'd like

I'd like the label to be the value of the item. This could be achieved by modifiying the following in [master.ts](https://github.com/eclipsesource/jsonforms/blob/f40e95b5d6815b94f30460fa68e03b8e815a36be/packages/angular-material/src/other/master-detail/master.ts#L186)

```typescript
const dataIsPrimitive = d && typeof d !== 'object';
const masterItem = {
  label: get(d, labelRefInstancePath, dataIsPrimitive ? d : ''),
  data: d,
  path: `${path}.${index}`,
  schema,
  uischema: detailUISchema
};
```

### Describe alternatives you've considered

Using "my own" version of `MasterListComponent`.

### Framework

Angular

### RendererSet

Material

**Comment by sdirix** [comment]
Hi @JBBianchi, thanks for creating this issue.

We wrote the `ListWithDetail` renderer with arrays of objects in mind, therefore I'm not that surprised that it doesn't properly work on primitives. However it can certainly be improved to also handle that case.

Instead of calling `get` with a default value we should just return the primitive value (maybe stringified?) directly as the label. Also we should make sure that there is no runtime error for when `options.labelRef` is not given.

I'm just wondering, what is the use case of using `ListWithDetail` on an array of primitives? Wouldn't it be better to rely on the usual "list" renderer but adding a possibility to add and remove items?

**Comment by JBBianchi** [comment]
Hello @sdirix 

>
> Instead of calling get with a default value we should just return the primitive value (maybe stringified?) directly as the label. Also we should make sure that there is no runtime error for when options.labelRef is not given.
>

Indeed, that makes sense.

> 
> I'm just wondering, what is the use case of using ListWithDetail on an array of primitives? Wouldn't it be better to rely on the usual "list" renderer but adding a possibility to add and remove items?
>

Unfortunatly, from what I understood of the [renderer set table](https://jsonforms.io/docs/renderer-sets/) (and after trying it out), the 'simple' list isn't supported/working in angular.

By providing the following JSON Schema in the [Angular seed](https://github.com/eclipsesource/jsonforms-angular-seed):

**JSON Schema**
```json
{
  "type":"object",
  "properties":{
    "strings":{
      "title":"Array of strings",
      "type":"array",
      "items":{ "type" : "string" }
    },
    "objects":{
      "title":"Array of objects",
      "type":"array",
      "items":{ 
        "type" : "object",
        "properties": {
          "some-prop": {
            "type": "string"
          },
          "another-prop": {
            "type": "string"
          }
        }
      }
    }
  }
}      
```

And the following UI Schema:

```json
{
  "type": "VerticalLayout",
  "elements": [
    {
      "type": "Control",
      "scope": "#/properties/strings"
    }
  ]
}
```

It renders an empty table. (In some configuration, it will render a container with a single input but no button to add/remove items, I'll try to edit/reply if I find a way to reproduce it.) (it's the same behavior if the scope was `#/properties/objects` instead)

**Comment by sdirix** [comment]
The renderer set overview is actually wrong there and is missing the "checkmark" for Angular Material here. Primitive values in arrays work just fine, however the renderer is missing a way to
 - create an empty array
 - add an item to the array
 - remove an item from the array
 
To see the existing renderer in some capacity with your provided schemas you need to also provide the data. So changing `data.ts` to the following does the trick.

```ts
export default {
  strings: ["string1", "string2"]
};
```

![image](https://user-images.githubusercontent.com/8998368/124953782-b923d380-e015-11eb-8b92-c23bd0660f42.png)

**Comment by JBBianchi** [comment]
I see (the same can also be achieved by providing a `default` in the json schema and turning `useDefaults` to true in Ajv btw) but it indeed lacks the capability to add/remove items like the React Material version does. That's why I tricked and used `ListWithDetail`, it allows me to have those features.

**Comment by sdirix** [comment]
I extracted this into a separate issue: https://github.com/eclipsesource/jsonforms/issues/1782
