### ISSUE TITLE
Add "Add" and "Remove" actions to the Angular Table

### ISSUE THREAD

**Issue by sdirix** [eclipsesource/jsonforms#1782]
### Is your feature request related to a problem? Please describe.

At the moment the Angular Table is very basic. It would be great to add "Add" and "Remove" actions, similar to the Array Layout renderer.

### Describe the solution you'd like

Add an "Add" button which is able to
 - create a new item instance (should also support primitives)
 - create the array if it not yet exists

Add a "Remove" button in each row which is able to
- remove the corresponding entry

### Describe alternatives you've considered

There could also be a remove button for the whole array which not only empties the array but removes it completely. Note that we don't have such a remove button yet in any other renderer set too.

### Framework

Angular

### RendererSet

Material

**Comment by bappctl** [comment]
@sdirix 
Following up here on https://jsonforms.discourse.group/t/array-not-rendering-add-button-is-missing/174/13

Thank you. What would be the alternate approach to resolve this issue?

**Comment by robertcbit** [comment]
Following up here on https://jsonforms.discourse.group/t/array-not-rendering-add-button-is-missing/174/13
Same. What would be the alternate approach to resolve this issue? Any status updates on this? 
We desperately need this right now.

**Comment by sdirix** [comment]
There is no status update.

You have basically two options:
 - Implement a custom table renderer for arrays which includes support for these buttons
 - Use the non-table renderer for arrays. This can be done for example by specifying [an inlined UI schema via the `options`](https://jsonforms.io/docs/uischema/controls#the-detail-option).

Of course we would also look at a contribution adding "Add" and "Remove" to the existing table renderer.

**Comment by brunodubcosta** [comment]
Hello friends
I have created a custom table renderer that has the Add and Remove copied from the ArrayRenderer.
Would like to contribute.
![Screenshot 2022-05-13 at 04 56 24](https://user-images.githubusercontent.com/46161091/168208256-ccd1b5ae-9b9b-4fb3-9597-6ec67de2cd4b.png)
