### ISSUE TITLE
RadioGroupControl not registered in React Vanilla

### ISSUE THREAD

**Issue by skandula106** [eclipsesource/jsonforms#1783]
### Describe the bug

Hai 

          I am unable to use Input type ="radio" and checkbox if config below schema and schema json with vanilla renders its displaying select button can you help me with that you people are already developed render for radio button and check box can you please share configuration for this types in vanilla renders  
          
          
          
          {
  "type": "object",
  "properties": {
    "exampleRadioEnum": {
      "type": "string",
      "enum": [
        "One",
        "Two",
        "Three"
      ]
    }
  }
}

{
  "type": "Control",
  "scope": "#/properties/exampleRadioEnum",
  "options": {
    "format": "radio"
  }
}

### Expected behavior

Radio button

### Screenshots

{
          "type": "Control",
          "scope": "#/properties/sex",
          "options": {
            "format": "radio"
          }
        },

"sex": {
      "title": "Sex",
      "type": "string",
      "enum": [
        "male",
        "female"
      ]
    },

![image](https://user-images.githubusercontent.com/58414973/125195282-9fcb9300-e272-11eb-8f65-dbb2f493f4c7.png)

### In which browser are you experiencing the issue?

google chrome latest 

### Framework

React

### RendererSet

Vanilla

### Additional context

dADSad

**Comment by sdirix** [comment]
Hi! Thanks for the report. However, please don't post the same message on [multiple channels](https://jsonforms.discourse.group/t/how-we-can-use-input-type-radio-and-input-type-checkbox-with-vanilla-renderers/278). 

The `RadioGroupControl` is currently not part of the build. If you'd like to use it you can copy [the source](https://github.com/eclipsesource/jsonforms/blob/96e2c41efd3d29a2b349838105cb0e3c29115913/packages/vanilla/src/controls/RadioGroupControl.tsx) to your app and register it as an additional renderer.
