### ISSUE TITLE
`mapStateToAnyOfProps` -> `mapStateToCombinatorRendererProps` StructuralKeywords should include `const`

### ISSUE THREAD

**Issue by richturner** [eclipsesource/jsonforms#1787]
### Describe the bug

Currently the [mapStateToCombinatorRendererProps](https://github.com/eclipsesource/jsonforms/blob/cc2d578dc280538403b815e7689f0b178ee6feb2/packages/core/src/util/renderer.ts#L852) function does not consider a validation error relating to a `const` constraint as invalid and therefore the incorrect `indexOfFittingSchema` can be returned.

### Expected behavior

A `const` validation failure should be invalid and therefore `indexOfFittingSchema` should move onto the next schema for validation.

StructuralKeywords should include `const`

### Steps to reproduce the issue

Use a schema containing an `anyOf` array with `const` constraints and the `indexOfFittingSchema` will always return 0

### In which browser are you experiencing the issue?

Google Chrome 91.0.4472.164

**Comment by sdirix** [comment]
Thanks for the report! Would you be willing to contribute the change including a test case? This would be the fastest way to get the change in.

**Comment by richturner** [comment]
Pull request created; I couldn't get the tests to compile without switching this import:
```
import { setValidationMode } from '../../lib';
```
to : 
```
import { setValidationMode } from '../../src/actions';
```

Don't know where `lib` comes from? I reverted this change in the PR but wanted to make you aware.

**Comment by sdirix** [comment]
`lib` is the output directory of our build. So switching the import path is certainly the right thing to do for the tests. Maybe this came in via the editor's auto import feature.
