### ISSUE TITLE
Add PR and Issue templates and move GitHub files

### ISSUE THREAD

**Issue by sdirix** [eclipsesource/jsonforms#179]
Github now supports templates for PRs and issues. We should probably use them.

Also all Github related files can now be moved in a specialized github directory to avoid clutter.

https://github.com/blog/2111-issue-and-pull-request-templates

**Comment by sdirix** [comment]
PR templates were already added with #194

**Comment by edgarmueller** [comment]
Can we close this one then?

**Comment by edgarmueller** [comment]
@sdirix this can be closed, right?

**Comment by edgarmueller** [comment]
@sdirix I assume this is a 'yes' ;)
