### ISSUE TITLE
No elements rendered with testing-library/react when using Material Renderers

### ISSUE THREAD

**Issue by CarlosGomez-dev** [eclipsesource/jsonforms#1795]
### Describe the bug

I'm writing tests with Jest and testing-library/react and I noticed the `<JsonForms/>` component and its children are not rendered. Any assertions on those elements fail.

Vanilla renderers do not have this issue, the form is rendered correctly and assertions pass with no issues.

Issue can be reproduced with 2.5.2 and 3.0.0-alpha.1

### Expected behavior

`<JsonForms/>` component should render the form and its children correctly when rendered with @testing-library/react, whether it's using vanilla renderers or material renderers.

### Steps to reproduce the issue

1. `npx create-react-app jsonform-test`
2. `cd jsonform-test`
3. `npm install @jsonforms/core @jsonforms/react @jsonforms/material-renderers @jsonforms/vanilla-renderers @material-ui/core @material-ui/icons`
3. Copy the following code into `App.test.js` and run tests `npm test`
```jsx
import { render, screen } from '@testing-library/react';
import { JsonForms } from '@jsonforms/react';
import { materialCells, materialRenderers } from '@jsonforms/material-renderers';
import { vanillaCells, vanillaRenderers } from '@jsonforms/vanilla-renderers';
import { Box, Typography } from '@material-ui/core';

const schema = {
  type: 'object',
  properties: {
    name: {
      type: 'string',
    },
  },
};

const uischemaVanilla = {
  type: 'HorizontalLayout',
  elements: [
    {
      type: 'Control',
      label: 'Vanilla',
      scope: '#/properties/name',
    },
  ],
};

const uischemamaterial = {
  type: 'HorizontalLayout',
  elements: [
    {
      type: 'Control',
      label: 'Material',
      scope: '#/properties/name',
    },
  ],
};

const data = {
  name: 'John Doe',
};

const Component = () => (
  <div className='App'>
    <Box>
      <Typography>Typography</Typography>
    </Box>
    <JsonForms
      schema={schema}
      uischema={uischemaVanilla}
      data={data}
      renderers={vanillaRenderers}
      cells={vanillaCells}
    />
    <JsonForms
      schema={schema}
      uischema={uischemamaterial}
      data={data}
      renderers={materialRenderers}
      cells={materialCells}
    />
  </div>
);

test('render jsonforms', () => {
  render(<Component />).debug();
  expect(screen.getByText(/vanilla/i)).toBeInTheDocument();
  expect(screen.getByText(/material/i)).toBeInTheDocument();
});
```
4. Vanilla assertion will pass while material assertion fails.
5. The rendered DOM contains material components and JsonForms with vanilla renderers, but JsonForms with material renderers is not rendered
```html
<body>
      <div>
        <div
          class="App"
        >
          <div
            class="MuiBox-root MuiBox-root-1"
          >
            <p
              class="MuiTypography-root MuiTypography-body1"
            >
              Typography
            </p>
          </div>
          <div
            class="horizontal-layout"
          >
            <div
              class="horizontal-layout-item horizontal-layout-1"
            >
              <div
                class="control root_properties_name"
                id="#/properties/name"
              >
                <label
                  class=""
                  for="#/properties/name-input"
                >
                  Vanilla
                </label>
                <input
                  class="validate valid input"
                  id="#/properties/name-input"
                  type="text"
                  value="John Doe"
                />
                <div
                  class="validation input-description"
                />
              </div>
            </div>
          </div>
        </div>
      </div>
    </body>
```

### In which browser are you experiencing the issue?

@testing-library/react 11.1.0

### Framework

React

### RendererSet

Material

**Comment by sdirix** [comment]
Hi @CarlosGomez-dev, thanks for the report!

We faced the same problem when developing our own test cases. The issue is that the media queries of the `Hidden` elements in Material UI "fail" in the testing scenario and therefore the elements are not rendered. As all elements in JSON Forms can be hidden, the form appears to be empty.

For our testcases we solved it [via a mock](https://github.com/eclipsesource/jsonforms/blob/ba6bdc5a93044a872285cd71ed40d9a54f437561/packages/material/test/renderers/MatchMediaMock.ts) which we [import in all our test files](https://github.com/eclipsesource/jsonforms/blob/ba6bdc5a93044a872285cd71ed40d9a54f437561/packages/material/test/renderers/MaterialAllOfRenderer.test.tsx#L25).

Please let us know whether this solves your issue.

**Comment by CarlosGomez-dev** [comment]
Hi @sdirix, that was exactly it! Thank you, sir.
