### ISSUE TITLE
Effect `HIDE/SHOW` not working when rule applied on `formatMinimum` of `date` format field

### ISSUE THREAD

**Issue by jawad360** [eclipsesource/jsonforms#1799]
### Describe the bug

I've a two fields in form one is date format field (`dob`) and other is array type field (`study`).
Now here I've applied effect HIDE on `study` field such that it gets hidden when the `dob` field is above certain value

Used `formatMinimum` in rule effect conditional schema to toggle the visibility.

Both the fields are getting rendered correctly on screen, which validates that schema is valid

```
  "name": "@jsonforms/core",
  "version": "2.4.0",
```

### Expected behavior

Effect HIDE is not happening on `study` field even though I'm satisfying `formatMinimum` condition mentioned in the rule condition schema

### Steps to reproduce the issue

Here is my schema and uischema

```
const formSchemaVisibility = {
  type: "object",
  properties: {
    dob: {
      type: "string",
      format: "date",
    },
    fieldOfStudy: {
      type: "array",
      items: {
        type: "string",
        enum: ["Science", "Maths", "Arts", "Commerce"],
      },
    },
  },
  required: ["dob", "fieldOfStudy"],
};
const formUiSchemaVisibility = {
  type: "StepLayout",
  elements: [
    {
      type: "VerticalLayout",
      name: "DEFAULT",
      elements: [
        {
          type: "Control",
          label: "Date of birth",
          scope: "#/properties/dob",
          options: {
            controlType: "DatePicker",
            uiFormat: "MM-DD-YYYY",
          },
        },
        {
          type: "Control",
          label: "Field of Study",
          scope: "#/properties/fieldOfStudy",
          rule: {
            effect: "HIDE",
            condition: {
              scope: "#/properties/dob",
              schema: {
                format: "date",
                formatMinimum: "2020-04-30",
              },
            },
          },
        },
      ],
    },
  ],
};

```
Here is how I'm rendering the UI
```
import { createAjv } from '@jsonforms/core';
import AjvKeywords from 'ajv-keywords';
const ajv = createAjv({
	format: 'full',
	validateSchema: false,
});
AjvKeywords(ajv);
<JsonForms
    schema={schemaParsed}
    uischema={uischemaParsed}
    data={data}
    renderers={CustomRenderers}
    cells={vanillaCells}
    onChange={onChange}
    ajv={ajv}
/>
```
Above schema and uischema renders both the fields correctly and they work as expected, but the HIDE effect on `fieldOfStudy` is not working

### Reason for not working
In the above code we can see that I've customise the AJV options to pass `format:full`, which give me advance validation on `formatMinimum` and `formatMaximum` and that is working correctly

But when we are doing effect evaluation in file `@jsonforms/core/src/util/runtime.ts`, here i can see we are importing ajv `const ajv = createAjv();` which will not have the customisation that I've done when passing it to JSON form.
And since default ajv do not support advance checks on `formatMinimum` or `formatMaximum` the ajv validation always returns true and does not fail

In `runtime.js` somehow we need to fetch the ajv that is provided in the `JSONForm` and not create a new one

### In which browser are you experiencing the issue?

Google Chrome 92.0.4515.131

### Framework

Core

### RendererSet

Vanilla

**Comment by sdirix** [comment]
Hi @jawad360, can you try with a later version of JSON Forms, e.g. `2.4.1` or even `3.0.0-alpha.1`? We [changed the evaluation code a while ago](https://github.com/eclipsesource/jsonforms/commit/0595f777178fe21488d650a3cb5147b94623eacd#diff-3190824619bda1478eaff578280918f16a7257047f86ebc6aa9b60f5531d24b0) (published with version `2.4.1`) to fix this exact issue that the provided AJV was not used in all places.

Once you update JSON Forms your custom AJV will also be used for the rule evaluations.

**Comment by sdirix** [comment]
@jawad360 Any update on this?

**Comment by jawad360** [comment]
@sdirix  thanks a lot this help 👍
