### ISSUE TITLE
Unable to resolve ref to external file (angular)

### ISSUE THREAD

**Issue by sayushideep** [eclipsesource/jsonforms#1800]
### Describe the bug

I'm trying to use external file refs in schema.json but I don't think they are being resolved internally by the jsonforms. I tried adding the schema to ajv but it isn't working. Is there something I'm missing out here?

Below are my files
My customerData.json:
```
{
    "$id":"example.com/customerData.json",
    "definitions": {
        "user": {
            "type":"object",
            "properties": {
               "name": { "type": "string"},
                "department": { "type": "string" }
               },
            "required": ["name","department"]
        }
    },
    "type": "object"
}
```
schema.json - 
```
{
  "$id":"example.com/schema.json",
  "type": "object",
  "properties": {
    "user": {
      "$ref":"customerData.json#/definitions/user"
    }
  }
}
```

uischema.json - 
```
{
  "type": "Group",
  "label": "Customer",
  "elements": [
    {
      "type":"VerticalLayout",
      "elements": [
        {
          "type": "Control",
          "scope": "#/properties/user"
        }
      ]
    }
  ]
}
```

### Expected behavior

Refs should resolve

### Steps to reproduce the issue

1. Use the angular seed app - https://github.com/eclipsesource/jsonforms-angular-seed
2. Replace schema.json and uischema.json with above files.
3. Put customerData.json in same assets directory
4. Run the app and check the issue on browser

### Screenshots

Error UI - 
![image](https://user-images.githubusercontent.com/84182137/130650308-481d765e-7e01-4f6e-8eec-369735e1a488.png)

Error on console - 
![image](https://user-images.githubusercontent.com/84182137/130650709-5a36e8a0-3b8d-4349-b788-c0d337863eba.png)

### In which browser are you experiencing the issue?

Google Chrome Latest

### Framework

Angular

### RendererSet

Material

**Comment by sdirix** [comment]
Hi. The Angular renderers did never support resolving external references pointing to other files. With JSON Forms 3.0 we also removed this capability in the React Material renderers. You can find the [reasoning here](https://github.com/eclipsesource/jsonforms/blob/ba6bdc5a93044a872285cd71ed40d9a54f437561/MIGRATION.md#migrating-to-json-forms-30-for-react-users) and the recommended approach for external references [here](https://jsonforms.io/docs/ref-resolving).
