### ISSUE TITLE
Should formatIs ranker support null types?

### ISSUE THREAD

**Issue by alastair-todd** [eclipsesource/jsonforms#1804]
### Describe the bug

```
export const formatIs = (expectedFormat: string): Tester =>
  schemaMatches(
    schema =>
      !isEmpty(schema) &&
      schema.format === expectedFormat &&
      schema.type === 'string'
  );
```

### Expected behavior

Should support nulls

`type: ['string', 'null']`

### Steps to reproduce the issue

N/A

### In which browser are you experiencing the issue?

N/A

### Framework

Core

**Comment by sdirix** [comment]
Hi @alastair-todd thanks for the report. If I read [the spec](https://json-schema.org/draft/2020-12/json-schema-validation.html#format) correctly we should probably not hard code a check against `null` but rather check whether `string` is included in the `type` array.

The only problem I see here is for users who are already using `formatIs`, rely on the type always being a `string` and then suddenly their custom renderer is also invoked on other types.

**Comment by sdirix** [comment]
In the mean time you can always write your own version of `formatIs` which works "properly"

**Comment by alastair-todd** [comment]
Well yeah I've gone and created my own testers.

```typescript
const formatIs = (expectedFormat: string): Tester => 
  schemaMatches((schema) => !isEmpty(schema) && schema.format === expectedFormat);
```

Its the same for `oneOf` with a null value e.g.

```json
[
   {
      "title":" ",
      "type":"null"
   },
   {
      "title":"Permanent",
      "const":"Permanent"
   },
   {
      "title":"Temporary",
      "const":"Temporary"
   },
   {
      "title":"Casual",
      "const":"Casual"
   }
]
```

```typescript
const isOneOfEnumControl = and(
  uiTypeIs('Control'),
  schemaMatches(schema =>
    schema.hasOwnProperty('oneOf')
  )
);
```

(removed the in-built version's forcing all values to be `const`)

**Comment by sdirix** [comment]
This was fixed with https://github.com/eclipsesource/jsonforms/pull/1925
