### ISSUE TITLE
Update React Material renderer set to Material UI v5

### ISSUE THREAD

**Issue by sdirix** [eclipsesource/jsonforms#1805]
### Is your feature request related to a problem? Please describe.

Material UI v5 has some breaking changes, most notably the import paths. 

### Describe the solution you'd like

Update the React Material renderer set to Material UI v5

### Describe alternatives you've considered

Adjust React Material renderer set to be compatible with Material UI v4 and v5. However this requires additional effort and may have consequences on the renderer set architecture.

### Framework

React

### RendererSet

Material

### Additional context

https://next.material-ui.com/guides/migration-v4/

**Comment by lcanavesio** [comment]
Hi @sdirix 
I use jsonforms/packages/material 
Have an estimated date to update to mui 5?

**Comment by sdirix** [comment]
Hi @lcanavesio, we're actively working on it, see https://github.com/eclipsesource/jsonforms/pull/1812. It'll probably be part of the next prerelease and definitely part of the 3.0 release.

I don't like to commit to specific dates, however my best guess is the MUI update should be in a (pre)release within November.

**Comment by lcanavesio** [comment]
> Hi @lcanavesio, we're actively working on it, see #1812. It'll probably be part of the next prerelease and definitely part of the 3.0 release.
> 
> I don't like to commit to specific dates, however my best guess is the MUI update should be in a (pre)release within November.

Thanks for answering @sdirix 

I take the opportunity to tell you that the text input when deleting the data with keyboard backspace <-- ; it is not required again but if I press the clean button yes. When deleting it does not reassign undefinded when it is empty

https://jsonforms.io/examples/basic -> Occupation*

Thanks for everything

**Comment by sdirix** [comment]
> I take the opportunity to tell you that the text input when deleting the data with keyboard backspace <-- ; it is not required again but if I press the clean button yes. When deleting it does not reassign undefinded when it is empty

This is currently [by design](https://github.com/eclipsesource/jsonforms/issues/1810#issuecomment-930295225). We are considering changing it.
