### ISSUE TITLE
Question: How to pass data between components

### ISSUE THREAD

**Issue by irakli-g** [eclipsesource/jsonforms#1811]
### Is your feature request related to a problem? Please describe.

Hi, first of all, great library!

I have two custom renderers one is google autocomplete textfield and other one is google map.

Both are shown as custom renderers and everything works fine except one part. Google map is dependant on address generated by autocomplete text field.

For example if I type some address and then choose one of the suggestions, upon updating autocomplete field google map should reflect the changes. Basically, all I am asking is how can I pass data between components, in this case I want to pass coordinates ( latitude and longitude which is generated by autocomplete behind the scenes, only actual address is visible for the user ) from autocomplete textfield to google map.

Example
<img width="1089" alt="Screenshot 2021-09-29 at 13 08 19" src="https://user-images.githubusercontent.com/70649220/135238812-6af7dcc0-bfca-425e-ba18-3c1434c8360b.png">

### Describe the solution you'd like

To update one component's data based on other component's input.

### Describe alternatives you've considered

Managing input generated by autocomplete manually in a separate state.

### Framework

React

### RendererSet

Material

**Comment by irakli-g** [comment]
I've checked $ref and linking inputs. So this is how my schema looks like now 

`{
    "type": "object",
    "properties": {
        "firstName": {
            "type": "string",
            "minLength": 3,
            "description": "Please enter your first name"
        },
        "secondName": {
            "type": "string",
            "minLength": 3,
            "description": "Please enter your second name"
        },
        "vegetarian": {
            "type": "boolean"
        },
        "birthDate": {
            "type": "string",
            "format": "date",
            "description": "Please enter your birth date."
        },
        "nationality": {
            "type": "string",
            "enum": ["DE", "IT", "JP", "US", "RU", "Other"]
        },
        "provideAddress": {
            "type": "boolean"
        },
        "address": {
            "type": "object",
            "properties": {
                "street": {
                    "type": "string"
                },
                "latitude": {
                    "type": "number"
                },
                "longitude": {
                    "type": "number"
                }
            }
        },
        "map": {
            "type": "object",
            "properties": {
                "latitude": {
                    "$ref": "#/properties/address/properties/latitude"
                },
                "longitude": {
                    "$ref": "#/properties/address/properties/longitude"
                }
            }
        },
        "vegetarianOptions": {
            "type": "object",
            "properties": {
                "vegan": {
                    "type": "boolean"
                },
                "favoriteVegetable": {
                    "type": "string",
                    "enum": ["Tomato", "Potato", "Salad", "Aubergine", "Cucumber", "Other"]
                },
                "otherFavoriteVegetable": {
                    "type": "string"
                }
            }
        }
    }
}
`

But data property passed to map does not get filled upon changing the address:
<img width="1437" alt="Screenshot 2021-09-29 at 14 20 34" src="https://user-images.githubusercontent.com/70649220/135250665-68b996c8-07f8-415c-9ecf-b88e8165d389.png">


`import React from "react";
import { withJsonFormsControlProps } from "@jsonforms/react";
import Map from "./Map";

const MapControl = ({ data, handleChange, path }) => {
    console.log(data);
    return (
        <Map
            value={data}
            updateValue={newValue => {
                handleChange(path, newValue);
            }}
        />
    );
};

export default withJsonFormsControlProps(MapControl);
`

Data passed to map is undefined and changing address seems to have no effect on it.

This is my address component:
`import React from "react";
import { withJsonFormsControlProps } from "@jsonforms/react";
import AutoComplete from "./AutoComplete";

const AutoCompleteControl = ({ data, handleChange, path }) => {
    return (
        <AutoComplete
            value={data && typeof data === "object" ? data.street : ""}
            updateValue={newValue => {
                handleChange(path, newValue);
            }}
        />
    );
};

export default withJsonFormsControlProps(AutoCompleteControl);
`

**Comment by sdirix** [comment]
Hi @irakli-g, please use the [JSON Forms board for questions](https://jsonforms.discourse.group/). We would like to use the issues for bugs and planned features only.

`$ref` doesn't help you here as it only works on the level of the meta schema, i.e. they just declare that the type of `map.latitude` is the same as the one of `address.latitude` and the type of `map.longitude` is the same as `address.longitude`. They don't express anything about the instance values.

To access other data in your custom renderer you can use the `useJsonForms()` hook which gives you access to the whole JSON Forms store, e.g.

```ts
const context = useJsonForms();
const { latitude, longitude } = context.core.data.address;
```

The component using `useJsonForms()` will be rerendered with any core change so you might want to put a `memo` barrier in between if your map renderer doesn't like to be rerendered without any actual change.
