### ISSUE TITLE
Is there a way to access the properties of any element rendered by json forms?

### ISSUE THREAD

**Issue by kevoese** [eclipsesource/jsonforms#1816]
### Is your feature request related to a problem? Please describe.

After the JSON form renders the UI schema say like this
![image](https://user-images.githubusercontent.com/45713801/137278385-86901679-955d-48ef-88b6-589e4299cda4.png)

If there's a change in an element  say
![image](https://user-images.githubusercontent.com/45713801/137281964-59a71887-5c36-4baf-ae9e-96e7f9bbd60a.png)

On each data change, I only have access to the data object of the form when it is changed at the onChange callback function.

Is there a way to get a more specific detail about the changed element?

### Describe the solution you'd like

I would like to have a function to get an element by a reference that could be any property that can be passed along in the JSON forms. If this already exists I would appreciate it if you can help with a solution. 

### Describe alternatives you've considered

The current alternative is looping through the new data and comparing it with the old data for where changes were made, then utilizing the information.
The problem with my alternative is it doesn't scale well as data increases. But do help me out if you have a better approach to this.

### Framework

React

### RendererSet

Material

**Comment by kevoese** [comment]
Thanks for the response. I will check this out.

**Comment by sdirix** [comment]
I can also recommend [`fast-json-patch`](https://www.npmjs.com/package/fast-json-patch) to calculate a diff between the old and the new data. Using this you get a nice description of what actually changed with each update.

**Comment by sdirix** [comment]
I'll close this issue for now as there are some workarounds like `fast-json-patch` which can be used for this. For the foreseeable future we'll not support more detailed change notifications.
