### ISSUE TITLE
Incorrect typings for react JsonForms component props

### ISSUE THREAD

**Issue by bsShoham** [eclipsesource/jsonforms#1818]
### Describe the bug

`JsonForm` expected props are `JsonFormsInitStateProps & JsonFormsReactProps`, in which `uischema` type is `UISchemaElement`. 
That declaration is incorrect since it can't accept a `Layout`, which includes the elements field.

### Expected behavior

the type should be replaced for something more inclusive and allow insertion of `Layout` type

### Steps to reproduce the issue

1. Import `JsonForms` component
2. Insert required props for component
3. Add `uischema` prop with a value including "elements" field

### Screenshots

Both ways to type it correctly fail
![image](https://user-images.githubusercontent.com/91195275/137332703-0824e70b-45ab-41bc-9168-559b010508ab.png)

The Error itself
![image](https://user-images.githubusercontent.com/91195275/137333033-65046595-61be-445d-ac6f-b1243fa7579c.png)

### In which browser are you experiencing the issue?

Microsoft Edge  94.0.992.38 (Official build) (64-bit)

### Framework

React

### RendererSet

Material

### Additional context

using typescript 4.3.5
using @jsonforms/core 2.5.2
using @jsonforms/material-renderers 2.5.2
using @jsonforms/react 2.5.2

**Comment by sdirix** [comment]
I'll close this issue for now as the typings are not incorrect. Feel free to reopen if you disagree.
