### ISSUE TITLE
Sliders cause infinite loop. Step size not working

### ISSUE THREAD

**Issue by stefdoerr** [eclipsesource/jsonforms#1819]
### Describe the bug

Trying to add a slider to my form. I'm using react and material-ui and jsonforms 2.5.1. 
I have not modified the component, I am using the default component for number inputs as shown here: https://jsonforms.io/examples/control/ in the second example.
If I put `"slider": false` everything works fine, I can modify the value.
If I put `"slider": true` I start getting the following errors in the web console and cannot modify the value.

Also the step size doesn't seem to work with slider: true, even though it works with slider: false

```
Warning: Maximum update depth exceeded. This can happen when a component calls setState inside useEffect, but useEffect either doesn't have a dependency array, or one of the dependencies changes on every render.
./node_modules/@jsonforms/react/lib/JsonFormsContext.js/exports.JsonFormsStateProvider@http://localhost:3000/static/js/0.chunk.js:12730:18
./node_modules/@jsonforms/react/lib/JsonForms.js/exports.JsonForms@http://localhost:3000/static/js/0.chunk.js:12607:13
div
div
Grid@http://localhost:3000/static/js/0.chunk.js:24692:29
WithStyles@http://localhost:3000/static/js/0.chunk.js:56768:25
div
Grid@http://localhost:3000/static/js/0.chunk.js:24692:29
WithStyles@http://localhost:3000/static/js/0.chunk.js:56768:25
App@http://localhost:3000/static/js/main.chunk.js:219:17
ThemeProvider@http://localhost:3000/static/js/0.chunk.js:55470:18
```

### Expected behavior

No infinite loop
Working step size for sliders

### Steps to reproduce the issue

I'm using react 17.0.1 and material-ui 4.11.2 and jsonforms 2.5.1. 

My schema.json looks as follows:
```json
{
  "type": "object",
  "properties": {
    "myslider": {
      "description": "Touch this slider!",
      "type": "number",
      "minimum": 3.1,
      "maximum": 8.0,
      "default": 4.2,
      "step": 0.1
    }
  },
  "required": []
}
```

My uischema.json looks as follows:
```json
{
  "type": "VerticalLayout",
  "elements": [
    {
      "type": "Control",
      "scope": "#/properties/myslider",
      "options": {
        "slider": true
      },
      "label": "My Slider"
    }
  ]
}
```

### Screenshots

![image](https://user-images.githubusercontent.com/7935362/137472709-7979b283-d2a4-4059-a88d-ac664e28fcc7.png)

### In which browser are you experiencing the issue?

Firefox 93 Ubuntu

### Framework

React

### RendererSet

Material

**Comment by rkoleci** [comment]
Can you assignthis to me ?

**Comment by sdirix** [comment]
Hi @rkoleci, this issue will be fixed by https://github.com/eclipsesource/jsonforms/pull/1812. So I would recommend not working on this ;)

**Comment by sdirix** [comment]
I can no longer reproduce the problem with the update to Material v5. Please reopen if you still encounter issues.
