### ISSUE TITLE
Translate hard coded strings in existing renderer sets

### ISSUE THREAD

**Issue by sdirix** [eclipsesource/jsonforms#1826]
### Is your feature request related to a problem? Please describe.

The goal is to allow a full translation of currently hard coded strings in the existing renderer sets.

### Describe the solution you'd like

With https://github.com/eclipsesource/jsonforms/issues/1751 JSON Forms now has the capabilities to localize any UI element. The new translation functions now need to be integrated in the existing React Material, React Vanilla, Angular Material, Vue 2/3 Vanilla and Vue 2 Vuetify renderer sets.

### Describe alternatives you've considered

The alternative is for users to provide custom renderers.

### Framework

React, Angular, Vue 3, Vue 2

### RendererSet

Material, Vanilla, Other (please specify in the Additional context field)

### Additional context

Vuetify

**Comment by oteoe** [comment]
page needs to be updated:
https://jsonforms.io/docs/i18n/
