### ISSUE TITLE
Control labels can not be hidden

### ISSUE THREAD

**Issue by edgarmueller** [eclipsesource/jsonforms#183]
Since we are trying to be super-smart, we derive labels from the schema path for controls even if one did not specify a label in the UI schema. Question then is: how can we actually hide a label?

**Comment by JonasHelming** [comment]
In EMF Forms, we have the Label Alignment: DEFAULT, NONE, LEFT, etc.
If we add only DEFAULT and NONE now, we have solved the issue but have room for extension
