### ISSUE TITLE
Categorization change Event

### ISSUE THREAD

**Issue by diegoulloao** [eclipsesource/jsonforms#1839]
### Describe the bug

I don't see any event I can handle to detect when user goes to a different category section (categorization).

### Expected behavior

I need to detect when user changes of section in order to show title and description per section.
Also I need to get the current ui-schema data for that category in specific (to extract my custom fields: title - description)

### Steps to reproduce the issue

---

### In which browser are you experiencing the issue?

All

### Framework

React

### RendererSet

Vanilla

**Comment by sdirix** [comment]
Hi @diegoulloao, the state of the categorization is encapsulated in the category renderer. So when you need to react to categorization switches then you need to provide your own custom categorization renderer.

In the future please use the [discussion board](https://jsonforms.discourse.group/) for questions ;) Thanks!
