### ISSUE TITLE
undefined rootSchema in resolveSchema() causes: Cannot read properties of undefined (reading 'properties')

### ISSUE THREAD

**Issue by mirismaili** [eclipsesource/jsonforms#1855]
### Describe the bug

In `resolveSchema()` function:

https://github.com/eclipsesource/jsonforms/blob/81f1f19dac49b1864e712e9abbc5c5c6355a2b91/packages/core/src/util/resolvers.ts#L156-L162

`rootSchema` in `catch` block can be `undefined`. This is an optional parameter of `resolveShcema()`:

https://github.com/eclipsesource/jsonforms/blob/81f1f19dac49b1864e712e9abbc5c5c6355a2b91/packages/core/src/util/resolvers.ts#L110-L114

and its value hasn't been checked (for being `undefined`) before.
***
This is not only a potential bug. The function has actually been called without `rootSchema` in some places (e.g. in `testers.js`) and I especially encountered it after this:

https://github.com/eclipsesource/jsonforms/blob/81f1f19dac49b1864e712e9abbc5c5c6355a2b91/packages/core/src/testers/testers.ts#L89

### Expected behavior

Obviously, _having no error_. 

But I think the more important issue here is **why schema `$ref`s should be resolved in testers many times? This would be a big performance issue!** The schema can be parsed (resolved) one time and be used multiple times (in testers and probably any other places).

### Steps to reproduce the issue

 1. Go to [Playground](https://mirismaili.github.io/jsonforms-playground)
 2. Set:
    `JSON-Schema`:
    ```json
    {
      "type": "object",
      "definitions": {
        "test": {
          "type": "string"
        }
      },
      "properties": {
        "foo": {
          "type": "object",
          "properties": {
            "bar": {
              "$ref": "#/definitions/test"
            }
          }
        }
      }
    }
    ```
    `UI-Schema`:
    ```json
    false
    ```
    `Data`:
    ```json
    {}
    ```

### Screenshots

![image](https://user-images.githubusercontent.com/15800189/146761002-28129f1f-aff1-41c1-97b7-c9a8bc1d196d.png)

***Note: The above playground works with JsonForms v3.0.0-alpha.2***

### In which browser are you experiencing the issue?

Google Chrome v96.0.4664.93 (Official Build) (64-bit)

**Comment by sdirix** [comment]
Hi @mirismaili, thanks for the report!

Yes the resolving is not in the best state at the moment in the alpha release. We will make sure that all basic resolving cases work before the stable release, see https://github.com/eclipsesource/jsonforms/issues/1750 for more information.

Note that you can always resolve your JSON Schema yourself before handing it over to JSON Forms. I would like recommend `json-refs` for that, see https://jsonforms.io/docs/ref-resolving

**Comment by mirismaili** [comment]
Hi @sdirix, you're welcome.

OK. I did so. Thanks.

**Comment by sdirix** [comment]
This issue should be solved by https://github.com/eclipsesource/jsonforms/pull/1829. Can you verify?

**Comment by sdirix** [comment]
I'll close this for now. Please reopen if you encounter further issues.
