### ISSUE TITLE
Infinite loop caused by Address Autofill in Chrome

### ISSUE THREAD

**Issue by jakobmcfarland** [eclipsesource/jsonforms#1857]
### Describe the bug

After upgrading to 3.0.0-alpha.3, using address autofill prompt in chrome causes a "Maximum update depth exceeded" error. This only occurs if three or more fields are autofilled at once. Firefox's equivalent address autofill seems to work as expected.

### Expected behavior

The address fields should be autofilled without crashing.

### Steps to reproduce the issue

1. Add a test address in chrome://settings/addresses.
2. Create a form containing at least three fields labeled "Name", "Address", and "City".
2. Click on one of the fields, and the chrome autofill dialog should appear. 
3. Click on the test address.
3. React should crash due to an infinite loop. 

### Screenshots

![jsonforms_address_autofill_crash](https://user-images.githubusercontent.com/35501345/147009727-6344c38e-b2c6-4be1-8c47-9d2d3d7cf1b2.png)
![jsonforms_address_autofill_crash2](https://user-images.githubusercontent.com/35501345/147009729-4951542d-6970-4237-ab5d-e08b4626a701.PNG)

### In which browser are you experiencing the issue?

Google Chrome Version 96.0.4664.110

### Framework

React

### RendererSet

Material

### Additional context

I recreated this in the jsonforms-react-seed, only changing the schema and uischema.

**Comment by sdirix** [comment]
Thanks for the report. We'll take a look as soon as possible :)
