### ISSUE TITLE
TypeScript error in jsonforms/vue: renderers cannot be assigned to 'JsonFormsRendererRegistryEntry[]'

### ISSUE THREAD

**Issue by rokiyama** [eclipsesource/jsonforms#1859]
### Describe the bug

I have checked out [jsonforms-vue-seed](https://github.com/eclipsesource/jsonforms-vue-seed) and it works with `npm run serve` and `npm run build`, but my VSCode reports the TypeScript error:

```
(JSX attribute) renderers: JsonFormsRendererRegistryEntry[]

The type 'readonly any[]' is 'readonly' and cannot be assigned to the mutable type 'JsonFormsRendererRegistryEntry[]'.ts(4104)
```

The error is occurring on `App.vue:7`.

```vue
    <json-forms
      :data="data"
      :renderers="renderers"
```

### Expected behavior

No errors reported

### Steps to reproduce the issue

1. Clone https://github.com/eclipsesource/jsonforms-vue-seed.git
1. Run `npm install`
1. Open in VSCode
1. See error

### Screenshots

![image](https://user-images.githubusercontent.com/57606749/147177828-ed7c1473-8a6c-4191-811f-d41404d82961.png)

### In which browser are you experiencing the issue?

Google Chrome 96.0.4664.110

### Framework

Vue 3

### RendererSet

Vanilla

### Additional context

- Node v16.13.1
- VSCode 1.63.2

**Comment by sdirix** [comment]
Thanks for the report and the contribution!

**Comment by sdirix** [comment]
Hi @rokiyama I tried to reproduce the issue with the VS Code Extension `Vetur` but was unable to. Can you give us the steps to reproduce the error?

**Comment by haoyun** [comment]
I had the same, with neovim+coc-volar+eslint. I am not quite sure which linter/type checker gives this information. But I would agree that the above PR, using `MaybeReadonly<T>`, would solve the issue.

**Comment by rokiyama** [comment]
@sdirix I am using [volar](https://github.com/johnsoncodehk/volar) and reproduce the error. When I disable that extension the error does not occur.

**Comment by sdirix** [comment]
Thanks for the hint, we'll check and merge the PR for the next release when we can reproduce the issue.
