### ISSUE TITLE
Add a React MUI "outlined" renderers set

### ISSUE THREAD

**Issue by ogizanagi** [eclipsesource/jsonforms#1873]
### Is your feature request related to a problem? Please describe.

The Material reco and MUI default for inputs is now [the "outlined" variant](https://mui.com/guides/migration-v4/#formcontrol):

> Change the default variant from standard to outlined. Standard has been removed from the Material Design guidelines.

but `jsonforms/material-renderers` implements the "standard" one and does not provide a way to change it.

Moreover, changing the hardcoded `variant="standard"` to `variant="outlined"` in the current code isn't enough and needs more tweaks in order to fully match the "outlined" expected rendering:

### Current (`variant="standard"`)

![Capture d’écran 2022-01-17 à 10 34 36](https://user-images.githubusercontent.com/2211145/149747797-ec595299-b39a-4755-9168-e7185c1a8dd7.png)

### Replaced (changed to `variant="outlined"` in current code)

![Capture d’écran 2022-01-17 à 11 09 52](https://user-images.githubusercontent.com/2211145/149750084-73dd8151-20a7-4477-9220-4740b4242c0f.png)

### Expected outlined rendering

![Capture d’écran 2022-01-17 à 10 34 45](https://user-images.githubusercontent.com/2211145/149747803-a62f3920-5dd3-459e-a7b4-a1ee745d688c.png)

### Describe the solution you'd like

I think a dedicated `jsonforms/material-renderers-outlined` renderers set might make sense, but we could consider another option to configure the existing renderers.

For now, the main difference I've spotted by implementing my own renderers, is the `MaterialInputControl` in which I added a flag to render or not the `InputLabel`, since in some components like `MaterialEnumControl`, I updated the original controls so they render their labels themselves and using [`TextField`](https://mui.com/components/text-fields/#select) instead of `Select`, in order to get expected rendering. 

### Describe alternatives you've considered

I stumbled upon https://github.com/eclipsesource/jsonforms/issues/1797, which suggests a way to configure this in the existing renderer set, so this feature request might be redundant. But I'm wondering is using a dedicated renderer sets would be a better option.

It might also be suggested as the default one, following Material guidelines and MUI defaults.

### Framework

React

### RendererSet

Material

**Comment by sdirix** [comment]
Hi @ogizanagi! Thanks for the suggestion!

As you mentioned, #1797 would fix this issue. Using a configuration option for the existing Material renderer set is definitely the preferred solution from my point of view. Providing a whole additional renderer set in which most of the code is the same as the existing one is too much of an overhead for this rather small feature.

At least it's too much for the core repository to maintain. You can of course publish your own outlined renderer set if you'd like ;)

**Comment by sdirix** [comment]
I'll close this issue as it's handled via #1797. Please comment if you want to see it reopened ;)
