### ISSUE TITLE
Add more renderers for Vue

### ISSUE THREAD

**Issue by Minecraftschurli** [eclipsesource/jsonforms#1878]
### Is your feature request related to a problem? Please describe.

I'm currently making a dynamic config GUI for [reposilite](https://github.com/dzikoysk/reposilite) for which I'd need features like the oneOf or object renderers. 

### Describe the solution you'd like

Implementation of more renderers for Vue like
- oneOf
- object (Vertical grid)

and more

### Describe alternatives you've considered

Since the project already uses vue switching to another framework is not an option.

### Framework

Vue 3

### RendererSet

Vanilla

**Comment by sdirix** [comment]
Hi @Minecraftschurli,

The Vue Vanilla renderers serve more of an example on how a basic Vue renderer set looks like. As long as they are not a priority of a paying customer we will not add more renderers on our own. If you like to contribute `oneOf` or `object` renderers then we'll gladly take a look.

Note that we have a very advanced [`@jsonforms/vue2-vuetify` renderer set](https://github.com/eclipsesource/jsonforms-vuetify-renderers) if that would help you. It includes also object and combinator renderers. See a [demo here](https://jsonforms-vuetify-renderers.netlify.app/).
