### ISSUE TITLE
multipleOf validation errors width decimals.

### ISSUE THREAD

**Issue by Ketec** [eclipsesource/jsonforms#1880]
### Describe the bug

multipleOf does not reliably work with decimal numbers.
When set to for example 0.1, you get an error 
`must be multiple of 0.1` when the value is 0.3.

Since this stems from the js floating-point issues - perhaps an alternative way should be used for multipleOf validations?

### Expected behavior

Valid values do not show misleading errors.

### Screenshots

multipleOf set to 0.1
Value set to 0.3

### In which browser are you experiencing the issue?

All

### Framework

Angular

### Additional context

AJV has multipleOfPrecision options to handle decimals - potentially should be provided in JsonForms core.

**Comment by sdirix** [comment]
Hi @Ketec,

you can hand over a customized AJV instance to JSON Forms whenever you need to configure it differently from the JSON Forms default. For this you can simply call the `createAjv(options)` method exported by JSON Forms Core. This way you could for example hand over the required `multipleOfPrecision` flag.

Is this sufficient for your use cases?

**Comment by sdirix** [comment]
I'll close this for now. Please reopen if you still have issues.
