### ISSUE TITLE
Getting defaults from schema not working (React)

### ISSUE THREAD

**Issue by lovervoorde** [eclipsesource/jsonforms#1885]
### Describe the bug

I am trying to follow the advice in the FAQ to get the defaults in the schema to be pre-filled into the form, but I can't get it working
https://jsonforms.io/faq#how-can-i-use-default-values-within-json-forms

### Expected behavior

I use a schema like this, and the text field is pre-filled with 'blah'

```
const schema = {
  type: "object",
  properties: {
    name: {
      type: "string",
      default: "blah"
    }
  }
}

const handleDefaultsAjv = createAjv({ useDefaults: true })

return (
  <JsonForms
      schema={schema}
      renderers={materialRenderers}
      cells={materialCells}
      ajv={handleDefaultsAjv}
  />
)
```

### Steps to reproduce the issue

https://codesandbox.io/s/peaceful-sky-u3f93

### In which browser are you experiencing the issue?

Chrome

### Framework

Core, React

### RendererSet

Material

**Comment by sdirix** [comment]
Hi @lovervoorde!

Ajv's default handling is very simplistic. It will only set a default value if the current value of that property is `undefined`.

In the code listing of the issue, you do not hand over a `data` property to JSON Forms, therefore `data` is undefined. Ajv bails on `undefined` and will not validate and therefore not set a default property.

Would this be in a nested schema, you could fix that by additionally setting a default for the object, e.g. `default: {}`. Then it would set this as the default for the object, validate deeper and then also set the default for the `name` property. However as mentioned above, this does not work for the root object.

The code of your linked example looks different than the code you posted in the issue. It looks like this

```js
const initialData = {
  name: ""
};

function App() {
  const [data, setData] = useState(initialData);

  const handleDefaultsAjv = createAjv({ useDefaults: true });

  return (
    <JsonForms
      schema={schema}
      data={data}
      renderers={materialRenderers}
      cells={materialCells}
      ajv={handleDefaultsAjv}
    />
  );
}
```

Here the default value does not work as `name` already has a value: the empty string (`""`). If you change this to

```js
const initialData = {};
```

then Ajv will set `blah` as indicated in the schema.

---

Note that you should not create a new AJV instance with every render call. JSON Forms will recognize that it received a new AJV instance and will revalidate the whole form with every render pass. You should either memoize the AJV instance or create it outside of the React component.

**Comment by sdirix** [comment]
When you have questions, please use the [discussion board](https://jsonforms.discourse.group/) instead of the issue tracker. Thanks!

**Comment by lovervoorde** [comment]
Thank you very much for the quick response, setting initialData to just {} did indeed make the default appear.
