### ISSUE TITLE
Angular Material:  Localization Options are overridden after jsonforms are displayed

### ISSUE THREAD

**Issue by demoversionOo** [eclipsesource/jsonforms#1889]
### Describe the bug

Hi, 

i added jsonforms to an existing Angular Material Project (v13) with preexisting  localization in app.module.ts:
```
    { provide: MAT_DATE_LOCALE, useValue: 'de-DE' },
    { provide: MAT_DATE_FORMATS, useValue: CUSTOM_MAT_DATE_FORMATS },
    { provide: MatDatepickerIntl, useClass: DatepickerDe },
```

After opening the component with the jsonforms component the predefined localization is overridden with english loclaization in the whole application. (e.G. the DatePicker displays the week starting on Sunday instead of Monday, etc.)

Thanks in advance for your support!

### Expected behavior

The Material Components inside jsonforms should use the global configuration defined in app.module.

### Steps to reproduce the issue

0. Define localization for Material to de-DE 
1. Open regular Material Datepicker
2. Result is Screenshot 1 (datepicker before jsonforms)
3. Opne Jsonforms dialog component
4. Result is: every material component is now english

### Screenshots

![datepicker before jsonforms](https://user-images.githubusercontent.com/5716289/153570997-0e7c2963-22ff-49b4-9ad0-f9525d65f390.png)
![datepicker after jsonforms](https://user-images.githubusercontent.com/5716289/153571027-dce78811-44da-45bc-a245-3e92ca3333bb.png)

### In which browser are you experiencing the issue?

Google Chrome 98.0.4758.82; Firefox 97.0 x64

### Framework

Angular

### RendererSet

Material

**Comment by sdirix** [comment]
JSON Forms also has a locale setting, so that each form could potentially be localized differently. It seems like we're also setting the "global" locale here. As a workaround you can hand over the locale you are using to JSON Forms, so that it's not changed overall. Depending on your version of JSON Forms you can hand over the `locale` directly as a prop or as part of an `i18n` object.

We'll take a look.
