### ISSUE TITLE
Multi controls per type, 2d arrays and dynamic schemas

### ISSUE THREAD

**Issue by sf17** [eclipsesource/jsonforms#1891]
### Is your feature request related to a problem? Please describe.

Hi, great framework!
Have a few questions:
1. It appears right now there's one control/widget per type, would it be possible to select from multiple options ?
For example - if I have a date I could show the actual date in the default date control or select a diff control called **yearsDifferece** which will show me the difference in years for that field (e.g. person age, or years worked, etc..)
2. How can I handle an array of arrays, both in the schema and in the UI schema ? is there an example ? how to specify  the "scope" in the UI view fo the 2d array elements.
3. I have a use case where I have a base schema and a number of UI schemas using it. I want to be able to layer on top of the schema a number of schema extensions, let's say for each country I want to add a few country specific fields. Then, I'd like to go to the UI schemas and use these new fields in the proper country context. I can generate both schema and UI schema from my existing model and UI model on the fly, but I was wondering if there's any support to do this directly in jsonForms. 

Thanks,
/sebi

### Describe the solution you'd like

1. Ability to select from a list of multiple controls available per type.
2. See an example of handling arrays of arrays, and how the "scope" would have to be defined in the UI view.

### Describe alternatives you've considered

already have a similar framework and exploring to migrate to jsonforms

### Framework

Core, Other (please specify in the Additional context field)

### RendererSet

Material

**Comment by sdirix** [comment]
Hi @sf17, please only open questions in our [community board](https://jsonforms.discourse.group/).

> It appears right now there's one control/widget per type, would it be possible to select from multiple options ?
For example - if I have a date I could show the actual date in the default date control or select a diff control called yearsDifferece which will show me the difference in years for that field (e.g. person age, or years worked, etc..)

There is no built-in support in JSON Forms. However if you'd like to have something like this you can implement a generic "select renderer" custom renderer with a high priority which checks the renderer registry for all renderers which would apply and offers a dropdown list to choose one of them (it should probably exclude itself from the list).

> How can I handle an array of arrays, both in the schema and in the UI schema ? is there an example ? how to specify the "scope" in the UI view fo the 2d array elements.

In JSON Schema you can just model nested arrays or objects, that's part of the spec. In JSON Forms you can either rely on the default UI Schema generation for detail UI Schemas, hand over the [`detail` UI Schema via the UI Schema options](https://jsonforms.io/docs/uischema/controls#the-detail-option), use the [UI Schema registry](https://jsonforms.io/docs/integrations/react#uischemas), or use custom renderers which encode your requirements. By default the detail UI Schemas will be generated, so you don't need to do anything in the UI Schema for a first version.

> I have a use case where I have a base schema and a number of UI schemas using it. I want to be able to layer on top of the schema a number of schema extensions, let's say for each country I want to add a few country specific fields. Then, I'd like to go to the UI schemas and use these new fields in the proper country context. I can generate both schema and UI schema from my existing model and UI model on the fly, but I was wondering if there's any support to do this directly in jsonForms.

Was already asked and answered [here](https://jsonforms.discourse.group/t/dynamic-schema-and-ui-schema-fields/619).
