### ISSUE TITLE
JsonForms mutates passed in schema

### ISSUE THREAD

**Issue by dieseldjango** [eclipsesource/jsonforms#1892]
### Describe the bug

The schema I pass into JsonForms is an immutable object. I get this error when rendering:

```
Uncaught (in promise) TypeError: Cannot assign to read only property 'additionalProperties' of object '#<Object>'
```

Also, the rejected promise isn't handled, so the UI just hangs, showing `Loading...`. Promise rejections should never be unhandled.

### Expected behavior

It appears the code does some dereferencing and other manipulation of the schema. The component should not mutate the object passed into it, but should instead clone it.

### Steps to reproduce the issue

1. Pass in an immutable object for the JsonSchema component's schema property
2. Render the form

### In which browser are you experiencing the issue?

Chrome Version 98.0.4758.102 (Official Build) (arm64)

### Framework

React

### RendererSet

Material

**Comment by sdirix** [comment]
Hi @dieseldjango,

the library we used in the past for reference resolving had a lot of downsides, one of them to mutate the JSON Schema in place. For the 3.0 release we removed this library, for more information see here. 3.0 is currently in beta and shortly before release. You can consume it via the `next` stream, i.e. `npm i --save @jsonforms/core@next @jsonforms/react@next @jsonforms/material-renderers@next`.

Please see the [migration guide](https://github.com/eclipsesource/jsonforms/blob/master/MIGRATION.md) for more detailed information and what to look at for updating. Note that the `next` stream is also already on Material v5, so you will need to update your app too.
