### ISSUE TITLE
Svelte support

### ISSUE THREAD

**Issue by magick93** [eclipsesource/jsonforms#1894]
### Is your feature request related to a problem? Please describe.

No problem, would just be great to support Svelte.

### Describe the solution you'd like

[Svelte](https://svelte.dev/) is a popular framework, comparable to Vue and React but arguably easier to learn.

### Describe alternatives you've considered

na

### Framework

Other (please specify in the Additional context field)

### RendererSet

Other (please specify in the Additional context field)

**Comment by sdirix** [comment]
Hi @magick93, thanks for the suggestion.

At the moment we have no plans to create and maintain Svelte bindings and/or a Svelte-based renderer set ourselves. If you are interested in such an offering you might want to consider our [professional support](https://jsonforms.io/support) by which we would help you to create Svelte bindings and renderer set, ranging from answering questions to taking over the full implementation.
