### ISSUE TITLE
Error with "npm run dev"

### ISSUE THREAD

**Issue by sarink** [eclipsesource/jsonforms#1895]
```
git clone git@github.com:eclipsesource/jsonforms.git
cd jsonforms
nvm use v14
npm ci
npm run init
cd packages/material
npm run dev
```

[log.txt](https://github.com/eclipsesource/jsonforms/files/8164630/log.txt)

**Comment by sarink** [comment]
It looks like this is related to some way that the monorepo is configured and that dependencies are not being linked properly? I see a lot of `Unable to find module @jsonforms/core`.

Yet,
```
kabirsarin@MBPM1P142021-0004:material (master)$ npm ls @jsonforms/core
@jsonforms/material-renderers@3.0.0-beta.1 /Users/kabirsarin/sarink/Projects/jsonforms/packages/material
├── @jsonforms/core@3.0.0-beta.1 -> ./../core
└─┬ @jsonforms/react@3.0.0-beta.1 -> ./../react
  └── @jsonforms/core@3.0.0-beta.1 -> ./../core
```

Does anyone have any ideas how to get this running?

**Comment by sdirix** [comment]
Hi @sarink, you're missing a `npm run build` after `npm run init`.

Please use our [discussion board](https://jsonforms.discourse.group/) for questions instead of opening new issues. Thanks!

**Comment by sarink** [comment]
Hey @sdirix the `npm run build` also fails with some TS errors in the `angular` package.

I was however able to get `material` working by instructing lerna to only build its dependencies: `./node_modules/.bin/lerna run --scope "@jsonforms/material-renderers" --include-dependencies build`

**Comment by sdirix** [comment]
> npm run dev still fails with Cannot find module @jsonforms/examples - I think this is because examples is not listed as a dependency in the material package's package.json, so lerna did not build it (this should probably be updated)

Good point. Never ran into the problem as I'll always build everything via `npm run build`.

> the npm run build also fails with some TS errors in the angular package.

What exactly is going wrong? On which system are you developing? If you're able to you can also always use our [dev-container](https://github.com/eclipsesource/jsonforms/tree/d65d7eb8a5050c6de7a4e086e01237bd2488f64c/.devcontainer) for a reproducible environment.

**Comment by sarink** [comment]
It looks like the `angular` package has some TS errors on the current `master` branch, and when those occur the entire `npm run build` process aborts (leaving a bunch of packages unbuilt and thus `npm run dev` fails).

I have switched to the `v2.5.2` branch where everything is stable.

**Comment by sdirix** [comment]
The 2.5.2 tag is very old. I don't think it makes sense to work from that. The CI build works fine on Linux, Mac and Windows with Node 14. Can you post the actual error which is occurring for you?

**Comment by sdirix** [comment]
2.5.2 was released 9 months ago. Since then we did some major improvements within 6 prereleases. Over 30% of the community is already consuming 3.0. Now whether 9 months is "old" or not is in the eye of the beholder ;)
