### ISSUE TITLE
Json validation with "multipleOf": 0.1 fails when it shouldn't

### ISSUE THREAD

**Issue by dimpon** [eclipsesource/jsonforms#1897]
### Describe the bug

json validation ` "multipleOf": 0.1`  doesn't work with some values.

### Expected behavior

with constraint `"multipleOf": 0.1`  value `100.1` must be considered as valid.

### Steps to reproduce the issue

1. run the project https://github.com/dimpon/jsonforms-angular-seed
2. enter 100.1 - validation is failed
3. enter 45.5, 41.1 - all is fine

### Screenshots

![image](https://user-images.githubusercontent.com/37782079/157288591-1d234e4a-9b33-4eaa-ae4d-2711ee94208c.png)

### In which browser are you experiencing the issue?

Google Chrome Version 98.0.4758.102 (Official Build) (64-bit)

### Framework

Angular

### RendererSet

Material

**Comment by eneufeld** [comment]
Thank you for the report and the great reproducer.
I tracked the error down to ajv, there is even a discussion about it:
https://github.com/ajv-validator/ajv/issues/84 and https://github.com/ajv-validator/ajv/issues/652

So the recommendation is to either use an additional option:
https://github.com/ajv-validator/ajv/blob/master/docs/options.md#multipleofprecision
or a regex pattern: https://github.com/ajv-validator/ajv/issues/84#issuecomment-364795655

Does this help?

**Comment by sdirix** [comment]
This was also already reported before: https://github.com/eclipsesource/jsonforms/issues/1880.

I'll add a task for the website to add this to the FAQ.

**Comment by sdirix** [comment]
I'll close this for now as no change to JSON Forms is needed. Feel free to reopen if you disagree.
