### ISSUE TITLE
Create custom component for grid

### ISSUE THREAD

**Issue by azizkhani** [eclipsesource/jsonforms#1899]
### Is your feature request related to a problem? Please describe.

How can id create grid component in json-form?

### Describe the solution you'd like

I want create grid component that get list of column and url of rest api or data for render grid 

### Describe alternatives you've considered

i dont know

**Comment by sdirix** [comment]
Please use the [discussion board](https://jsonforms.discourse.group/) for questions.

In general you can implement any kind of custom renderer in JSON Forms in which you can handle your data in any way you want. Please open a question on the board with more details, e.g. which renderer set you're using and what you're actually struggling with.
