### ISSUE TITLE
Remove startCase from label in MaterialEnumArrayRenderer.tsx

### ISSUE THREAD

**Issue by JoshuaFortriede** [eclipsesource/jsonforms#1903]
### Describe the bug

When an enum array is rendered as checkboxes, the checkbox label is changed from the actual value. This is done by using the lodash.startCase function.

### Expected behavior

It is expected that the labels of the checkboxes are exactly the same as the string specified in the enum. 

### Steps to reproduce the issue

Step 1:
Use form of: 
"isotype":{
                    "type":"array",
                    "uniqueItems":true,
                    "items":{

                        "type":"string",
                        "enum":[
                        "IgG",
                        "IgM",
                        "IgG1",
                        "IgG2a",
                        "IgG2b",
                        "IgG3",
                        "IgG1/IgG2a",
                        "IgA",
                        "IgE"
                    ]
                    },
                    "example":"IgG",
                    "title":"Isotype",
                    "description":"The isotype of the antibody"
                }
Step 2: 
Notice checkbox labels are not the same as the enum strings.

### Screenshots

**Current Behavior**
![image](https://user-images.githubusercontent.com/51160626/160035558-d2369745-c55e-4ea2-9857-7b9089d11df2.png)

**Expected Behavior**
![image](https://user-images.githubusercontent.com/51160626/160035521-af478f96-760c-4444-b017-3f293f749906.png)

### In which browser are you experiencing the issue?

Version 99.0.4844.82

### Additional context

The code is line 71 of packages/material/src/complex/MaterialEnumArrayRenderer.tsx.  The request is to remove the startCase function.

**Comment by sdirix** [comment]
Hi @JoshuaFortriede, thanks for the report. The suggestion definitely makes sense to me. Do you want to contribute the change?

**Comment by JoshuaFortriede** [comment]
Thank you, I have submitted a pull request.
