### ISSUE TITLE
Hover effect of categories in the stepper is too large

### ISSUE THREAD

**Issue by LukasBoll** [eclipsesource/jsonforms#1910]
### Describe the bug

Hovering over one of the categories in the Stepper of the “Categorization (Stepper)”-example leads to a very big hover-effect, that partially overlaps with other form elements.

### Expected behavior

The hover-effect should be smaller.

### Steps to reproduce the issue

1. Select the “Categorization (Stepper)” example
2. Hover over a category in the Stepper component

### Screenshots

![Stepper](https://user-images.githubusercontent.com/23579215/161389113-17f318e4-1cdd-454a-b820-3aec89a0507f.PNG)

### In which browser are you experiencing the issue?

Google Chrome 99.0.4844.84

### Framework

React

### RendererSet

Material

**Comment by sdirix** [comment]
This is handled on MUI side, see [here](https://github.com/mui/material-ui/issues/32751).

**Comment by LukasBoll** [comment]
The issue still occurs, but it actually occurs on `onMouseDown` and not `onHover`. I don't know if the onHover effect was removed or if I accidentally used the wrong term.
![image](https://github.com/eclipsesource/jsonforms/assets/23579215/d6b8e799-829c-4df6-ab34-c994fe0a6d3e)
The issue in MUI wasn't resolved.

**Comment by sdirix** [comment]
Thanks for checking. I'll close this for now.
