### ISSUE TITLE
hasOption required

### ISSUE THREAD

**Issue by zeroamps** [eclipsesource/jsonforms#1920]
### Is your feature request related to a problem? Please describe.

Hi, not sure if something like hasOption exists in your library.

### Describe the solution you'd like
```
export const hasOption = (optionName: string): Tester => (
    uischema: UISchemaElement): boolean => {
    if (isEmpty(uischema))
        return false;
    const options = uischema.options;
    return !isEmpty(options) && options![optionName];
};
```
### Describe alternatives you've considered

I couldn't find any alternative.

### Framework

Angular

### RendererSet

Material

**Comment by sdirix** [comment]
Hi @zeroamps, please use the [dicussion board](https://jsonforms.discourse.group/) for questions of these type.

We're offering the helper [`optionIs`](https://github.com/eclipsesource/jsonforms/blob/23e1a557d176e27d35febe74c75279b6b29b0a09/packages/core/src/testers/testers.ts#L165-L174) which basically does the same as the provided `hasOption`
