### ISSUE TITLE
Move away from Lerna

### ISSUE THREAD

**Issue by dzikoysk** [eclipsesource/jsonforms#1928]
### Is your feature request related to a problem? Please describe.

Currently, the JsonForms repository uses Lerna tool to manage monorepo structure:

* https://github.com/lerna/lerna

2 weeks ago it has been officially confirmed that Lerna is no longer actively maintained ([README](https://github.com/lerna/lerna/commit/8b99493ac90484e05f7ebee533c0763534d60218)):

> Important note: this project https://github.com/lerna/lerna/issues/2703. Consider adopting an alternative toolset for monorepo management.

Might be a good idea to consider alternative approach to manger repository, especially that it's still 3.x beta phase. It could be also a good impulse to review dependencies and update all packages to latest versions, as it's quite sad JsonForms still requires Node 14.

### Describe the solution you'd like

https://github.com/vercel/turborepo looks promising and some people decided to use it as an alternative seeing referenced issues:

* https://github.com/lerna/lerna/issues/2703

But I'm not expert here, so you should probably find proper solution on your own. Probably just plain npm/yarn would be great if possible.

### Describe alternatives you've considered

N/A

### Framework

Core

### RendererSet

Other (please specify in the Additional context field)

**Comment by sdirix** [comment]
Thanks for letting us know. At the moment I don't see a need to migrate away immediately, although turborepo definitely looks interesting.

We're certainly open for refactoring the repo structure and build system to something more stable on all platforms. If someone likes this kind of tasks and wants to contribute, feel free to let us know so we can discuss technologies and desired patterns.

**Comment by sdirix** [comment]
As lerna is "re-maintained" I'll close this issue. Feel free to reopen if you disagree.

**Comment by dzikoysk** [comment]
As far as I know Turborepo is overall considered as a better solution these days, but it's at least not that urgent, so I think it's fine to close it for now.
