### ISSUE TITLE
I am using vue-vanilla renderes and try to use a custom css-only framework https://mildrenben.github.io/surface/ noticed that fields don't have HTML5 type attribute

### ISSUE THREAD

**Issue by jaguirre-pricesmart** [eclipsesource/jsonforms#1934]
### Is your feature request related to a problem? Please describe.

https://mildrenben.github.io/surface/ using HTML5 type to apply their css the renderers don't have that attribute 

### Describe the solution you'd like

add the correct type to the control, for example:
<input
      :id="control.id + '-input'"
      **:type="styles.control.type?"**
      :class="styles.control.input"
      :value="control.data"
      :disabled="!control.enabled"
      :autofocus="appliedOptions.focus"
      :placeholder="appliedOptions.placeholder"
      @change="onChange"
      @focus="isFocused = true"
      @blur="isFocused = false"
    />

### Describe alternatives you've considered

none

### Framework

Vue 3

### RendererSet

Vanilla

**Comment by sdirix** [comment]
Hi @jaguirre-pricesmart,

I'm not sure that I can follow. We are using the `type` attribute where necessary, see for example [here](https://github.com/eclipsesource/jsonforms/blob/8dc8751717e8680568fe4e0da713786b0202b2fe/packages/vue/vue-vanilla/src/controls/DateTimeControlRenderer.vue#L9) and [here](https://github.com/eclipsesource/jsonforms/blob/8dc8751717e8680568fe4e0da713786b0202b2fe/packages/vue/vue-vanilla/src/controls/IntegerControlRenderer.vue#L9). Is there something I'm missing?

**Comment by sdirix** [comment]
Closed as there was no more information. Feel free to reopen when needed.
