### ISSUE TITLE
when set <"type": "array">, No applicatable cell found

### ISSUE THREAD

**Issue by davidxwwang** [eclipsesource/jsonforms#1947]
### Describe the bug

<img width="992" alt="屏幕快照 2022-05-30 上午10 18 28" src="https://user-images.githubusercontent.com/13027592/170906357-fed3e349-7e4f-4f9f-8cbf-fa9990e3ac33.png">

### Expected behavior

the "REFERENCE-VALUES" props in the schame show in the web editor.

### Steps to reproduce the issue

1. set data:
`{
	"SHORT-NAME": "FiMInhibitionConfiguration_0",
	"DEFINITION-REF": {
		"type_arxml": "EcucParamConfContainerDef",
		"$ref_arxml": "ar:/#/AUTOSAR_FiM/EcucModuleDefs/FiM/FiMConfigSet/FiMInhibitionConfiguration?type_arxml=EcucParamConfContainerDef"
	},
	"PARAMETER-VALUES": {
		"FiMInhInhibitionMask": {
			"type_arxml": "EcucTextualParamValue",
			"DEFINITION-REF": {
				"type_arxml": "EcucEnumerationParamDef",
				"$ref_arxml": "ar:/#/AUTOSAR_FiM/EcucModuleDefs/FiM/FiMConfigSet/FiMInhibitionConfiguration/FiMInhInhibitionMask?type_arxml=EcucEnumerationParamDef"
			},
			"VALUE": "FIM_TESTED_AND_FAILED",
			"name": "FiMInhInhibitionMask"
		}
	},
	"REFERENCE-VALUES": [{
		"type_arxml": "EcucReferenceValue",
		"DEFINITION-REF": {
			"type_arxml": "EcucReferenceDef",
			"$ref_arxml": "ar:/#/AUTOSAR_FiM/EcucModuleDefs/FiM/FiMConfigSet/FiMInhibitionConfiguration/FiMInhFunctionIdRef?type_arxml=EcucReferenceDef"
		},
		"VALUE-REF": {
			"type_arxml": "EcucIntegerParamDef",
			"$ref_arxml": "ar:/#/AUTOSAR_FiM/EcucModuleDefs/FiM/FiMGeneral/FiMMaxSummaryLinks?type_arxml=EcucIntegerParamDef"
		},
		"name": "FiMInhFunctionIdRef"
	}]
}`
2. set Schame:
`{
	"type": "object",
	"properties": {
		"SHORT-NAME": {
			"type": "string"
		},
		"PARAMETER-VALUES": {
			"type": "object",
			"properties": {
				"FiMInhInhibitionMask": {
					"type": "object",
					"properties": {
						"name": {
							"type": "string",
							"description": "The configuration parameter is used to specify the inhibition mask for an event - FID relation."
						},
						"VALUE": {
							"type": "string",
							"enum": ["FIM_LAST_FAILED", "FIM_NOT_TESTED", "FIM_TESTED", "FIM_TESTED_AND_FAILED"]
						}
					}
				}
			}
		},
		"REFERENCE-VALUES": {
			"type": "array",
			"items": {
				"type": "object",
				"properties": {
					"name": {
						"type": "string"
					},
					"VALUE-REF": {
						"type": "object",
						"properties": {
							"$ref_arxml": {
								"type": "string"
							}
						}
					}
				}
			}
		}
	}
}`
3. set Uischame:
`{
	"type": "VerticalLayout",
	"elements": [{
		"type": "Control",
		"label": "",
		"scope": "#/properties/SHORT-NAME"
	}, {
		"type": "Group",
		"label": "PARAMETER-VALUES",
		"elements": [{
			"type": "HorizontalLayout",
			"label": "",
			"elements": [{
				"type": "Control",
				"label": "",
				"scope": "#/properties/PARAMETER-VALUES/properties/FiMInhInhibitionMask/properties/name",
				"options": {
					"readonly": true
				}
			}, {
				"type": "Control",
				"label": "",
				"scope": "#/properties/PARAMETER-VALUES/properties/FiMInhInhibitionMask/properties/VALUE"
			}]
		}]
	}, {
		"type": "Control",
		"scope": "#/properties/REFERENCE-VALUES"
	}]
}`
4. error: REFERENCE-VALUES(type is "array") show "no applicable cell found"
<img width="992" alt="屏幕快照 2022-05-30 上午10 18 28" src="https://user-images.githubusercontent.com/13027592/170906272-2c7211e5-b619-4b22-b5df-ab60bafe8374.png">

### In which browser are you experiencing the issue?

google chrome 101.0.4951.64

### Framework

React

### RendererSet

Material

**Comment by eneufeld** [comment]
Hi @davidxwwang,

good that the COffee Editor is running for you again.
About your question.
Did you adapt anything in https://github.com/eclipse-emfcloud/theia-tree-editor/blob/master/theia-tree-editor/src/browser/detail-form-widget.tsx ?
Please check that your `JSONForms` element also sets the `cells` property see: https://github.com/eclipse-emfcloud/theia-tree-editor/blob/master/theia-tree-editor/src/browser/detail-form-widget.tsx#L118

**Comment by davidxwwang** [comment]
> Hi @davidxwwang,
> 
> good that the COffee Editor is running for you again. About your question. Did you adapt anything in https://github.com/eclipse-emfcloud/theia-tree-editor/blob/master/theia-tree-editor/src/browser/detail-form-widget.tsx ? Please check that your `JSONForms` element also sets the `cells` property see: https://github.com/eclipse-emfcloud/theia-tree-editor/blob/master/theia-tree-editor/src/browser/detail-form-widget.tsx#L118

thanks

**Comment by davidxwwang** [comment]
> Hi @davidxwwang,
> 
> The React Vanilla table renderer for arrays is not able to handle nested objects, this is why you get the `No applicable cell found` for `VALUE REF`.
> 
> To solve this you can either:
> 
> * Adapt your schema to not contain nested objects within arrays
> * Add a custom cell renderer which is able to handle nested array objects
> * Add a custom control renderer for arrays which does not render them in tables when they are nested, similar to the React Material Array layout renderer
> * Switch to the React Material renderer set which currently supports many more use cases than the React Vanilla renderer set
> 
> When you have questions about JSON Forms, please post in the [JSON Forms discussion board](https://jsonforms.discourse.group/) instead of the issue tracker. For more specialized questions about JSON Forms in Theia you can also use the [EMF.cloud discussion board](https://github.com/eclipse-emfcloud/emfcloud/discussions) instead.

thanks
