### ISSUE TITLE
Unable to add list element

### ISSUE THREAD

**Issue by agonzalezgaliana** [eclipsesource/jsonforms#1948]
### Describe the bug

The problem comes from [here]( https://github.com/eclipse-emfcloud/emfcloud/discussions/157)

Using `@eclipse-emfcloud/theia-tree-editor` and indirectly:

```
    "@jsonforms/core": "3.0.0-alpha.2",
    "@jsonforms/react": "3.0.0-alpha.2",
    "@jsonforms/vanilla-renderers": "3.0.0-alpha.2"
```

Basically, when providing

- JSON schema
- JSON data

to JSON forms, it shows a UI with a [+] button (which seems that should allow to add a new element to my list).

![](https://user-images.githubusercontent.com/39406939/170648994-f0718d36-1333-4f22-bbe3-0bcfc8e3d5ae.PNG)

Actually, by clicking that button nothing happens:

- No errors
- No exceptions in the console
- Corresponding method in the Tree Editor is not called

However, when we only provide

- JSON data

to JSON forms, it shows a completely different UI. 

![](https://user-images.githubusercontent.com/39406939/170649234-e511a98c-e897-464d-b769-b147e0489349.PNG)

In this UI, the add button actually triggers the corresponding listener in the Tree Editor.

### Expected behavior

That by clicking the [+] button the listener methods are called and we can react on user action.

### Steps to reproduce the issue

/

### In which browser are you experiencing the issue?

Firefox Version 99.0.1

### Framework

Core, React

### RendererSet

Vanilla

### Additional context

The relevant schema snippet is the following:
```
               "import": {
			"$id": "#import",
			"title": "Import",
			"type": "object",
			"properties": {
				"eClass": {
					"const": "http://my_schema/1.0.0#//Import"
				},
				"document": {
					"type": "string"
				},
				"package": {
					"type": "string"
				},
				"prefix": {
					"type": "string"
				}
			},
			"additionalProperties": false,
			"required": ["document", "package", "prefix"]
		},
		"imports": {
			"$id": "#imports",
			"title": "Imports",
			"type": "object",
			"properties": {
				"eClass": {
					"const": "http://my_schema/1.0.0#//Imports"
				},
				"import": {
					"type": "array",
					"items": {
						"$ref": "#/definitions/import"
					}
				}
			},
			"additionalProperties": false,
			"required": ["import"]
		}
```
The data looks like the following:
```
{
	"import": [{
		"document": "Document1",
		"package": "Package1",
		"prefix": "Prefix"
	}]
}
```

**Comment by eneufeld** [comment]
Hi @agonzalezgaliana ,
I looked into the issue. I can reproduce the different renderers being chosen.
I didn't adapt this but I fixed the add functionality in the array layout control case.

**Comment by eneufeld** [comment]
Now I also fixed the wrong renderer selection ;-) .
