### ISSUE TITLE
date-time format material renderer crashes

### ISSUE THREAD

**Issue by hellkite500** [eclipsesource/jsonforms#1953]
### Describe the bug

When trying to use the date time picker for a date-time format field with `materialRenders`, the follow error occurs:
`TypeError: Cannot read properties of undefined (reading 'indexOf')`

### Expected behavior

The date-time picker should fill the form field with the selected date-time.

### Steps to reproduce the issue

The easiest way to see this in action is on the [date time picker](https://jsonforms.io/docs/date-time-picker/#date-time-picker) demo on the documentation pages.

In the Demo, click the picker icon, see the resulting error.

### Screenshots

<img width="1680" alt="image" src="https://user-images.githubusercontent.com/5186647/172402363-29853fe3-5316-4587-bb98-2bef1bb42f45.png">

### In which browser are you experiencing the issue?

Google Chrome Version 101.0.4951.64 (Official Build) (x86_64)

### Framework

React

### RendererSet

Material

### Additional context

I initially encountered this problem prototyping a form locally, then discovered the documentation demo appears to suffer the same issue.  Here is a stack trace from my local application:
<img width="1000" alt="image" src="https://user-images.githubusercontent.com/5186647/172402900-3fecf9a6-e069-494d-8012-d9accabba4be.png">

**Comment by sdirix** [comment]
Thank you very much for the report, this definitely needs to be fixed.

**Comment by sdirix** [comment]
The date pickers in the regular examples seem to work: https://jsonforms.io/examples/basic

**Comment by lucas-koehler** [comment]
@sdirix I think we can close this, can't we? The corresponding PR was merged already.

**Comment by sdirix** [comment]
Fixed with #1960
