### ISSUE TITLE
Unable to pass own ajv instance as prop

### ISSUE THREAD

**Issue by mithun1999** [eclipsesource/jsonforms#1956]
### Describe the bug

I am using jsonforms/react package. I tried to create my own ajv instance and pass it as prop to JsonForms component. But it's throwing an error when I tried to pass it as prop.

```
  const ajv = new Ajv({
    allErrors: true,
    verbose: true,
    strict: false
  });
  addFormats(ajv);
  addErrors(ajv);
```

```
<JsonForms
      ajv={ajv}
      schema={schema}
      uischema={uiSchema}
      renderers={vanillaRenderers}
      cells={vanillaCells}
      onChange={({ data, _errors }) => console.log(data)}
/>
```

I am also attaching the link to codesandbox.
https://codesandbox.io/s/json-forms-issue-8oc43z?file=/src/App.js:1130-1345

### Expected behavior

ajv-formats and ajv-errors should be working fine without any error.

### Steps to reproduce the issue

1. Create an ajv instance
2. Pass the created ajv instance to the JsonForms component as a prop
3. Pass a schema that contains the custom error message.

### Screenshots

![image](https://user-images.githubusercontent.com/56348891/174225961-98d64a2e-c726-4a0f-b22c-f72656f7287e.png)

### In which browser are you experiencing the issue?

Chrome

### Framework

React

### RendererSet

Material

**Comment by sdirix** [comment]
Hi @mithun1999,

Thanks for the report.

Your'e using AJV v8 which is only supported in the JSON Forms v3.0.0 pre releases, i.e. I would like to recommend to switch to `3.0.0-beta.4` for all JSON Forms dependencies. Then it should work for you.

If you like to stay with JSON Forms v2.5.2 then you need to use AJV v6.
