### ISSUE TITLE
MUI Autocomplete has no endAdornment arrow

### ISSUE THREAD

**Issue by lovervoorde** [eclipsesource/jsonforms#1965]
### Is your feature request related to a problem? Please describe.

The autocomplete renderer does not have a a downwards pointing arrow to indicate that clicking it will open a dropdown.

### Describe the solution you'd like

A downward arrow at the left of the autocomplete, as is the default behaviour for the MUI autocomplete.

### Describe alternatives you've considered

Creating a custom autocomplete renderer (this seems like overkill)

### Framework

React

### RendererSet

Material

**Comment by sdirix** [comment]
ToDo:
 - Check all enum renderers whether they show this adornment, they seem to be shown by default for `Select` and `Autocomplete` in Material UI
