### ISSUE TITLE
Incorrect return type for useControl in Vue

### ISSUE THREAD

**Issue by Cynthiafan** [eclipsesource/jsonforms#1967]
### Describe the bug

![Screen Shot 2022-06-28 at 4 10 16 PM](https://user-images.githubusercontent.com/28385546/176128551-2819af7d-27a9-4e12-a4af-4cff84d03fb1.png)

Typescript shows an error when using `control.value`: `Property 'value' does not exist on type`
But the `control` is returned as a `ComputedRef` object actually.

### Expected behavior

`control` returns a ComputedRef object.

https://github.com/eclipsesource/jsonforms/blob/d2bf053315be914b1766a62eb6b7681a530a6633/packages/vue/vue/src/jsonFormsCompositions.ts#L169-L172

Perhaps the line 150, 155, and 190 should replace with `ComputedRef<R>`

https://github.com/eclipsesource/jsonforms/blob/d2bf053315be914b1766a62eb6b7681a530a6633/packages/vue/vue/src/jsonFormsCompositions.ts#L147-L155

### Steps to reproduce the issue

1. Call functions that call `useControl` inside, e.g. `useJsonFormsControl`
2. Get value by `control.value`
3. See type error

### In which browser are you experiencing the issue?

Brave 1.38.115

### Framework

Vue 2

### RendererSet

Other (please specify in the Additional context field)

**Comment by sdirix** [comment]
I'm unfamiliar with the construct of your listing. You build and return the component within the `setup` method?

In general I agree, yes we should use `ComputedRef` within the typings to better express the actual return value.
