### ISSUE TITLE
Handle control alignments with and without label and required markers in a generic way

### ISSUE THREAD

**Issue by sdirix** [eclipsesource/jsonforms#197]
With #183 means to hide labels of controls are introduced. Since labels are currently displayed above controls and are also used to mark the "required" feature there should be a mechanism which makes sure that all controls are properly aligned.

Example 1:
<table>
<tr>
<td>Label + Marker(*)</td> <td>Label</td> <td>Marker(*)</td> <td></td>
</tr>
<tr>
<td>Control</td> <td>Control</td> <td>Control</td> <td>Control</td>
</tr>
</table>
Here the user expects all controls to be aligned without the last control moving up.

Example 2:
<table>
<tr>
<td></td> <td></td>
</tr>
<tr>
<td>Control</td> <td>Control</td>
</tr>
</table>
Here the user expects all controls to be moving up to avoid displaying useless whitespace

**Comment by koegel** [comment]
I think there should not be a required marker if there is no label

**Comment by edgarmueller** [comment]
This should only apply to the Horizontal Renderer, right? Or are there any other cases where the proposed behavior should apply?
