### ISSUE TITLE
onchange not getting called when rendering using react testing library on local machine

### ISSUE THREAD

**Issue by georgesunnyt** [eclipsesource/jsonforms#1972]
### Describe the bug

This issue happens on local development but not on codesandbox. Both codesandbox and local machine have same versions for dependencies. Neither the first load nor any further changes to form triggers the onchange handler when it is being tested by the react testing library and jest. 

link to code sandbox:  https://codesandbox.io/s/wizardly-panka-u9z3ff?file=/src/App.js

The submit button should be enabled on first load since onchange handler gets called. App.test.js passes fully in codesandbox but fails on the local machine. Jest preview and screen.debug both show that submit button is disabled due to onchange not getting triggered

### Expected behavior

onChange within jsonforms should get triggered on first render and subsequent changes when it is being tested in local machine as well.

### Steps to reproduce the issue

1.copy files to local machine from codesandbox
2.run npm test
3.test will fail.

### Screenshots

<img width="1094" alt="Screenshot 2022-07-07 at 3 13 36 AM" src="https://user-images.githubusercontent.com/66377779/177648719-77ea937b-59cb-44e4-8643-da1c2ca85cfe.png">

<img width="1435" alt="Screenshot 2022-07-07 at 3 17 40 AM" src="https://user-images.githubusercontent.com/66377779/177649240-187b67c4-af26-4744-8f90-94bf8c64fb52.png">

### In which browser are you experiencing the issue?

103.0.5060.114

### Framework

React

### RendererSet

Material

**Comment by georgesunnyt** [comment]
Unable to reproduce issue inside a fresh react project indicating something was wrong in the local configuration of the previous project I was working on

**Comment by georgesunnyt** [comment]
So it turned out to be an issue where the UI was taking more time in the test environment. I fixed it by waiting for it.
`await waitFor(() => {
    screen.getByRole("button", {
        name: /submit/i
      })
    ).toHaveProperty("disabled", false);
})`
Hope this helps someone else :-)

**Comment by sdirix** [comment]
Thanks for the update! Yes we use `useEffect` for emitting so this needs to be waited for :+1:
