### ISSUE TITLE
Nuxt 3 & Vuetify 3 integration with JSON Forms

### ISSUE THREAD

**Issue by Endrit-seek** [eclipsesource/jsonforms#1989]
### Is your feature request related to a problem? Please describe.

As it stands right now there is no way (or rather simple way) to integrate JSON Forms to Nuxt 3 and use it with Vuetify 3 renderer set.

### Describe the solution you'd like

Support for Nuxt 3 frontend framework and Vuetify 3 renderer set.

### Describe alternatives you've considered

Using Nuxt 2 and Vuetify 2.

### Framework

Other (please specify in the Additional context field)

### RendererSet

Other (please specify in the Additional context field)

### Additional context

Framework: Nuxt 3
RendererSet: Vuetify 3

**Comment by sdirix** [comment]
At the moment we don't plan to switch to or support a Vuetify 3 based renderer set. Whether and when this will happen depends on our [professional support customers](https://jsonforms.io/support) and/or community contributions.

**Comment by sdirix** [comment]
I'll close this for now as the Vuetify issues are tracked in another repository. See [here](https://github.com/eclipsesource/jsonforms-vuetify-renderers/issues/44) for the corresponding issue there.
