### ISSUE TITLE
Quasar Renderer Option

### ISSUE THREAD

**Issue by Kade-Powell** [eclipsesource/jsonforms#1997]
### Is your feature request related to a problem? Please describe.

No.

### Describe the solution you'd like

I'd like to see a renderer set implementation using quasar for components instead of plain html elements.

### Describe alternatives you've considered

using react inside of Vue, using other libraries to do the same thing (though they are sparse and undocumented).

### Framework

Vue 3

### RendererSet

Other (please specify in the Additional context field)

**Comment by sdirix** [comment]
Hi @Kade-Powell, Thanks for the suggestion.

At the moment we have no plans to create and maintain another renderer set ourselves. If you are interested in such an offering you might want to consider our [professional support](https://jsonforms.io/support) by which we would help you to create a quasar based renderer set, ranging from answering questions to taking over the full implementation.
