### ISSUE TITLE
Event 'change' is triggered twice in Vue from 3.0.0-beta.3

### ISSUE THREAD

**Issue by meiweimuli** [eclipsesource/jsonforms#2003]
### Describe the bug

Component `JsonForms` trigger the change event twice when changing one form value. The second time is caused by the operation of setting `this.data` to `event.data`

<img width="348" alt="image" src="https://user-images.githubusercontent.com/53048974/185549450-9d00dd64-c81e-48b4-96ab-d9e0694ab897.png">

### Expected behavior

Only trigger the change event once.

### Steps to reproduce the issue

1. Clone project `jsonforms-vue-seed`.
2. Delete file `package-lock.json`.
3. Add code `console.log("onChange", event.data);` to method `onChange` in `App.vue`.
4. Run the project and change any input value in browser.
5. See the output twice in the browser console.

### Screenshots

![image](https://user-images.githubusercontent.com/53048974/185547941-af4d57c1-8ccb-4d2b-95ab-50834f73954d.png)

### In which browser are you experiencing the issue?

Google Chrome Version 104.0.5112.79 (Official Build) (arm64)

### Framework

Vue 3

### RendererSet

Other (please specify in the Additional context field)

### Additional context

vue-vanilla
Sorry for my poor English.

**Comment by sdirix** [comment]
Thanks for the report! We'll take a look
