### ISSUE TITLE
 Nested schema error in RadioGroup

### ISSUE THREAD

**Issue by Git-mind** [eclipsesource/jsonforms#2007]
### Describe the bug

Bug:  A component is changing the uncontrolled state of RadioGroup to be controlled.

If i remove the options radio group and make it to single select dropdown list. There is no error.

### Expected behavior

When using radio group, it should not have error.

### Steps to reproduce the issue

1. Use radio group for json 3.0.0.rc

### Screenshots

![image](https://user-images.githubusercontent.com/68322946/185729476-278c1bee-c739-4b55-8c9c-acde0ba39fe4.png)
![image](https://user-images.githubusercontent.com/68322946/185729479-aec78195-c538-4b78-8041-cb33715c87a5.png)

### In which browser are you experiencing the issue?

google chrome 104.0.5112.101

### Framework

React

### RendererSet

Material

**Comment by sdirix** [comment]
Thanks for the report! We'll have a look.
