### ISSUE TITLE
Missing or hard to find "localization guide"

### ISSUE THREAD

**Issue by bolora** [eclipsesource/jsonforms#2010]
### Describe the bug

In https://jsonforms.io/docs/multiple-choice#localization you mention that "For how to localize the enum, have a look at our localization guide."

I've searched everywhere and cannot find this "localization guide"

### Expected behavior

I would expect "localization guide" to be a link

### Steps to reproduce the issue

1. Go to https://jsonforms.io/docs/multiple-choice#localization
2. See the localization section has the following instruction "For how to localize the enum, have a look at our localization guide."
3. There is nowhere to go

### In which browser are you experiencing the issue?

Chrome, doesn't matter

**Comment by sdirix** [comment]
Hi @bolora, good point! The localization documentation is still WIP and under review. You can find the PR [here](https://github.com/eclipsesource/jsonforms2-website/pull/222) and the hosted version of the current state [here](https://deploy-preview-222--jsonforms.netlify.app/docs/i18n).

As it's not yet merged, the documentation is not 100% complete. It's missing a section about how to translate UI Schema elements and does not describe the translation context in all details. But it should give a good first introduction. Feel free to leave comments in the PR to improve the documentation.

**Comment by sdirix** [comment]
This is fixed for a while. The documentation can now be found here: https://jsonforms.io/docs/i18n
