### ISSUE TITLE
Update version of peer dependency RXJS 

### ISSUE THREAD

**Issue by stanvanrooy** [eclipsesource/jsonforms#2014]
### Is your feature request related to a problem? Please describe.

We're running into some issues trying to implement JSON forms. 

We have an Angular app running on version 13.3.0. That version of Angular has a peer dependency on RXJS, at version `^7.4.0`.

Unfortunately, this results in conflicts when trying to install `jsonforms`, because this package has a peer dependency on RXJS at version `6.4.0`. 

### Describe the solution you'd like

Would it be possible to update this dependency to `^6.4.0 || ^7.4.0`?

### Describe alternatives you've considered

Using `npm install --force`, but that is not an ideal solution.

### Framework

Angular

**Comment by gaspa** [comment]
Hi, we have the same issue here. I'm interested in having this released. Thanks.

**Comment by stanvanrooy** [comment]
@lucas-koehler, thank you for the quick solution!
