### ISSUE TITLE
3.0 Release

### ISSUE THREAD

**Issue by sdirix** [eclipsesource/jsonforms#2022]
- [x] Create Changelog (@LukasBoll)
 - [x] Release JSON Forms 3.0 (@sdirix)
 - [x] Update all seed applications (@LukasBoll) (Review: @lucas-koehler)
   - [x] [React](https://github.com/eclipsesource/jsonforms-react-seed)
   - [x] [Angular](https://github.com/eclipsesource/jsonforms-angular-seed)
   - [x] [Vue](https://github.com/eclipsesource/jsonforms-vue-seed)
   - [x] [Vue2](https://github.com/eclipsesource/jsonforms-vue-seed/tree/vue2) 
 - [x] Update website with JSON Forms 3.0 and Api Docs (@LukasBoll) (Review: @lucas-koehler)
 - [x] Review/Merge open Website PRs (@sdirix) (@lucas-koehler)
    - [x] https://github.com/eclipsesource/jsonforms2-website/pull/239
    - [x] https://github.com/eclipsesource/jsonforms2-website/pull/235
    - [x] https://github.com/eclipsesource/jsonforms2-website/pull/227
    - [x] https://github.com/eclipsesource/jsonforms2-website/pull/224
    - [x] https://github.com/eclipsesource/jsonforms2-website/pull/222
 - [x] Release JSON Forms 3.0 Vuetify Renderers (@sdirix) 
 - [ ] Announce release on Twitter and Website (@sdirix)

**Comment by mikebski** [comment]
Hello @sdirix  - Just wondering if the vuetify for vue3 renderers are done yet?  I see it checked off here but no PR or documentation links (and the vue seed linked above does not use vuetify)...

If so, can you point me to the documentation on how to set it up? I've looked in the docs and via Google and all I can seem to find are vuetify for vue2 docs.

**Comment by sdirix** [comment]
Hi @mikebski,

This is about the release of JSON Forms 3.0 itself, not the switch to Vue 3 for the Vuetify renderers. There is nothing to announce yet in that direction, however the switch to Vuetify 3 is currently actively investigate. Any help for this endeavor is certainly appreciated, the ticket can be found [here](https://github.com/eclipsesource/jsonforms-vuetify-renderers/issues/44).
