### ISSUE TITLE
Custom Renderers  [Vue warn]

### ISSUE THREAD

**Issue by xushanpei** [eclipsesource/jsonforms#2025]
### Describe the bug

[Vue warn]: Vue received a Component which was made a reactive object. This can lead to unnecessary performance overhead, and should be avoided by marking the component with `markRaw` or using `shallowRef` instead of `ref`. 

![image](https://user-images.githubusercontent.com/35324963/192675753-c34a06e3-ecc3-4c11-8a2d-cb89888de68b.png)

### Expected behavior

Custom Renderers 

https://github.com/xushanpei/jsonForms_vue3_customRenderer

### Steps to reproduce the issue

Custom Renderers 

![image](https://user-images.githubusercontent.com/35324963/192675753-c34a06e3-ecc3-4c11-8a2d-cb89888de68b.png)

### Screenshots

![image](https://user-images.githubusercontent.com/35324963/192675753-c34a06e3-ecc3-4c11-8a2d-cb89888de68b.png)

### In which browser are you experiencing the issue?

Google Chrome  v 105.0.5195.128

### Framework

Vue 3

### RendererSet

Other (please specify in the Additional context field)

**Comment by sdirix** [comment]
Hi @xushanpei, I would like to recommend freezing the renderers before handing them over to JSON Forms. See [this example code](https://github.com/eclipsesource/jsonforms-vue-seed/blob/7c040f810b81db4c3d6a18196875a36178e4b3ff/src/App.vue#L121) from the JSON Forms Vue seed. Does this fix your problem?

**Comment by sdirix** [comment]
As there were no further comments I'll close the issue. Feel free to reopen if you disagree.
