### ISSUE TITLE
Helper Text

### ISSUE THREAD

**Issue by alexiskattan** [eclipsesource/jsonforms#2028]
### Is your feature request related to a problem? Please describe.

Is there a way to provide helper text next to an input?

For example:

{"Pet", string, "cat, dog, bird, etc..."}

### Describe the solution you'd like

Have some text appear next to the input form to give the user some context about what do enter in the field.

### Describe alternatives you've considered

Using the placeholder text, but it disappears once you start writting.

**Comment by sdirix** [comment]
Hi @alexiskattan, you can use the `description` field for this. If that does not fit your use cases you can implement custom renderers which can render arbitrary UI including for example a small tooltip for such a helper text.
