### ISSUE TITLE
TextArea doesn't work with material-renderers

### ISSUE THREAD

**Issue by alexiskattan** [eclipsesource/jsonforms#2029]
### Describe the bug

When rendering a textarea, it doesn't appear to work with `materialRenderers` but does with `vanillaRenderers`

```
const uischema = {
        "type": "VerticalLayout",
        "elements": [
            {
                "type": "Control",
                "scope": "#/properties/FreeText",
                options: {
                    multi: true
                }
                        
            }
        ]
    }
```

### Expected behavior

Should show a textarea

### In which browser are you experiencing the issue?

Chrome

**Comment by sdirix** [comment]
Hi @alexiskattan, which version of JSON Forms are you using?

Using the latest `3.0.0` it seems to work fine, [see the JSON Forms React seed](https://github.com/eclipsesource/jsonforms-react-seed/blob/b3838859791ce5e807b31fb17352ff1ef8b3610f/src/uischema.json#L47-L53) and the [deployed version](https://jsonforms-react-seed.netlify.app/).

![multitrue](https://user-images.githubusercontent.com/8998368/193773649-59fbc68d-9c84-45bf-9947-296f96734272.gif)

**Comment by sdirix** [comment]
I'll close this as there were no further comments. Feel free to reopen when you can reproduce the issue.
