### ISSUE TITLE
 Formfield “Description” Value is not displayed in Angular

### ISSUE THREAD

**Issue by TonyStrobach** [eclipsesource/jsonforms#2030]
### Describe the bug

Using Angular Material Renderer, the "description" value of a schema propertie does not get displayed.

E.g.:
```
{
    "type": "object",
        "properties": {
            "name": {
                "type": "string",
                "minLength": 3,
                "description": "Please enter your name"
             },
        }
}
```

description is not displayed

### Expected behavior

The expected behaviour for the example above would be:
Click on the formfield --> Description does get displayed 

### Steps to reproduce the issue

Use theis example with angular material render:
https://jsonforms.io/examples/basic

Klick into the "Name" Field.
Notice that it does not display the description

### In which browser are you experiencing the issue?

Google Chrome Version 105.0.5195.127

### Framework

Angular

### RendererSet

Material

**Comment by sdirix** [comment]
We'll take a look!
