### ISSUE TITLE
Control Error Icon Renders Falsely while screen size is less than 600px 

### ISSUE THREAD

**Issue by gittc100** [eclipsesource/jsonforms#2031]
### Describe the bug

1. There are zero errors produced by the <JsonForms> component onChange method.
2. The Control Component Error Icon renders while the screen size is less than 600px.
3. If the screen width is expanded past 600px the Error Icon will disappear. 

### Expected behavior

The Error Icon should not render while there are zero errors produced by the <JsonForms> component.

### Steps to reproduce the issue

1. Render a group component without errors.
2. Make your screen width larger than 600px.
3. Compress the width until you get the Icon Error.
4. See attached screen shots for example.

### Screenshots

Without Bug
![Screenshot from 2022-09-30 14-50-09](https://user-images.githubusercontent.com/37307521/193337329-6044a956-65b4-4ae5-a7a0-3a4dc2e93c13.png)
With Bug
![Screenshot from 2022-09-30 14-50-29](https://user-images.githubusercontent.com/37307521/193337408-c97b52b7-adbe-4be6-bdac-440c2086f76f.png)

### In which browser are you experiencing the issue?

Fire Fox Version 102.0

### Framework

React

### RendererSet

Material

**Comment by sdirix** [comment]
Thanks for the report! We'll take a look.
