### ISSUE TITLE
Make full form data available in custom controls

### ISSUE THREAD

**Issue by clemens-msupply** [eclipsesource/jsonforms#2046]
### Is your feature request related to a problem? Please describe.

I have a case where a custom control has to have a peek at the whole form data and not only on its own data (the property it operates on). For example, the control needs to do some advanced conditional checks on a configurable property that can't be done using rules.

### Describe the solution you'd like

In the control props object I like to have a `formData` object additionally to the existing `data` object. The `formData` would contain the whole data for the form. (Or some other way to get the current form data)

### Describe alternatives you've considered

Alternative solution is to let the custom control work in the scope of "#" so that it can see all data. This works but seems to be not very intuitive when working with the custom control in the ui schema...

### Framework

Core, React

**Comment by badalkhatri0924** [comment]
@clemens-msupply 

https://jsonforms.discourse.group/t/cascading-dropdowns-returning-only-one-value/488

**Comment by sdirix** [comment]
Hi @clemens-msupply!

As @badalkhatri0924 correctly pointed out: In all custom renderers you can always access the form wide state and therefore allow for all kinds of use cases. I'll therefore close this issue.

Whenever you have questions feel free to open a post in [our community](https://jsonforms.discourse.group/).

**Comment by clemens-msupply** [comment]
Works great! thanks for your great work!!

```typescript
const ctx = useJsonForms();
const data = ctx.core.data;
```
