### ISSUE TITLE
Typescript incompatibilities after angular 14.2 and TS 4.6.4

### ISSUE THREAD

**Issue by Ketec** [eclipsesource/jsonforms#2048]
### Describe the bug

A large number of type errors
`node_modules/@jsonforms/core/src/util/renderer.ts:878:51 - error TS2345: Argument of type 'UISchemaElement | undefined' is not assignable to parameter of type 'UISchemaElement'.`

All related to unhandled "undefined" types.
[log.txt](https://github.com/eclipsesource/jsonforms/files/9991383/log.txt)

Angular 15 will be switching to TS 4.8

### Expected behavior

Should be type safe

### In which browser are you experiencing the issue?

Version 107.0.5304.89 (Official Build) (64-bit)

### Which Version of JSON Forms are you using?

3.0.0

### Framework

Angular

### RendererSet

Other (please specify in the Additional context field)

### Additional context

Custom controls are built based on the material.

**Comment by sdirix** [comment]
Hi @Ketec, when does the error exactly occur? Can you workaround the issue with `skipLibCheck: true`?

**Comment by Ketec** [comment]
Build time. However, for the moment I had to reduce the TS version while upgrading since other libraries had conflicts.
I assume it is because of more strict rules with newer TS and any implicitly undefined value (no default) may get caught.
