### ISSUE TITLE
Make MUI Accordion `TransitionProps.unmountOnExit` configurable

### ISSUE THREAD

**Issue by janstuemmel** [eclipsesource/jsonforms#2059]
### Is your feature request related to a problem? Please describe.

I have a huge amount of ExpandPanel's in my appliation. Jsonforms MUI/React render's them with [mui/Accordion](https://mui.com/material-ui/react-accordion/). A lot of Accordions make my UI very slow because mui renders them with all sub items for SSR reasons by default, but this can be turned off via:

```js
<Accordion TransitionProps={{ unmountOnExit: true }} />
```

My ui responds a lot faster now.

### Describe the solution you'd like

Make accordion `TransitionProps.unmountOnExit` configurable via [`JsonFormsInitStateProps.config`](https://jsonforms.io/docs/integrations/react#config)

### Describe alternatives you've considered

no better alternative

### Framework

React

### RendererSet

Material

**Comment by sdirix** [comment]
Hi @janstuemmel, Thanks for the report!

As this prop is also configurable via the [Material UI Theming support](https://mui.com/material-ui/customization/theme-components/#default-props) I don't think we need to add it as a special setting to JSON Forms, e.g.

```jsx
const theme = createTheme({
  components: {
    MuiAccordion: {
      defaultProps: {
        TransitionProps: {
          unmountOnExit: true
        }
      }
    },
  },
});

const MyJsonForms = (props) => {
  return (
    <ThemeProvider theme={theme}>
      <JsonForms {...props} />
    </ThemeProvider>
  );
}
```

**Comment by janstuemmel** [comment]
That helped a lot, thanks!

**Comment by KarThikCh-dev** [comment]
there is any thing like this for angular , i am using angular material with tali-wind css, my application performance is also very poor
