### ISSUE TITLE
EMF Forms goes AngularJS: Backend integration with OpenAPI

### ISSUE THREAD

**Issue by koegel** [eclipsesource/jsonforms#206]
EMF Forms is an Eclipse framework to efficiently develop form-based UIs (see http://eclipse.org/ecp/emfforms/). It also provides a renderer for web application called “JSON Forms”. JSONForms transfers the concepts of EMF and EMF Forms to an JSON and AngularJS based web stack. While integration of desktops applications with backends is often done in Java and transparent for the UI, web applications are typically connected to REST services. The state-less and asynchronous way how single-page web applications typically operate, requires framework support for an efficient integration of form-based UIs with RESTful backends. The state-less and asynchronous way how single-page web applications typically operate often requires framework support: One prominent example is OpenAPI for documenting and describing such APIs, Having a description of an API also allows for a wide range of use cases , such as rapid prototyping or scaffolding. Our goal is therefore to integrate JSONForms with OpenAPI in order to derive declarative Web UIs for REST endpoints, which are ready-to-use while still being highly customizable.

**Comment by edgarmueller** [comment]
@koegel Is this still relevant? Can we close it?

**Comment by koegel** [comment]
No, we can close it

**Comment by jbadeau** [comment]
Too bad :(
