### ISSUE TITLE
when field is hidden

### ISSUE THREAD

**Issue by kfiros432** [eclipsesource/jsonforms#2067]
### Is your feature request related to a problem? Please describe.

when condition is true and the field is hidden and if the initial data of the field was set i still can see the field data in the data object when submitting.

### Describe the solution you'd like

i think that when i want to hide the field with condition i don't want to see its value anymore.

### Describe alternatives you've considered

don't show the value of hidden field in the submitted data.

### Framework

React

### RendererSet

Material

**Comment by sdirix** [comment]
Hi @kfiros432,

This is not implemented on purpose in JSON Forms. We consider the UI Schema rules including show/hide to be a UI concept which should not have an effect on the underlying data object. Often this is also bad for usability: Imagine the user entering some data, then enabling/disabling a checkbox which hides some fields. Once that action is reversed the data is gone and the user needs to reenter all their values again.

If you really need to strip the data from the object then:
- You could remove all unnecessary values after the fact before transmitting the object to some further process/backend
- You could listen to data changes emitted from JSON Forms and remove the unnecessary values before handing the data back to JSON Forms (make sure to not run in endless loops)
- You could implement custom renderers for the properties which trigger the hide/show and delete the appropriate data together with the data change
