### ISSUE TITLE
schema with key or id "<url>" already exists

### ISSUE THREAD

**Issue by Ketec** [eclipsesource/jsonforms#2071]
### Describe the bug

It seems like the schema passed to the ajv instance is not cleared when a new update/schema is passed to the jsonForms with updated values.

![image](https://user-images.githubusercontent.com/25903372/210976916-88b6ca4f-26d0-4595-b3be-c5d041858b29.png)

This seems to come from 
`thisAjv.compile(action.schema);` reusing existing instance and adding to it.

### Expected behavior

Can pass in the same schema with updated values.

It should likely call removeSchema on update?

### Steps to reproduce the issue

Schema root has $id.
```
{
  "$id": "something",
  "type": "object",
  "properties": {}
}
```

### In which browser are you experiencing the issue?

Version 107.0.5304.89 (Official Build) (64-bit)

### Which Version of JSON Forms are you using?

3.0.0

### Framework

Angular

### RendererSet

Other (please specify in the Additional context field)

**Comment by cloedu87** [comment]
I had the same issue.

worked around with a small interception, similar to the one @sdirix mentioned before.

the error only occures with schema's which got a `$id` or `id` set on the root.

if the schema is about to change, I do the following

```
ajvInstance.removeSchema(theCurrentSchema.$id)
```
I could not find another solution, neighter any side effects with mine.

Best, c.

**Comment by sdirix** [comment]
We have [some code in JSON Forms which should avoid this error](https://github.com/eclipsesource/jsonforms/blob/8b6c9d23c21f96737fb66d0a70068c24e55365ad/packages/core/src/reducers/core.ts#L86-L91). Probably we missed a use case so that it still occurs.

**Comment by sdirix** [comment]
@LukasBoll Please check in which code path we are not cleaning AJV, probably the init path. Also please check the AJV API whether it can be used in a non-stateful way.
