### ISSUE TITLE
Table using oneOf doesn't allow the "addNew" button to be disabled

### ISSUE THREAD

**Issue by dcjarvisvt** [eclipsesource/jsonforms#2086]
### Describe the bug

When defining a table and one of the fields uses oneOf (instead of enum), the format of the table changes to a detail list and the "readonly" attribute is not controlling the add new button to be disabled.

### Expected behavior

Just by switching to oneOf from enum shouldn't change the table to a detail list and the readonly only option should disable to add new button.

### Steps to reproduce the issue

With this UI schema and Schema the add new button gets disabled.
UI Schema:
{
  "type": "VerticalLayout",
  "elements": [
    {
      "type": "Control",
      "scope": "#/properties/zinstmap",
      "options": {
        "readonly": true
      }
    }
  ]
}

Schema:
{
  "type": "object",
  "properties": {
    "zinstmap": {
      "title": "Data Mapping",
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "name": {
            "title": "Name",
            "enum": [
              "SRCB1",
              "SRCB2",
              "SRINFO",
              "SRINFR"
            ]
          },
          "id": {
            "title": "ID",
            "type": "string"
          }
        }
      }
    }
  }
}

With the below Schema, the format changes to a ListwithDetail and the add new button can't be disabled/hidden.
{
  "type": "object",
  "properties": {
    "zinstmap": {
      "title": "Data Mapping",
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "name": {
            "title": "Name",
            "oneOf": [
              {
                "const": "123",
                "title": "SRCB1"
              },
              {
                "const": "111",
                "title": "SRCB2"
              },
              {
                "const": "222",
                "title": "SRINFO"
              },
              {
                "const": "333",
                "title": "SRINFR"
              }
            ]
          },
          "id": {
            "title": "ID",
            "type": "string"
          }
        }
      }
    }
  }
}

### Screenshots

![table with enum](https://user-images.githubusercontent.com/123497217/215129181-8308b326-31d2-4cb1-810d-01678a0d1c8b.PNG)
![table with oneof](https://user-images.githubusercontent.com/123497217/215129195-e652ed6b-123f-4253-ab2a-b311889d5310.PNG)

### In which browser are you experiencing the issue?

Google Chrome 109.0.5414.75

### Which Version of JSON Forms are you using?

3.1.0-alpha.0

### Framework

React

### RendererSet

Vanilla

**Comment by sdirix** [comment]
Hi! Thanks for the report. This is essentially the same issue as https://github.com/eclipsesource/jsonforms/issues/2081

**Comment by sdirix** [comment]
I'll close this as a duplicate but linked it in the other ticket.
