### ISSUE TITLE
Move to Node 16+ and upgrade build tech stack

### ISSUE THREAD

**Issue by lucas-koehler** [eclipsesource/jsonforms#2110]
Currently, we use Node 14 and NPM 6.x.

We want to increase the used Node version and the repository's build technology stack:

- Move to Node 16
- Introduce [pnpm](https://pnpm.io/) as a package manager
- Replace the outdated lerna version with [nx](https://nx.dev/) or the latest lerna version (bundling nx)

**Comment by dcantu96** [comment]
Am I currently able to use this if i'm using node 18+ ? I get this error but I dont know if its becuase of this

![Screenshot 2023-03-09 at 9 29 26](https://user-images.githubusercontent.com/32658690/224084551-5ce73071-8182-4477-8c2e-0ff0f657b1f8.png)

**Comment by sdirix** [comment]
@dcantu96 Users of the library can use any Node version they want. Technically you don't even need Node to consume JSON Forms. The move to Node 18+ concerns the development environment when working on JSON Forms itself.

---

The error you posted is related to our output. We export all our libraries as:
 - CommonJS modules targeting ES5
 - ES modules targeting esnext

You are probably consuming the ES modules variant which targets the latest ECMA script features but your tool chain is not able to handle some of them. You can either:
- Adjust your tool chain, for example by updating to Webpack 5 or [by adding Babel plugins for these features](https://github.com/eclipsesource/jsonforms/blob/2bbc64689cdf694daacac7ff5c1f5de6eb540849/packages/vue/vue-vanilla/babel.config.js#L8-L9)
- Force consume the CommonJS variant by customizing the resolving in Webpack, e.g.
  ```javascript
  resolve: {
    alias: {
      '@jsonforms/react': require.resolve('@jsonforms/react'),
    }
  }
  ```
