### ISSUE TITLE
Support for SolidJS

### ISSUE THREAD

**Issue by thedanchez** [eclipsesource/jsonforms#2115]
### Is your feature request related to a problem? Please describe.

No, this feature request is not related to an existing problem.

### Describe the solution you'd like

SolidJS is an up-and-coming frontend library (very much inspired by React and looks similar to it as well) that is starting to gain in popularity. It's received awards and much recognition in 2022. It would be great if `jsonforms` could export an adapter for Solid (i.e. `@jsonforms/solid`) as it does for React (`@jsonforms/react`) to further the growing ecosystem surrounding it.

### Describe alternatives you've considered

There are no alternatives to my knowledge.

### Framework

Other (please specify in the Additional context field)

### Additional context

[SolidJS](https://www.solidjs.com/)

**Comment by sdirix** [comment]
Hi @thedanchez , thanks for the suggestion.

At the moment we have no plans to create and maintain SolidJS bindings and/or a SolidJS-based renderer set ourselves. If you are interested in such an offering you might want to consider our [professional support](https://jsonforms.io/support) by which we would help you to create SolidJS bindings and renderer set, ranging from answering questions to taking over the full implementation.

In case you create and maintain such a binding and/or renderer set yourself we will be happy to link you in the [JSON Forms community page](https://jsonforms.io/community).
