### ISSUE TITLE
enableIvy should not be set to false!

### ISSUE THREAD

**Issue by ltetreault-va** [eclipsesource/jsonforms#2116]
### Describe the bug

In the `angular` and `angular/material` libraries `enableIvy` is set to false in the `tsconfig.json` files

Angular: https://github.com/eclipsesource/jsonforms/blob/2bbc64689cdf694daacac7ff5c1f5de6eb540849/packages/angular/tsconfig.json#L14

Angular Material: https://github.com/eclipsesource/jsonforms/blob/2bbc64689cdf694daacac7ff5c1f5de6eb540849/packages/angular-material/tsconfig.json#L14

Every version of angular supported by this library has `ivy` support (default since ng 9). With this setting off we are forced into longer build times because angular needs to use the legacy view engine processor on this dependency.

### Expected behavior

remove the `enableIvy: false` line and let angular default to using `ivy`

### Steps to reproduce the issue

1. `npm i @jsonforms/angular`
2. `ng build <project>`
3. See error in build logs 

```
Processing legacy "View Engine" libraries:
- @jsonforms/angular [module/esm5] (https://github.com/eclipsesource/jsonforms)
- @jsonforms/angular-material [module/esm5] (https: //github.com/eclipsesource/jsonforms)
- @jsonforms/angular [main/commonjs] (https://github.com/eclipsesource/jsonforms)
- @jsonforms/angular-material [main/commons] (https://github.com/eclipsesource/jsonforms)
```

### Screenshots

<img width="764" alt="remaining ngcc" src="https://user-images.githubusercontent.com/50848874/225156456-0076d989-19ca-4f32-8fbd-ad21299d0aee.png">

### In which browser are you experiencing the issue?

n/a

### Which Version of JSON Forms are you using?

v3.0.0

### Framework

Angular

### RendererSet

Material

**Comment by sdirix** [comment]
Changes like this should probably be accompanied by https://github.com/eclipsesource/jsonforms/issues/1546. Also related is https://github.com/eclipsesource/jsonforms/issues/1993
