### ISSUE TITLE
Bootstrap 5 support

### ISSUE THREAD

**Issue by KES777** [eclipsesource/jsonforms#2136]
### Is your feature request related to a problem? Please describe.

I want to render custom controls. I read documentation and did not find example how to use vanilla rendering. I do not want to install any of React, Vue, Angular libraries.

### Describe the solution you'd like

Looking for documentation how to provide custom hooks to render custom and/or bootstrap components.

### Describe alternatives you've considered

None.

**Comment by lucas-koehler** [comment]
Hi @KES777 ,
we currently do not offer an integration or renderer sets to be used without React, Vue or Angular. You need to implement your own bindings and renderers for that. See here for documentation on the architecture: https://jsonforms.io/docs/architecture

**Comment by KES777** [comment]
@lucas-koehler Thank you for the link. I saw that architecture. But that do not give any clue how to implement my own bindings and renderers. =(

**Comment by sdirix** [comment]
We use the React, Vue and Angular bindings for state management. All these frameworks offer convenient ways to manage state and update the according DOM elements.

If you want a pure Vanilla solution you need to store the form-wide state in your Vanilla bindings and come up with a rendering mechanism to render and update the DOM in a way you see fit.

I close this issue as we don't plan to support Bootstrap and/or Vanilla bindings in the foreseeable future.
