### ISSUE TITLE
JSONForms >= 3.0.0 is incompatible with @mui/x-date-pickers >= 6.0.0

### ISSUE THREAD

**Issue by sebastianfrey** [eclipsesource/jsonforms#2137]
### Describe the bug

JSONForms >= 3.0.0 crashes when used with @mui/x-date-pickers >= 6.0.0.

### Expected behavior

JSONForms >= 3.0.0 should not crash when used with @mui/x-date-pickers >= 6.0.0.

### Steps to reproduce the issue

1. Go to [https://codesandbox.io/s/jsonforms-with-v6-mui-date-pickers-b8mkzm](https://codesandbox.io/s/jsonforms-with-v6-mui-date-pickers-b8mkzm)
1. Click on DatePicker calendar button
1. See error

### In which browser are you experiencing the issue?

Google Chrome 113.0.5672.92 (Official Build) (64-bit)

### Which Version of JSON Forms are you using?

v3.0.0

### Framework

React

### RendererSet

Material

**Comment by sdirix** [comment]
Hi @sebastianfrey,

At the moment we build against [`^5.0.0-beta.5`](https://github.com/eclipsesource/jsonforms/blob/f8ea38f9f9dd3d46cbfde269ec43e9eb1632e428/packages/material-renderers/package.json#L98).

Would you like to contribute an upgrade to `^6.0.0`. If somehow possible it would be great to keep compatibility with `^5.0.0` but if it doesn't work then that's life.

**Comment by sebastianfrey** [comment]
Hi @sdirix,

Sure, I can submit a PR which upgrades @mui/x-date-pickers to v6.0.0.

What I can't guarantee is backwards compatibility to v5.0.0. The reason for that is, that there are a lot of breaking changes from v5 to v6.

Side note:

Those guys from MUI rush very fast forward and do not care a lot about backwards compatibility. From experience I can say that I have already experienced this several times on my own skin. So have you I guess.

As mentioned in their v6 release article, they will decouple the versioning of MUI-X packages from MUI-Core, so they can move forward a lot faster, because it allows them to introduce breaking changes easier.

Having this in mind, it might be a good idea to separate the MUI-X related material renderers into separate packages. That would allow JSONForms to support multiple @mui/x-date-pickers versions at the same time.
