### ISSUE TITLE
controlPath is undefined

### ISSUE THREAD

**Issue by Epse** [eclipsesource/jsonforms#2143]
### Describe the bug

Using the angular-material renderers, a bare-minimum component using jsonforms crashes reliably when removing the last character in the `name` input, or starting it with an empty value for `name` in the data object.
After this, no further validation is performed. If starting it an empty data object, the various inputs are only partially rendered.

<details>
<summary>Console output in Firefox</summary>

```
ERROR TypeError: controlPath is undefined
    getControlPath jsonforms-core.esm.js:592
    errorsAt jsonforms-core.esm.js:606
    Lodash 2
    errorsAt jsonforms-core.esm.js:602
    getErrorsAt jsonforms-core.esm.js:623
    getErrorAt jsonforms-core.esm.js:1065
    mapStateToControlProps jsonforms-core.esm.js:1489
    Angular 2
    RxJS 6
    Angular 14
    addEventListener eval:4
    Angular 84
    RxJS 5
    Angular 9
[core.mjs:7644:22](webpack:///node_modules/@angular/core/fesm2020/core.mjs)
    Angular 2
    RxJS 5
    Angular 20
    RxJS 7
    Angular 14
    (Async: EventListener.handleEvent)
    addEventListener eval:4
    Angular 29

```

</details>

<details>
<summary>Console output in Chrome</summary>

```
ROR TypeError: Cannot read properties of undefined (reading 'replace')
    at getControlPath (jsonforms-core.esm.js:592:31)
    at jsonforms-core.esm.js:606:29
    at arrayFilter (_arrayFilter.js:18:9)
    at filter (filter.js:49:10)
    at jsonforms-core.esm.js:602:18
    at jsonforms-core.esm.js:623:12
    at jsonforms-core.esm.js:1065:12
    at mapStateToControlProps (jsonforms-core.esm.js:1489:20)
    at JsonFormsControl.mapToProps (control.js:34:43)
    at Object.next (abstract-control.js:66:35)
    at SafeSubscriber.__tryOrUnsub (Subscriber.js:183:16)
    at SafeSubscriber.next (Subscriber.js:122:22)
    at Subscriber._next (Subscriber.js:72:26)
    at Subscriber.next (Subscriber.js:49:18)
    at BehaviorSubject.next (Subject.js:39:25)
    at BehaviorSubject.next (BehaviorSubject.js:30:15)
```

</details>

The offending snippet in JsonForms Core:

```ts
const getControlPath = (error) => {
    const dataPath = error.dataPath;
    if (dataPath) {
        return dataPath.replace(/\//g, '.').substr(1);
    }
    var controlPath = error.instancePath;
    controlPath = controlPath.replace(/\//g, '.'); // here
    const invalidProperty = getInvalidProperty(error);
    if (invalidProperty !== undefined && !controlPath.endsWith(invalidProperty)) {
        controlPath = `${controlPath}.${invalidProperty}`;
    }
    controlPath = controlPath.replace(/^./, '');
    return controlPath;
};
```

### Expected behavior

Form keeps being validated

### Steps to reproduce the issue

<details>
<summary>Angular component</summary>

```ts
import { Component } from "@angular/core";
import { angularMaterialRenderers, generateDefaultUISchema } from "@jsonforms/angular-material";

@Component({
  selector: "app-root",
  template: `<jsonforms
    [(data)]="data"
    [schema]="schema"
    [uischema]="uischema"
    [renderers]="renderers"
  ></jsonforms>`,
})
export class AppComponent {
  renderers = angularMaterialRenderers;
  schema = {
    type: "object",
    properties: {
      name: {
        type: "string",
        minLength: 1,
      },
      done: {
        type: "boolean",
      },
      due_date: {
        type: "string",
        format: "date",
      },
      recurrence: {
        type: "string",
        enum: ["Never", "Daily", "Weekly", "Monthly"],
      },
    },
    required: ["name", "due_date"],
  };
  uischema = generateDefaultUISchema(schema);
  data = {
    name: "test",
    due_date: "2023-06-06"
  };
}
```

</details>
Render this, start backspacing in the name field.

### Screenshots

When the data object is initially empty: 
![Screenshot_2023-06-06-155042](https://github.com/eclipsesource/jsonforms/assets/10013355/e2e80e45-61d1-47f6-913e-52a1c80d8583)

### In which browser are you experiencing the issue?

Chromium 113.0.5672.126, Mozilla Firefox 113.0.2

### Which Version of JSON Forms are you using?

v3.0.0

### Framework

Angular

### RendererSet

Material

### Additional context

Potentially relevant excerpt from `package-lock.json`:

```
    "node_modules/@jsonforms/core": {
      "version": "3.0.0",
      "resolved": "https://registry.npmjs.org/@jsonforms/core/-/core-3.0.0.tgz",
      "integrity": "sha512-DcUGLNaeAE411oA8d5dPuPEF2/nDmALAfQRsaA3GPAre2D76kJXyBb8TFMjLMRJCVIR0q5LsiRRdmLnuPVHKqA==",
      "dependencies": {
        "@types/json-schema": "^7.0.3",
        "ajv": "^8.6.1",
        "ajv-formats": "^2.1.0",
        "lodash": "^4.17.15"
      }
    },
    "node_modules/@jsonforms/core/node_modules/ajv": {
      "version": "8.12.0",
      "resolved": "https://registry.npmjs.org/ajv/-/ajv-8.12.0.tgz",
      "integrity": "sha512-sRu1kpcO9yLtYxBKvqfTeh9KzZEwO3STyX1HT+4CaDzC6HpTGYhIhPIzj9XuKU7KYDwnaeh5hcOwjy1QuJzBPA==",
      "dependencies": {
        "fast-deep-equal": "^3.1.1",
        "json-schema-traverse": "^1.0.0",
        "require-from-string": "^2.0.2",
        "uri-js": "^4.2.2"
      },
      "funding": {
        "type": "github",
        "url": "https://github.com/sponsors/epoberezkin"
      }
    },
```

The contents of `error` at the point of error:
```js
{
  "keyword": "required",
  "dataPath": "",
  "schemaPath": "#/required",
  "params": {
    "missingProperty": "name"
  },
  "message": "should have required property 'name'",
  "schema": [
    "name",
    "due_date"
  ],
  "parentSchema": {
    "type": "object",
    "properties": {
      "name": {
        "type": "string",
        "minLength": 1
      },
      "done": {
        "type": "boolean"
      },
      "due_date": {
        "type": "string",
        "format": "date"
      },
      "recurrence": {
        "type": "string",
        "enum": [
          "Never",
          "Daily",
          "Weekly",
          "Monthly"
        ]
      }
    },
    "required": [
      "name",
      "due_date"
    ]
  },
  "data": {}
}
```

**Comment by sdirix** [comment]
Hi @Epse,

Thanks for the detailed report.

There seems to be some AJV version issue going on: The `errror` you posted is in the old AJV v6 format, specifying the `dataPath`. JSON Forms expects AJV v8 errors specifying the `instancePath` instead.

We added a small fallback (as you can see in the code) should we receive AJV v6 style errors which have the `dataPath` specified. However the fallback overlooked the case for the empty path which is what is handed over in your case. Therefore we run into the new `instancePath` case which then fails because it's undefined. The fallback code could be improved and that would fix the issue for you. If you like you can make a contribution to improve the fallback code check.

However the question is why we even get AJV v6 style errors. Your `package-lock.json` shows that AJV v8 should be brought in. Maybe the Angular build is throwing it out again? Or do you hand over an own AJV instance to JSON Forms which you create yourself? I would like to recommend checking this. For example by specifying AJV v8 as a direct dependency of your application.

**Comment by Epse** [comment]
Hi

Your message really put me on the right path to figuring this one out. It turns out that AJV v7 was included as a peer dependency of another component. I had to do some version juggling, but there's now validation and no more error reports.

Thanks for the help, I'll close the issue here
