### ISSUE TITLE
Is UI Schema is necessary?

### ISSUE THREAD

**Issue by zuo305** [eclipsesource/jsonforms#2145]
### Is your feature request related to a problem? Please describe.

In my case, there is only JSON schema. Is it possible to show the form with only schema data?

### Describe the solution you'd like

In my case, there is only JSON schema. Is it possible to show the form with only schema data?

### Describe alternatives you've considered

In my case, there is only JSON schema. Is it possible to show the form with schema data?

**Comment by Altair-Bueno** [comment]
You can generate a basic UI scheme from the JSON scheme using `generateDefaultUISchema`

```ts
import { generateDefaultUISchema } from "@jsonforms/core";

const uiScheme = generateDefaultUISchema(myJsonScheme);
```

**Comment by zuo305** [comment]
Thanks @Altair-Bueno , it is working well now.
