### ISSUE TITLE
Regression: 'React Material array and list with detail' toolbar errors are justified incorrectly

### ISSUE THREAD

**Issue by chriswhitehead** [eclipsesource/jsonforms#2152]
### Describe the bug

The errors grid item in the array toolbar now renders in the centre:

![image](https://github.com/eclipsesource/jsonforms/assets/58263891/38f9513c-8b3f-4d6e-83b5-fafc14143f92)

Looks to be caused by https://github.com/eclipsesource/jsonforms/commit/fa055c286ee149a48cf47203ef8e1624e32de1ca.

The issue appears to be that 3 grid items are rendered now, rather than the label and errors items being nested in 1 grid item.

### Expected behavior

Errors icon renders next to the label.

### Steps to reproduce the issue

1. Create a form with "List with Detail".
2. Add fields with required values as per the example: https://jsonforms.io/examples/list-with-detail
3. Errors icon renders centered.

### Screenshots

![image](https://github.com/eclipsesource/jsonforms/assets/58263891/1cd96e94-f368-4ccd-afd6-98b8a84c2a77)

### In which browser are you experiencing the issue?

Google Chrome Version 114.0.5735.134 (Official Build) (64-bit)

### Which Version of JSON Forms are you using?

v3.1.0

### Framework

React

### RendererSet

Material

**Comment by sdirix** [comment]
Hi @chriswhitehead,

Are you sure that this is a regression? I was under the impression that we always rendered the validation badge in the middle of the title bar.

I quickly verified: This is how we render the list with detail badge in JSON Forms 3.0

![image](https://github.com/eclipsesource/jsonforms/assets/8998368/6ec5a2c3-27f5-4be4-9405-c89983cceaea)

**Comment by chriswhitehead** [comment]
Its not like this in the demo here: https://jsonforms.io/examples/list-with-detail.

**Comment by sdirix** [comment]
The website is also using JSON Forms `3.1.0` so it's actually the other way around.

We always rendered the badge in the middle of the toolbar. Only since `3.1.0` we moved it to the left because of the commit you linked.

**Comment by chriswhitehead** [comment]
My bad, I was on 3.1.0 of Core but beta for the Material Renderers which caused the confusion here. The new behaviour is much better and atleast this is now documented. Closing this out.
