### ISSUE TITLE
Renderers should handle array tuples

### ISSUE THREAD

**Issue by edgarmueller** [eclipsesource/jsonforms#217]
Renderers should be able to handle cases where `type` is an array

**Comment by edgarmueller** [comment]
This should probably read that the respective array renderer should handle [tuples](http://spacetelescope.github.io/understanding-json-schema/reference/array.html#tuple-validation)  as well. I've updated the title & description accordingly.

**Comment by eneufeld** [comment]
I think we will need an extra renderer for this, as the requirements for the two different arrays are very different.
- in the case of a list array we repeat the same form multiple times
- in the case of a tuple array we need to renderer completely different stuff in a special order exactly one time

Personally I'm not sure whether the use of a tuple array is so common and whether is even makes sense form a modeling point of view.
