### ISSUE TITLE
invalid output from allOf/anyOf combinator

### ISSUE THREAD

**Issue by a1528zhang** [eclipsesource/jsonforms#2173]
### Describe the bug

Here is my code
```

import { JsonForms } from "@jsonforms/react";
import { useState } from "react";
import {
  materialRenderers,
  materialCells,
} from "@jsonforms/material-renderers";

const Example = () => {
  const [data] = useState({});
  const schema = {
    anyOf: [
      {
        type: "object",
        properties: {
          firstName: {
            type: "object",
            properties: {
              A: {
                type: "number",
                maxLength: 1,
              },
            },
          },
        },
      },
      {
        type: "string",
      },
    ],
  };
  return (
    <JsonForms
      schema={schema}
      uischema={undefined}
      data={data}
      onChange={(d: any) => {
        console.log("getData ", d);
      }}
      renderers={materialRenderers}
      cells={materialCells}
    />
  );
};
```

I got this output: 

<img width="339" alt="image" src="https://github.com/eclipsesource/jsonforms/assets/13843324/05c75b3d-17d6-48a5-ba03-4e84bdeaac9a">

I cant paste by code because it is a String object. When I copy this object it turns to: 
`{
    "data": "1",
    "errors": []
}`.
Obviously it is not a valid json object.

### Expected behavior

I expected output: 
`
{
    "data": {
        "firstName": {
            "A": 1
        }
    },
    "errors": []
}
` 

### Steps to reproduce the issue

1. Start this example and render:
![image](https://github.com/eclipsesource/jsonforms/assets/13843324/06ab3fd7-3ff9-4e78-b9c5-0e421ca9627b)
2. select anyof-1 tab & input any string
![image](https://github.com/eclipsesource/jsonforms/assets/13843324/5f5896e3-6dc5-47df-98dc-8181a969915f)
3. select anyof-0 tab & input any string
![image](https://github.com/eclipsesource/jsonforms/assets/13843324/10de8131-b7b6-4742-84d5-2512f8aa5075)
4.  see error on console

### In which browser are you experiencing the issue?

Google Chrome  116.0.5845.96

### Which Version of JSON Forms are you using?

v3.1.0

### Framework

React

### RendererSet

Material

**Comment by sdirix** [comment]
Thanks for the report! My guess is that the update function fails when the current data is incompatible with the data to be set, but this needs to be further investigated. If my guess is correct using a `oneOf` instead of the `anyOf` should work.

**Comment by a1528zhang** [comment]
> Thanks for the report! My guess is that the update function fails when the current data is incompatible with the data to be set, but this needs to be further investigated. If my guess is correct using a `oneOf` instead of the `anyOf` should work.

yes, oneOf with no problem because change tab will clean data in root, anyOf/allOf can not doing this, we cannot only use oneOf for our demands.
