### ISSUE TITLE
Enum without "type" can't be rendered

### ISSUE THREAD

**Issue by acomagu** [eclipsesource/jsonforms#2177]
### Describe the bug

Enum definition without "type", like:

```json
{
  "enum": ["A", "B"]
}
```

, is valid JSON Schema, but can't be rendered.

### Expected behavior

Rendered as normal enum.

### Steps to reproduce the issue

The following schema does not render any fields:

```json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "properties": {
    "foo": {
      "enum": ["A"]
    }
  }
}
```

![image](https://github.com/eclipsesource/jsonforms/assets/1362750/529789af-a0ab-48c3-87fa-fbf69686ad35)

And the following schema causes runtime error, `options is undefined` at [this line](https://github.com/eclipsesource/jsonforms/blob/1e44159b4e9e7aaf4f5324b6f67636e5e35bd777/packages/material-renderers/src/mui-controls/MuiAutocomplete.tsx#L85):

```json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "properties": {
    "foo": {
      "type": "string",
      "anyOf": [
        {
          "enum": ["A", "B"]
        },
        {
          "enum": ["C", "D"]
        }
      ]
    }
  }
}
```

![image](https://github.com/eclipsesource/jsonforms/assets/1362750/b26e77fd-ba8f-41ce-aa3b-c5c1a25d4a1d)

### In which browser are you experiencing the issue?

Firefox 117.0 (64-bit Windows)

### Which Version of JSON Forms are you using?

v3.1.0

### Framework

React

### RendererSet

Material

### Additional context

I don't give any UI Schema(using default behavior).

**Comment by lucas-koehler** [comment]
Thanks for the report :)

**Comment by acomagu** [comment]
Thank you for your works!
