### ISSUE TITLE
Date Picker Validation

### ISSUE THREAD

**Issue by avwchapman12** [eclipsesource/jsonforms#2183]
### Describe the bug

When you delete (using the backspace button) an invalid date (whether by the default date format or additional errors such as min or max date), even if the field is not required the invalid date error persists. 

<img width="272" alt="Screenshot 2023-10-04 at 12 05 13 PM" src="https://github.com/eclipsesource/jsonforms/assets/122613815/688b7992-17db-4009-af9d-a2a55f7d9b8c">

### Expected behavior

When you delete (using the backspace button) an invalid date (whether by the default date format or additional errors such as min or max date), if the field is not required there is no error showing and the data should be undefined for that input.

### Screenshots

Screen Recording 2023-10-05 at 12.21.09 PM.mov

### In which browser are you experiencing the issue?

Google Chrome Version 117.0.5938.92 

### Which Version of JSON Forms are you using?

v3.0.0

### Framework

React

### RendererSet

Material

**Comment by sdirix** [comment]
Thanks for the report. We'll have a look. However instead of `null` we usually place `undefined` in the data.
