### ISSUE TITLE
 Plaintext control renderer is not loading data or binding it to the textfield when the key contains a dot

### ISSUE THREAD

**Issue by arunarivarasan** [eclipsesource/jsonforms#2184]
### Describe the bug

The Plaintext control renderer is not loading data or binding it to the textfield when the key contains a dot, as in the following schema and data example
schema = {
“type”: “object”,
“properties”: {
“name.test”: {
“type”: “string”
}
},
“required”: 
}

data = {
‘name.test’: ‘John Doe’
}

currently i am seeing empty data
looking for direction how to fix this

### Expected behavior

control load with value "John Doe"

### Steps to reproduce the issue

use plaintext control renderer
use following schema and data
schema = {
“type”: “object”,
“properties”: {
“name.test”: {
“type”: “string”
}
},
“required”: 
}

data = {
‘name.test’: ‘John Doe’
}

textfield will be empty and label is without dot.

### In which browser are you experiencing the issue?

117.0.5938.150

### Which Version of JSON Forms are you using?

3.1.0

### Framework

Core

### RendererSet

Other (please specify in the Additional context field)

### Additional context

we use fluentUI as system design

**Comment by lucas-koehler** [comment]
Hi @arunarivarasan ,
thank you for the report. This is a known issue and a solution is currently in development via #2153 . Thus, I close this issue.

**Comment by arunarivarasan** [comment]
Hi @lucas-koehler can we use patch if you can share the commit so we can use it now and later upgrade. Also can you share the expected timeline for version? 4
