### ISSUE TITLE
EnumArray Renderer not working with $refs

### ISSUE THREAD

**Issue by ananyabarthakur** [eclipsesource/jsonforms#2192]
### Describe the bug

The EnumArray renderer works without $refs in the schema, but with $refs, those EnumOptions do not seem to get handled. 

The 'options' prop should have returned the list of enum options, but comes back undefined. There seems to be no other prop to use other than 'options'  in ControlProps, OwnPropsOfEnum, DispatchPropsOfMultiEnumControl.

Here is the sample schema:
 schemaWithRef = {
      $schema: 'http://json-schema.org/draft-07/schema#',
      additionalProperties: false,
      type: 'object',
      definitions: {
        Partner: {
          enum: ['DeutscheTelekom', 'GoDaddy', 'Liquid', 'Rogers'],
          type: 'string'
        }
      },
      properties: {
        partner: {
          items: {
            $ref: '#/definitions/Partner'
          },
          type: 'array'
        }
      }
    }

### Expected behavior

The expected behavior is that the 'options' prop should return ['DeutscheTelekom', 'GoDaddy', 'Liquid', 'Rogers'], but instead returns undefined.

### Steps to reproduce the issue

Dispatch JSON forms with the given sample schema.

### In which browser are you experiencing the issue?

Edge 118

### Which Version of JSON Forms are you using?

v3.1.0

### Framework

React

### Additional context

FluentUI

**Comment by sdirix** [comment]
HI @ananyabarthakur,

Thanks for the report. In which renderer set does this problem occur? It works fine for me in the Material UI renderer set:

![image](https://github.com/eclipsesource/jsonforms/assets/8998368/d93901c5-beaf-4762-8baf-a1503722ba6f)

**Comment by ananyabarthakur** [comment]
Hello! Thanks for reaching out to me :)

It occurs in FluentUI renderer, specifically, it's called "ComboBox",

(Also, just to clarify the way array of enums need to be rendered - are
they to be rendered like you did, with the ability to add a single select
enum menu each time, or do we make just one menu, with the ability to check
multiple options? I am currently making the latter with fluentUIs combobox)

Thank you,
Best,
Ananya

**Comment by sdirix** [comment]
Hi @ananyabarthakur,

Where is this FluentUI renderer coming from? We don't offer a renderer set with FluentUI.

An `enum` in JSON Schema is necessarily a single selection. To allow for multi selection you can for example model an array consisting of enum values and marking the array as to contain unique elements. We support this already for some of the renderer sets, see [here](https://jsonforms.io/docs/multiple-choice#multi-select) for the docs.

**Comment by ananyabarthakur** [comment]
Hello @sdirix, I am using React.

**Comment by ananyabarthakur** [comment]
Hi @sdirix , for more information, I am creating a custom renderer using React, and here is the way I get the props + begin my component: interface EnumArrayControlProps
  extends ControlProps,
    OwnPropsOfEnum,
    DispatchPropsOfMultiEnumControl {}
export const EnumArrayControl: React.FC<EnumArrayControlProps> = ({
  visible,
  errors,
  path,
  options,
  data,
  addItem,
  removeItem,
  label,
  required,
  enabled,
  schema,
  rootSchema
}) => {


Would you be able to share the component code that works on your end?

**Comment by sdirix** [comment]
The source of all our renderers is available in this repository, so you can simply check how they are implemented, e.g. see [here](https://github.com/eclipsesource/jsonforms/blob/9146b0fdf5913d2251fadd5435d2c7e813db6f71/packages/material-renderers/src/complex/MaterialEnumArrayRenderer.tsx).

**Comment by ananyabarthakur** [comment]
Hello @sdirix,

I had question - your renderer MaterialEnumArrayRenderer uses an MUI Checkbox as its control. However, per the screenshot you sent and after implementing the same renderer locally, I see that it in fact renders a detail List of a single select dropdowns. How is it the case that it is not the MUI checkbox?

**Comment by ananyabarthakur** [comment]
I see! Thank you for trying it out as well. So how would you fix the tester such that, if there is a $ref, we have it resolved?

**Comment by ananyabarthakur** [comment]
I see. And does it work for you? I tried it on my end and it control fails to render due to the following error TypeError: Cannot read properties of undefined (reading 'map'). It seems like the resolver resolves the schema that is sent to it, but the schema that gets processed by the EnumArray renderer still has the $ref in it. Probably because we are not saving/sending back the resolvedschema anywhere?

**Comment by ananyabarthakur** [comment]
Is there a helper function that allows for the modification of the schema for all instances of the schema (for example, editing the schema with said function would have the renderers use the modified, resolved schema instead of the original unresolved schema?

**Comment by sdirix** [comment]
The testers and the render are independent from which other. So in the renderer the items also need to be resolved again. For renderers like the arrays we are already doing this. Here, similar to the tester, this was overlooked.

However as you are implementing a custom renderer anyway you can easily resolve them yourself in the renderer in the same way as is done in the tester.

**Comment by ananyabarthakur** [comment]
Would you be able to share the link to the file of the array renderer that implements the resolving of schema? I may be looking in the wrong place (materialrenderers/complex). Thanks!!

**Comment by ananyabarthakur** [comment]
Thank you!! It works now :) A somewhat side question, our default control is a plain text field, and now with EnumArrays working, it seems that fields without a specific control are defaulting to EnumArray instead of the text fields. EnumArrays are taking precedence over Default, even though our ranking, in order, is - 
`  Default,
  EnumArrayControl,
  PlainText,...`
 It is interesting because when it is - 
`  Default,
  PlainText,  
 EnumArrayControl,...`, what happens is that not only the defaults, but also actual textfields become dropdowns. I wonder if it is because we need to use cells?

**Comment by sdirix** [comment]
Hi @ananyabarthakur, it seems that your tester reacts too broadly, i.e. it not only returns a high priority for the enum arrays case, but also for the other cases you mentioned. For example you might have placed an "or" check to high. I would recommend to implement some test cases for the now used tester to verify that it only returns a high priority for enum arrays and not for strings etc.
