### ISSUE TITLE
Dependency Issue with latest MUI

### ISSUE THREAD

**Issue by devbydaniel** [eclipsesource/jsonforms#2214]
### Describe the bug

I am getting a dependency error when trying to install JSON forms with material renderers in a project using the latest version of MUI & MUI icons:

```
npm ERR! Found: @mui/icons-material@5.14.18
npm ERR! node_modules/@mui/icons-material
npm ERR!   @mui/icons-material@"^5.14.18" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @mui/icons-material@"~5.11.16" from @jsonforms/material-renderers@3.1.0
npm ERR! node_modules/@jsonforms/material-renderers
npm ERR!   @jsonforms/material-renderers@"*" from the root project
```

### Expected behavior

No dependency conflict

### Steps to reproduce the issue

```
$ npm create vite@latest
$ cd project
$ npm i
$ npm install @mui/material @mui/styled-engine-sc styled-components
$ npm install @mui/icons-material
$ npm i @jsonforms/core @jsonforms/react @jsonforms/material-renderers
```

### In which browser are you experiencing the issue?

-

### Which Version of JSON Forms are you using?

latest

### Framework

React

### RendererSet

Material

### Additional context

I tried to install the packages with --force flag and it seems to work fine.

Link to repo: https://github.com/devbydaniel/jsonforms-mui-deps

**Comment by lucas-koehler** [comment]
Hello @devbydaniel ,
thank  you for your report! In the past we had issues with MUI having breaking changes even between minor versions (e.g. 5.11 and 5.12). Therefore, we restricted the dependencies to changes in the patch version.
However, that inconveniences adopters like you discovered. It might be necessary to reconsider this appraoch. I'll discuss with the team whether we want to switch back to restricting to the minor version only.

**Comment by lucas-koehler** [comment]
Hello @devbydaniel,
I discussed with the team and we are open to adapt the dependencies to allow minor versions again, i.e. switching from ranges like `~5.11.16` to `^5.11.16`. With that all newer 5.x versions would also be allowed.
Would you like to contribute this?

**Comment by devbydaniel** [comment]
Hi @lucas-koehler , thanks for the quick response! [I just created a PR](https://github.com/eclipsesource/jsonforms/pull/2218) which doesn't seem to be working, I left a comment with more info there.

**Comment by sdirix** [comment]
Closed with https://github.com/eclipsesource/jsonforms/pull/2218
