### ISSUE TITLE
 NG0300: Multiple components match node with tagname button: MatLegacyButton and MatButton error

### ISSUE THREAD

**Issue by nilam-jadhav** [eclipsesource/jsonforms#2233]
### Describe the bug

I am using below JSON form package:
    "@jsonforms/angular": "^3.0.0",
    "@jsonforms/angular-material": "^3.0.0",
    "@jsonforms/core": "^3.0.0",
 Ans recently upgraded to Angular V15 where using legacy material component, after upgrading to V15 from, getting below error:

core.mjs:8400  ERROR Error: NG0300: Multiple components match node with tagname button: MatLegacyButton and MatButton. Find more at https://angular.io/errors/NG0300

Tried with v3.1.0 still issue persists.

After commenting JsonFormsAngularMaterialModule import, issue doesnt persist, but i need this import in my application so how to get rid of this error
can you help me to resolve this issue?

### Expected behavior

Thre should not be any error

### In which browser are you experiencing the issue?

Every

### Which Version of JSON Forms are you using?

v3.0.0

### Framework

Core, Angular

### RendererSet

Material

**Comment by lucas-koehler** [comment]
Hi @nilam-jadhav ,
JsonForms 3.0.0 and 3.1.0 are not compatible with Angular 15+.
You can try pre-release version `[3.2.0-alpha.4](https://www.npmjs.com/package/@jsonforms/core/v/3.2.0-alpha.4)`. This includes support for Angular 15.
I'll close this issue. You can re-open it if you continue having problems.

**Comment by sdirix** [comment]
We will [update to Angular 16/17 very soon](https://github.com/eclipsesource/jsonforms/pull/2229) and therefore will no longer be compatible with Angular 15.

**Comment by nilam-jadhav** [comment]
Even after upgrading to mentioned version same issue is coming.

**Comment by nilam-jadhav** [comment]
@lucas-koehler I am not able to reopen this issue, can you please reopen? or Do I have to open new issue and link this one?

**Comment by lucas-koehler** [comment]
Hi @nilam-jadhav , sure. Just to be clear, when using a later Angular version, did you also use the latest pre-release version `3.2.0-beta.0` when re-testing this?

**Comment by nilam-jadhav** [comment]
Hi @lucas-koehler 
I am using Angular 15 with angular-material legacy component, and tried upgrading to version 3.2.0-beta.0 after your comment , now build is failing:
![image](https://github.com/eclipsesource/jsonforms/assets/134496412/4cf528c9-6c57-42c8-9021-daa7d7dc99e4)

**Comment by lucas-koehler** [comment]
Hi @nilam-jadhav , after moving to `3.2.0-beta.0`, did you also upgrade to Angular 16? Angular 15 does not work anymore with this.

**Comment by nilam-jadhav** [comment]
@lucas-koehler No, I haven't upgraded to Angular 16, its Angular 15 with 3.2.0-beta.0

**Comment by nilam-jadhav** [comment]
@lucas-koehler  Any update?

**Comment by lucas-koehler** [comment]
@nilam-jadhav No, did you try it with Angular 16 and get the same result? It is not expected to work with Angular 15

**Comment by lucas-koehler** [comment]
Closing this as it does not concern the current version. If there are any more questions, feel free to ask in the [community forum](https://jsonforms.discourse.group/) :)
