### ISSUE TITLE
3.2 Release

### ISSUE THREAD

**Issue by sdirix** [eclipsesource/jsonforms#2245]
- [x] Create Changelog
 - [x] Update all seed applications to latest beta
   - [x] [React](https://github.com/eclipsesource/jsonforms-react-seed) @LukasBoll Reviewer: @lucas-koehler 
   - [x] [Angular](https://github.com/eclipsesource/jsonforms-angular-seed/pull/76) @LukasBoll Reviewer: @lucas-koehler 
   - [x] [Vue](https://github.com/eclipsesource/jsonforms-vue-seed/pull/19) @LukasBoll Reviewer: @sdirix 
   - [x] [Vue2](https://github.com/eclipsesource/jsonforms-vue-seed/tree/vue2) @LukasBoll Reviewer: @sdirix 
 - [x] Release JSON Forms 3.2
 - [x] Update all seed applications to released version
   - [x] React
   - [x] Angular
   - [x] Vue
 - [x] Update website with JSON Forms 3.2 and Api Docs
 - [ ] ~Review/Merge open Website PRs~
 - [x] Announce release and Website

**Comment by gexclaude** [comment]
Is there an estimated release date for 3.2?

**Comment by sdirix** [comment]
Hi @gexclaude, We plan to release very soon, i.e. this week

**Comment by sdirix** [comment]
Hi @gexclaude, we released today. Version `3.2.0` is now officially available

**Comment by gexclaude** [comment]
thank you @sdirix
