### ISSUE TITLE
Uncaught RangeError: Maximum call stack size exceeded when oneOf contains a very large number of items

### ISSUE THREAD

**Issue by alxdru** [eclipsesource/jsonforms#2271]
### Describe the bug

When trying to load a schema with a oneOf field specifying a list of over 300 items (approximately) and validation mode: ValidateAndShow, it fails to render the form with the following errors:

> Uncaught RangeError: Maximum call stack size exceeded
> RangeError: Maximum call stack size exceeded

### Expected behavior

In this case I am expecting it to be able to render a list of 500 items at least including validations without issues.

### Steps to reproduce the issue

Use a json schema with a oneOf that specifies 500 items to make sure you reproduce.
Something like below

```
{
    "type": "object",
    "properties": {
        "field": {
            "title": "Destination",
            "type": "string",
            "oneOf": [] // Can specify 500 items to reproduce the issue
        },
 }
}
```

### Which Version of JSON Forms are you using?

v3.1.0

### Additional context

I could successfully render with less than 300 items in the `oneOf` field, or just by disabling the validation which is not an option unfortunately.
I've also traced some similar issues in the ajv library that handles validation here https://github.com/ajv-validator/ajv/issues/1581#issuecomment-835774241 . Note that I've tried the proposed resolutions at the link and they do not work in this case.

**Comment by Alexandru11** [comment]
@sdirix Thanks for the quick response.
While those are very good workarounds, as part of the explanation I should've added that the forms are always dynamic and there's no control over the schema definition being used. I can't control how many `oneOf` constructs the forms would have.

Just to put it out there, if it helps anybody else. I've tried to bypass the issue by using `$ref` and dividing the long `oneOf` list into multiple smaller size ones. It did render the form with validations in this case. Although, the UX of the form changes by having a couple of tabs to choose from for that particular dropdown.

**Comment by sdirix** [comment]
> While those are very good workarounds, as part of the explanation I should've added that the forms are always dynamic and there's no control over the schema definition being used. I can't control how many oneOf constructs the forms would have

You can use the second workaround I posted and just always activate it whenever there is a oneOf with more than X entries in your retrieved schema. There really is no downside to that workaround besides the loss of validation for the oneOf. That validation is almost always meaningless anyway as the UI already makes sure that only a valid value is stored in the form data.

**Comment by alxdru** [comment]
@sdirix 
Hi Stefan,
Just coming back with updates, the workaround you proposed is a good solution.
We're only losing validation for the oneOfs that are too long, but it doesn't feel like a big lose.
Thank you!
