### ISSUE TITLE
React Material Date control breaks once "Clear" is pressed

### ISSUE THREAD

**Issue by lukasf** [eclipsesource/jsonforms#2278]
### Describe the bug

Once you clear out the value of a date control, the control becomes completely unusable. The date picker does not come up at all.

### Expected behavior

When clicking into the date control after its value was cleared, the date picker should come up.

### Steps to reproduce the issue

1. Open the "Control" example
2. Click on the date to open the picker
3. Click "Clear"
4. Now click on the control again. Picker does not come up, no matter what you do.

### Which Version of JSON Forms are you using?

v3.2.0

### Framework

React

### RendererSet

Material

### Additional context

This did not occur in 3.1.0.

**Comment by sdirix** [comment]
Hi @lukasf,

Thanks for the report! It seems we broke the control with the improvements we did for https://github.com/eclipsesource/jsonforms/issues/2183.

**Comment by sdirix** [comment]
@LukasBoll Can you take a look?
