### ISSUE TITLE
Using jsonforms/react with scss

### ISSUE THREAD

**Issue by Marco-Ca** [eclipsesource/jsonforms#2282]
### Is your feature request related to a problem? Please describe.

Hello, firstly, I would like to know if jsonforms works with css preprocessor (couldnt find it in docs)? We use scss in our project and it would be nice to have the support for it. Additionally, it would also help to add the feature to add `class/classNames` to custom elements (see suggested solution)

### Describe the solution you'd like

```
{
  "type": "HorizontalLayout",
    "elements": [
      {
        "type": "Control",
        "scope": "#/properties/due_date",
        "options":  {
          "format": "date",
          "classNames: ['customClass', 'anotherCustomClass']
        }
      }
```

### Describe alternatives you've considered

Tried using `custom renderers` but it does not work in our use case as we generate `uischema` and `schema` on the constantly and dynamically

### Framework

Core, React

### RendererSet

Material, Other (please specify in the Additional context field)

**Comment by sdirix** [comment]
Hi!

Adding additional classes via UI Schema is currently only supported out of the box in the Vue Vanilla renderers. In the React Vanilla renderers the form-wide classes can be configured, but not not for specific controls.

> Tried using custom renderers but it does not work in our use case as we generate uischema and schema on the constantly and dynamically

Custom renderers and their testers are fully generic, so they can be used to solve any use case. At minimum, you can add the custom class support via custom renderers, leveraging the approach you would like to see.

Please describe your use cases in more detail if you want more detailed advice.
