### ISSUE TITLE
React MUI inputs are disabled instead of readonly

### ISSUE THREAD

**Issue by Maxouwell** [eclipsesource/jsonforms#2283]
### Describe the bug

Hello,

On the [MUI page for the TextInput](https://mui.com/material-ui/react-text-field/#form-props), MUI define two different UI for disabled and read only inputs.

On JsonForms, when a field has a readonly option in the UI Schema, it renders in the material renderer as a disabled field.
Is that voluntary ?

### Expected behavior

The field should have been a readonly field.

### Steps to reproduce the issue

Put a readonly option on a field in the UI Schema.

### Which Version of JSON Forms are you using?

v3.2.1

### Framework

React

### RendererSet

Material

**Comment by sdirix** [comment]
Hi @Maxouwell,
Yes we render "disabled" on purpose as the "readOnly" field looks like it accepts inputs but doesn't, leading to confusion. To adapt this you can use custom renderers.

**Comment by akademy** [comment]
I don't believe it should be the job of JsonForms to change readonly to mean disabled. This should be the decision of which ever designer is using them. The OP already highlights that this is confusing, (MUI shows things very differently.)

Plus. by default, browsers make anything disabled less easier to view, this is a real world problem for some individuals who need better contrast. And furthermore, screen readers treat readonly and disabled very differntly.

Can we have a setting somewhere that makes "readonly" actually set fields to readonly? I realise the existing "readonly" setting is far to well established in it's currently confusing setting, but it should be possible to add another setting?

**Comment by sdirix** [comment]
It's just the choice within our "off-the-shelf" renderer sets. You can customize the existing renderer sets via custom renderers and/or implement an own renderer set. In it, `readonly` can be interpreted in any way you like.

**Comment by sarathkcm** [comment]
Thank you for the awesome library.

I was wondering why JSON forms is converting a custom textbox renderer to disabled when the readonly flag is set and stumbled on this issue.


> It's just the choice within our "off-the-shelf" renderer sets. You can customize the existing renderer sets via custom renderers and/or implement an own renderer set. In it, `readonly` can be interpreted in any way you like.

It seems that the core runtime is converting readonly to enabled/disabled and not the renderer sets, so it's not possible to override this from renderer sets reliably.

https://github.com/eclipsesource/jsonforms/issues/1735#issuecomment-856632817
https://github.com/eclipsesource/jsonforms/blob/master/packages/core/src/mappers/util.ts#L24

Are there any ways to override this behaviour, so that it can be handled by the renderer instead?

PS: sorry for piggybacking on a closed issue, it was easier to set the context here.

**Comment by lucas-koehler** [comment]
> It seems that the core runtime is converting readonly to enabled/disabled and not the renderer sets, so it's not possible to override this from renderer sets reliably.

> https://github.com/eclipsesource/jsonforms/issues/1735#issuecomment-856632817
https://github.com/eclipsesource/jsonforms/blob/master/packages/core/src/mappers/util.ts#L24

Hi @sarathkcm , that is a good point! I can appreciate that it was easier here but could you please open a separate feature request issue for this? This makes it easier to discuss and for other to find the discussion/resolution. Thanks!

**Comment by sarathkcm** [comment]
Thanks for the response @lucas-koehler . I've raised a feature request as you suggested here: https://github.com/eclipsesource/jsonforms/issues/2479
