### ISSUE TITLE
React MUI Array delete button should have a tooltip

### ISSUE THREAD

**Issue by Maxouwell** [eclipsesource/jsonforms#2284]
### Is your feature request related to a problem? Please describe.

On the MUI array layout, the delete button does not have a tooltip, while the add button have one.

### Describe the solution you'd like

The delete button should have a tooltip.

### Describe alternatives you've considered

Rewrite the array renderer 😢 

### Framework

React

### RendererSet

Material

**Comment by lucas-koehler** [comment]
Hi @Maxouwell , thanks for raising this issue. It's definitely not intended that only the delete button misses the tooltip. Would you like to contribute a fix?

**Comment by Maxouwell** [comment]
Done !
I added one for up and down button as well

**Comment by linxxx1000** [comment]
Can we change the  delete tooltip text and title? Now it is default as "Confirm Deletion" and "Are you sure you want to delete the selected entry?"

**Comment by linxxx1000** [comment]
@lucas-koehler @Maxouwell

**Comment by lucas-koehler** [comment]
Hi @linxxx1000 , you can change the tooltip text and title via [JsonForms i18n functionality](https://jsonforms.io/docs/i18n#enum-translation). For this, you need to hand in a custom `translate` function into JsonForms. The function could look similar to the one in the arrayI18n example. See: https://github.com/eclipsesource/jsonforms/blob/d7f34b98d9091fa29bc61178b33b96ae2cbd8519/packages/examples/src/examples/arraysI18n.ts#L81-L93


As indicated in the code snippet from the example, you can get the i18n keys to override from `ArrayTranslationEnum` of the `@jsonforms/core` package.

Also note that the [community forum](https://jsonforms.discourse.group/) is the preferred way to ask questions. Thanks!
