### ISSUE TITLE
React MUI Array Layout as a 'No Data' hardcoded

### ISSUE THREAD

**Issue by Maxouwell** [eclipsesource/jsonforms#2285]
### Describe the bug

In [MaterialArrayLayout.tsx](https://github.com/eclipsesource/jsonforms/blob/072caa5d0140584e7d563b73cf07a2acf8d2f817/packages/material-renderers/src/layouts/MaterialArrayLayout.tsx#L115) there is a hardcoded 'No data' text that can't be internationalized. 

### Expected behavior

The text should be translable.

### Steps to reproduce the issue

N/A

### Which Version of JSON Forms are you using?

v3.2.1

### Framework

React

### RendererSet

Material

**Comment by lucas-koehler** [comment]
Fixed via #2286
