### ISSUE TITLE
jsonforms is not allowing null value for a key

### ISSUE THREAD

**Issue by MUJAHIDoo7** [eclipsesource/jsonforms#2302]
### Describe the bug

I have created a schema and the default that i have to set is null, but when im doing it, the jsonforms is giving me error by saying "must be string":
 `{
“instancePath”: “/header_content”,
“schemaPath”: “#/properties/header_content/type”,
“keyword”: “type”,
“params”: {
“type”: “string”
},
“message”: “must be string”,
“schema”: “string”,
“parentSchema”: {
“type”: “string”
},
“data”: null
}`

I even tried giving the type as `"type": ["string", "null"]` but still no luck
Im using jsonform v3.1.0 and im using this for validation `const handleDefaultsAjv = createAjv({ allErrors: false})`

### Expected behavior

I want it to somehow allow null value also

### Steps to reproduce the issue

Simply created the jsonforms

### Which Version of JSON Forms are you using?

v3.1.0

### Framework

React

### RendererSet

Material

**Comment by MUJAHIDoo7** [comment]
@sdirix @lucas-koehler Could you guys please help

**Comment by sdirix** [comment]
Hi @MUJAHIDoo7,

Please do not repeat messages between the JSON Forms issue tracker and the forum.

JSON Forms' error analysis is delegated to AJV and is purely JSON Schema related. So any validation error you encounter is a mismatch between the JSON Schema you are using and the data you are handing over. See [here for my answer in the forum with more details](https://jsonforms.discourse.group/t/how-to-allow-null-value-to-a-key-in-jsonforms/2019/4?u=sdirix).

Also you should not set `allErrors: false` as then the form will no longer show all errors.
