### ISSUE TITLE
default value set is not working in angular 

### ISSUE THREAD

**Issue by Priyadarsini-techriff** [eclipsesource/jsonforms#2305]
### Describe the bug

I have gender field which is radio button with value Male and Female.i Want to set default value of gender is Female.
 gender: {
        type: 'string',
        enum: ['Male', 'Female'],
        default: 'Female',
      }this is my schema value.But it didnot working.

### Expected behavior

By default I want to set gender value  is male.

### Which Version of JSON Forms are you using?

3.2.1

### Framework

Angular

### RendererSet

Material

**Comment by sdirix** [comment]
Hi @Priyadarsini-techriff,

please see the documentation "[How can I use default values within JSON Forms?](https://jsonforms.io/faq#how-can-i-use-default-values-within-json-forms)".

Note that we also have a community forum for questions, see [here](https://jsonforms.discourse.group/).
