### ISSUE TITLE
Cannot clear field with default value

### ISSUE THREAD

**Issue by lmestel** [eclipsesource/jsonforms#2306]
### Describe the bug

If there is a default value in the schema and ajv is configured with `useDefaults: true`, there is no way to clear the input field to set the value to an empty string.  
After the last character has been deleted, the input field is immediately filled with the default value again.

### Expected behavior

The input field can be cleared to get an empty string in the data.

### Steps to reproduce the issue

1. Go to https://codepen.io/lmestel/pen/QWPMMjR
2. Try to clear the input fields
3. After the last character has been deleted, the input field is immediately filled again with the default value

### Which Version of JSON Forms are you using?

3.2.1

### Additional context

https://github.com/eclipsesource/jsonforms/issues/1983
https://github.com/eclipsesource/jsonforms/pull/1984

**Comment by sdirix** [comment]
Hi @lmestel,

You can solve this on your side via a custom string renderer which places an empty string in the data. We previously had this as the default behavior but it seems the majority prefers `undefined`.

Alternatively if a one-time generation of default values is sufficient for you, you could invoke AJV once outside of JSON Forms to fill your data object.

**Comment by lmestel** [comment]
Thank you!

I ended up doing both. I use AJV to initialize the data with default values and a custom renderer to be able to empty the fields.
