### ISSUE TITLE
Jsonforms Map Render Support in React

### ISSUE THREAD

**Issue by mahmutbilir** [eclipsesource/jsonforms#2310]
### Describe the bug

Hi,
Below, I expect the following schema to create a form in React in a key-value format, so I expect it to support mapping, but React render doesn't seem to support it. Am I missing something?
{
  "type": "object",
  "properties": {
    "Addresses": {
      "type": "object",
      "additionalProperties": {
        "type": "string"
      }
    }
  }
}
Thanks.

### Expected behavior

I expect support for mapping, so I expect a form in key-value format with an addable new items feature.

### Screenshots

![image](https://github.com/eclipsesource/jsonforms/assets/5039461/36fe3553-c4e6-4016-8182-c2cd2cc8afb5)

### Which Version of JSON Forms are you using?

V3.2.1

### Framework

React

### RendererSet

Material

**Comment by lucas-koehler** [comment]
Hi @mahmutbilir , thanks for reaching out. You are not missing anything. There is no key-value renderer to add new properties. There is currently no plan on our side to implement this. Would you like to contribute an implementation?

**Comment by mahmutbilir** [comment]
Thank you @lucas-koehler ,
If we can solve this problem with a custom renderer, there would be no need for me to develop it.
Do you normally recommend solving such a need with a custom renderer?

**Comment by lucas-koehler** [comment]
Hi @mahmutbilir , yes for more specialized needs we generally recommend implementing a [custom renderer](https://jsonforms.io/docs/tutorial/custom-renderers). I don't see a reason why this shouldn't be possible in this case :)
Also note that for general questions, we also have a discussion board at https://jsonforms.discourse.group/
