### ISSUE TITLE
UI broken in the Documentation

### ISSUE THREAD

**Issue by Pavan-Rajesh** [eclipsesource/jsonforms#2313]
### Describe the bug

There is an overflow of the rendered ui in the website

### Expected behavior

It should be responsive or the overflow must be scrolled
![jsonschemapull](https://github.com/eclipsesource/jsonforms/assets/90332218/b74b775d-2295-4c9f-8402-1b0e49c20c3f)

### Steps to reproduce the issue

1. Go to '.[.](https://jsonforms.io/docs/uischema/controls).'
3. Scroll down to 'Label for array elements'

### Screenshots

![jsonschemapull](https://github.com/eclipsesource/jsonforms/assets/90332218/063c9a59-917f-433e-838c-5ce05b59508c)

### Which Version of JSON Forms are you using?

latest

**Comment by sdirix** [comment]
Hi @Pavan-Rajesh, thanks for the report! The website repository can be found [here](https://github.com/eclipsesource/jsonforms2-website), in case you, or someone else, wants to contribute a fix.

**Comment by Pavan-Rajesh** [comment]
Hi @sdirix  I sended a pull request  can be reviewed here [Pull Request](https://github.com/eclipsesource/jsonforms2-website/pull/293)
