### ISSUE TITLE
Typescript types not exported

### ISSUE THREAD

**Issue by dwrBad** [eclipsesource/jsonforms#2316]
### Describe the bug

Types are not exported, the ![screenshot](https://github.com/eclipsesource/jsonforms/assets/65392306/26a66659-1415-4739-b56c-6926e920dbdd) shows that all the folders are empty, though I would expect these [types](https://github.com/eclipsesource/jsonforms/blob/master/packages/core/src/models/uischema.ts) to be present.

### Expected behavior

`import type { UISchemaElement } from "@jsonforms/core";` should give exported types

### Steps to reproduce the issue

Install @jsonforms/core as dependency, use `import type { UISchemaElement } from "@jsonforms/core";` in a TS file.

### Which Version of JSON Forms are you using?

3.2.1

### Framework

Core, React

### RendererSet

Other (please specify in the Additional context field)

**Comment by sdirix** [comment]
Hi @dwrBad,

Using unpkg, it seems that the typings are in fact there, see for example https://www.unpkg.com/browse/@jsonforms/core@3.2.1/lib/models/

![image](https://github.com/eclipsesource/jsonforms/assets/8998368/e681e2dd-fc6f-47ac-a30a-ddfd746d0e36)

I would like to recommend clearing the `node_modules` and setting them up again.

**Comment by dwrBad** [comment]
Thank you for looking into it. I will check again why they were not present!
