### ISSUE TITLE
ArrayLayoutRenderer was not found in '@jsonforms/angular-material'

### ISSUE THREAD

**Issue by Bryelmo** [eclipsesource/jsonforms#2319]
### Describe the bug

If I try to create a custom renderer that extends the ArrayLayoutRenderer and I build the angular library I receive this error

`export 'ArrayLayoutRenderer' (imported as 'ArrayLayoutRenderer') was not found in '@jsonforms/angular-material' (possible exports: AutocompleteControlRenderer, BooleanControlRenderer, CategorizationTabLayoutRenderer, DateControlRenderer, DateControlRendererTester, GroupLayoutRenderer, HorizontalLayoutRenderer, JsonFormsAngularMaterialModule, JsonFormsDetailComponent, LabelRenderer, LabelRendererTester, LayoutChildrenRenderPropsPipe, LayoutRenderer, MasterListComponent, NumberControlRenderer, NumberControlRendererTester, ObjectControlRenderer, ObjectControlRendererTester, RangeControlRenderer, RangeControlRendererTester, TableRenderer, TableRendererTester, TextAreaRenderer, TextAreaRendererTester, TextControlRenderer, TextControlRendererTester, ToggleControlRenderer, ToggleControlRendererTester, VerticalLayoutRenderer, angularMaterialRenderers, booleanControlTester, categorizationTester, controlWithoutLabel, enumControlTester, groupLayoutTester, horizontalLayoutTester, masterDetailTester, removeSchemaKeywords, verticalLayoutTester)`

### Expected behavior

I think shoud be possible extend the Array class renderer 

### Steps to reproduce the issue

1. Create a new custom renderer
2. add import { ArrayLayoutRenderer } from '@jsonforms/angular-material/src/library/layouts/array-layout.renderer';
3. Complete the custom renderer
4. Build the angular library

### Which Version of JSON Forms are you using?

v3.2.0

### Framework

Angular

### RendererSet

Other (please specify in the Additional context field)

### Additional context

I'm creating renderers based on PrimeNg and in this specific case I need to extend the Array renderer

**Comment by lucas-koehler** [comment]
Hi @Bryelmo , thanks for the report :)
I had a look and indeed the export is missing in the code. I opened a small PR to fix this (#2320)

**Comment by lucas-koehler** [comment]
Hi @Bryelmo , one other thing I noticed in your issue description is that you import the ArrayLayoutRenderer from the `src` folder with
```ts
import { ArrayLayoutRenderer } from '@jsonforms/angular-material/src/library/layouts/array-layout.renderer';
```

Instead, if you want to do a deep import, you should import from the lib folder that contains the transpiled JS code.
Maybe the following works until the fix in the PR is merged:

```ts
import { ArrayLayoutRenderer } from '@jsonforms/angular-material/lib/esm2022/library/layouts/array-layout.renderer';
```

**Comment by Bryelmo** [comment]
Hi @lucas-koehler ,
thanks for your response. 
I already tried importing from the lib folder but it does not work, i receive this error.
`Error: Cannot find module '@jsonforms/angular-material/lib/library/layouts/array-layout.renderer'`

**Comment by lucas-koehler** [comment]
Hi @Bryelmo ,
did you also try importing from the **esm2022** folder in lib? This contains the code but no typings.

import { ArrayLayoutRenderer } from '@jsonforms/angular-material/lib/**esm2022**/library/layouts/array-layout.renderer';

**Comment by Bryelmo** [comment]
Hi @lucas-koehler,
yes I tried but I got the same error:
`Error: Cannot find module`

**Comment by lucas-koehler** [comment]
@Bryelmo In the latest pre-release version [3.3.0-alpha.1](https://www.npmjs.com/package/@jsonforms/angular-material/v/3.3.0-alpha.1), the angular material package should now export the renderer
