### ISSUE TITLE
Data not be modify

### ISSUE THREAD

**Issue by vvalette** [eclipsesource/jsonforms#2322]
### Describe the bug

Hello, 

I use json form on angular, I can import existing json to fill my form (work very well). After that, I want to modify this data and export the new version of my json_data but the data seems not modified anyway.

Could you help me. Are there a bug that not update data when you modifie the form ? Because when I juste fill the forms without import it's not working as well.

Best regards.

### Expected behavior

I use json form on angular, I can import existing json to fill my form (work very well). After that, I want to modify this data and export the new version of my json_data and have the new version of the data varriable

### Which Version of JSON Forms are you using?

v3.0.0

### Framework

Angular

### RendererSet

Material

**Comment by sdirix** [comment]
Hi @vvalette, this seems more like a question than a bug. Please use our [discussion board](https://jsonforms.discourse.group) for questions.

In Angular, data changes are emitted by the `dataChange @Output`, see [here](https://github.com/eclipsesource/jsonforms/blob/c0549f2f55aa94a032ba4ea120d55751c0f19b04/packages/angular/src/library/jsonforms-root.component.ts#L62). If you bind against this you should always have the latest data in hand.

**Comment by vvalette** [comment]
Ok thanks a lot, it works very well with dataChange ! 

Best regards
