### ISSUE TITLE
Errors duplication while validating

### ISSUE THREAD

**Issue by sapuz1508** [eclipsesource/jsonforms#2324]
### Describe the bug

While writing in a simple input, when the validation occurs, the (eventual) error message appears to be duplicated.

![image-2](https://github.com/eclipsesource/jsonforms/assets/21139633/b41aec42-8f24-4011-a9f8-1e7a3add8e98)

### Expected behavior

There shouldn't be any changes on how the components behaves, but the error message should appear only 1 time

### Steps to reproduce the issue

1. Select field
2. Update field with value > 10
3. See duplicated error

### Screenshots

![image-2](https://github.com/eclipsesource/jsonforms/assets/21139633/105e847e-16a4-4c3e-9e50-adafa9eef45e)

### Which Version of JSON Forms are you using?

3.1.1

### Framework

Vue

### RendererSet

Other (please specify in the Additional context field)

### Additional context

It's mostly the vanilla renderer set with custom styling

**Comment by LukasBoll** [comment]
Hello @sapuz1508 ,
thank you for the report. Unfortunately, I wasn't able to reproduce the issue on version 3.1.1.
Can you provide additional information about the schema or a minimal example to reproduce the issue?

**Comment by lucas-koehler** [comment]
Closing this as it could not be reproduced. Feel free to reopen this if it is still reproducible with the latest 3.3 version @sapuz1508
