### ISSUE TITLE
The delete button should be displayed only when an item is hovered and hidden

### ISSUE THREAD

**Issue by stanisev** [eclipsesource/jsonforms#2327]
### Describe the bug

The delete button should be displayed only when an item is hovered and hidden (via the hide class) by default which was removed In one of the previous MRs

### Expected behavior

We should add back removed `hint` css class

### Steps to reproduce the issue

Use master details renderer. All elements of the master details will have the delete button (delete button should be displayed only on hover)

### Which Version of JSON Forms are you using?

v3.2.1

### Framework

Angular

### RendererSet

Other (please specify in the Additional context field)

**Comment by JBBianchi** [comment]
Little typo ~`hint`~ _`hide`_ 

Discussed in https://github.com/eclipsesource/jsonforms/pull/2229#discussion_r1583038946
