### ISSUE TITLE
Support @mui/x-date-pickers v7

### ISSUE THREAD

**Issue by larsmunkholm** [eclipsesource/jsonforms#2328]
### Is your feature request related to a problem? Please describe.

I'm using the newest version of MUI X, and I'm getting the warning below:

 WARN  Issues with peer dependencies found
libs/core-react
└─┬ @jsonforms/material-renderers 3.2.1
  └── ✕ unmet peer @mui/x-date-pickers@^6.0.0: found 7.3.1

### Describe the solution you'd like

Support for MUI X v7

### Describe alternatives you've considered

At the moment I am ignoring the warning, and I haven't experienced any issues yet.

### Framework

React

### RendererSet

Material

**Comment by lucas-koehler** [comment]
Hi @larsmunkholm , thanks for raising this issue.
We are in favor of supporting latest versions of peer dependencies. If you want to contribute a PR or just report on your ongoing experience with using the latest version, that would be invaluable.

For reference. This is the migration guide for anyone tackling the issue: https://mui.com/x/migration/migration-pickers-v6/.
There seem to be a few breaking changes, so just raising the peer dependency seems a little risky.
