### ISSUE TITLE
JSON Schema with special characters like "." in the key not rendering properly

### ISSUE THREAD

**Issue by pjeschba** [eclipsesource/jsonforms#2335]
### Describe the bug

I'm not able to properly render data stored inside a json schema key with a special character like a period. I'm using JSONForms.io and React and have tried both the stock material/vanilla renderers and writing my own custom renderer, but when the data is nested within a key like `123.123` it is not properly piped into the ControlProps for access by my custom renderer. Unless there is some way to escape special characters that I am missing this feels like a bug.

### Expected behavior

JSON Keys containing periods should properly render in JSON Forms in react. 

### Steps to reproduce the issue

1. Build a json blob that has keys containing periods
2. Try to render that data using JSONForms in React
3. Observe that it does not work

### Which Version of JSON Forms are you using?

3

**Comment by lucas-koehler** [comment]
Hi @pjeschba , thanks for raising this issue :)
This is a known bug that is captured and will be solved here: https://github.com/eclipsesource/jsonforms/issues/2153
Thus, I'll close this as a duplicate.
