### ISSUE TITLE
Add Angular 18 support

### ISSUE THREAD

**Issue by laurentgrangier** [eclipsesource/jsonforms#2336]
### Is your feature request related to a problem? Please describe.

Angular 18 will be released in the week of 20.05.2024 (https://angular.io/guide/releases). The library should supports the new version.

### Describe the solution you'd like

Support for Angular 18.

### Describe alternatives you've considered

No alternative.

### Framework

Angular

**Comment by laurentgrangier** [comment]
I'm already working to add support for Angular 18. Here is my first findings:
- Angular 18 needs Typescript 5.2.x. Typescript should be updated to all modules. Support for Angular 16 must be dropped because it needs Typescript >=4.9.3 <5.1.0.
- zone.js must be updated to 0.14.0.

**Comment by laurentgrangier** [comment]
When running test for angular-material, I get lot of the following error: 

`        Error: NG0402: A required Injectable was not found in the dependency injection tree. If you are bootstrapping an NgModule, make sure that the `BrowserModule` is imported.      
        error properties: Object({ code: 402 })
`

If I move the code from angular-test to angular-material directly, the tests run. I wonder why the angular-test package is needed, since it is only used from angular-material. Should we not simply move all the code from angular-test to angular-material?

@JBBianchi Since you did the previous Angular upgrade. Maybe you can help here?

**Comment by JBBianchi** [comment]
I must admit I didn't understand either what was the use of having a specific module angular-test if it's only use in one other module anyways. I don't have a lot of time currently but I can try to have a look in the next weeks.

**Comment by sdirix** [comment]
Hi! Thanks for raising this issue and proactively working on it :+1: 

The Angular test package is only there for historic reasons, I don't see a problem with removing it if it makes the overall task easier.
