### ISSUE TITLE
@mui/icons-material imports balloon bundle sizes

### ISSUE THREAD

**Issue by semery-fractalev** [eclipsesource/jsonforms#2350]
### Describe the bug

In https://github.com/eclipsesource/jsonforms/commit/c8d3ecf2255e537e3e3eaefe4e977273c72db572, the way material-icons were imported was changed (purportedly to deal with typescript incompatibilities). However, this causes the entire module to be imported on build, not just the few icons that are required.

If/when possible, the imports should switch back to "Option 1" described here: https://mui.com/material-ui/icons/#usage

### Expected behavior

When using the material-renderers bundle size is not adversely affected by imports.

### Steps to reproduce the issue

1. Upgrade the versions of the below from 3.1.0 to 3.3.0
```json
"@jsonforms/core": "^3.3.0",
"@jsonforms/material-renderers": "^3.3.0",
"@jsonforms/react": "^3.3.0",
```
2. Notice a large increase in bundle size and compile time

### Which Version of JSON Forms are you using?

v3.3.0

### Framework

React

### RendererSet

Material

**Comment by sdirix** [comment]
@semery-fractalev,

Thanks for the report. You are right, we should switch back to option 1. Do you want to contribute this improvement?
