### ISSUE TITLE
Support MUI X `DateRange` and `DateTimeRange` components

### ISSUE THREAD

**Issue by TheOneTheOnlyJJ** [eclipsesource/jsonforms#2353]
### Is your feature request related to a problem? Please describe.

I would like to have the user select date & date-time ranges. My use case involves highly dynamic JSON and UI schemes, so I cannot add middleware to check if the starting date is less or equal to the end date (and time). Integrating the MUI X range components would allow range validation to happen without requiring custom middleware and would make for a very beautiful UI.

### Describe the solution you'd like

A way to integrate the new `DateRange` and `DateTimeRange` pickers from MUI X in places where the form consists of an object with 2 date/date-time attributes. I see this as possible mainly through the UI schema. Widget customisation should also be supported, as is the case with other components.

### Describe alternatives you've considered

I've looked for alternatives but haven't found any. The best user experience would be ensured by integrating these widgets.

### Framework

React

### RendererSet

Material

**Comment by lucas-koehler** [comment]
Hi @TheOneTheOnlyJJ , thank you for the suggestion.
Looking at the documentation of the date range and date time range pickers, these are MUI X Pro components. Thus, these require a payed subscription. Thus, we cannot add renderers using these.
If you can use them despite this, I suggest implementing a custom renderer for an object of 2 dates/date-times like you suggested.

If you have further questions, also take a look at our [community forum](https://jsonforms.discourse.group/).
