### ISSUE TITLE
Zero value not supported in type=number Vue controls

### ISSUE THREAD

**Issue by benjivm** [eclipsesource/jsonforms#2361]
### Describe the bug

Possibly same issue as https://github.com/eclipsesource/jsonforms/issues/1351 https://github.com/eclipsesource/jsonforms/issues/1352

### Expected behavior

Render/accept zero values.

### Steps to reproduce the issue

```json
{
    "properties": {
        "number": {
            "type": "number"
        }
    }
}
```

### Which Version of JSON Forms are you using?

v3.3.0

### Framework

Vue

### RendererSet

Vanilla

**Comment by lucas-koehler** [comment]
Hi @benjivm , thanks for the report :) Can you give more details when this exactly happens? I.e. only when you enter a new number of if it is already present?
I ask because I cannot reproduce this problem for the vue vanilla renderers in the example app.

**Comment by benjivm** [comment]
You're right, this is a problem in my code: there was an "isEqual" comparison erroneously treating 0 as null. Thanks!
