### ISSUE TITLE
vue-vanilla - postfix of id of select element should be '-input' not '-select'

### ISSUE THREAD

**Issue by changjung-kim** [eclipsesource/jsonforms#2363]
### Describe the bug

postfix of id of label id for enum type is set to '-select' though the label's for is expecting the postfix '-input' due to 
the code https://github.com/eclipsesource/jsonforms/blob/d3ee13a059ff9e0bc6dc9282b8f0ca65b799f5e6/packages/vue-vanilla/src/controls/EnumControlRenderer.vue#L9 .

### Expected behavior

postfix of id of select element should be '-input'.

### Which Version of JSON Forms are you using?

v3.3.0

### Framework

Vue

### RendererSet

Vanilla

**Comment by sdirix** [comment]
@changjung-kim Thanks for the report! Would you like to contribute the fix?

**Comment by changjung-kim** [comment]
Okay. Sure.

**Comment by sdirix** [comment]
Hi @changjung-kim I see you developed a fix. Would you like to open a PR?

**Comment by changjung-kim** [comment]
Hi @sdirix Yes. I did. Please review and merge the PR. :)

**Comment by sdirix** [comment]
Fixed with https://github.com/eclipsesource/jsonforms/pull/2368
