### ISSUE TITLE
Support for Angular 16+ 

### ISSUE THREAD

**Issue by urbanmaintenance** [eclipsesource/jsonforms#2372]
### Is your feature request related to a problem? Please describe.

Keeping up with new angular versions

### Describe the solution you'd like

Support for Angular 16+

### Describe alternatives you've considered

no alternative

**Comment by lucas-koehler** [comment]
Hi @urbanmaintenance , thanks for reporting this issue. Angular 16 was supported in JSON Forms from `3.2.0` and up until `v3.3.0-beta.0`. With `3.3.0` Angular 16 support was dropped in favor of properly supporting Angular 17 and 18. Thus, Angular 16 support will not come back with newer version.
I recommend using JSON Forms `3.2.1` if you must use Angular 16.
