### ISSUE TITLE
Vue Vuetify Forms not rendered after update to 3.4.0, but only in release builds

### ISSUE THREAD

**Issue by AtjonTV** [eclipsesource/jsonforms#2378]
### Describe the bug

With JSON Forms 3.3.0 and Forms Vuetify 3.3.0-preview.0, I was able to correctly use JSON Forms.

The recent release of 3.4.0 broke something, and now Controls and HorizontalLayout are no longer rendered.
In the DOM it is only an empty HTML comment.

This only occurs when I run `pnpm build && pnpm preview`, in dev mode (`pnpm dev`) it still works correctly.  

### Expected behavior

All Control and Layout components are rendered correctly.

### Screenshots

This is how it looks with latest versions:
```json
{
  "dependencies": {
      "@jsonforms/core": "^3.4.0",
      "@jsonforms/vue": "^3.4.0",
      "@jsonforms/vue-vuetify": "^3.4.0",
  }
}
```

![image](https://github.com/user-attachments/assets/a92bca1e-d5f8-418f-a83c-7b672b19de55)

![Screenshot_20240917_111136](https://github.com/user-attachments/assets/1ce2acee-2c1f-4b44-abaa-6f841991e557)

This is how it looks with **only** vue-vuetify downgraded:
```json
{
  "dependencies": {
      "@jsonforms/core": "^3.4.0",
      "@jsonforms/vue": "^3.4.0",
      "@jsonforms/vue-vuetify": "3.3.0-preview.0",
  }
}
```

![image](https://github.com/user-attachments/assets/eb967bb6-8629-4cd3-9c7f-6fd081c5187f)

![Screenshot_20240917_110745](https://github.com/user-attachments/assets/a8554d9c-2ee4-4504-a881-399344da5a95)

### Which Version of JSON Forms are you using?

v3.4.0

### Package

Vue Vuetify Renderers

### Additional context

Here is the full list of the dependencies:
```json
{
  "dependencies": {
    "@jsonforms/core": "^3.4.0",
    "@jsonforms/vue": "^3.4.0",
    "@jsonforms/vue-vuetify": "^3.4.0",
    "@mdi/font": "^7.4.47",
    "@nuxtjs/i18n": "^8.5.2",
    "@nuxtjs/supabase": "^1.4.0",
    "@pinia/nuxt": "^0.5.4",
    "@sentry/nuxt": "^8.30.0",
    "@vuelidate/core": "^2.0.3",
    "@vuelidate/validators": "^2.0.4",
    "nuxt": "^3.13.2",
    "pinia": "^2.2.2",
    "vue": "latest",
    "vue-router": "latest"
  },
  "devDependencies": {
    "vite-plugin-vuetify": "^2.0.4",
    "vuetify": "^3.7.1"
  }
}
```

**Comment by sdirix** [comment]
Thanks for the report, we'll take a look.

Note that mixing JSON Forms versions is fine for investigating, however you might run into weird runtime behavior. So for now I recommend you to stay on the same old version which works for you.
