### ISSUE TITLE
Support for Angular 19

### ISSUE THREAD

**Issue by laurentgrangier** [eclipsesource/jsonforms#2386]
### Is your feature request related to a problem? Please describe.

Angular 19 will be published in the "Week of 2024-11-19" according to release plans of Angular's team (https://angular.dev/reference/releases).

JsonForms should support Angular 19 "quickly" after the release of Angular 19.

### Describe the solution you'd like

Support for Angular 19.
Drop support for Angular 17 and 18.
Actually I think JsonForms should not have support for two different major versions of Angular, since that could come with problems.

### Describe alternatives you've considered

Not relevant.

### Package

Angular Bindings, Angular Material Renderers

**Comment by laurentgrangier** [comment]
Results of first attempt with 19.0.0-rc.0 (support for 17 & 18 dropped):
- Components, Directives and Pipes must be marked as "standalone: false" since the new default is "true". https://blog.angular.dev/the-future-is-standalone-475d7edbc706
- Typescript must be updated from 5.2.2 to 5.5.0. No change needed in code.

Not related to Angular: 
- package.json in vue-vutify: the target "build-only" must be adapted with "cross-env". I assume this works without problem on Linux but not on Windows. 
"build-only": "*cross-env* NODE_OPTIONS=\"--max-old-space-size=4096\" vite build",

**Comment by laurentgrangier** [comment]
Hi @lucas-koehler 

It should be possible to keep support for 18 and 19 if the code stays on Typescript 5.5 which is compatible with Angular 18 and 19 (https://angular.dev/reference/versions). 
Most of libraries only supports one Angular version at a time (or have different releases). I don't consider myself as an expert with Angular and I must say I don't know it it could have problems supporting both versions. I will try to let supports for both versions in the package.json.

Angular 19 was released on 19.11.2024. I will come with a Pull Request soon.

It is OK for me if you fix the small "cross-env" problems. 

Thank you
Laurent

**Comment by laurentgrangier** [comment]
I had to drop the support for Angular 18. There was problems I couldn't solve. With Angular 19 they added "incremental hydration" (see https://angular.dev/guide/incremental-hydration). That leads to changes in angular/core. As I tested the support for both Angular 18 and 19, I got the following error in the angular-material/example app:

```
../../node_modules/.pnpm/@angular+platform-browser@19.0.0_@angular+animations@19.0.0_@angular+core@18.2.12_rxjs@6.6.7__p5bg3whqizntzzj7ixiqpz7scu/node_modules/@angular/platform-brows
er/fesm2022/platform-browser.mjs:2112:69-94 - Error: export 'ɵwithIncrementalHydration' (imported as 'ɵwithIncrementalHydration') was not found in '@angular/core'
```

The error log itself shows some attempt to use both angular 18 and 19 at the same time.

I also added an angular workspace in angular-material package to be able to use Angular CLI (ng build, ng test). I couldn't bring the test to run with the current build system. Using Angular CLI it avoids some strange problems because the current scripts do not initialize everything the same as Angular CLI or are missing some dependencies we don't know.

**Comment by lucas-koehler** [comment]
Hi @laurentgrangier , thanks for the update. However, as we do not explicitly use incremental hydration, why would its addition be a problem? It seems that the problem stems from mixed usage of Angular 18 and 19, i.e. the platform v19 code trying it to import it from core v18. Concretely, it looks like angular core 18 got drawn in while some other dependencies are used as version 19.

Thus, I think we should see if we can still support Angular 18 as along as all angular dependencies are resolved in the same version. If that still breaks then, we can still remove the Angular 18 support. However, I would like to avoid it because of a potential configuration error.

**Comment by SimonRingeisen** [comment]
@lucas-koehler do you know, when JSON Forms 3.5 with Angular 19 compatibility will be released?
