### ISSUE TITLE
UMD version release 

### ISSUE THREAD

**Issue by icoco** [eclipsesource/jsonforms#2388]
### Is your feature request related to a problem? Please describe.

looks it can use pure js environment, but not find some example usage...

possible a demo to do ?

 

### Describe the solution you'd like

UMD

### Describe alternatives you've considered

UDM release demo

**Comment by sdirix** [comment]
Hi @icoco,

JSON Forms doesn’t currently provide UMD builds out of the box. That said, you can always consume our packages and create a UMD build yourself—it's no different than doing so for most other libraries.

If you're looking to use JSON Forms "standalone" (e.g., by dropping it in with a `<script>` tag), a good way to go is to wrap JSON Forms as a web component. We actually have an older example showing how to do this for the Angular Material variant of JSON Forms, check it out [here](https://github.com/eclipsesource/jsonforms-angular-webcomponent).

Hope that helps!
