### ISSUE TITLE
ValidateAndHide only partially working for react material table cell

### ISSUE THREAD

**Issue by 0mpurdy** [eclipsesource/jsonforms#2398]
### Describe the bug

Validation mode `'ValidateAndHide'` does not hide error messages in array object cells (rendered by the React MaterialTableControl)

### Expected behavior

The error should be hidden

### Steps to reproduce the issue

1. Create a schema with an array of objects, where the object has required properties

   e.g.

   ```json
   {
       "type": "object",
       "properties": {
           "someArray": {
               "type": "array",
               "items": {
                   "type": "object",
                   "properties": {
                       "name": {"type": "string"},
                       "age": {"type": "number"},
                   },
                   "required": ["name"],
               },
           },
       },
   }
   ```

2. Render the schema with the react material renderers and validation mode `'ValidateAndHide'`

   ```jsx
   <JsonForms
     {...otherProps}
     validationMode={'ValidateAndHide'}
   />
   ```

### Screenshots

| validationMode | screenshot |
| --- | --- |
| NoValidation | <img width="522" alt="NoValidation shows grey box input box and no red error message" src="https://github.com/user-attachments/assets/fb5feb0c-64a9-42a0-98de-0f1ac4c0d8e8"> |
| ValidateAndHide | <img width="394" alt="ValidateAndHide shows grey input box with red error message" src="https://github.com/user-attachments/assets/43e05ea0-42ff-4a1f-bd1b-79515434ba1a"> |
| ValidateAndShow | <img width="400" alt="ValidateAndShow shows red input box with red error message" src="https://github.com/user-attachments/assets/8383291c-69dd-4e71-8764-8228c0f30321"> |

### Which Version of JSON Forms are you using?

v3.4.1

### Package

Core, React Material Renderers

### Additional context

I'm not very familiar with the codebase so apologies if this is a red herring, but it looks like the control code which correctly hides the error [uses getErrorAt](https://github.com/eclipsesource/jsonforms/blob/fcef896c8927269d3f3ed609a7255651085b193d/packages/core/src/mappers/renderer.ts#L532) from [src/store/jsonFormsCore](https://github.com/eclipsesource/jsonforms/blob/fcef896c8927269d3f3ed609a7255651085b193d/packages/core/src/store/jsonFormsCore.ts#L40) and this respects validation mode.

Whereas the [cell error label](https://github.com/eclipsesource/jsonforms/blob/fcef896c8927269d3f3ed609a7255651085b193d/packages/material-renderers/src/complex/MaterialTableControl.tsx#L253) instead [uses errorsAt](https://github.com/eclipsesource/jsonforms/blob/fcef896c8927269d3f3ed609a7255651085b193d/packages/material-renderers/src/complex/MaterialTableControl.tsx#L180) which comes from [src/util/errors](https://github.com/eclipsesource/jsonforms/blob/fcef896c8927269d3f3ed609a7255651085b193d/packages/core/src/util/errors.ts#L66).

There may be a good reason for that of course which I don't understand - but I'd expect cells and controls both to respect that `validationMode` property

**Comment by sdirix** [comment]
Hi @0mpurdy,

good catch, this is definitely a bug! Would you like to contribute the fix?

**Comment by 0mpurdy** [comment]
Sure! I'll give it a go
