### ISSUE TITLE
Test with real-world example

### ISSUE THREAD

**Issue by koegel** [eclipsesource/jsonforms#255]
Test migrating an EMF Forms project to a JSON Forms project

**Comment by eneufeld** [comment]
We tested this and set up a dedicated repo with the example, i think we can close this @koegel ?

**Comment by koegel** [comment]
+1

On Mon, May 23, 2016 at 1:54 PM, Eugen Neufeld <notifications@github.com>
wrote:

> We tested this and set up a dedicated repo with the example, i think we
> can close this @koegel <https://github.com/koegel> ?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/eclipsesource/jsonforms/issues/255#issuecomment-220959885>
>



-- 

Dr. Maximilian Koegel

Senior Software Architect / General Manager
EclipseSource Munich

Email: mkoegel@eclipsesource.com
Web: http://eclipsesource.com/munich
Mobil: +49 176 223 619 18
Phone: +49 89 21 555 30 - 10
Fax: +49 89 21 555 30 - 19
Skype: maximilian.koegel
Hangouts: mkoegel@eclipsesource.com

EclipseSource Muenchen GmbH
Agnes-Pockels-Bogen 1
80992 München

General Managers: Dr. Jonas Helming, Dr. Maximilian Koegel
Registered Office: Agnes-Pockels-Bogen 1, 80992 Muenchen,
Commercial Register München, HRB 191789

**Comment by edgarmueller** [comment]
Out of curiosity: Is the repo public?

**Comment by koegel** [comment]
no :)

On Wed, May 25, 2016 at 3:04 PM, Edgar Müller <notifications@github.com>
wrote:

> Out of curiosity: Is the repo public?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/eclipsesource/jsonforms/issues/255#issuecomment-221569194>
>



-- 

Dr. Maximilian Koegel

Senior Software Architect / General Manager
EclipseSource Munich

Email: mkoegel@eclipsesource.com
Web: http://eclipsesource.com/munich
Mobil: +49 176 223 619 18
Phone: +49 89 21 555 30 - 10
Fax: +49 89 21 555 30 - 19
Skype: maximilian.koegel
Hangouts: mkoegel@eclipsesource.com

EclipseSource Muenchen GmbH
Agnes-Pockels-Bogen 1
80992 München

General Managers: Dr. Jonas Helming, Dr. Maximilian Koegel
Registered Office: Agnes-Pockels-Bogen 1, 80992 Muenchen,
Commercial Register München, HRB 191789

**Comment by eneufeld** [comment]
no as long as github has no bug
