### ISSUE TITLE
Change "ui-schema" to "uischema" to fix angular2 incompabilities

### ISSUE THREAD

**Issue by pancho111203** [eclipsesource/jsonforms#259]
We can also think about renaming the attribute to something different.

**Comment by edgarmueller** [comment]
I dunno if this a bug in A2 or something simliar but @pancho111203 could not get JSON Forms to work with A2 unless he changed the attribute name.
@eneufeld @koegel Any suggestions?

**Comment by eneufeld** [comment]
It would be interesting to know whether this is a bug in A2 or not, otherwise I don't mind renaming the parameter

**Comment by eneufeld** [comment]
This is a "feature" of angular2 see [here](https://github.com/angular/angular/blob/master/modules/%40angular/docs/migration/kebab-case.md) or [here](https://github.com/angular/angular/issues/5812)

**Comment by eneufeld** [comment]
I think we can do the change with a release of an angular2 version of jsonforms. As we also will have to change the rendererservice.
I like the ui-schema name, as we can't use uiSchema in angular1 and I don't like uischema (readability). @edgarmueller @koegel  what do you think?
