### ISSUE TITLE
Required control validation error only triggers at the beginning

### ISSUE THREAD

**Issue by hecforga** [eclipsesource/jsonforms#275]
If a control is required, the validation error only triggers at the beginning. If I write something on that control, the error disappears. But if I delete the content, the error doesn't appear again.

**Comment by eneufeld** [comment]
this is not a bug, this is an "feature".
The problem is, that required only checks for null . So if a value is eg an empty string, then it is set thus the required validation is satisfied. If you want to forbid empty strings you have to set a min length rule to the properties.
