### ISSUE TITLE
Javascript CustomControl Example Enhancements

### ISSUE THREAD

**Issue by sdirix** [eclipsesource/jsonforms#294]
- Currently the custom control in the example has no label. This label could be added in the custom directive controller via:
```
    vm.showLabel = true;
    vm.label = $scope.uischema.label;
```
- Show how to add a Required marker
- Show how to add Validation

**Comment by edgarmueller** [comment]
The mechanism to provide custom controls has been changed and in most cases it is sufficient to only replace the template. The custom control example has been updated and also features a label now.
