### ISSUE TITLE
Add support for aggregation types

### ISSUE THREAD

**Issue by eneufeld** [eclipsesource/jsonforms#297]
Currently we don't support aggregation types like, oneOf. The result is, that no ui schema is generated in this cases.

**Comment by edgarmueller** [comment]
`oneOf` and `anyOf` semantics are unclear, but we should support `allOf`.

**Comment by bjorgdagny** [comment]
Hi
Some questions regarding this issue:

1. This issue is related to the use of aggregated types in the data schema? 
2. Any chance you will add this feature in the near future? 
3. What is unclear with the semantics? 
4. If we make a custom rendrer for this wouldn't we have to make a custom rendrer for each field type to support the agg. types?

**Comment by edgarmueller** [comment]
Hi @bjorgdagny 
1. Yes
2. We might add some sort of support, but we currently do not yet know how it might look like. It's not planned for any of the next releases, this is related to 3.
3. What's unclear is what kind of forms should be generated: How would you expect JSONForms to handle oneOf and anyOf? allOf could be supported by just merging all required properties into a single form, but that does not work for oneOf and allOf.
4. I'm not sure, if I understand the question right, but one possible way of adding support for oneOf/anyOf (if that's what you are asking for) could be to go over all the possible elements of the respective entries, generate forms accordingly and then bundle them together in a way that makes sense, e.g. for oneOf I think it would only make sense to display a single form at a time. Do you have anything specific in mind how this could look like?

**Comment by edgarmueller** [comment]
Closing this as support for oneOf/anyOf/allOf has been added to the MUI based renderer set.
