### ISSUE TITLE
Connect JSONForms to a RESTFul API

### ISSUE THREAD

**Issue by mlemarrec** [eclipsesource/jsonforms#355]
Congratulations for your work. This is the best implementation of JSON Form I saw.
But I'm surprised not to see any example with a form submission.

I currently have a backend CMS project in which I will wish to use your library. Do you think it is possible to integrate the functionality to connect to a RESTFul API in tour project ?

One more time: "very good job !"

**Comment by edgarmueller** [comment]
Thanks for the kind words! We had a similar example in the past but it got somewhat outdated. I'll try to update it until next week. The basic idea is that we used angular $resource to consume the API.
I'll let you know once I've updated the example.

**Comment by mlemarrec** [comment]
Thank you very much, it's a very good news :o)

**Comment by edgarmueller** [comment]
I've finally found some time to update the examples today. You can have a look at the [placeholder example](https://github.com/eclipsesource/jsonforms/tree/master/examples/app/placeholder) located in our repo for a simple demo how to integrate with a RESTful API with angular $resource. See [the instructions](https://github.com/eclipsesource/jsonforms#how-to-run-the-examples) how to get the examples running if you want to try it yourself.

A more advanced example, which can be used to maintain a list of tasks, is located [here](https://github.com/eclipsesource/make-it-happen-jsonforms). That example also shows how to create a custom control. 

If you have any questions, let me know!

**Comment by mlemarrec** [comment]
Thank you for this example.

I try to load Schema and UISchema dynamicaly with angular $ressource, but it doesn't work.
I think Schema and UISchema, can't be changed after page loading. Maybe I made a mistake...

I would like to use a route like this: "/schema/<users>/<id>"
And load the Schema "/schema/<users>.json", 
the UISchema "/uischema/<users>.json" 
and the data "/data/<users>.json" or "/data/<users>/<id>.json" .

Do you have any idea ?

**Comment by edgarmueller** [comment]
So you want your schemas to be loaded from an endpoint, is that correct?

**Comment by mlemarrec** [comment]
Yes, exactly.

I can load the data and the UISchema from an endpoint (with $resource), but when i do it for Schema i have this error:

Error: too much recursion
s@http://jsonform.plugonweb.com/node_modules/jsonforms/dist/jsonforms.js:11:8757
s@http://jsonform.plugonweb.com/node_modules/jsonforms/dist/jsonforms.js:11:8776

And after a few seconds, it's ok.

**Comment by mlemarrec** [comment]
I've found a solution.
In my controller I set a variable when all is loaded (data, shema and UIschema) and i test this variable in the template with "ng-if".

**Comment by edgarmueller** [comment]
Which version are your using? We ought to support this case, if not it may be a bug.

**Comment by edgarmueller** [comment]
Closing, feel free to re-open if you still experience problems.
