### ISSUE TITLE
Review Travis build

### ISSUE THREAD

**Issue by edgarmueller** [eclipsesource/jsonforms#360]
The Travis build fails frequently although tests are running just fine locally. Probably a problem with phantomjs.

**Comment by sdirix** [comment]
Travis linux images come with a pre-installed PhantomJS version lower than 2.0. They are aware of the issue but there is no built-in solution yet. See https://github.com/travis-ci/travis-ci/issues/3225 for more information. I added a workaround to download a prebuilt later version which is described here: https://github.com/Medium/phantomjs

It probably also makes sense to add a C11+ Compiler so we are save from node-gyp rebuilds. See https://docs.travis-ci.com/user/languages/javascript-with-nodejs#Node.js-v4-(or-io.js-v3)-compiler-requirements for more information
