### ISSUE TITLE
Readme.md vs. jsonforms.org

### ISSUE THREAD

**Issue by koegel** [eclipsesource/jsonforms#383]
Readme.md should (and is) mainly about contributing. Nevertheless when people firt come from the JSONForms Gibhub page they need to be able to find their way to jsonforms.org.

Required Improvements:
1. Consistency of jsonforms.org messages with Github readme: use same slogans:
"More Forms. Less Code.
Complex AngularJS Forms in the blink of an eye"
2. Usage: Remove and point to Getting started on JSONForms.org
3. Introduce Section "Documentation and more information" with a link to the JSONForms webpage.

**Comment by edgarmueller** [comment]
@koegel Done, except for point 2: Which 'Getting started' are you referring to?

**Comment by koegel** [comment]
http://github.eclipsesource.com/jsonforms/#/docs/introduction

**Comment by edgarmueller** [comment]
Closing in favor of https://github.com/eclipsesource/jsonforms/issues/387
