### ISSUE TITLE
Test Contribution Guide in Readme.md

### ISSUE THREAD

**Issue by koegel** [eclipsesource/jsonforms#384]
https://github.com/eclipsesource/jsonforms

**Comment by AlexandraBuzila** [comment]
I get the following error when trying to sign the CLA by using CLAHub (https://www.clahub.com/agreements/eclipsesource/jsonforms), with no other explanation 

We're sorry, but something went wrong.

**Comment by koegel** [comment]
Stefan can you please take a look?

**Comment by edgarmueller** [comment]
@sdirix Any update on this?

**Comment by sdirix** [comment]
The migration to [CLA assistant](https://github.com/cla-assistant) is currently in the works and will be completed in the near future.
