### ISSUE TITLE
Initial make it happen sample app does not work

### ISSUE THREAD

**Issue by koegel** [eclipsesource/jsonforms#390]
The example does not look like explained in the guide:
http://github.eclipsesource.com/jsonforms/#/docs/setup
But like this. 
![selection_054](https://cloud.githubusercontent.com/assets/1044916/18248957/ae022c60-737b-11e6-8d0a-6d8304bb5693.png)

npm install completed without error but with the following warnings:
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.14

npm run initial completed without errors

**Comment by eneufeld** [comment]
fixed this with this PR [https://github.com/eclipsesource/make-it-happen-jsonforms/pull/9](https://github.com/eclipsesource/make-it-happen-jsonforms/pull/9)

**Comment by eneufeld** [comment]
is fixed now
