### ISSUE TITLE
Rewrite form tutorial to a real tutorial

### ISSUE THREAD

**Issue by koegel** [eclipsesource/jsonforms#393]
Currently there are no instructions on what to actually do concretely.

http://github.eclipsesource.com/jsonforms/#/docs/firstform

**Comment by koegel** [comment]
Add pointers to actual code into article, alle pointers are links with path and filename as label and linking to the file in github (initial state)
Missing pointers:
> The first step to create such a form is to define the underlying data schema.
 => see schema
> Based on the data schema, you can now define a UI schema showing all of the defined properties.
  => see UI Schema
>To embed the form, JSON Forms provides a dedicated AngularJS directive, jsonforms.
=> see html
Additional stuff
> As before, there are two ways of creating and modifying a UI schema, the JSON Forms Editor and directly writing the underlying JSON file. When using the JSON Forms Editor
 => JSON Forms Editor should link to the editor on http://jsonforms-editor.eclipsesource.com/
>Once you have embedded the form into your application, it will bind the data and show live validation.
=> delete this sentence

**Comment by eneufeld** [comment]
added changes on new website repository, see current version here: [http://jsonforms-beta.de/#/docs/firstform](url)

**Comment by koegel** [comment]
+1
