### ISSUE TITLE
Date validation in MiH example

### ISSUE THREAD

**Issue by AlexandraBuzila** [eclipsesource/jsonforms#419]
Tested on Win32, npm version 2.15.9, node version 4.5.0.

Follow instructions from http://github.eclipsesource.com/jsonforms/#/docs/setup and run final app. Open task "Buy gloves" and select a new value for the Due Date using the calendar widget. A validation error is shown: 
![image](https://cloud.githubusercontent.com/assets/6464495/18835251/73cab046-83fa-11e6-9852-8ffa1e557198.png)

**Comment by eneufeld** [comment]
There is a more generic problem, as the date renderer is rendering as date only but checks for a date-time format constraint.
We should discuss what the date renderer actually do
