### ISSUE TITLE
Add custom renderer for array editable control to final state

### ISSUE THREAD

**Issue by AlexandraBuzila** [eclipsesource/jsonforms#420]
Tested on Win32, npm version 2.15.9, node version 4.5.0.

Follow instructions from http://github.eclipsesource.com/jsonforms/#/docs/setup and run final app.

New comments can't be added to any of the tasks, as presented in the tutorial.

**Comment by eneufeld** [comment]
This related to #415

**Comment by edgarmueller** [comment]
Re-test since I think Alex is lying :)

**Comment by eneufeld** [comment]
I rechecked this. 
In tutorial the array control is shown with simple:true as well as without.
Furthermore it also shows how to implement a custom renderer which renderers the array entries read-only but allows to add new entries.

This custom renderer is NOT part of the MiH package. Should we add it?
Which renderer should be visible if somebody opens the final state for the first time (read-only or not)?

**Comment by edgarmueller** [comment]
@eneufeld What exactly do you mean with the last paragraph? Can you drop by to shortly discuss this? Thanks!

**Comment by edgarmueller** [comment]
Check what should be part of the final solution and whether there should be an intermediate solution.

**Comment by eneufeld** [comment]
should be done
