### ISSUE TITLE
MiH Example Setup instructions

### ISSUE THREAD

**Issue by AlexandraBuzila** [eclipsesource/jsonforms#421]
There's no info in the tutorial where to get nodejs/npm from.

**Comment by eneufeld** [comment]
The [Prerequistites](https://github.com/eclipsesource/make-it-happen-jsonforms/blob/master/README.md#prerequisites) section contains a link to nodejs.org

**Comment by eneufeld** [comment]
@AlexandraBuzila meant this : http://github.eclipsesource.com/jsonforms/#/docs/setup

**Comment by eneufeld** [comment]
@AlexandraBuzila @edgarmueller can we close this?

**Comment by edgarmueller** [comment]
@eneufeld I think so.

**Comment by eneufeld** [comment]
We still need to rebuild the webpage
