### ISSUE TITLE
Try to further improve loading time

### ISSUE THREAD

**Issue by edgarmueller** [eclipsesource/jsonforms#427]
The initial loading time of the web page is still too high. We might think about integration pace.js or the like.

**Comment by edgarmueller** [comment]
Try gzip and static conten.

**Comment by eneufeld** [comment]
I checked this.
The main issue is, that before any part of the page is rendered we need to load the whole bundle.js . 
This process takes between 1 and 2 seconds. 
We can do multiple things to speed this up.
- reduce the size of the bundle.js (remove unneeded dependencies, tree shaking etc)
- split the bundle.js into multiple files by using lazy-loading for all routes except landing
- provide a static landing page
Providing a static version of the page while the script is loading would be the fastest.
On the other hand if the user tries to navigate anywhere while the script is still loading this will not working.

We need to discuss this.

**Comment by eneufeld** [comment]
We discussed this offline. 
The result is, that we do not want a static landing page.
This are the steps we want to do:
- reduce the size of the javascript
- split into multiple files (see [here](http://michalzalecki.com/lazy-load-angularjs-with-webpack/) ) 
- the initial bundle should contain route, angular and the landing page, no jsonforms, no material 
- load all the other stuff in background
- remove material from landing page
- load example on landing page using route (can be removed in the first version)

**Comment by edgarmueller** [comment]
Fixed, see follow up issue #513.
