### ISSUE TITLE
Create Code Styleguide

### ISSUE THREAD

**Issue by eneufeld** [eclipsesource/jsonforms#542]
We should create a style guide for developers.
- inline return calls or not
- variable naming

**Comment by edgarmueller** [comment]
I'd propose to stick with the following, already existing styleguides:
- [AirBnB Styleguide](https://github.com/airbnb/javascript)
- and for any TS specifica: [Unofficial TS Styleguide](https://github.com/basarat/typescript-book/blob/master/docs/styleguide/styleguide.md)

Some notes (up for discussion):
* I haven't checked whether these contradict with each other.
* There's no clear guideline whether to prefer multiple returns vs. using a mutable local var and a single return statement
* For acronyms I'd propose the follow the guidelines as described [here](https://msdn.microsoft.com/en-us/library/ms229043(v=vs.100).aspx#Anchor_2)
* I think some of these settings can be configured via TSLint, but we need to check which exactly

**Comment by eneufeld** [comment]
The "Unofficial TS Styleguide" looks good and has some nice points which we should embrace.
The AirBnB guide is written for JavaScript, one thing I noticed is that the AirBnB Guide doesn't like _ names for private member whereas I saw this pattern eg in Angular2.
We also need a decision on how to name the renderers and services correctly, eg foo.renderer.ts  beeing FooRenderer ?

I think we should create a small wiki page like eg the Theia guys here: [Theia Wiki](https://github.com/theia-ide/theia/wiki/Coding-Guidelines)
