### ISSUE TITLE
Port make-it-happen to JSONForms2

### ISSUE THREAD

**Issue by edgarmueller** [eclipsesource/jsonforms#547]

**Comment by eneufeld** [comment]
initial version [here](https://github.com/eneufeld/make-it-happen-jsonforms/tree/jsonforms2). 
Should we create a PR for this or move the whole branch?

**Comment by edgarmueller** [comment]
I'd propose to move the whole branch.

**Comment by edgarmueller** [comment]
Branch it is then.

**Comment by eneufeld** [comment]
Created [PR](https://github.com/eclipsesource/make-it-happen-jsonforms/pull/17)
