### ISSUE TITLE
Fix exports for end-users

### ISSUE THREAD

**Issue by edgarmueller** [eclipsesource/jsonforms#568]
Check exports of index.ts to make JSON Forms easily consumable for end-users.

**Comment by eneufeld** [comment]
stuff I used in a project:
import {JsonSchema} from 'jsonforms/dist/ts-build/models/jsonSchema';
import {JsonForms} from 'jsonforms/dist/ts-build/json-forms';
import {DataService} from 'jsonforms/dist/ts-build/core/data.service';
import {retrieveResolvableSchema} from 'jsonforms/dist/ts-build/path.util';
import {ControlElement} from 'jsonforms/dist/ts-build/models/uischema';
