### ISSUE TITLE
watching form input changes doesn't work

### ISSUE THREAD

**Issue by AChakraborty1982** [eclipsesource/jsonforms#571]
```
function updateEcoreEditorData(element, data) {
	console.log("Initializing ECore editor...");

	angular.module('MiHexample').value('Task', data);

	angular.bootstrap(element, [ 'MiHexample' ], {
		strictDi : true
	});
	
	var scope=angular.element(element).scope();
	scope.$watch(data,function(){
		editorDirtyState();
	})
}
```

**Comment by koegel** [comment]
Sorry for the delay. We will come back to you by Friday this week at latest.

**Comment by eneufeld** [comment]
Hi Abhi,
could you try this out:
`function updateEcoreEditorData(element, data) {
	console.log("Initializing ECore editor...");

	angular.module('MiHexample').value('Task', data);

	angular.bootstrap(element, [ 'MiHexample' ], {
		strictDi : true
	});
	
	var scope=angular.element(element).scope();
	scope.$watch(function() { return data},function(){
		editorDirtyState();
	}, true);
}`

**Comment by edgarmueller** [comment]
I'm closing this now since we released a release candidate for JSON Forms 2 and we will not continue working on JSON Forms 1 for the time being.
