### ISSUE TITLE
Validation of Control Elements should be done in a ValidationService

### ISSUE THREAD

**Issue by sdirix** [eclipsesource/jsonforms#63]

**Comment by edgarmueller** [comment]
+1, are you already on to this?

**Comment by sdirix** [comment]
No, just wanted to record this requ

**Comment by eneufeld** [comment]
Can't be closed, as we have a validation service doing exactly this now?

**Comment by edgarmueller** [comment]
Yes, this needs to stay open, since we additionalll need to flesh out how to perform validation in case properties are dependent on each other (or nested), which is currently not possible.

**Comment by edgarmueller** [comment]
Closing this for now, as we refactored all services into the `Services` object, which the validation service is also part of.
