### ISSUE TITLE
Layout renderers should provide item style support

### ISSUE THREAD

**Issue by edgarmueller** [eclipsesource/jsonforms#630]
Layout renderers should provide a method that allows its items to be styled dynamically.

**Comment by sdirix** [comment]
Is this task covered by the layout renderers calling the styling registry? For example within the ```HorizontalLayoutRenderer```:
```typescript
    const childrenSize = div.children.length;
    for (let i = 0; i < childrenSize; i++) {
      const child = div.children.item(i);
      JsonForms.stylingRegistry
        .addStyle(child, 'horizontal-layout-item', childrenSize);
    }
```
Is this sufficient or did you have another idea in mind?
