### ISSUE TITLE
A change event should be fired on array item deletion

### ISSUE THREAD

**Issue by gwn** [eclipsesource/jsonforms#638]
Hi,
I recently developed a feature on an app that uses JSONForms,
and this feature relies on "jsonforms:change" events that are fired
on data changes.
The only problem I encountered is that JSONForms fails to
immediately trigger a change event after an array item deletion.
I feel that this is related to the `$watch`ing method in use and the
behavior of the `concat` method of `Array` objects.
In any case, array item deletion are not being detected, which
should not be the case, in my opinion.
Looking forward to your comments..

**Comment by edgarmueller** [comment]
I'm sorry we didn't take care of this issue. We stopped working on JSON Forms 1 a while back in order to focus entirely on JSON Forms 2, but we should have let you know earlier. Sorry for any inconvenience.
