### ISSUE TITLE
Example Apps + Docu

### ISSUE THREAD

**Issue by koegel** [eclipsesource/jsonforms#647]
Comparable to http://jsonforms.io/#/docs/setup

**Comment by koegel** [comment]
Examples as defined in #646

**Comment by edgarmueller** [comment]
Implement with react and jsonforms 2.0.x

**Comment by edgarmueller** [comment]
@koegel Is this issue covered by https://github.com/edgarmueller/jsonforms2-website/issues/10? If so, I'd close this one.
