### ISSUE TITLE
Validate multiple fields - and custom validation

### ISSUE THREAD

**Issue by gentledepp** [eclipsesource/jsonforms#662]
Hi!

I had a look at your documenation and examples and I am wondering now, how I could achieve a somewhat more advanced validation.

**Example 1:** an object is only valid, in case two properties match (e.g. confirm password)
**Example 2:** I have a "username" field, which I want to validate to contain a unique username. So I would have to asynchronously call a rest api to validate the username and then set/clear the validation error.

How can I achieve that?

**Comment by koegel** [comment]
Example 1 is not directly supported by the JSONSchema standard. There is an open issue for this: [JSONSchema $data](https://github.com/json-schema-org/json-schema-spec/issues/51). It can be addressed independent of JSON Schema in JSON Forms thought, see below.

Example 2 is also not directly supported by the JSONSchema standard. JSONSchema has a uniqueness check on arrays, but this is not what you want. 

So in both cases you will need a custom solution based on JSON Forms. This is possible with JSONForms 2. You can provide a custom service, which will listen to data changes and then react by providing the required validation results similar to the existing [validation service](https://github.com/eclipsesource/jsonforms/blob/jsonforms2/src/services/validation.service.ts). The service only needs to set the validation result on the affected controls and the renderers for the controls will pick it up from there and show the validation markers.
I opened an issue for an API dedicated to supply custom validators directly in JSON Forms: #663

**Comment by koegel** [comment]
The custom service could of course also run and supply the results async.

**Comment by edgarmueller** [comment]
Closing this in favor of #663.
