### ISSUE TITLE
Allow to contribute custom validators

### ISSUE THREAD

**Issue by koegel** [eclipsesource/jsonforms#663]
A custom validator contributes code to validate certain constraints. It must be possible to contribute this quite simple.

**Comment by eneufeld** [comment]
also check [HTML5 Constraint Validation](https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/HTML5/Constraint_validation)

**Comment by eneufeld** [comment]
@edgarmueller I would suggest to close this as a user can contribute a custom ajv into the store, what do you think?

**Comment by edgarmueller** [comment]
I agree, closing.
