### ISSUE TITLE
Add DnD support

### ISSUE THREAD

**Issue by edgarmueller** [eclipsesource/jsonforms#682]
Add Drag'n'Drop support for the default tree control.

**Comment by iluuu1994** [comment]
Was this implemented by any chance? This library looks fantastic! Thank you for your hard work!

**Comment by sdirix** [comment]
Thanks for the compliments ;) We implemented drag'n'drop only for the `material-tree-renderer` which is maintained in its own package. What are your use cases regarding drag'n'drop?

**Comment by iluuu1994** [comment]
I actually need reordering for arrays, not trees. I didn't read the issue properly 😅 If found #1378 which works for my use case. Is there any documentation for this feature? Thanks!

**Comment by sdirix** [comment]
No problem ;). It is documented on our website: https://jsonforms.io/docs/uischema/controls

Basically all you need to do is to set `showSortButtons` to `true` in the `options` object of your control, e.g.:
```
{
      type: 'Control',
      scope: '#/properties/myarrayproperty',
      options: {
        showSortButtons: true
      }
}
```

**Comment by iluuu1994** [comment]
Oh, I missed that one. Thanks again!

**Comment by sdirix** [comment]
Actually now looking at the documentation it needs to say `showSortButtons` instead of `showSortingButtons`. We'll fix that soon.

**Comment by sdirix** [comment]
https://github.com/eclipsesource/jsonforms2-website/issues/76
