### ISSUE TITLE
Finalize API typings & JSDoc

### ISSUE THREAD

**Issue by edgarmueller** [eclipsesource/jsonforms#698]
Some parts of the code are not typed at all or only weakly typed. We need to make sure that at least all API relevant code is typed.

**Comment by edgarmueller** [comment]
This is a follow-up of #696

**Comment by edgarmueller** [comment]
Review API and check for unwanted exports.

**Comment by eneufeld** [comment]
http://jsonforms-beta.de/api/core/index.html contains the core-package only.
Is it possible to add a landing page where to select which api to browse?
So that we have core, material, vanilla etc only?

**Comment by eneufeld** [comment]
Review of the **current** react branch.
# Generic
- Can we delegate to react doc?, eg in the hierarchy of the `Renderer` the `Component`

# interfaces
- Control is missing doc
- Renderer missing doc
- Gen missing doc, can't this be a static helper?
- JsonFormsGlobal missing doc on properties
- UnkonwRenderer missing doc
- Scopable missing doc
- ControlProps doc not correct
- RendererProps missing doc
- ControlState missing doc
- DispatchFieldProps missing doc
- FieldProps missing doc
- DispatchRendererProps missing doc
- JsonFormsFieldConstructable missing doc
- JsonFormsInitialState missing doc
- JsonFormsRendererConfig doc unclear
- JsonFormsRendererConstructable missing doc
- JsonFormsState missing doc
- JsonFormsStore missing doc
- ReferenceSchemaMap missing doc
- ValidationState missing doc

# Variables
- most missing a doc
- mapDispatchToFieldProps is a Variable albeit  mapDispatchToControlProps is a function
# Functions
- most missing a doc
# Object literal 
- missing a doc

do we need to export functions available in helpers eg in `Generate`.

Maybe we should also wrap all tester methods in an own module/object literal?

**Comment by eneufeld** [comment]
Maybe we should simple use dynamic modules for those helper files? see http://typedoc.org/guides/doccomments/#dynamic-modules

**Comment by edgarmueller** [comment]
Regarding your 1st comment about linking the API docs: yes, this is WIP.

**Comment by edgarmueller** [comment]
I'm working on this
