### ISSUE TITLE
Validation message for enum control displayed too high

### ISSUE THREAD

**Issue by 1903Daniel** [eclipsesource/jsonforms#706]
Please compare the fields for "Nationality" (Drop-down field, enum control) and "Occupation" (text control) in the attached screenshot.
Below the nationality field, the validation message is displayed too high and overlaps with the border of the input field, compared to the message below the occupation field.

![validation_message_too_high](https://user-images.githubusercontent.com/20644059/33245515-47126670-d309-11e7-9d32-974239261246.png)

**Comment by edgarmueller** [comment]
Check if this still applies.

**Comment by edgarmueller** [comment]
It doesn't anymore.
