### ISSUE TITLE
Fix file naming

### ISSUE THREAD

**Issue by edgarmueller** [eclipsesource/jsonforms#745]
Set-up file naming guidelines and fix them

**Comment by edgarmueller** [comment]
For components, I'd follow the guidelines as outlined [here](https://github.com/airbnb/javascript/tree/master/react#naming), i.e. files containing components should be pascal case.

All other files should be lowercased. I'd also propose to remove dots and hyphens from file names, e.g. in the case of `field.util` and `renderer.util` we could introduce a new `util` subfolder. If that shouldn't be applicable, fallback to camelCase. 

@eneufeld Any objections/other suggestions?

**Comment by eneufeld** [comment]
fine with me

**Comment by edgarmueller** [comment]
Fixed via #818
