### ISSUE TITLE
npm run build doesn't work on Windows because ../ (forward slash) is not recognized

### ISSUE THREAD

**Issue by 1903Daniel** [eclipsesource/jsonforms#752]
lerna run build
lerna info version 2.5.1
lerna ERR! build Errored while running script in 'jsonforms-core'
lerna ERR! execute callback with error
lerna ERR! Error: Command failed: npm run build
lerna ERR! Der Befehl ".." ist entweder falsch geschrieben oder
lerna ERR! konnte nicht gefunden werden.
lerna ERR! npm ERR! code ELIFECYCLE
lerna ERR! npm ERR! errno 1
lerna ERR! npm ERR! jsonforms-core@2.1.0 build: `../../node_modules/.bin/tsc`
lerna ERR! npm ERR! Exit status 1
lerna ERR! npm ERR!
lerna ERR! npm ERR! Failed at the jsonforms-core@2.1.0 build script.
lerna ERR! npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
lerna ERR!
lerna ERR! npm ERR! A complete log of this run can be found in:
lerna ERR! npm ERR!     C:\Users\User\AppData\Roaming\npm-cache\_logs\2017-12-19T17_41_52_930Z-debug.log
lerna ERR!
lerna ERR! > jsonforms-core@2.1.0 build C:\Users\User\Documents\git\packages\core
lerna ERR! > ../../node_modules/.bin/tsc
lerna ERR!
lerna ERR!
lerna ERR!     at Promise.all.then.arr (C:\Users\User\AppData\Roaming\npm\node_modules\lerna\node_modules\execa\index.js:236:11)
lerna ERR!     at <anonymous>
(node:10276) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 4): Error: Command failed: npm run build
Der Befehl ".." ist entweder falsch geschrieben oder
konnte nicht gefunden werden.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! jsonforms-core@2.1.0 build: `../../node_modules/.bin/tsc`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the jsonforms-core@2.1.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\User\AppData\Roaming\npm-cache\_logs\2017-12-19T17_41_52_930Z-debug.log
lerna run build
lerna info version 2.5.1
lerna ERR! build Errored while running script in 'jsonforms-core'
lerna ERR! execute callback with error
lerna ERR! Error: Command failed: npm run build
lerna ERR! Der Befehl ".." ist entweder falsch geschrieben oder
lerna ERR! konnte nicht gefunden werden.
lerna ERR! npm ERR! code ELIFECYCLE
lerna ERR! npm ERR! errno 1
lerna ERR! npm ERR! jsonforms-core@2.1.0 build: `../../node_modules/.bin/tsc`
lerna ERR! npm ERR! Exit status 1
lerna ERR! npm ERR!
lerna ERR! npm ERR! Failed at the jsonforms-core@2.1.0 build script.
lerna ERR! npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
lerna ERR!
lerna ERR! npm ERR! A complete log of this run can be found in:
lerna ERR! npm ERR!     C:\Users\User\AppData\Roaming\npm-cache\_logs\2017-12-19T17_41_52_930Z-debug.log
lerna ERR!
lerna ERR! > jsonforms-core@2.1.0 build C:\Users\User\Documents\git\packages\core
lerna ERR! > ../../node_modules/.bin/tsc
lerna ERR!
lerna ERR!
lerna ERR!     at Promise.all.then.arr (C:\Users\User\AppData\Roaming\npm\node_modules\lerna\node_modules\execa\index.js:236:11)
lerna ERR!     at <anonymous>
(node:10276) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 4): Error: Command failed: npm run build
Der Befehl ".." ist entweder falsch geschrieben oder
konnte nicht gefunden werden.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! jsonforms-core@2.1.0 build: `../../node_modules/.bin/tsc`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the jsonforms-core@2.1.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\User\AppData\Roaming\npm-cache\_logs\2017-12-19T17_41_52_930Z-debug.log

> jsonforms-core@2.1.0 build C:\Users\User\Documents\git\packages\core
> ../../node_modules/.bin/tsc

(node:10276) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
> jsonforms-core@2.1.0 build C:\Users\User\Documents\git\packages\core
> ../../node_modules/.bin/tsc

(node:10276) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by eneufeld** [comment]
Found multiple things:
NPM closed this issue by a bot: https://github.com/npm/npm/issues/13789
Yarn has a solution: https://github.com/yarnpkg/yarn/issues/1729
SO suggest to use symlinks https://stackoverflow.com/questions/28078780/relative-paths-in-package-json

@edgarmueller any ideas?

**Comment by Felix-Puetz** [comment]
i just ran into the same issue while trying to run build
