### ISSUE TITLE
Set up Angular-based example app

### ISSUE THREAD

**Issue by edgarmueller** [eclipsesource/jsonforms#767]
Follow-up of #647

**Comment by edgarmueller** [comment]
@eneufeld Did you already transfer ownership of the repo to the organization?

**Comment by eneufeld** [comment]
no, I didn't. Will do.

**Comment by eneufeld** [comment]
The repo is here: https://github.com/eneufeld/make-it-happen-angular

Must be moved.

**Comment by eneufeld** [comment]
Moved Repo to https://github.com/eclipsesource/make-it-happen-angular
