### ISSUE TITLE
Update Readme of Deprecated Packages

### ISSUE THREAD

**Issue by sdirix** [eclipsesource/jsonforms#847]
The [jsonforms](https://www.npmjs.com/package/jsonforms) and [jsonforms-inferno](https://www.npmjs.com/package/jsonforms-inferno) packages are now deprecated with #765. We should consider updating the readme files of these packages with migration information.

**Comment by edgarmueller** [comment]
Also link to #651

**Comment by edgarmueller** [comment]
Closing in favor of https://github.com/eclipsesource/jsonforms/issues/922
