### ISSUE TITLE
Port Slider Renderer to material-ui

### ISSUE THREAD

**Issue by sdirix** [eclipsesource/jsonforms#853]
- The slider control is rendered slightly lower than the standard controls.
- The number next to the slider should be horizontally aligned

Screenshot from Basic example of jsonforms.io:
![sliderrenderer](https://user-images.githubusercontent.com/8998368/35797083-e30c5202-0a5e-11e8-8e9d-f6f0d6063a10.png)

**Comment by AhmetTanakol** [comment]
There is an ongoing work related to this issue https://github.com/mui-org/material-ui/pull/10665

**Comment by edgarmueller** [comment]
A bit off-topic, but maybe we should also apply the slider in case of `multipleOf`, i.e. in cases when it's not necessary to select an exact value, which, I think, is a common use case for sliders.

**Comment by AhmetTanakol** [comment]
Slider is available in the new version of material-ui https://github.com/mui-org/material-ui/pull/11040

**Comment by edgarmueller** [comment]
Fixed via #1025. Any issues with the newly added control should be tracked as separate issues.
