### ISSUE TITLE
Customizable Validation Messages

### ISSUE THREAD

**Issue by sdirix** [eclipsesource/jsonforms#854]
- Within the array control there is a summary of validation errors. However since the messages are local to each control the summary does not make much sense. See screenshot below from array control example of jsonforms.io:
![validationsummary](https://user-images.githubusercontent.com/8998368/35797359-c9cf101c-0a5f-11e8-8d2d-2b8fbde8d694.png)
- Enum values are rendered as drop boxes. Therefore the validation message ```should be equal to one of the allowed values``` seems strange. See screenshot below from Rule example of jsonforms.io:
![image](https://user-images.githubusercontent.com/8998368/35797491-2a101926-0a60-11e8-8f99-bb5aea9a8d09.png)

**Comment by edgarmueller** [comment]
ajv seems to supports customizable error message via [ajv-errors](https://github.com/epoberezkin/ajv-errors), although it seems a bit strange that the error message is placed within the schema itself. For our uses case, I'd rather place it in UI schema and then do some kind of pre-processingtransformation of the schema for ajv. We need to pay attentation how this will integrate with i18n (which perhaps also needs to re-work) and #923

**Comment by sdirix** [comment]
Error messages can now be customized via the [new `i18n` support in JSON Forms 3.0](https://jsonforms.io/docs/i18n).

**Comment by harsh-ayasya** [comment]
I tried doing whatever you have mentioned @sdirix but still its not working
