### ISSUE TITLE
Webpage should be app consuming JSONForms

### ISSUE THREAD

**Issue by edgarmueller** [eclipsesource/jsonforms#86]
Currently it uses a copy of the whole framework.

**Comment by edgarmueller** [comment]
Validation would also be demoable then

**Comment by edgarmueller** [comment]
This of course implies that data needs to be entered into the form. Hence, it would make sense to display the bound data outside the rendered form.

**Comment by eneufeld** [comment]
Isn't this closed as well now?

**Comment by edgarmueller** [comment]
Yes, it is.
