### ISSUE TITLE
[Seed] JSONForms scrolls automatically

### ISSUE THREAD

**Issue by sdirix** [eclipsesource/jsonforms#897]
When adding tasks or entering values in error-validated inputs of the default JSONForms seed application form, the web page scrolls a little bit to the top. After scrolling manually this behavior vanishes.

We should investigate the reason for this behavior and fix it in JSONForms / seed where applicable.

Chrome: 64.0.3282.167
JSONForms seed commit: 2cafd82af6d65b04fb40c75af5c8362967f84c71

**Comment by edgarmueller** [comment]
Not exactly how to add tasks in the seed, but I'd suppose that this happens when enter 'new' data that causes the 'Bound data' div to update, effectively pushing down the rendered form. A simple fix would be to place the 'bound data' div and the rendered form side by side.

**Comment by edgarmueller** [comment]
Closing this now as it should've been fixed with https://github.com/eclipsesource/jsonforms-react-seed/pull/16, please re-open if your disagree.
