### ISSUE TITLE
Update JSONForms Integration Guide at EMFForms

### ISSUE THREAD

**Issue by koegel** [eclipsesource/jsonforms#902]
https://eclipsesource.com/blogs/tutorials/emf-forms-and-json-forms-integration-guide/

**Comment by koegel** [comment]
Could you also update this guide (if updates are required)

**Comment by sdirix** [comment]
Updated document for new Seed and EMFForms 1.16. Still needs to be published. Note that EMFForms 1.16 is not yet officially released.

**Comment by koegel** [comment]
Looks good!

**Comment by koegel** [comment]
We will make sure to publish it with the 1.16 EMF Forms release

**Comment by koegel** [comment]
Will publish on March 23
