### ISSUE TITLE
Review all READMEs

### ISSUE THREAD

**Issue by eneufeld** [eclipsesource/jsonforms#909]
We pulled out react and must thus update the readme and the docu

**Comment by edgarmueller** [comment]
Didn't update the README yet, but the website. Moving issue to 2.0.0.

**Comment by eneufeld** [comment]
The packages are here: https://github.com/eclipsesource/jsonforms/tree/master/packages

**Comment by koegel** [comment]
Can you please add readmes for all packages currently some do not have a readme. Even if they are not published to npm I think it is good to have one. I am happy to review after that :)
