### ISSUE TITLE
Fix missing glyphicons warnings

### ISSUE THREAD

**Issue by edgarmueller** [eclipsesource/jsonforms#93]
GET 
http://localhost:8080/fonts/glyphicons-halflings-regular.woff [HTTP/1.1 404 Not Found 5ms]
downloadable font: download failed (font-family: "Glyphicons Halflings" style:normal weight:normal stretch:normal src index:1): status=2147746065 source: http://localhost:8080/fonts/glyphicons-halflings-regular.woff qb-bootstrap.min.css:261:12
GET 
http://localhost:8080/fonts/glyphicons-halflings-regular.ttf [HTTP/1.1 404 Not Found 5ms]
downloadable font: download failed (font-family: "Glyphicons Halflings" style:normal weight:normal stretch:normal src index:2): status=2147746065 source: http://localhost:8080/fonts/glyphicons-halflings-regular.ttf qb-bootstrap.min.css:261:12
GET 
http://localhost:8080/bower_components/jsonforms/dist/fonts/glyphicons-halflings-regular.woff2 [HTTP/1.1 404 Not Found 5ms]
downloadable font: download failed (font-family: "Glyphicons Halflings" style:normal weight:normal stretch:normal src index:1): status=2147746065 source: http://localhost:8080/bower_components/jsonforms/dist/fonts/glyphicons-halflings-regular.woff2 jsonforms.css:257:12
GET 
http://localhost:8080/bower_components/jsonforms/dist/fonts/glyphicons-halflings-regular.woff [HTTP/1.1 404 Not Found 6ms]
downloadable font: download failed (font-family: "Glyphicons Halflings" style:normal weight:normal stretch:normal src index:2): status=2147746065 source: http://localhost:8080/bower_components/jsonforms/dist/fonts/glyphicons-halflings-regular.woff jsonforms.css:257:12
GET 
http://localhost:8080/bower_components/jsonforms/dist/fonts/glyphicons-halflings-regular.ttf [HTTP/1.1 404 Not Found 4ms]
downloadable font: download failed (font-family: "Glyphicons Halflings" style:normal weight:normal stretch:normal src index:3): status=2147746065 source: http://localhost:8080/bower_components/jsonforms/dist/fonts/glyphicons-halflings-regular.ttf

**Comment by edgarmueller** [comment]
Seems like a bootstrap problem. In the our resulting CSS file the paths to glyphicons are wrong.

**Comment by koegel** [comment]
In Firefox on Ubuntu there is a visible problem in the examples even, the right arrows are displayed as "[" and the down arrows as "%"
