### ISSUE TITLE
Run validation before form submit

### ISSUE THREAD

**Issue by ketysek** [eclipsesource/jsonforms#930]
Hi, I'm using your library for rendering the part of my form, let's call it `settings`. I don't want to use Material UI renderers, so your vanilla renderers is more suitable for me. Now I've got successfully rendered my form:

```
<form className="form conf-edit-form" autoComplete="off" onSubmit={ handleSubmit( this.onSubmit ) }>
  <Field
    name="name"
    component={ RenderTextField }
    label="Name *"
    className="text-input"
    fullWidth={ true }
    validate={ required }
    autoFocus
  />
  --- other fields ---
        
  <div className="json-form">
    <Typography variant="subheading" className="settings-heading">
      Settings
    </Typography>
    <JsonForms />
  </div>

  <Typography variant="button" className="save-button">
    <Button className="submit" variant="raised" color="primary" type="submit"> 
      Save
    </Button>
    <Button className="back" variant="raised" color="default" onClick={ handleRequestClose } }>
      Cancel
    </Button>
  </Typography>
</form>
```

Now I would like to run validation on form submit, but I don't know how...
```
onSubmit(data) {
    const { jsonFormData } = this.props

    data.settings = jsonFormData
    console.log(data)
    // run validation!!!
    //this.props.onSubmitAction(data)
}

// this is the place where I get jsonFormData
function mapStateToProps(state) {
  return { 
    jsonFormData: getData(state)
  }
}
```

Any help would be highly appreciated! Thanks :-)

**Comment by edgarmueller** [comment]
Hi, validation is run on each change of the data rendered by the form, so you'd only to retrieve the current validation state, which you can do by accessing `state.jsonforms.core.errors` (we do not have a selector for the whole error sub-state yet). This represents the validation result of the data as produced by ajv (with slight modifications of the `dataPath` attribute, which is separated by dots and does not contain a leading `/`).  You can also use the `errorAt` selector in case you are interested in a certain instance path. Does this help?

**Comment by ketysek** [comment]
seems it doesn't work for me, just take a look, I have required fields, but errors array is empty .. below is `console.log` output of my `jsonforms` state
```
core:
  data:
    parameters:
      foo:"bar"
    runtime:
      branch:""
      password:""
      repository:""
      username:""
  errors:[]
  schema:
    $schema:"http://json-schema.org/draft-04/schema#"
    properties:
      parameters:
        properties:
          foo: {type: "string"}
        type:"object"
      runtime:
        properties:
          branch: {type: "string"}
          password: {type: "string"}
          repository: {type: "string"}
          username: {type: "string"}
        required: (4) ["repository", "branch", "username", "password"]
        type: "object"
      required: (2) ["parameters", "runtime"]
      type:"object"
...
```

**Comment by edgarmueller** [comment]
Looking at `data`, it seems as if you don't get any errors because all `required` fields are present (some with a value of an empty string, but that's still valid). The only time JSONForms will actually display `required` validation errors is when your initial data is missing the required fields, but once you edit them, it will initialize the strings.  Are you looking for [`minLength`](https://spacetelescope.github.io/understanding-json-schema/reference/string.html#length), maybe?

**Comment by ketysek** [comment]
Thanks, I'll try it and let you know

**Comment by edgarmueller** [comment]
@ketysek There wasn't any activity on this one for a while, hence I'm closing it now. If you experience any issues regarding validation, plrease re-open or create a new issue.
