### ISSUE TITLE
Form valdation check

### ISSUE THREAD

**Issue by sunandabbytes** [eclipsesource/jsonforms#931]
Below is how we used jsonforms
```javascript
<jsonforms schema="formSchema" data="formData" ng-if="formData"></jsonforms>
```

If form is not valid, I need to disable the submit button which is outside the form.
I tried using jsonforms.core.state.errors as below. But its is not working.
I tried log.console($scope.jsonforms);, It is undefined.

```javascript
<button ng-click="vm.updateForm(formData)" ng-disabled="jsonforms.core.state.errors.length !== 0">Update</button> 
```
Can anyone help me, how I can check form validation.

Thanks in advance :)

**Comment by sunandabbytes** [comment]
Hi @edgarmueller, thanks for the response. we are using JSONForms 1 and angularJS. I did not know that jsonforms.core.state.errors is redux state. Now how to check form validation in JSONForms 1.

**Comment by edgarmueller** [comment]
Unfortunately, this is not directly possible as you can not access the validation service from outside a control. I think your best bet would be to create a wrapper around the jsonforms element and trigger the validation yourself via ajv. Here's a hacky example to get you started, please update it to your needs:

```js
const Ajv = require('ajv');
const ajv = new Ajv({allErrors: true, jsonPointers: true});

class SubmitFormDirective implements ng.IDirective {
    template = `
        <jsonforms schema="vm.schema" uischema="vm.uischema" data="vm.data"></jsonforms>
        <button ng-click="vm.updateForm()" ng-disabled="!vm.isValid">Update</button>
    `;
    scope = {
        schema: '=',
        uischema: '=',
        data: '='
    };
    controller = SubmitFormController;
    controllerAs = 'vm';
    bindToController: true;
}

class SubmitFormController {
    static $inject = ['$scope'];
    private isValid;
    constructor(private scope: ng.IScope) {
        // ugly!
        scope.$watch(
            () => scope['vm'].data,
            (newValue, oldValue) => { 
                this.isValid = ajv.validate(scope['vm'].schema, newValue) 
            },
            true
        ) 
    }
    updateForm() {
        console.log("form updated");
    }
}

export default angular
    .module('app')
    .directive('submitControl', () => new SubmitFormDirective())
    .name;
```

Usage:
```html
<body ng-app="app" ng-controller="MyController as my">
  <submit-control schema="my.schema" uischema="my.uischema" data="my.data"></submit-control>
</body>
```

Please note that our main focus has shifted to JSONForms 2, so you might want to consider updating if that's an option for you.
