### ISSUE TITLE
[Material] Sometimes the line under a control is missing

### ISSUE THREAD

**Issue by lucas-koehler** [eclipsesource/jsonforms#955]
See Screenshot (Number of Cores)
![image](https://user-images.githubusercontent.com/6959840/39530394-2cc0c42e-4e29-11e8-8761-05d4fc5c3b8e.png)

**Comment by eneufeld** [comment]
I suggest to close this, due to the update to Material-UI 1.0.0?
@edgarmueller  what do you think?

**Comment by edgarmueller** [comment]
Ok, @lucas-koehler please re-open if the problem should persist.
