### ISSUE TITLE
Generating UI elements for complex objects

### ISSUE THREAD

**Issue by yogaesh** [eclipsesource/jsonforms#96]
Hi,

I'm trying to use your library to auto-generate the data entry form for a fairly complex JSON. Are there any element types other than "Control" available for use in the uiSchema? Right now, I'm not able to auto-generate UI fields unless I'm referring to a specific string field in the schema. For example:

                  "details" : {
                    "type" : "object",
                    "properties" : {
                      "localized_details" : {
                        "type" : "array",
                        "items" : {
                          "type" : { "$ref" : "#/definitions/localized_details" }
                        }
                      },
                      "images" : {
                        "type" : "array",
                        "items" : {
                          "type" : "string"
                        }
                      },
                      "videos" : {
                        "type" : "array",
                        "items" : {
                          "type" : "string"
                        }
                      },
                      "avg_annual_visitor_count": "number",
                      "status": {
                        "type" : { "enum" : ["approved", "pending", "rejected"] }
                      },
                      "created_by": { "type" : "string" },
                      "modified_by": { "type" : "string" },
                      "created_at": { "type" : "string" },
                      "modified_at": { "type" : "string" },
                      "approved_by": {"type" : "string" }
                    },
                    "required" : ["localized_details", "avg_annual_visitor_count"]
                  }

is a snippet from my schema and I'm not sure how I can auto-generate the form based on this definition, unless I go to every single simple string field (like created_by) and add a control in the ui-schema. Please advise.

**Comment by sdirix** [comment]
At the moment the only supported elements are ```Control``` and ```Horizontal/VerticalLayout```. ```Control``` is used to generate the inputs and the layouts are used to arrange them.

You are right, each ```Control``` has to refer to a specific field in the schema. Besides implementing your own custom element, there is no way to avoid specifying the reference to the schema. Maybe in the future we will add support for controls to resolve with some default behavior but this is currently not in our scope.

The good news is: If you only want a simple default form for your JSON you do not need an UI schema at all. When JSONForms does not receive an UI schema it will generate a default one for you, consisting of a ```VerticalLayout``` where each field of your JSON corresponds to one ```Control```. Maybe it is easier for you to use this generated UI schema and modify it according to your needs.

**Comment by sdirix** [comment]
Did you manage to solve your problem? Please do not hesitate to contact us if you have any further questions.
