### ISSUE TITLE
Schema Service Containment Properties Regression

### ISSUE THREAD

**Issue by lucas-koehler** [eclipsesource/jsonforms#968]
Since the refactoring(s), the schema service does not support all schemata that it supported before.
See attached file for example schema and config (in a .ts file) that do not work anymore but did before:
[coffee-config.zip](https://github.com/eclipsesource/jsonforms/files/2004045/coffee-config.zip)

**Comment by edgarmueller** [comment]
Is there an error or what do you mean by 'not supported'? If yes what is it? Ideally, it'd be great if you could provide a test case that catches  your expectations.
