### ISSUE TITLE
Populate input field using api call

### ISSUE THREAD

**Issue by AnkurBegining** [eclipsesource/jsonforms#987]
Hello, I was able to follow the tutorial to create UI based on my own JSON schema.
import schema from './schema.json';
import uischema from './uischema.json';

I am new to jsonforms and to React. I am loving using this great jsnforms.
My problem statement is, suppose i have fetched some data by some API using componetWillMount and i have two interdependent input fields i.e. Country and Cities which are there in that country. I have made this using rules in uischema and effect("HIDE", "SHOW", "DISABLE", "ENABLE"). For now i have used enum in Country and filled it using some of the raw country name in schema.json in enum of Country. Now i want to use some api call and fetch the result of all country and city then change the value in enum.  Once i change the enum value of Country then when i select some country then cities input filed should also get list of cities of that particular country using some api call.

I am new to React and jsonforms. If i am going something wrong, then you could correct me.

**Comment by AnkurBegining** [comment]
@sdirix  It helped and I filled the list of country by response of API call and prepopulate the drop-down list of city (which i called by another API call) based on selected city.

**Comment by eneufeld** [comment]
@sdirix @edgarmueller Can we close this as the underlying issue will be tracked with #988?

**Comment by edgarmueller** [comment]
@eneufeld  Right, I think we can therefore close this one now. @AnkurBegining If you have any additional questions, let us know.

**Comment by maulik-modi** [comment]
This REact Example helps solving cascade dropdown in json forms

**Comment by jainam-shah-cygnet** [comment]
Above example is great but from docs "As of JSON Forms 2.5 the React-Redux variant is deprecated in favor of the JSON Forms "standalone" component." so I have some questions 

 - How can we do cascading dropdown with the use of react hooks and without using redux ? 

 - Can we create common custom renderer for multiple fields in multiple forms ?

 - Can we pass props in our custom renderer ?
