### ISSUE TITLE
Optimize controls to be extendable and composable

### ISSUE THREAD

**Issue by sdirix** [eclipsesource/jsonforms#988]
Often there are use cases where one wants to specialize or compose existing controls. This should be as easy as possible.

Extended and composed controls should be able to support and re-use existing functionality of already provided controls like validation and translation services. 

**Example:**
Depending on previous input existing controls are modified to only allow only certain input ranges or selection in lists. See #987 for one concrete example and the current approach to control specialization.

**Comment by edgarmueller** [comment]
Closing this one for now as all renderers component are exported and available for customization (see #987). Any additional issues regarding extensibility and composability should be tracked in new issues.
